### ISSUE TITLE
Could not open a file on AsyncProfiler.stop()

### ISSUE THREAD

**Issue by leventov** [jvm-profiling-tools/async-profiler#100]
When being called from within a Java process, the profiler should probably communicate the problem opening the dump file as `IOException` rather than just printing to stderr and complete "successfully".

**Comment by apangin** [comment]
Did you mean `AsyncProfiler.execute()`? Because `stop` does not open a file and does not dump anything.

I thought about that. I'll probably fix this by the next release.

**Comment by leventov** [comment]
I didn't realise that if I call `AsyncProfiler.execute("start")`, I need to pair it with `AsyncProfiler.execute("stop")` rather than `stop()`. Thanks.

**Comment by apangin** [comment]
Actually `AsyncProfiler.execute()` already throws `IOException` if it fails to open output file.
Can you please clarify what else works wrong?

**Comment by leventov** [comment]
No, real reason was #103
