### ISSUE TITLE
SIGSEGV on Linux when actual page size is not 4k

### ISSUE THREAD

**Issue by dchuyko** [jvm-profiling-tools/async-profiler#101]
JVM crashes on attach if actual page size is 64k. The solution is to get is from OS instead of hardcoding in arch.h.
Other platforms suffer as well.

**Comment by apangin** [comment]
Makes sense. Thanks for pointing this out.
I'll accept the PR after I verify it introduces no regression.

**Comment by dchuyko** [comment]
I realized that sysconf() is POSIX so I've updated PR to check '__unix__'. This should work on macOS X either now.

**Comment by apangin** [comment]
This means `#ifdef` is not needed then. Profiler is not supposed to work on non-POSIX systems so far.

**Comment by apangin** [comment]
I found that initializing a global variable in a header file is not the best approach, since the initialization code is repeated in all places that include this `.h` file.

**Comment by apangin** [comment]
I've reimplemented the fix. Please verify that it works as expected.

**Comment by dchuyko** [comment]
Great, it works.
