### ISSUE TITLE
Emit a warning when profiler is stopped and no dump options are specified

### ISSUE THREAD

**Issue by leventov** [jvm-profiling-tools/async-profiler#103]
It's valid, but rarely useful to stop profiling without dumping the results. Currently async-profiler just writes "Profiling stopped after X seconds", not specifying why it didn't produce any output. I spent quite long time trying to debug this. It would be helpful to emit a message a-la
```
Warning: no dump options are specified. You may want to specify one or several of "summary", "flat", "traces", "flamegraph"
```

**Comment by leventov** [comment]
My mistake was that I thought for some reason that the dump option should be provided long with the "start" command. So it might make sense to emit a warning (or even a error) if *any* dump option is specified with the start event, indicating that it doesn't make any sense.

**Comment by apangin** [comment]
I would argue that sole `stop` is useless - I personally use it pretty often when I need to cease profiling right now and get results lazily some time later.
But there is no problem to extend the message - will do it.
