### ISSUE TITLE
Can we add details about each output format to the documentation?

### ISSUE THREAD

**Issue by MarkMccl** [jvm-profiling-tools/async-profiler#107]
Hi,

Great project! I had a chance to run your async profiler with one of our applications, experimenting with a few different output formats. I was wondering if we could perhaps add a section to the documentation outlining the structure / explaining the captured metrics?

I was wondering if it is possible to estimate how much time is spent in a specific method call?

**Comment by apangin** [comment]
Thank you for the feedback.
Async-profiler is a sampling profiler. It collects execution stacktraces every `N` events (where `N` is an interval specified with `-i` option; the default is 1'000'000 nanoseconds). Along with the number of collected samples async-profiler accumulates the value of the counter (e.g. nanoseconds of CPU time for `cpu` profiling or amount of allocated memory for `alloc` profiling).

`flat` and `traces` output include both the number of samples *and* the value of the counter for each method.

`collapsed` and `svg` formats include *either* number of samples *or* the counter value for each method. Which one - is specified by `-o format=samples` or `-o format=total`.

> I was wondering if it is possible to estimate how much time is spent in a specific method call?

    method_time ≈ total_profiling_time * (method_samples / total_samples)

**Comment by nitsanw** [comment]
Note: For CPU profiling the "time" is CPU time, not wall clock time. This can be quite confusing.
E.g.:
- An operation takes 1 second, utilizing 10 CPUs at 100%, it has consumed 10s of CPU and should result in ~10k samples in the default sampling rate.
- An operation takes 1 second, of which 900ms are blocked on some external resource, it has spent 100ms of CPU time and should result in 100 samples.

To convert samples to **time on CPU** we could compute:
`CPU time ≈ total_profiling_time * (method_samples/total_potential_samples)`

But: `total_potential_samples = sample_rate * total_profiling_time`
So we get: `CPU time ≈ method_samples/sample_rate` (note that potentially: CPU time > total_profiling_time)
If the method is known to run on a single core, and known to never be blocked or interrupted, we can reason the CPU time is similar to `time`. Even then the conversion can be further confused by CPU frequency scaling, which I'm not sure if the sampling frequency compensates for.

@apangin computation above would be correct when you are looking at 100% CPU utilization on a single core system at a fixed frequency.

**Comment by MarkMccl** [comment]
Thanks for the informative responses @apangin & @nitsanw!

I am currently working with a rule execution framework, which has roughly 5 main components. I am simulating the workflow of these rules (Event->Cond.->Action) through a test framework. I am trying to measure some soft SLA's

Would it be possible to assert what % of the time was spent in each critical component (defining a critical component as a specific method and all trailing methods) after pruning all test framework native calls?
