### ISSUE TITLE
Tree view for caller callee

### ISSUE THREAD

**Issue by rpulle** [jvm-profiling-tools/async-profiler#109]
Is it possible to generate a tree view showing caller callee with %CPU times at each tree method?

**Comment by apangin** [comment]
Well, Flame Graph *is* a visualization of such a tree.
Or please clarify what you mean. Do you have an example?

**Comment by rpulle** [comment]
@apangin  I am planning for a demo next week across my group, are you planning for 1.4 release?

**Comment by apangin** [comment]
@rpulle My intention was to complete JFR support by 1.4 release. I'm going to finish it soon, but not sure it'll be done by the next week.

**Comment by rpulle** [comment]
@apangin  Can you please clarify on the numbers on profiler output?

1)
how to interpret number "10569704" for alloc profiling?
[alloc] profiling
    10569704 (50.00%)       1  java.lang.Object[]
    10569688 (50.00%)       1  char[]

2)
how to interpret number "4117339" for cpu profiling?
[cpu] profiling
     4117339 (13.00%)       4  [unknown]
     2074622 ( 6.55%)       2  MutableSpaceUsedHelper::take_sample()
     1060175 ( 3.35%)       1  Monitor::IWait(Thread*, long)

**Comment by apangin** [comment]
Integrated in #117
