### ISSUE TITLE
Track SynchronousQueue and AbstractQueued(Long)Synchronizer during lock profiling

### ISSUE THREAD

**Issue by leventov** [jvm-profiling-tools/async-profiler#111]
`SynchronousQueue` is in fact a separate synchronization primitive, that doesn't build on top of `ReentrantLock`.

**Comment by apangin** [comment]
I don't think this is a desired default behavior to include queue wait time when profiling contended locks. E.g. if you have a regular thread pool, all its idle threads will be waiting on a blocking queue. This is absolutely normal; idle threads are not very interesting.

**Comment by leventov** [comment]
It's true that this is not a source of *lock contention* per se, but waiting on enqueueing something into queues, associated with executors such as `ThreadPoolExecutor` and `ForkJoinPool`, and waiting on dequeueing from some queues in some other cases, could be a real source of *pauses* in the application, possibly unexpected and due to inefficiencies in the code or misconfiguration (e. g. of queue sizes). Hunting down and eliminating all such pauses (which are not only caused by lock contention) is one of the things that the process of profiling is after.

**Comment by leventov** [comment]
What do you think about adding an option that doesn't do any filtering of Unsafe/LockSupport's park sources? Or calling it a different "profiling event", e. g. "park" or "wait"?

**Comment by apangin** [comment]
Yes, adding "park" profiling event seems a reasonable option.

**Comment by leventov** [comment]
I've prototyped this feature (https://github.com/leventov/async-profiler/commit/510462c94d201f732d105ecbb616942c7c705b93) but admittedly results are 99% noisy. To make any sense out of them, flamegraph should support more advanced filtering capabilities. Created https://github.com/brendangregg/FlameGraph/issues/168.

**Comment by brettwooldridge** [comment]
I have a question about this as well.  I have a highly asynchronous processing application, with some threads spending the vast majority of their time in ``LockSupport.parkNanos()``/``Unsafe.park()``.  These are showing up as high CPU "usage" in the flamegraph.

In my opinion, these are "idle" threads, as they are not burning CPU cycles, as least as CPU is viewed externally on the same machine.  Is there a reason these appear in the flamegraph?  I'm trying to get an accurate picture of where the application is actually spending CPU cycles.

**Comment by apangin** [comment]
@brettwooldridge Parking/unparking does not come for free. It involves non-trivial logic both inside JVM and OS kernel. This indeed can be CPU consuming when called too often.

If you got this flame graph from async-profiler in `cpu` mode, I'm pretty sure it points you to a real hot spot. Otherwise idle threads don't even have a chance to receive profiler signal. Note that `lock` profiling mode is quite different - it is not related to CPU usage at all.

Can you share a bit more details on how you run the profiler and what (unexpected) results you got?

**Comment by apangin** [comment]
Closing the issue, as the wall-clock profiling mode along with filtering options (#187) should cover this use case.
