### ISSUE TITLE
Profiler not returning samples

### ISSUE THREAD

**Issue by rbalamohan** [jvm-profiling-tools/async-profiler#113]
I have been using async for quite sometime successfully on my clusters. It works awesome. On one of the cluster, I am facing an issue where in it does not gather samples. 

I have tried the following

./profiler.sh -b 36000000 -e cpu -d 10 -f cpu.traces.txt -o traces <PID> (This is the usual command, and I use SVG format as well).

Have tried the following as well
./profiler.sh start <PID>

./profiler.sh status  <PID>
[perf] profiling is running for 4 seconds

./profiler.sh stop  <PID>
--- Execution profile ---
Total samples:         0

Frame buffer usage:    0%

But these do not generate any samples and they are not reporting any errors as well. I am currently using "1.8.0_112". 

Has anyone faced issue like this earlier? Please note that this is specific to set of nodes in a cluster and not a general issue.

**Comment by apangin** [comment]
Either a target process sleeps and does not consume CPU at all, or `perf_event_open` syscall fails.
Please check `stderr` of the target java process whether it has *"perf_event_open failed"* messages.

- What is kernel version?
- Is there `/proc/sys/kernel/perf_event_paranoid` and what value does it have?
- Does an application work in a virtualized environment or in a container?
- Is SELinux or seccomp enabled?

**Comment by rbalamohan** [comment]
It may have to be related to the seccomp I suspect.

Security Options:
 apparmor
 seccomp

 "docker info" shows it as "seccomp", so it may not be able to do anything else. I need to check fixing this.

**Comment by apangin** [comment]
Added an error message when `perf_event_open` API is unavailable. Updated the documentation with possible reasons. That's all for now. Feel free to reopen the issue if the problem happens again.

**Comment by rajeshbalamohan** [comment]
Thanks a lot  for adding the error message and the documentation.

**Comment by fjssilva** [comment]
Hi,

This is happening for me too. I'm using Ubuntu 18.04 and Oracle Java 8.

I've set the two options in `/proc/sys/kernel` as per documentations and I don't get any warnings or errors  in any of the outputs.

Some help would be appreciated. Thanks!

**Comment by apangin** [comment]
@fjssilva Do you run docker, too? Or do you run Linux in a virtual machine?
Does `perf record` work?

**Comment by fjssilva** [comment]
No docker neither Linux on a virtual machine. This is Ubuntu 18.04 out of the box directly on hardware.

`perf record` seems to work well. At least I had it run for some time and it generated a non-empty `perf.data` file.

**Comment by apangin** [comment]
@fjssilva Sounds strange. Can you please clone the repository and run `make test` - will it work?

**Comment by fjssilva** [comment]
Not sure how to read the results. This is what I get:
```
$ make test
mkdir -p build
g++ -O2 -DPROFILER_VERSION=\"1.4\" -I/opt/jdk1.8.0_172/include -I/opt/jdk1.8.0_172/include/linux -fPIC -shared -o build/libasyncProfiler.so src/*.cpp -ldl -lpthread
gcc -O2 -DJATTACH_VERSION=\"1.3\" -o build/jattach src/jattach/jattach.c
src/jattach/jattach.c: In function ‘alt_lookup_nspid’:
src/jattach/jattach.c:159:66: warning: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size between 100 and 110 [-Wformat-truncation=]
                 snprintf(path, sizeof(path), "/proc/%d/root/proc/%s/sched", pid, entry->d_name);
                                                                  ^~
In file included from /usr/include/stdio.h:862:0,
                 from src/jattach/jattach.c:17:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 25 and 290 bytes into a destination of size 128
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mkdir -p build/classes
/opt/jdk1.8.0_172/bin/javac -source 6 -target 6 -d build/classes src/java/one/profiler/Events.java src/java/one/profiler/AsyncProfiler.java src/java/one/profiler/AsyncProfilerMXBean.java src/java/one/profiler/Counter.java
warning: [options] bootstrap class path not set in conjunction with -source 1.6
1 warning
/opt/jdk1.8.0_172/bin/jar cvf build/async-profiler.jar -C build/classes .
added manifest
adding: one/(in = 0) (out= 0)(stored 0%)
adding: one/profiler/(in = 0) (out= 0)(stored 0%)
adding: one/profiler/Counter.class(in = 845) (out= 473)(deflated 44%)
adding: one/profiler/AsyncProfiler.class(in = 1789) (out= 878)(deflated 50%)
adding: one/profiler/Events.class(in = 335) (out= 253)(deflated 24%)
adding: one/profiler/AsyncProfilerMXBean.class(in = 604) (out= 334)(deflated 44%)
rm -rf build/classes
test/smoke-test.sh
+ '[' -z /opt/jdk1.8.0_172 ']'
++ dirname test/smoke-test.sh
+ cd test
+ '[' Target.class -ot Target.java ']'
+ FILENAME=/tmp/java.trace
+ JAVAPID=16792
+ sleep 1
+ /opt/jdk1.8.0_172/bin/java Target
+ ../profiler.sh -f /tmp/java.trace -o collapsed -d 5 16792
+ kill 16792
+ assert_string 'Target.main;Target.method1 '
+ grep -q 'Target.main;Target.method1 ' /tmp/java.trace
+ assert_string 'Target.main;Target.method2 '
+ grep -q 'Target.main;Target.method2 ' /tmp/java.trace
+ assert_string 'Target.main;Target.method3;java/io/File'
+ grep -q 'Target.main;Target.method3;java/io/File' /tmp/java.trace
test/alloc-smoke-test.sh
+ '[' -z /opt/jdk1.8.0_172 ']'
++ dirname test/alloc-smoke-test.sh
+ cd test
+ '[' AllocatingTarget.class -ot AllocatingTarget.java ']'
+ FILENAME=/tmp/java.trace
+ JAVAPID=16831
+ sleep 1
+ /opt/jdk1.8.0_172/bin/java AllocatingTarget
+ ../profiler.sh -f /tmp/java.trace -o collapsed -d 5 -e alloc -t 16831
+ kill 16831
+ assert_string 'AllocThread-1;.*AllocatingTarget.allocate;.*java.lang.Integer\[\]'
+ grep -q 'AllocThread-1;.*AllocatingTarget.allocate;.*java.lang.Integer\[\]' /tmp/java.trace
+ assert_string 'AllocThread-2;.*AllocatingTarget.allocate;.*int\[\]'
+ grep -q 'AllocThread-2;.*AllocatingTarget.allocate;.*int\[\]' /tmp/java.trace
```

**Comment by fjssilva** [comment]
I think I found it. My code had a `Thread.sleep(100)`. Without it all seems work fine.

So, I can't profile anything with `Thread.sleep()` calls? What if my code uses an external library that does it?

**Comment by apangin** [comment]
Ah, profiling `Thread.sleep` is indeed a futile job :)

`make test` completes successfully meaning that profiler works.
In default mode async-profiler samples code where the most CPU time is spent. `Thread.sleep` does not consume CPU and thus does not generate profiler events. This is expected.

However, your case is definitely interesting from another point of view. Sometimes developers want to know not only the hottest pieces of code, but also the places which waste time by doing nothing. This is so called "wall clock profiling". We already have a feature request to add this mode to async-profiler, see  #69. I plan to implement this in one of the nearest releases.
