### ISSUE TITLE
can I run async-profiler under root user to profile the java process under another user?

### ISSUE THREAD

**Issue by ygdyang** [jvm-profiling-tools/async-profiler#114]
just as the title said, I want to profile a java process under other user. But I fail, even I run async-profiler under root user.  jattach print the error: "Could not start attach mechanism: No such file or directory". And jvm process print some call stack at the same time.
Any solution for this?

**Comment by apangin** [comment]
I've just commited the fix b39ab0d2aa56fdec403a68d1dcb76ddd933d3ac7 in `sudo` branch.
It should allow to profile any Java process when run under root.

Please check if it helps.

**Comment by apangin** [comment]
Thank you for verifying. I've merged the fix into master.
