### ISSUE TITLE
problem with display svg and chrome/firefox

### ISSUE THREAD

**Issue by quochoangnguyen** [jvm-profiling-tools/async-profiler#118]
I use the lastest version of async-profiler --> async-profiler-1.3-linux-x64 with the java environment openjdk version "1.8.0_102"

But the resulting svg file gives the following output when opened in Chrome/firefox see attach file 
![display_test_svg_gchrome](https://user-images.githubusercontent.com/6152245/40102897-f91507ac-58eb-11e8-9b1e-5d59b63a34c2.png)

I also attach the product svg (tomcattest.svg

)

Do you have any idea for my problem ?

Thanks in advance

**Comment by apangin** [comment]
Looks similar to #94.
What's your OS version and locale settings?
Please also attach .svg if possible.

**Comment by quochoangnguyen** [comment]
Hi apangin

for the OS system :

cat /proc/version
Linux version 3.10.0-514.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Tue Nov 22 16:42:41 UTC 2016

for the locale setting :
[test1@12 ~]$ locale
LANG=fr_FR.UTF-8
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=

and also the attach svg

[tomcat_test_svg.txt](https://github.com/jvm-profiling-tools/async-profiler/files/2008727/tomcat_test_svg.txt)

**Comment by quochoangnguyen** [comment]
Hi apangin

That's exactly.
I forget to restart the Tomcat jvm.
And now It works well.
Thank a lot.
