### ISSUE TITLE
Call tree report isn't valid HTML

### ISSUE THREAD

**Issue by jesperpedersen** [jvm-profiling-tools/async-profiler#120]
The call tree report isn't valid HTML, and hence the report eats 100% CPU in Firefox.

https://validator.w3.org/ can be used for verifying the resulting file.

@rpulle

**Comment by jesperpedersen** [comment]
Related: `profiler.sh` doesn't have `tree` in its `-o fmt` help

**Comment by rpulle** [comment]
@jesperpedersen  I have fixed both and created a PR.

**Comment by jesperpedersen** [comment]
Thank you

**Comment by jesperpedersen** [comment]
The `+` button doesn't expand the tree in Firefox 60 (Linux), but that is a separate issue -- I havn't investigated yet

**Comment by jesperpedersen** [comment]
The `++` and `--` works

**Comment by rpulle** [comment]
@jesperpedersen  @apangin  Fixed  Firefox 60 (Linux) issue.
