### ISSUE TITLE
Display 'Unknown (native/Java)' stack traces in Flamegraph

### ISSUE THREAD

**Issue by lic9** [jvm-profiling-tools/async-profiler#123]
Currently 'Unknown (native/Java)' stack traces are displayed in plain text result (-o summary) but not shown in flamegraph, which could make flamegraph skewed.

To verify, I built a jdk8 by making 'find_initial_Java_frame()' in hotspot/src/share/vm/prims/forte.cpp always return false so that no Java frame would be available from the AGCT api. In this case, flamegraph does not show any java stack traces, and could mislead users think that all time was spent in native methods.
<img width="953" alt="40447624-10890e00-5e88-11e8-9df0-2c625d085580" src="https://user-images.githubusercontent.com/1966176/40516901-a85acb6c-5f67-11e8-835f-74241a11120e.png">

It is better to add those unknown/unwalkable stack traces on top of root so they are part of the distribution.

**Comment by apangin** [comment]
Flamegraph now includes all AsyncGetCallTrace failures, e.g. `[unknown_Java]`:

![unknown_java](https://user-images.githubusercontent.com/1749416/52920323-3d2d7180-331c-11e9-8974-47596dd1ddc4.jpg)
