### ISSUE TITLE
Add units to the profiler output

### ISSUE THREAD

**Issue by mosesn** [jvm-profiling-tools/async-profiler#124]
Looking at my execution profile, I'm seeing a strange result

```
--- Execution profile ---
Total samples:         5

Frame buffer usage:    0.0311%

Total: 47839 (56.23%)  samples: 3
  [ 0] java.util.concurrent.ConcurrentHashMap$Node
  [ 1] java.util.concurrent.ConcurrentHashMap.replaceNode
  [ 2] java.util.concurrent.ConcurrentHashMap.remove
  [ 3] io.netty.channel.ChannelInitializer.remove
  [ 4] io.netty.channel.ChannelInitializer.initChannel
  [ 5] io.netty.channel.ChannelInitializer.handlerAdded
  [ 6] io.netty.channel.DefaultChannelPipeline.callHandlerAdded0
  [ 7] io.netty.channel.DefaultChannelPipeline.addLast
  [ 8] io.netty.channel.DefaultChannelPipeline.addLast
  [ 9] com.twitter.finagle.netty4.ListeningServerBuilder$$anon$1$$anon$2$$anon$3.initChannel
  [10] io.netty.channel.ChannelInitializer.initChannel
```

What I don't understand is what these numbers mean:

```
Total samples:         5

Frame buffer usage:    0.0311%

Total: 47839 (56.23%)  samples: 3
```

What is the 47839 in this context, and how does it relate to the number of samples?

I ran the command like `./async-profiler/profiler.sh -e lock -d 30 -f lock.txt $PID`

**Comment by apangin** [comment]
`Total samples: 5` means there were 5 contended lock attempts during the whole profiling session.

Below goes the break down of these samples grouped by stack traces.

```
Total: 47839 (56.23%)  samples: 3
  [ 0] java.util.concurrent.ConcurrentHashMap$Node
```
It says the contention on the monitor `ConcurrentHashMap$Node` happened 3 times. The application was waiting for this monitor to become free for 47839 nanoseconds in total, that constitute 56% of total monitor wait time.

**Comment by mosesn** [comment]
Thanks @apangin!  Do you think you could attach units to the 47839?  I think that would make it easier for noobs like me to understand what's happening.

**Comment by apangin** [comment]
Yes, it worth doing. Will add the units.

**Comment by apangin** [comment]
Now the output looks like
```
--- 53191000 (16.86%) ns, 16 samples
  [ 0] java.util.concurrent.locks.ReentrantLock$NonfairSync
  [ 1] sun.misc.Unsafe.park
  [ 2] java.util.concurrent.locks.LockSupport.park
  [ 3] java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt
  [ 4] java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued
  [ 5] java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire
  [ 6] java.util.concurrent.locks.ReentrantLock$NonfairSync.lock
  [ 7] java.util.concurrent.locks.ReentrantLock.lock
  [ 8] sun.awt.SunToolkit.awtLock
  [ 9] sun.awt.X11.XToolkit.waitForEvents
  [10] sun.awt.X11.XToolkit.run
  [11] sun.awt.X11.XToolkit.run
  [12] java.lang.Thread.run

          ns  percent  samples  top
  ----------  -------  -------  ---
   173452000   54.99%       37  java.awt.Component$AWTTreeLock
   140553000   44.56%       68  java.util.concurrent.locks.ReentrantLock$NonfairSync
      739000    0.23%        1  javax.swing.RepaintManager
      645000    0.20%        2  java.util.HashMap
       12000    0.00%        2  java.util.jar.JarFile
```

**Comment by mosesn** [comment]
Great, thanks @apangin!  This looks much easier to interpret.  fwiw, I think it might be clearer if it says

`--- 53191000ns (16.86%), 16 samples`

instead of 

`--- 53191000 (16.86%) ns, 16 samples`

**Comment by apangin** [comment]
Done

**Comment by mosesn** [comment]
you're the best =)

**Comment by plokhotnyuk** [comment]
The best option would be to use a default locale formatter for numbers which can prettify big numbers with commas between thousands, etc.

But, any way, thanks a lot for your great work, Andrei!

**Comment by apangin** [comment]
@plokhotnyuk Locale-dependent output has already played a bad joke some time ago - #94
So I explicitly turned this off. Though I can probably re-enable it for text output only.
