### ISSUE TITLE
Is it possible to use async-profiler as a javaagent?

### ISSUE THREAD

**Issue by dsyer** [jvm-profiling-tools/async-profiler#125]
Some discussion in #93 leads me to think it might not be possible, but people are thinking about it. I asked @apangin about launching a java process with `profiler.sh` at Riga DevDays, and he said I could do it by attaching the profiler as an agent. So maybe it's just documentation that's missing? I couldn't find a `preMain` method anywhere in the source code though, so I'm kind of confused.

**Comment by apangin** [comment]
Yes, it's possible to use async-profiler as a JVMTI agent (not a Java agent though).
In this case it will be launched at JVM startup time.

    java -agentpath:/path/to/libasyncProfiler.so=start,svg,file=profile.svg

I'll update the documentation a bit later. Or you can do it if you'd like.

**Comment by apangin** [comment]
BTW, the entry point for native agents is called [Agent_OnLoad](https://github.com/jvm-profiling-tools/async-profiler/blob/master/src/vmEntry.cpp#L124) for loading at JVM start up time or [Agent_OnAttach](https://github.com/jvm-profiling-tools/async-profiler/blob/master/src/vmEntry.cpp#L137) for loading at runtime.

**Comment by dsyer** [comment]
I can send a PR for the README I guess. How do you set the command line options from the .sh script though? E.g. the `-d`, `-o`, `-e`, `-f` (the flags I use currently).

**Comment by apangin** [comment]
Agent library is configured through the JVMTI argument interface. The format of the arguments string is described [here](https://github.com/jvm-profiling-tools/async-profiler/blob/master/src/arguments.cpp#L26).

profiler.sh script converts command line arguments to the above format.

For instance, `-e alloc` is converted to `event=alloc`, `-f profile.svg` is converted to `file=profile.svg` and so on. But some arguments are processed directly by profiler.sh script. E.g. `-d 5` results in 3 actions: 1) attaching profiler agent with `start` command, sleeping for 5 seconds, and then attaching the agent again with `stop` command.

**Comment by dsyer** [comment]
See #128

**Comment by kubagruszka** [comment]
> Agent library is configured through the JVMTI argument interface. The format of the arguments string is described [here](https://github.com/jvm-profiling-tools/async-profiler/blob/master/src/arguments.cpp#L26).
> 
> profiler.sh script converts command line arguments to the above format.
> 
> For instance, `-e alloc` is converted to `event=alloc`, `-f profile.svg` is converted to `file=profile.svg` and so on. But some arguments are processed directly by profiler.sh script. E.g. `-d 5` results in 3 actions: 1) attaching profiler agent with `start` command, sleeping for 5 seconds, and then attaching the agent again with `stop` command.

Can you please give an example how I can run the profiler as javagent on startup for defined duration? I was trying to do 
```
-agentpath:/opt/async-profiler/build/libasyncProfiler.so=-d=5,file=profile.svg
```

but the profile was empty file.

**Comment by apangin** [comment]
> Can you please give an example how I can run the profiler as javagent on startup for defined duration? I was trying to do
> 
> ```
> -agentpath:/opt/async-profiler/build/libasyncProfiler.so=-d=5,file=profile.svg
> ```
> 
> but the profile was empty file.

@kubagruszka There is no such option in the agent now. Profiling must be stopped explicitly, either by running `profiler.sh` (or `jattach`) externally, or by calling [`AsyncProfiler.stop`](https://github.com/jvm-profiling-tools/async-profiler/blob/800580bb30b96421834783434939869246e1a1aa/src/api/one/profiler/AsyncProfiler.java#L77) method from within the application.
