### ISSUE TITLE
[feature request] Show Inlined frames

### ISSUE THREAD

**Issue by franz1981** [jvm-profiling-tools/async-profiler#129]
Mixed mode flame graphs with perf-java-flames show inlined frames 
using aqua color, making easy identify them.
It is possible to do the same with async-profiler?
AGCT allow to recognize these "virtual" frames?

**Comment by apangin** [comment]
AGCT does not support this.
But ultimately async-profiler should work without AGCT support.
Closed as duplicate of #66.
