### ISSUE TITLE
CPU profiling Memory and CPU overhead

### ISSUE THREAD

**Issue by rpulle** [jvm-profiling-tools/async-profiler#131]
I have done some internal workloads to analyze system level CPU and memory impact while doing CPU profiling.

![image](https://user-images.githubusercontent.com/5393092/41313762-a59dcfd2-6e3f-11e8-8cf7-39bd754dce5a.png)

Java stack depth and profiling sample count has significant impact on CPU, the overhead range observed  between 0.8% to 5.6%.

What seems to be concerning is Memory usage, in a 64G host, the Memory usage increased to 8 to 9%, which is ~5G.  I am analyzing this.

But meanwhile, let me know if any analysis is already carried out on Memory usage during CPU profiling.

**Comment by rpulle** [comment]
I have also done Memory profiling for same workload.

![image](https://user-images.githubusercontent.com/5393092/41314461-aa10b6cc-6e41-11e8-9987-da14f60f8bd1.png)

The CPU and Memory overhead is much higher with Memory profiling.

**Comment by apangin** [comment]
Dumping call tree can take huge amount of memory. I suggest you measure with "summary" output format.

**Comment by rpulle** [comment]
I have done these tests with flat,traces output  format.

**Comment by apangin** [comment]
ОК. I would suspect the memory is taken by jmethodIDs, JIT symbols or NativeCodeCaches. Haven't analyzed this yet.
How do you measure memory utilization?

**Comment by rpulle** [comment]
using /proc/meminfo

%Memory Used:  100*(MemTotal - MemFree - Buffers - Cached)/MemTotal

**Comment by apangin** [comment]
BTW, there is already an issue #14 for overhead related discussion.

**Comment by apangin** [comment]
I'll close this one and leave #14 open for further discussion on profiler overhead.
