### ISSUE TITLE
Feature: Option to exclude pure native calls

### ISSUE THREAD

**Issue by jesperpedersen** [jvm-profiling-tools/async-profiler#133]
It would be nice to have an option to exclude pure native calls from the resulting output.

F.ex. in the flamegraph output only Java calls would show up, and everything under `start_thread` would be excluded.

Default should probably be off.

**Comment by apangin** [comment]
Isn't this a *mis*feature? :)
The value of async-profiler in its ability to show everything including native and kernel hot spots.
However, there is still a possibility to dump results in collapsed stack traces format, filter whatever you want, and then generate a flame graph.

**Comment by jesperpedersen** [comment]
Yeah, that is true.

While it would be easier to have it as a built-in (no dependencies on external tools) I agree it could be worked around.

**Comment by apangin** [comment]
I already had several requests for a similar option. Though I'm not fond of it, seems like people still want this feature.

OK. There is already `--cstack` option to force native stack traces for Java-level events. So I've added a symmetric `--no-cstack` option to forcibly prevent from collecting native frames.
