### ISSUE TITLE
Missing allocation stack traces

### ISSUE THREAD

**Issue by RafalSumislawski** [jvm-profiling-tools/async-profiler#138]
Hi,
I'm getting 99% of `Unknown (native)`  when profiling allocations, and so I get just numbers of allocations, no stack traces. Profiling CPU works fine. It looks a bit similar to #99, but as far I as understand that is already fixed.

I'm using:
```
# ./profiler.sh --version
Async-profiler 1.4 built on Jun 24 2018
Copyright 2018 Andrei Pangin
```

```
# java -version
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
```

```
CentOS Linux 7 (Core)
Linux 3.10.0-693.5.2.el7.x86_64
```

JVM options:
```
-Xms24g
-Xmx24g
-XX:+UnlockExperimentalVMOptions
-XX:+UseG1GC
-XX:G1NewSizePercent=30
-XX:InitiatingHeapOccupancyPercent=60
-Xloggc:<path>
-XX:+PrintGCDetails
-XX:+PrintGCTimeStamps
-XX:+PrintTenuringDistribution
-XX:+PrintGCCause
-XX:+UseGCLogFileRotation
-XX:NumberOfGCLogFiles=10
-XX:GCLogFileSize=5M
-XX:+UseNUMA
-XX:+HeapDumpOnOutOfMemoryError
-XX:HeapDumpPath=<path>
```

Result of profiling allocations:
```
# ./profiler.sh -d 5 -e alloc -o summary <PID>
Started [alloc] profiling
--- Execution profile ---
Total samples:         405
Unknown (native):      402 (99,26%)

Frame buffer usage:    0.0171%
```

Result of profiling CPU:
```
# ./profiler.sh -d 5 -e cpu -o summary <PID>
Started [cpu] profiling
--- Execution profile ---
Total samples:         8517
Non-Java:              813 (9,55%)
Unknown (native):      2 (0,02%)
Unknown (Java):        66 (0,77%)
Not walkable (Java):   3 (0,04%)

Frame buffer usage:    9.6904%
```

Could you give me some hints how to troubleshoot this?

BTW Thanks for the great tool :+1:

**Comment by apangin** [comment]
Does allocation profiling work on other applications?

Does `./profiler.sh --version <pid>` (with PID!) also shows the latest version?

**Comment by RafalSumislawski** [comment]
Just tested with a different application and different JVM options running on the same machine (the same OS and JVM). There the allocation profiling works.

--version with the PID of the problematic application exits without printing anything.

```
# ./profiler.sh --version <ok-app-pid>
Async-profiler 1.4 built on Jun 24 2018
Copyright 2018 Andrei Pangin
# ./profiler.sh --version <problematic-app-pid>
# echo $?
0
```

I'll check if different application or different JVM options made the difference. It will take me some time. Will post the results once ready.

**Comment by apangin** [comment]
> --version with the PID of the problematic application exits without printing anything.

This explains the issue. Earlier version of profiler agent has been already loaded into the target process. New version won't take effect until the application is restarted. Unfortunately, HotSpot does not support agent unloading.

**Comment by RafalSumislawski** [comment]
That was it indeed. Works like a charm on a second instance of that application, which I haven't touched with async-profiler before.

Thanks for such a quick help :)
