### ISSUE TITLE
spring batch  and glowroot

### ISSUE THREAD

**Issue by quochoangnguyen** [jvm-profiling-tools/async-profiler#151]
Hi Trask,

with Glowroot, I known that we can use this tool to make profiling operations with java batch programs 
developed with spring batch framework.

With Spring Batch Framework, I want to make profiling the method write in the class ItemWriter like the extract example code below :

public class StringItemWriter implements ItemWriter<String> {

private static final Logger LOGGER =LoggerFactory.getLogger(StringItemWriter.class);

public void write(List<? extends String> items) throws Exception {

	for(String item : items) {
					LOGGER.info("writing "+item);
				 }

	}
}

Do you have an idea to help me writing the json configuration file ?

Thank in advance

**Comment by apangin** [comment]
@quochoangnguyen Are you writing to the right project? :) I'm not Trask, have no idea about Glowroot or Spring Batch, and there is no json configuration files in async-profiler.

**Comment by quochoangnguyen** [comment]
Hi Apangin

I am very sorry for this mistake.

Regards,

Nguyen
