### ISSUE TITLE
Azul Zinc support

### ISSUE THREAD

**Issue by martin-g** [jvm-profiling-tools/async-profiler#153]
Hi,

This is not a bug report but rather a question: is Azul Zinc JVM (https://www.azul.com/products/zing/) supported ?
The only ticket mentioning Azul is https://github.com/jvm-profiling-tools/async-profiler/issues/143, but there @dsyer uses `libasyncProfiler.so`, while I try to attach to a running Java process:

```
~/dev/async-profiler-1.4/profiler.sh -d 30 -f /tmp/flame1.svg 14305  
Could not start attach mechanism: No such file or directory
```

In https://github.com/jvm-profiling-tools/async-profiler#troubleshooting there are three possible reasons for this error:

```
1) /tmp directory of Java process is physically the same directory as /tmp of your shell.
2) Attach socket /tmp/.java_pidNNN has not been deleted.
3) JVM is not run with -XX:+DisableAttachMechanism option.
```

1) should be OK because I run it directly on my dev Ubuntu, no containers involved.
2) there is **no** such file, but there is no such file even for OpenJDK 1.8.0_181
3) At least I have not set it. Not sure whether Azul does something internally. `jinfo PID` fails with
```
Error attaching to process: Doesn't appear to be a HotSpot VM (could not find symbol "gHotSpotVMTypes" in remote process)
sun.jvm.hotspot.debugger.DebuggerException: Doesn't appear to be a HotSpot VM (could not find symbol "gHotSpotVMTypes" in remote process)
	at sun.jvm.hotspot.HotSpotAgent.setupVM(HotSpotAgent.java:412)
```

**Comment by apangin** [comment]
As README says, async-profiler works with Java runtimes based on HotSpot JVM.

Azul Zing is **not** supported, while Azul Zulu (which is build of OpenJDK) is.

**Comment by martin-g** [comment]
Thank you for the answer, @apangin !

**Comment by apangin** [comment]
### Update

I've verified that with some [minor fixes](https://github.com/jvm-profiling-tools/async-profiler/commit/2829aa7f0ae2fef512aa05fe8a6b3848baf1975b) async-profiler **works** with the latest Zing 18.12.0.0 (both JDK 8 and JDK 11 variants).

`cpu`, `perf_events`, `lock` and `wall` profiling modes are fine. Only `alloc` mode does not work.

There is a problem with traversing native stack of JIT compiler, but that's not an async-profiler's fault. Java stacks look good.
