### ISSUE TITLE
Question about traces file merge and conversion

### ISSUE THREAD

**Issue by wenleix** [jvm-profiling-tools/async-profiler#156]
Thanks for making this great Java profiling tool. I have two questions in terms of trace files:

- Is there any way to merge trace files? (Instead of writing my tools :) )

- Is there any way to convert trace file to collapsed stacks can be consumed by https://github.com/brendangregg/FlameGraph ? I know I can use `-o collapsed` to directly generated collapsed stack, but can I convert existing trace files to collapsed stack files?

Thanks!

**Comment by apangin** [comment]
@wenleix I'm in doubt, what trace files do you mean? Default text representation of the hottest stack traces? This is more like a human readable format, not indended for automated processing. Though it's pretty easy to convert it to collapsed format with a five-minute script.

`-o collapsed` is a recommended way to dump profile in the format suitable for post-processing.

`-o svg` can be also used to generate FlameGraph directly without third-party tools.

**Comment by apangin** [comment]
@aalexand Async-profiler can dump results as

- general purpose 'collapsed' format (`-o collapsed`);
- flame graph SVG (`-o svg`);
- interactive HTML caller/callee tree (`-o tree`);
- JFR format (`-o jfr`) viewable in Java Misson Control and parseable with [JMC API](http://hirt.se/blog/?p=920).

So, there is already a number of UI options available, and I also welcome contributions to provide converters to other popular formats.

**Comment by wenleix** [comment]
Thanks @apangin 

> -o collapsed is a recommended way to dump profile in the format suitable for post-processing.
I understand I can use `-o collapsed` to get collapsed trace. But I have some trace files generated by async-profiler use `-o trace` and I would like to convert them to collapsed trace :) 


At a high-level, I want to do "continuous profiling", i.e. sample 1 seconds for every 1 minute. I write a script to do this, and get a trace file for every minute. However today I don't see a way to merge them :(

**Comment by apangin** [comment]
Here is a simple script to convert `traces` format to `collapsed`.  
Merging `collapsed` profiles is trivial: just concatenate the files.

```python
#!/usr/bin/python
import re
import sys

while True:
    line = sys.stdin.readline()
    if not line:
        break

    samples = re.search("(\d+) sample", line).group(1)
    trace = ""

    while True:
        frame = sys.stdin.readline()
        if not frame or len(frame) < 4:
            break
        trace = frame[frame.find("]")+2:-1] + ("" if trace == "" else ";") + trace

    print(trace + " " + samples)
```
