### ISSUE TITLE
Profiler does not record failed samples in JFR

### ISSUE THREAD

**Issue by nitsanw** [jvm-profiling-tools/async-profiler#163]
See here:
https://github.com/jvm-profiling-tools/async-profiler/blob/2ceb1d1e952aa5f5502898a1777fdf067a26463b/src/profiler.cpp#L353

**Comment by nitsanw** [comment]
On closer inspection, only summary handles errors. It would be good to handle the errors as frames. Also non java threads are non-errors, so no need to account for them.

**Comment by apangin** [comment]
Flamegraph now includes all AsyncGetCallTrace failures, e.g. `[unknown_Java]`:

![unknown_java](https://user-images.githubusercontent.com/1749416/52920323-3d2d7180-331c-11e9-8974-47596dd1ddc4.jpg)

Also native threads (including GC and compiler threads) and no longer listed as errors.

**Comment by nitsanw** [comment]
Thanks!
