### ISSUE TITLE
Generate summary from trace file

### ISSUE THREAD

**Issue by wenleix** [jvm-profiling-tools/async-profiler#164]
Hi, 

I am wondering if there is any command to generate summary from the raw trace files (or collapsed stacks) 

Thanks!!

Best,
Wenlei

**Comment by apangin** [comment]
Hi @wenleix
Please clarify what kind of summary would you like to get from trace files and why.

**Comment by nitsanw** [comment]
@wenleix There are a few of options for viewing the collapsed stacks profile:
- Use flamegraphs
- Scripted summary (awk/sed/grep scripts)
- Use speedscope
- Use IntelliJ (import profile)

**Comment by KirillTim** [comment]
@wenleix you can read here about IntelliJ integration: https://blog.jetbrains.com/idea/2018/09/intellij-idea-2018-3-eap-git-submodules-jvm-profiler-macos-and-linux-and-more/
