### ISSUE TITLE
Failed to inject profiler into

### ISSUE THREAD

**Issue by pilot513** [jvm-profiling-tools/async-profiler#166]
When run ./profiler.sh -d 60 [pid]  (user id 0) get error:
`bash: command substitution: line 1: unexpected EOF while looking for matching `"'
bash: command substitution: line 2: syntax error: unexpected end of file
Failed to inject profiler into 49642
        linux-vdso.so.1 =>  (0x00007fffd5bf7000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fc9cdcd2000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fc9cdab6000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fc9cd8ad000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fc9cd5a5000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fc9cd2a3000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fc9cd08c000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fc9cccc9000)
        /lib64/ld-linux-x86-64.so.2 (0x000055b88f811000)`

I try run Profiler (compiled, and downloaded)

OEL 7
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

4.1.12-103.3.8.el7uek.x86_64 #2 SMP Mon Aug 21 17:27:54 PDT 2017 x86_64

Can you help me ?

**Comment by apangin** [comment]
Please add `set -x` in the beginning of `profiler.sh` script to see all executed lines.

**Comment by pilot513** [comment]
`+ OPTIND=1
++ dirname ./profiler.sh
+ SCRIPT_DIR=.
+ JATTACH=./build/jattach
++ abspath ./build/libasyncProfiler.so
+++ uname -s
++ UNAME_S=Linux
++ '[' Linux == Darwin ']'
++ readlink -f ./build/libasyncProfiler.so
+ PROFILER=/home/pilot/build/libasyncProfiler.so
+ ACTION=collect
+ EVENT=cpu
+ DURATION=60
+ FILE=
+ USE_TMP=true
+ INTERVAL=
+ JSTACKDEPTH=
+ FRAMEBUF=
+ THREADS=
+ OUTPUT=
+ FORMAT=
+ [[ 3 -gt 0 ]]
+ case $1 in
+ DURATION=60
+ shift
+ shift
+ [[ 1 -gt 0 ]]
+ case $1 in
+ PID=49642
+ shift
+ [[ 0 -gt 0 ]]
+ [[ 49642 == '' ]]
+ [[ -n true ]]
+ FILE=/tmp/async-profiler.85392.49642
+ [[ '' == '' ]]
+ [[ /tmp/async-profiler.85392.49642 == *.svg ]]
+ [[ /tmp/async-profiler.85392.49642 == *.html ]]
+ [[ /tmp/async-profiler.85392.49642 == *.jfr ]]
+ [[ /tmp/async-profiler.85392.49642 == *.collapsed ]]
+ [[ /tmp/async-profiler.85392.49642 == *.folded ]]
+ OUTPUT=summary,traces=200,flat=200
+ case $ACTION in
+ jattach start,event=cpu,file=/tmp/async-profiler.85392.49642,summary,traces=200,flat=200
+ ./build/jattach 49642 load /home/pilot/build/libasyncProfiler.so true start,event=cpu,file=/tmp/async-profiler.85392.49642,summary,traces=200,flat=200
+ RET=255
+ '[' 255 -ne 0 ']'
+ '[' 255 -eq 255 ']'
+ echo 'Failed to inject profiler into 49642'
Failed to inject profiler into 49642
++ uname -s
+ UNAME_S=Linux
+ '[' Linux == Darwin ']'
+ ldd /home/pilot/build/libasyncProfiler.so
        linux-vdso.so.1 =>  (0x00007ffc809fb000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007ff260df9000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ff260bdd000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007ff2608d4000)
        libm.so.6 => /lib64/libm.so.6 (0x00007ff2605d2000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007ff2603bc000)
        libc.so.6 => /lib64/libc.so.6 (0x00007ff25fff8000)
        /lib64/ld-linux-x86-64.so.2 (0x000056319deb8000)
+ exit 255`

**Comment by apangin** [comment]
Looks like JVM failed to load libasyncProfiler.so.
Can you check if the following code works, and if not, what message it prints?
```
public class Test {
    public static void main(String[] args) {
        System.load("/path/to/libasyncProfiler.so");
    }
}
```

**Comment by apangin** [comment]
@pilot513 Type in the console
```
jrunscript -e "java.lang.System.load('/path/to/libasyncProfiler.so')"
```

**Comment by pilot513** [comment]
Ok. After runnung it - nothing... No errors or any messages

**Comment by apangin** [comment]
OK. If the library loads fine, then probably jattach doesn't work. Please try the following commands in the console:
```
./build/jattach PID load /home/pilot/build/libasyncProfiler.so true start,event=cpu
./build/jattach PID load /home/pilot/build/libasyncProfiler.so true stop,summary
```
where PID is the process ID of the target Java application.

**Comment by pilot513** [comment]
both return:
Connected to remote JVM
Response code = -1

**Comment by apangin** [comment]
Is anything printed in stderr of the target process?

**Comment by pilot513** [comment]
Yes, worked! Thanks!
