### ISSUE TITLE
Error reading response: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by BenoitVatan** [jvm-profiling-tools/async-profiler#168]
Hi,

I'm trying to run async-profiler on an old RHEL5 Linux.
I get an error preceded by 2 warnings and then the target process is aborted.

I don't really know where to start here, so if you could give me a hint I would really appreciate.

**./profiler.sh -d 30 -e cpu -o svg -f `pwd`/profile.svg 5796**
**WARNING: couldn't find container pid of the target process
WARNING: couldn't enter target process mnt namespace
Error reading response: Inappropriate ioctl for device**
-jbossadm@server ./run.sh: line 286:  5796 Aborted                 "/usr/java/default//bin/java" -Dprogram.name=run.sh -server -Xss256k -XX:NewSize=2048m -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -Xmx10g -Xms10g [...]

**Linux is :**
Red Hat Enterprise Linux Server release 5.11 (Tikanga)
Linux server 2.6.18-426.el5 #1 SMP Wed Feb 7 11:05:23 EST 2018 x86_64 x86_64 x86_64 GNU/Linux

**Java version** 
jdk1.6.0_191

**Full command line**
-jbossadm@server ./profiler.sh -d 30 -e cpu -o svg -f `pwd`/profile.svg 5796
+ OPTIND=1
++ dirname ./profiler.sh
+ SCRIPT_DIR=.
+ JATTACH=./build/jattach
++ abspath ./build/libasyncProfiler.so
+++ uname -s
++ UNAME_S=Linux
++ '[' Linux == Darwin ']'
++ readlink -f ./build/libasyncProfiler.so
+ PROFILER=/app/jboss/deployments/scripts/async-profiler/build/libasyncProfiler.so
+ ACTION=collect
+ EVENT=cpu
+ DURATION=60
+ FILE=
+ USE_TMP=true
+ INTERVAL=
+ JSTACKDEPTH=
+ FRAMEBUF=
+ THREADS=
+ OUTPUT=
+ FORMAT=
+ [[ 9 -gt 0 ]]
+ case $1 in
+ DURATION=30
+ shift
+ shift
+ [[ 7 -gt 0 ]]
+ case $1 in
+ EVENT=cpu
+ shift
+ shift
+ [[ 5 -gt 0 ]]
+ case $1 in
+ OUTPUT=svg
+ shift
+ shift
+ [[ 3 -gt 0 ]]
+ case $1 in
+ FILE=/app/jboss/deployments/scripts/async-profiler/profile.svg
+ unset USE_TMP
+ shift
+ shift
+ [[ 1 -gt 0 ]]
+ case $1 in
+ PID=5796
+ shift
+ [[ 0 -gt 0 ]]
+ [[ 5796 == '' ]]
+ [[ -n '' ]]
+ [[ svg == '' ]]
+ case $ACTION in
+ jattach start,event=cpu,file=/app/jboss/deployments/scripts/async-profiler/profile.svg,svg
+ ./build/jattach 5796 load /app/jboss/deployments/scripts/async-profiler/build/libasyncProfiler.so true start,event=cpu,file=/app/jboss/deployments/scripts/async-profiler/profile.svg,svg
WARNING: couldn't find container pid of the target process
WARNING: couldn't enter target process mnt namespace
Error reading response: Inappropriate ioctl for device
+ RET=1
+ '[' 1 -ne 0 ']'
+ '[' 1 -eq 255 ']'
+ exit 1
-jbossadm@server ./run.sh: line 286:  5796 Aborted                 "/usr/java/default//bin/java" -Dprogram.name=run.sh -server -Xss256k -XX:NewSize=2048m -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -Xmx10g -Xms10g -XX:PermSize=300m -XX:MaxPermSize=300m -XX:+DisableExplicitGC -XX:+CMSClassUnloadingEnabled -XX:+CMSPermGenSweepingEnabled -XX:MaxNewSize=2048m -XX:MaxGCPauseMillis=1000 -Dsun.rmi.dgc.server.gcInterval=3600000 -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.transport.tcp.handshakeTimeout=180000 -Dsun.rmi.transport.connectionTimeout=30000 -Datg.dynamo.layers= -XX:+HeapDumpOnOutOfMemoryError -Ddisable.atg.dynamo.log=true -XX:HeapDumpPath=/app/jboss -XX:+PrintGCApplicationConcurrentTime -XX:+PrintGCApplicationStoppedTime -XX:+PrintTenuringDistribution -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintHeapAtGC -Xloggc:/app/jboss/jboss-eap-5.1/jboss-as/server/prod1-1/log/gc.log-2018_10_19-14_39 -XX:ErrorFile=/app/jboss/java_error%p.log -Xrs -XX:SurvivorRatio=6 -XX:MaxTenuringThreshold=12 -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:+UseParNewGC -XX:ConcGCThreads=2 -XX:ParallelGCThreads=4 -XX:-UseGCOverheadLimit -Dcom.sun.management.jmxremote.port=3333 -XX:TargetSurvivorRatio=90 -XX:+ScavengeBeforeFullGC -XX:+CMSScavengeBeforeRemark -Dsun.net.inetaddr.ttl=60 -Dnetworkaddress.cache.ttl=60 -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv6Addresses=false -Dsun.net.http.retryPost=false -XX:+PerfDisableSharedMem -Djboss.platform.mbeanserver -Djavax.management.builder.initial=org.jboss.system.server.jmx.MBeanServerBuilderImpl -Dcom.sun.management.jmxremote.password.file=/app/jboss/jboss-eap-5.1/jboss-as/bin/jmxpassword.conf -Dcom.sun.management.jmxremote.access.file=/app/jboss/jboss-eap-5.1/jboss-as/bin/jmxaccess.conf -Dcom.sun.management.jmxremote.ssl=false -Djavax.xml.rpc.ServiceFactory=org.jboss.ws.core.jaxrpc.client.ServiceFactoryImpl -Djavax.xml.soap.MessageFactory=org.jboss.ws.core.soap.MessageFactoryImpl -Djavax.xml.soap.MetaFactory=org.jboss.ws.core.soap.SAAJMetaFactoryImpl -Djavax.xml.soap.SOAPConnectionFactory=org.jboss.ws.core.soap.SOAPConnectionFactoryImpl -Djavax.xml.soap.SOAPFactory=org.jboss.ws.core.soap.SOAPFactoryImpl -Djavax.xml.ws.spi.Provider=org.jboss.ws.core.jaxws.spi.ProviderImpl -Djavax.net.ssl.trustStore=/app/jboss/jboss-eap-5.1/jboss-as/bin/cacerts -Dorg.apache.jasper.Constants.INJECT_TAGS=false -Dorg.apache.jasper.Constants.USE_INSTANCE_MANAGER_FOR_TAGS=false -DENABLE_BUG_REPORT=true -Djava.net.preferIPv4Stack=true -Djava.endorsed.dirs="/app/jboss/jboss-eap-5.1/jboss-as/lib/endorsed" -classpath "/app/jboss/jboss-eap-5.1/jboss-as/bin/run.jar:/usr/java/default//lib/tools.jar" org.jboss.Main -c prod1-1 -Djboss.server.log.threshold=WARN -Djava.awt.headless=true -Duser.timezone=CET -Djboss.service.binding.set=ports-default -b 0.0.0.0

Thanks for reading.

**Comment by BenoitVatan** [comment]
That is what I feared. A kernel upgrade is not possible in my case for some reason.
It might be a good advantage for async-profiler to be able to profile old platforms, even with limited output.
Anyway, I will arrange myself and try another solution.
Thank you very much for your time

**Comment by apangin** [comment]
I've created a special version that does not rely on perf_events support. Please check [itimer](https://github.com/jvm-profiling-tools/async-profiler/tree/itimer) branch and tell if it works for you.

**Comment by apangin** [comment]
You may try binaries built by my own - [async-profiler-1.5-itimer-linux-x64.tar.gz](https://github.com/jvm-profiling-tools/async-profiler/files/2514662/async-profiler-1.5-itimer-linux-x64.tar.gz). Not sure they will work though - they depend on GLIBC 2.2.5 and GLIBC++ 3.4.

**Comment by BenoitVatan** [comment]
Just tried your build and I'm getting the same ioctl error, then the process is killed (see after).
Will try playing with LD_LIBRARY_PATH, it might pass if there is not too much spread within versions...
Thank you for tour custom build.

`./profiler.sh -f profile.out -o svg 23078
+ OPTIND=1
++ uname -s
+ UNAME_S=Linux
+++ abspath ./profiler.sh
+++ '[' Linux == Darwin ']'
+++ readlink -f ./profiler.sh
++ dirname /app/atg/perf/lt/monitoring/async-profiler/profiler.sh
+ SCRIPT_DIR=/app/atg/perf/lt/monitoring/async-profiler
+ JATTACH=/app/atg/perf/lt/monitoring/async-profiler/build/jattach
+ PROFILER=/app/atg/perf/lt/monitoring/async-profiler/build/libasyncProfiler.so
+ ACTION=collect
+ EVENT=cpu
+ DURATION=60
+ FILE=
+ USE_TMP=true
+ INTERVAL=
+ JSTACKDEPTH=
+ FRAMEBUF=
+ THREADS=
+ OUTPUT=
+ FORMAT=
+ [[ 5 -gt 0 ]]
+ case $1 in
+ FILE=profile.out
+ unset USE_TMP
+ shift
+ shift
+ [[ 3 -gt 0 ]]
+ case $1 in
+ OUTPUT=svg
+ shift
+ shift
+ [[ 1 -gt 0 ]]
+ case $1 in
+ PID=23078
+ shift
+ [[ 0 -gt 0 ]]
+ [[ 23078 == '' ]]
+ [[ -n '' ]]
+ [[ svg == '' ]]
+ case $ACTION in
+ jattach start,event=cpu,file=profile.out,svg
+ /app/atg/perf/lt/monitoring/async-profiler/build/jattach 23078 load /app/atg/perf/lt/monitoring/async-profiler/build/libasyncProfiler.so true start,event=cpu,file=profile.out,svg
Error reading response: Inappropriate ioctl for device
+ RET=1
+ '[' 1 -ne 0 ']'
+ '[' 1 -eq 255 ']'
+ exit 1`

**Comment by apangin** [comment]
This cannot be my recent 'itimer' build, since it does not call `ioctl()` at all.
I suppose this is a leftover from previous profiling attempts. Once the profiler library is loaded into the target JVM process, it cannot be replaced until the process restarts. So, you are trying to attach a new version of the profiler, but the older one is already loaded.

**Comment by BenoitVatan** [comment]
I see, thanks for pointing this. I will restart from a fresh extract and check.

**Comment by BenoitVatan** [comment]
Hi,
I looked into this but had to move to a centos5.11 VM so I that I could install strace and see what went wrong.
Moving from RHEL5.1 to CentOS5.1 made it possible to trace things out but this time the JVM crashes earlier. jattach cannot read socket and terminates with an error stating that socket file does not exist, and indeed, the file does not exist (anymore ? after JVM has crashed ?)
This [archive](https://github.com/jvm-profiling-tools/async-profiler/files/2540521/async-profiler-issue-centos5.11-jdk6.tar.gz) contains all stdout/stderr of JVM and the strace of jattach

I think the relevant strace output lies here :

```
kill(4947, SIGQUIT)                                                                                 = 0
nanosleep({0, 20000000}, NULL)                                                                      = 0
stat("/tmp/.java_pid4947", {st_dev=makedev(253, 0), st_ino=520206, st_mode=S_IFSOCK|0600, st_nlink=1, st_uid=500, st_gid=500, st_blksize=4096, st_blocks=8, st_size=0, st_atime=2018/11/01-23:40:01, st_mtime=2018/11/01-23:40:01, st_ctime=2018/11/01-23:40:01}) = 0
unlink("/proc/4947/cwd/.attach_pid4947")                                                            = 0
socket(PF_FILE, SOCK_STREAM, 0)                                                                     = 3
connect(3, {sa_family=AF_FILE, path="/tmp/.java_pid4947"...}, 110)                                  = 0
fstat(1, {st_dev=makedev(253, 0), st_ino=520204, st_mode=S_IFREG|0664, st_nlink=1, st_uid=500, st_gid=500, st_blksize=4096, st_blocks=8, st_size=0, st_atime=2018/11/01-23:39:13, st_mtime=2018/11/01-23:40:01, st_ctime=2018/11/01-23:40:01}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0)                            = 0x2b27f21f6000
write(3, "\x31\x00", 2)                                                                             = 2
 | 00000  31 00                                             1.                |
write(3, "\x6c\x6f\x61\x64\x00", 5)                                                                 = 5
 | 00000  6c 6f 61 64 00                                    load.             |
write(3, "/home/benoit/async-profiler-1.5-itimer/build/libas"..., 65)                               = 65
 | 00000  2f 68 6f 6d 65 2f 62 65  6e 6f 69 74 2f 61 73 79  /home/be noit/asy |
 | 00010  6e 63 2d 70 72 6f 66 69  6c 65 72 2d 31 2e 35 2d  nc-profi ler-1.5- |
 | 00020  69 74 69 6d 65 72 2f 62  75 69 6c 64 2f 6c 69 62  itimer/b uild/lib |
 | 00030  61 73 79 6e 63 50 72 6f  66 69 6c 65 72 2e 73 6f  asyncPro filer.so |
 | 00040  00                                                .                 |
write(3, "\x74\x72\x75\x65\x00", 5)                                                                 = 5
 | 00000  74 72 75 65 00                                    true.             |
write(3, "\x73\x74\x61\x72\x74\x2c\x65\x76\x65\x6e\x74\x3d\x63\x70\x75\x2c\x66\x69\x6c\x65\x3d\x70\x72\x6f\x66\x69\x6c\x65\x2e\x6f\x75\x74\x2c\x73\x76\x67\x00", 37) = 37
 | 00000  73 74 61 72 74 2c 65 76  65 6e 74 3d 63 70 75 2c  start,ev ent=cpu, |
 | 00010  66 69 6c 65 3d 70 72 6f  66 69 6c 65 2e 6f 75 74  file=pro file.out |
 | 00020  2c 73 76 67 00                                    ,svg.             |
write(1, "Connected to remote JVM\nResponse code = ", 40)                                           = 40
read(3, "", 8191)                                                                                   = 0
dup(2)                                                                                              = 4
fcntl(4, F_GETFL)                                                                                   = 0x8001 (flags O_WRONLY|O_LARGEFILE)
close(4)                                                                                            = 0
write(2, "Error reading response: No such file or directory\n", 50Error reading response: No such file or directory
)                                 = 50
close(3)                                                                                            = 0
write(1, "\n", 1)                                                                                   = 1
exit_group(1)   
```
The JVM stdout:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00002ae343209b19, pid=4947, tid=47155572050240
#
# JRE version: 6.0_191-b09
# Java VM: Java HotSpot(TM) 64-Bit Server VM (20.191-b09 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libasyncProfiler.so+0x18b19]  ElfParser::parseMem(NativeCodeCache*, char const*, void const*)+0x9
#
# An error report file with more information is saved as:
# /home/benoit/async-profiler-1.5-itimer/hs_err_pid4947.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```
It looks like something in libasyncProfiler.so makes the JVM crash, then jattach tries to read socket file which does not exist anymore. Not sure though that this is the real scenario here.

**Comment by apangin** [comment]
Is it possible you can share the full crash log `/home/benoit/async-profiler-1.5-itimer/hs_err_pid4947.log`? It will help much in solving the issue. Remove any sensitive data if needed. I'm particularly interested in "Registers", "Instructions" and "Dynamic libraries" sections.

**Comment by BenoitVatan** [comment]
All the lof files contained in my previous archive archive:
[hs_err_pid4947.log](https://github.com/jvm-profiling-tools/async-profiler/files/2542061/hs_err_pid4947.log)
[jattach.err.log](https://github.com/jvm-profiling-tools/async-profiler/files/2542062/jattach.err.log)
[jattach.out.log](https://github.com/jvm-profiling-tools/async-profiler/files/2542063/jattach.out.log)
[profiler.err.log](https://github.com/jvm-profiling-tools/async-profiler/files/2542064/profiler.err.log)
[Test.err.log](https://github.com/jvm-profiling-tools/async-profiler/files/2542065/Test.err.log)
[Test.out.log](https://github.com/jvm-profiling-tools/async-profiler/files/2542066/Test.out.log)

**Comment by apangin** [comment]
Yes, I found the crash log and deleted my question shortly after.

This is a profiler bug also related to the old kernel. I'll create a fix shortly.

**Comment by apangin** [comment]
I've committed the fix. Check the updated binaries - [async-profiler-1.5-itimer-linux-x64.tar.gz](https://github.com/jvm-profiling-tools/async-profiler/files/2542438/async-profiler-1.5-itimer-linux-x64.tar.gz)

**Comment by BenoitVatan** [comment]
Hi !
I could finally test this on both Centos5.11 and RHEL5.1 boxes.
It works !
No more .so version error and no more crash.
Thank you for the time spent !

**Comment by apangin** [comment]
I merged `itimer` profiling mode into master.
Now `-e itimer` will allow profiling on systems that don't support perf_events.
