### ISSUE TITLE
Profile application that runs on top if Kubernetes?

### ISSUE THREAD

**Issue by apollotonkosmo** [jvm-profiling-tools/async-profiler#170]
Hello there,

Do you know how to run the profiler for an app that runs on kubernetes? I have tried from within the container but failes with:

> `"Perf events unavailble. See stderr of the target process."`

And also tried from within a kubernetes node with error:
>`Failed to inject profiler into 74053
	linux-vdso.so.1 =>  (0x00007fff48f78000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f914ce02000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f914cbe5000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f914c863000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f914c55a000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f914c344000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f914bf7a000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f914d6b0000)`
Anyone did this with success?
Thank you 
G.

**Comment by apangin** [comment]
Extended Troubleshooting section with more details.
Added a section about profiling in a container.

Implemented `itimer` profiling mode to workaround various restrictions.
