### ISSUE TITLE
please add arm release

### ISSUE THREAD

**Issue by rpodgorny** [jvm-profiling-tools/async-profiler#171]

**Comment by apangin** [comment]
There are many different ARM platforms featuring various CPU architectures, Linux kernels, versions of LIBC etc. I can include, for example, a Raspbian build in the next release, but it won't necessarily work on somebody's particular platform.

What architecture/platform are you interested in? Does current build procedure seem too hard?

**Comment by apangin** [comment]
Release 1.5 now includes binaries for ARMv7.

**Comment by martin-g** [comment]
Sorry for commenting in an old and closed issue but I think my comment does not deserve a new issue. I'm writing it here in case someone else looks for ARM64/AARCH64 binaries.

https://github.com/jvm-profiling-tools/async-profiler#supported-platforms says that AARCH64 is supported for Linux. Indeed, if I build it locally it works just fine!
I just wanted to mention that the `-arm.tar.gz` bundle in the `Releases` section is 32-bit (ARMv7), so one needs to build it locally!

Thank you for Async Profiler, @apangin !
