### ISSUE TITLE
JFR recordings have inversed stacktraces when loaded in JMC

### ISSUE THREAD

**Issue by msogrin** [jvm-profiling-tools/async-profiler#172]
When JFR recording, produced by this async profiler, is loaded into Java Mission Control (I tried version 5.5 bundled with JDK 8), then methods are presented with stacktraces inversed, compared to what's expected. For example, "hot methods" shows methods starting with `main` function. However, if recording were made by the actual JFR agent, then "hot methods" shows the actual hot methods. 

The issue can be fixed by reverting the order in the loop at
https://github.com/jvm-profiling-tools/async-profiler/blob/master/src/flightRecorder.cpp#L562

**Comment by apangin** [comment]
You are right! Don't know how I could miss that.
I've committed the fix.
Thank you!
