### ISSUE TITLE
Output seperately every 1s to catch the  reason of CPU spike

### ISSUE THREAD

**Issue by calvin1978** [jvm-profiling-tools/async-profiler#173]
to catch the reason of CPU spike, i hope to  output the profiling result every 1 second.

now, i write a shell script to loop it

`async-profiler. sh -d 1 ${PID}>${DATE_TIME}_result.log`

but if the system busy, 10:30:01's result would finish writing at 10:30:03, so 10:30:02 missed.

so i hope the profiler can try to continue collect data and output separately every 1s.

**Comment by plokhotnyuk** [comment]
As a follow up for easier spotting of spikes the heatmap representation can be used, like here: 

https://github.com/Netflix/flamescope

**Comment by apangin** [comment]
Yes, there are plans to implement continuous profiling. Not in the nearest release though.

Note that currently profiler can be attached only at safepoint pause - that's the limitation of HotSpot Attach mechanism. So, for example, if JVM is busy with Garbage Collection, the profiler will start only after GC is over. I guess something similar happens in your case. Increasing profiling duration might help in this case.

**Comment by apangin** [comment]
JFR output (`-o jfr`) should solve the problem, as it records all timing data with the collected samples.

The support for flamescopes has been recently added in #248.
