### ISSUE TITLE
Some items in documentation is not clear, tmp folder and exceptions

### ISSUE THREAD

**Issue by egor-ryashin** [jvm-profiling-tools/async-profiler#175]
1. `/tmp directory of Java process is physically the same directory as /tmp of your shell.` What `bash` shell commands should I run to ensure that?
2. I run command as the same user as JVM:
./profiler.sh -d 30 -e alloc  -f data.svg 111209
But I'm getting:
`Could not start attach mechanism: No such file or directory`
How to debug it further?

**Comment by apangin** [comment]
1. Two processes may have different `/tmp` directories if

- they run in different mount namespaces, or
- at least on of the processes is run in chroot environment

I'll paraphrase the statement in README.

2. Try the following command and tell what it prints:
```
strace build/jattach <pid> properties
```

**Comment by stefanodoni** [comment]
Related to this aspect,

It's not clear from the doc how to use async-profiler with dockerized Java apps. Would be great if you could add a section on how to accomplish that. I think many more users would be able to use the profiler.

Thank you

**Comment by egor-ryashin** [comment]
@apangin  ```strace build/jattach 111209 load /home/egor.ryashin/async/build/libasyncProfiler.so true start,event=alloc,file=t.svg,svg
execve("build/jattach", ["build/jattach", "111209", "load", "/home/egor.ryashin/async/build/l"..., "true", "start,event=alloc,file=t.svg,svg"], [/* 19 vars */]) = 0
brk(0)                                  = 0x168d000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f7ffd807000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=33454, ...}) = 0
mmap(NULL, 33454, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f7ffd7fe000
close(3)                                = 0
open("/lib64/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0`\n\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1730352, ...}) = 0
mmap(NULL, 3838848, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f7ffd23a000
mprotect(0x7f7ffd3d9000, 2097152, PROT_NONE) = 0
mmap(0x7f7ffd5d9000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x19f000) = 0x7f7ffd5d9000
mmap(0x7f7ffd5df000, 17280, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f7ffd5df000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f7ffd7fd000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f7ffd7fc000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f7ffd7fb000
arch_prctl(ARCH_SET_FS, 0x7f7ffd7fc700) = 0
mprotect(0x7f7ffd5d9000, 16384, PROT_READ) = 0
mprotect(0x602000, 4096, PROT_READ)     = 0
mprotect(0x7f7ffd808000, 4096, PROT_READ) = 0
munmap(0x7f7ffd7fe000, 33454)           = 0
geteuid()                               = 1000
getegid()                               = 1000
brk(0)                                  = 0x168d000
brk(0x16ae000)                          = 0x16ae000
open("/proc/111209/status", O_RDONLY)   = 3
fstat(3, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
read(3, "Name:\tjava\nUmask:\t0022\nState:\tS "..., 1024) = 1024
read(3, "owed_list:\t0-1\nvoluntary_ctxt_sw"..., 1024) = 74
read(3, "", 1024)                       = 0
close(3)                                = 0
open("/proc/self/ns/mnt", O_RDONLY)     = 3
open("/proc/111209/ns/mnt", O_RDONLY)   = 4
fstat(3, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
fstat(4, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
rt_sigaction(SIGPIPE, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x7f7ffd26dfd0}, {SIG_DFL, [], 0}, 8) = 0
stat("/tmp/.java_pid111209", 0x7ffc8f7d03b0) = -1 ENOENT (No such file or directory)
creat("/proc/111209/cwd/.attach_pid111209", 0660) = 5
close(5)                                = 0
stat("/proc/111209/cwd/.attach_pid111209", {st_mode=S_IFREG|0640, st_size=0, ...}) = 0
geteuid()                               = 1000
kill(111209, SIGQUIT)                   = 0
nanosleep({0, 100000000}, NULL)         = 0
stat("/tmp/.java_pid111209", 0x7ffc8f7d03b0) = -1 ENOENT (No such file or directory)
nanosleep({0, 100000000}, NULL)         = 0
stat("/tmp/.java_pid111209", 0x7ffc8f7d03b0) = -1 ENOENT (No such file or directory)
nanosleep({0, 100000000}, NULL)         = 0
stat("/tmp/.java_pid111209", 0x7ffc8f7d03b0) = -1 ENOENT (No such file or directory)
nanosleep({0, 100000000}, NULL)         = 0
stat("/tmp/.java_pid111209", 0x7ffc8f7d03b0) = -1 ENOENT (No such file or directory)
nanosleep({0, 100000000}, NULL)         = 0
stat("/tmp/.java_pid111209", 0x7ffc8f7d03b0) = -1 ENOENT (No such file or directory)
nanosleep({0, 100000000}, NULL)         = 0
stat("/tmp/.java_pid111209", 0x7ffc8f7d03b0) = -1 ENOENT (No such file or directory)
nanosleep({0, 100000000}, NULL)         = 0
stat("/tmp/.java_pid111209", 0x7ffc8f7d03b0) = -1 ENOENT (No such file or directory)
nanosleep({0, 100000000}, NULL)         = 0
stat("/tmp/.java_pid111209", 0x7ffc8f7d03b0) = -1 ENOENT (No such file or directory)
nanosleep({0, 100000000}, NULL)         = 0
stat("/tmp/.java_pid111209", 0x7ffc8f7d03b0) = -1 ENOENT (No such file or directory)
nanosleep({0, 100000000}, NULL)         = 0
stat("/tmp/.java_pid111209", 0x7ffc8f7d03b0) = -1 ENOENT (No such file or directory)
unlink("/proc/111209/cwd/.attach_pid111209") = 0
dup(2)                                  = 5
fcntl(5, F_GETFL)                       = 0x8002 (flags O_RDWR|O_LARGEFILE)
fstat(5, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
write(5, "Could not start attach mechanism"..., 60Could not start attach mechanism: No such file or directory
) = 60
close(5)                                = 0
exit_group(1)                           = ?
+++ exited with 1 +++```
At the same time it works of another process with the user and group.

**Comment by apangin** [comment]
@egor-ryashin It looks like jattach successfully sends a signal to the process, but JVM does not respond.

- Does `jcmd 111209 help` work?
- Is thread dump printed in the console of the target application after jattach attempt?
- Does `readlink -f /proc/111209/root/tmp` print `/tmp` or something else?
- Is there any `.java_pidNNN` file listed in `ls -la /proc/111209/fd`?
- Do you see a thread named `Attach Listener` in a thread dump of the target JVM?

Sorry for so many questions, but there are many reasons why attach may not work.

**Comment by egor-ryashin** [comment]
1) Don't have jdk on the instance, right now
2) `kill -3` works
3) Yes
4) None
5) 
```
"Attach Listener" #514 daemon prio=9 os_prio=0 tid=0x00007f4148000ad0 nid=0x1fd03 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
```

**Comment by egor-ryashin** [comment]
quite strange:
```java    111209 xncore 1022u     unix 0xffffa0901eb8bc00       0t0   746141493 /tmp/.java_pid111209.tmp type=STREAM
xncore@aws-prod-mesos-i-058483b068723b0a1 ~ $ ls -al /tmp/.j*
srw-------. 1 xncore xncore 0 Nov 13 16:48 /tmp/.java_pid111210```

**Comment by apangin** [comment]
So this apparently mean that `/tmp/.java_pid111209` has been deleted. It's not uncommon practice to clear `/tmp` by an automated script scheduled in crontab or something. If this is the case, add `.java_pid*` to an exclude list.

No need to check `jstack`/`jcmd` tools - I'm sure they will not work, too. Unfortunately, I don't know any workaround that will re-enable attach without restarting JVM.

This problem is already listed in troubleshooting section of README:

> For the profiler to be able to access JVM, make sure ...
> 2. Attach socket /tmp/.java_pidNNN has not been deleted.

Though I probably have to document the details how to check this.

**Comment by apangin** [comment]
Extended Troubleshooting section with more details.
Added a section about profiling in a container.
