### ISSUE TITLE
crash when use LD_PRELOAD to dynamic link so file

### ISSUE THREAD

**Issue by calvin1978** [jvm-profiling-tools/async-profiler#176]
```
---------------  T H R E A D  ---------------

Current thread (0x00007fd5e80347e0):  JavaThread "WK-VRE-431" [_thread_in_vm, id=15749, stack(0x00007fd39a6e0000,0x00007fd39a7e1000)]

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x0000000000000000

Stack: [0x00007fd39a6e0000,0x00007fd39a7e1000],  sp=0x00007fd39a7ded60,  free space=1019k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)

C  [libc.so.6+0x9c90d]  time+0xd

C  [libc.so.6+0xaedf5]  __sysconf+0x345

V  [libjvm.so+0x7140dc]  JVM_ActiveProcessorCount+0xac

J 7183  java.lang.Runtime.availableProcessors()I (0 bytes) 

J 8925 C2 java.util.concurrent.CompletableFuture.waitingGet(Z)Ljava/lang/Object; (184 bytes) 
```

In Docker, we hack the sysconf system call to return the right cpu cores for   java.lang.Runtime.availableProcessors(), use below sentence to link it.

`export LD_PRELOAD="/usr/local/lib/libsysconfcpus.so:` 

then crash....

**Comment by apangin** [comment]
How is this related to async-profiler?

BTW, a better way to patch `Runtime.availableProcessors` in Docker is to use [bind mount](https://docs.docker.com/storage/bind-mounts/) to override `/sys/devices/system/cpu/online` file in the container or to use JDK 8u191+ which has buit-in support for this feature.
