### ISSUE TITLE
More perf events on Mac OS X?

### ISSUE THREAD

**Issue by jumarko** [jvm-profiling-tools/async-profiler#182]
I'm exploring the possibilities of the async-profiler on my Mac OS X 10.14.1 and would love to see more events, especially cache misses.
Is there any hope that support for these will be added later? 
Or is there any recommended alternative how to profile those events?

Edit: this is what async-profiler reports as supported events on my system:
```
./profiler.sh list 21520
Perf events:
  cpu
Java events:
  alloc
  lock
```

**Comment by apangin** [comment]
I wish I could add perf counters on macOS, but unfortunately there is no public API for that.

Instruments.app and [Intel Performance Counter Monitor](https://software.intel.com/en-us/articles/intel-performance-counter-monitor) are the only tools I know capable of reading PMC on macOS, but they can hardly be integrated with Java profiler.

It is also problematic to do kernel-level profiling on macOS for the reasons described in #95.

I'll be happy to accept contributions or at least ideas on how to go further with the discussed features, but so far this looks hopeless. ¯\_(ツ)_/¯
