### ISSUE TITLE
Simple collapsed output does not contain type hints

### ISSUE THREAD

**Issue by oehme** [jvm-profiling-tools/async-profiler#183]
When using both the `collapsed` and `simple` options, the type hints that help the flame graph tool with coloring frames are missing from the output. The built-in `svg` still colors correctly, but I can't always us it, since sometimes I want to `grep` the frames before creating a graph.

**Comment by apangin** [comment]
In fact, this is not a problem of `simple` mode.
async-profiler does not print color hints in either modes except for kernel frames. `collapsed` output is a general purpose format, not specifically designed for FlameGraph script only. I believe it's more appropriate to fix Java coloring scheme in `flamegraph.pl`.

However, I could probably add a command-line switch to annotate all Java frames.

**Comment by oehme** [comment]
Having an option to get `collapsed` frames specifically for use with the flamegraph tool would be great. 

Out of curiosity, what other tools make use of that format?

**Comment by apangin** [comment]
I remember seeing alternative flame graph generators and various plugins.
Anyway, I've added `-a` option to always append `_[j]` suffix to Java methods.

**Comment by oehme** [comment]
Thank you!
