### ISSUE TITLE
cpu profiling delivers wrong result

### ISSUE THREAD

**Issue by oehme** [jvm-profiling-tools/async-profiler#184]
I just profiled some Gradle builds using async-profiler and I noticed that the `cpu` profile has some really odd hot spots that definitely don't match reality:

<img width="1200" alt="cpu-profile" src="https://user-images.githubusercontent.com/1191797/50374931-a5e6bf00-05f5-11e9-8330-1356179dd860.png">

You can see `open()` calls completely dominating the profile. I cross-checked this with the `wall` profiler (focussing only on the thread in question). The open calls are highlighted in purple. As you can see they really only make up ~1% of the runtime.

<img width="1198" alt="wall-profile" src="https://user-images.githubusercontent.com/1191797/50374936-c6af1480-05f5-11e9-802d-66fd3c2358bd.png">

This is a single-threaded, CPU-bound program, so there should be very little difference between the `cpu` and `wall` results. I cross-checked with JFR, JProfiler and YourKit and all of them agree with the `wall` profile. I also did an experiment and completely removed this code path from the code base. It disappeared from the `cpu` profile, making it look more like the `wall` profile, however runtime was completely unaffected as I expected. This shows that there is in fact no significant time spent in this method.

You can reproduce these measurements with the following commands:

- `git clone git@github.com:gradle/gradle.git`
- `./gradlew install -Pgradle_installPath=/usr/local/gradle-source-build largeJavaMultiProject` (this will take some time)
- `cd subprojects/performance/build/largeJavaMultiProject`
- repeatedly run `/usr/local/gradle-source-build/bin/gradle help` while async-profiler is attached to the Gradle daemon process, then dump the results to SVG

I'm on macOS High Sierra and tried both Oracle Java 8 and OpenJDK 11 with the same results. Let me know if there's anything else I can do to get to the bottom of this.

**Comment by apangin** [comment]
Sounds strange.
Does the problem happen on Linux as well?
Is it possible to get some reduced test case?

**Comment by oehme** [comment]
I'll try it on Linux. Constructing a reduced case might be tough, as I have no clue what combination of calls is causing this pattern. I'll try, but the steps above should be relatively easy to follow, they just take a bit of time to execute since Gradle is a big project.

**Comment by oehme** [comment]
I get the correct results on Ubuntu 18.04, so this seems MacOS specific.

**Comment by apangin** [comment]
Thank you for the input. That's what I suspected.
macOS kernel is a damned blackbox, and I'm afraid I can't influence on how it counts CPU time spent inside kernel. Probably the result will be plausible if we count only user-space CPU time. Let me do some experiments to see if there is anything we can improve here.

Do I understand correctly that you have also tried `-e itimer` mode on Linux, and it also looks fine with no `fileOpen` bias?

**Comment by oehme** [comment]
> Do I understand correctly that you have also tried -e itimer mode on Linux, and it also looks fine with no fileOpen bias?

No I tried it on MacOS and it had the same bias as `-e cpu`.

**Comment by apangin** [comment]
@oehme On macOS `cpu` and `itimer` modes are the same. `itimer` is basically the fallback mechanism on systems that have no perf_events support. Since you already have everything set up, can you please check if `itimer` behaves differently on Linux?

**Comment by apangin** [comment]
OK, I've re-implemented profiling on macOS using different engine. Now it acts more like wall-clock profiler, but samples only running threads. Please check if this works better.

**Comment by oehme** [comment]
Yep, that looks much better, thank you!

**Comment by retronym** [comment]
Related, I suppose :)

 https://github.com/jvm-profiling-tools/async-profiler/pull/52#issuecomment-330086645

> async-profiler (this PR) on Mac reports fewer total samples, and, of those, far too many seem to land in native IO methods.

> @retronym thank you for testing!
>
> Results seem legit to me, native stacks are not reported on mac os x and difference in samples count is acceptable: mac version samples random thread by timer interrupt and linux version samples all threads which are registered in perf_event_open with the same frequency
