### ISSUE TITLE
Oracle JVM crash when running SPECjvm2008 benchmarks on ARM64

### ISSUE THREAD

**Issue by miaozhuojun** [jvm-profiling-tools/async-profiler#185]
When I use [Oracle JDK8u191](https://download.oracle.com/otn-pub/java/jdk/8u191-b12/2787e4a523244c269598db4e85c51e0c/jdk-8u191-linux-arm64-vfp-hflt.tar.gz) running [SPECjvm2008 benchmarks](https://www.spec.org/download.html), the benchmark process will crash once async-profiler start profiling, however, if I use [OpenJDK ](http://hg.openjdk.java.net/aarch64-port/jdk8u-shenandoah/)instead of Oracle JDK, there is no problem at all. Here are the command I used and the error log for it.
Start benchmark crypto.signverify:
`java  -XX:+PreserveFramePointer -jar SPECjvm2008.jar -ikv crypto.signverify`
Attach benchmark process and profile:
`./profiler.sh -f /home/miaozhuojun/async-profiler/test1.svg 15168`

Once profiler.sh running, the benchmark process crashes immediately and prints error log to console:
> SPECjvm2008 Base
>   Properties file:   none
>   Benchmarks:        crypto.signverify
> 
>   WARNING: Run will not be compliant.
>   Not a compliant sequence of benchmarks for publication.
>   Property specjvm.run.checksum.validation must be true for publication.
> 
> 
> --- --- --- --- --- --- --- --- ---
> 
>   Benchmark:   check
>   Run mode:    static run
>   Test type:   functional
>   Threads:     1
>   Iterations:  1
>   Run length:  1 operation
> 
> Iteration 1 (1 operation) begins: Tue Dec 25 17:11:38 CST 2018
> Iteration 1 (1 operation) ends:   Tue Dec 25 17:11:38 CST 2018
> Iteration 1 (1 operation) result: PASSED
> 
> Valid run!
> 
> 
> --- --- --- --- --- --- --- --- ---
> 
>   Benchmark:   crypto.signverify
>   Run mode:    timed run
>   Test type:   multi
>   Threads:     32
>   Warmup:      120s
>   Iterations:  1
>   Run length:  240s
> 
> Warmup (120s) begins: Tue Dec 25 17:11:39 CST 2018
> frame::sender <sp=0xffff2f05f080, unext_sp=0xffff2f05f080, fp=0xffff2f05f080, pc=0xffff84bcb8a0>  --->  <sp=0xffff2f05f090, fp=0xffff2f05f0f0, pc=0xffff84c7db98>
> \#
> \# A fatal error has been detected by the Java Runtime Environment:
> \#
> \#  Internal Error (frame_arm.cpp:479), pid=15168, tid=0x0000ffff2f060200
> \#  Error: Unimplemented()
> \#
> \# JRE version: Java(TM) SE Runtime Environment (8.0_191-b12) (build 1.8.0_191-b12)
> \# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.191-b12 mixed mode linux-aarch64 compressed oops)
> \# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
> \#
> \# An error report file with more information is saved as:
> \# /home/miaozhuojun/specjvm2008/hs_err_pid15168.log
> \#
> \# If you would like to submit a bug report, please visit:
> \#   http://bugreport.java.com/bugreport/crash.jsp
> \#
> Aborted

and the contents of hs_err_pid15168.log is:

> \#
> \# A fatal error has been detected by the Java Runtime Environment:
> \#
> \#  Internal Error (frame_arm.cpp:479), pid=15168, tid=0x0000ffff2f060200
> \#  Error: Unimplemented()
> \#
> \# JRE version: Java(TM) SE Runtime Environment (8.0_191-b12) (build 1.8.0_191-b12)
> \# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.191-b12 mixed mode linux-aarch64 compressed oops)
> \# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
> \#
> \# If you would like to submit a bug report, please visit:
> \#   http://bugreport.java.com/bugreport/crash.jsp
> \#
> 
> ---------------  T H R E A D  ---------------
> 
> Current thread (0x000000002560c000):  JavaThread "BenchmarkThread crypto.signverify 12" [_thread_in_Java, id=15215, stack(0x0000ffff2ef60000,0x0000ffff2f061000)]
> 
> Stack: [0x0000ffff2ef60000,0x0000ffff2f061000],  sp=0x0000ffff2f05d140,  free space=1012k
> Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
> V  [libjvm.so+0x88a3f8]  VMError::report(outputStream*)+0x13b8
> V  [libjvm.so+0x88a640]  VMError::report_and_die()+0x130
> V  [libjvm.so+0x3b63d8]  report_unimplemented(char const*, int)+0x50
> V  [libjvm.so+0x42050c]  frame::sender(RegisterMap*) const+0x234
> V  [libjvm.so+0x415be4]  forte_fill_call_trace_given_top(JavaThread*, ASGCT_CallTrace*, int, frame) [clone .isra.113]+0x3f8
> V  [libjvm.so+0x415e70]  AsyncGetCallTrace+0x1ec
> C  [libasyncProfiler.so+0x18a80]  Profiler::getJavaTraceAsync(void*, ASGCT_CallFrame*, int)+0x90
> C  [libasyncProfiler.so+0x18e18]  Profiler::recordSample(void*, unsigned long long, int, _jmethodID*)+0x1b8
> C  [libasyncProfiler.so+0x172ec]  PerfEvents::signalHandler(int, siginfo_t*, void*)+0x74
> C  [+0x530]  __kernel_rt_sigreturn+0x0
> V  [libjvm.so+0x6ff9e4]  ObjectMonitor::exit(bool, Thread*)+0x54c
> V  [libjvm.so+0x7b1b98]  SharedRuntime::complete_monitor_unlocking_C(oopDesc*, BasicLock*)+0x44
> J 195 C2 sun.security.jca.ProviderList$ServiceList.tryGet(I)Ljava/security/Provider$Service; (181 bytes) @ 0x0000ffff812db77c [0x0000ffff812da820+0xf5c]
> C  0x000000060bbbd978
> .
> .
> .

**Comment by apangin** [comment]
Asynchronous stack walking is not implemented in Oracle's ARM64 port of JDK 8. However, this is required JVM functionality for async-profiler to work.

I'm afraid I can't do anything about it - this is a problem of JDK, not a defect of async-profiler. The sources of this port are not even available.

Since OpenJDK works fine, let me just close the issue.

**Comment by impl1874** [comment]
Using oracle jdk11 erro is gone.
