### ISSUE TITLE
How to get return value when tracing some functions?

### ISSUE THREAD

**Issue by miaozhuojun** [jvm-profiling-tools/async-profiler#186]
I can only get the arguments of the traced function at present using async-profiler like this:
`./profiler.sh -e malloc pid`
but when I want to get the return value of _malloc_, is there an easy way to do that?

**Comment by apangin** [comment]
I think this functionality is more about tracing rather than profiling. Not sure if this belongs to the scope of async-profiler.

What problem are you going to solve? Have you looked at [bcc](https://github.com/iovisor/bcc) or [ltrace](http://man7.org/linux/man-pages/man1/ltrace.1.html)?

**Comment by miaozhuojun** [comment]
I want to track long-term surviving allocations that haven't been freed in an interval in form of Flamegraph, with bytes, for identifying memory leaks. While, async-profiler can only track  the _malloc_ function with its argument even if the corresponding _free_ has been called with _-e malloc_.

I have used [memleak.py](http://blogs.microsoft.co.il/sasha/2016/02/14/two-new-ebpf-tools-memleak-and-argdist/) in bcc, but there is no Java symbol in stacktrace nor the form of Flamegraph. I have not used ltrace, but I think there are same problems with it.

Now that async-profiler has provided the functionality of tracing Kernel tracepoints and user defined breakpoints, adding the return value of each function will rich the information which is more usable for analysis I think.

**Comment by apangin** [comment]
Even if async-profiler somehow manages to get return values from `malloc`, it's still unclear how this will help.

It seems you are talking about a tool that will
1. trace all `malloc` and `free` calls;
2. record `malloc` address along with Java+native stack trace;
3. record `free` arguments and match them with `malloc` addresses;
4. aggregate the results in a FlameGraph-compatible format.

This looks like a quite separate tool, not what async-profiler currently does.

**Comment by apangin** [comment]
I assume I've answered the question.
Feel free to reopen if you have further comments.
