### ISSUE TITLE
How to dump data to TXT?

### ISSUE THREAD

**Issue by omnipresent07** [jvm-profiling-tools/async-profiler#189]
I noticed there is a `-f` option to dump the data to a TXT file. However, I'm not getting any data to the TXT file but rather all the information is put in the stdout (command line). the command I'm using is:

```
$ profiler.sh start -e alloc -o summary -f ~/dump2.txt  99154
...perform actions in my application...
$ profiler.sh stop 99154
```

But when I open `~/dump2.txt` it just says `Started [alloc] profiling`. Am I doing something wrong? Since the output is quite a lot, I'd like it available in a TXT file

**Comment by apangin** [comment]
Add `-f ~/dump2.txt` to `stop` command rather than `start`.

Each command processes `-f` option separately. Though it will be probably more intuitive to reuse `-f` option automatically if no one specified in `stop` command.
