### ISSUE TITLE
can not generate svg file

### ISSUE THREAD

**Issue by fendar** [jvm-profiling-tools/async-profiler#190]
version: latest version
platform: mac or linux x86
I following the tutorials. just run ./profiler.sh -d 30 -f profiler.svg [pid]
when profiler is end, can not svg file in PWD and the is no error alerts
![image](https://user-images.githubusercontent.com/6889329/50892263-091b8280-1439-11e9-8d42-621e57acff7d.png)
Also I checked the /proc/sys/kernel/perf_event_paranoid and /proc/sys/kernel/kptr_restrict, it`s 1 and 0 respectively
is there any other problem or dependency I ignore?

**Comment by apangin** [comment]
Since profiler works in the context of target JVM, the output file appears in the working directory of the JVM, not of the current shell.

Try specifying the absolute path. I'll probably fix this in future versions to avoid confusion.

**Comment by fendar** [comment]
> Since profiler works in the context of target JVM, the output file appears in the working directory of the JVM process, not of the current shell.
> 
> Try specifying the absolute path. I'll probably fix this in future versions to avoid confusion.

I check it and find the svg file!
thanks and thanks for reply so quickly
