### ISSUE TITLE
Immediately dump traces, rather than waiting for collection

### ISSUE THREAD

**Issue by squito** [jvm-profiling-tools/async-profiler#191]
I'd like to immediately dump traces as soon as they occur, rather than waiting to dump the summary on a "stop" event.

I realize this is a bit unusual use of async-profiler, so I'll explain my use case a little bit.  I'm trying to figure out where large offheap allocations are coming from, and so I'd like to trace all calls to malloc (I know it will be noisy, but I'll turn it on after initial memory has already been allocated).  I can't easily collect profiles afterwards, because the entire container where things are getting run gets killed when memory use gets too high.  Nor can I keep calling the profiler w/ start & stop, as I might miss the important event.

The larger context here is trying to understand the memory usage in Apache Spark, where a remote executor is given a discrete task to run, but it ends up calling all sorts of code that might be allocating memory, which is really hard to trace.

There may be a better tool to do this -- I was directed here from https://github.com/jvm-profiling-tools/perf-map-agent/issues/6.  I really need java stack traces leading to malloc.  It seems async-profiler has the necessary info, as the output after calling stop is exactly what I'm looking for.

**Comment by jesperpedersen** [comment]
@squito You can see if https://github.com/jesperpedersen/javamemflame is an option too

**Comment by squito** [comment]
@jesperpedersen thanks for the pointer, but can't use java9 at the moment.
from the description, though, it doesn't really seem to fit -- sounds like its onheap allocations?  And I thought I'd get a flame graph, not an individual trace?

**Comment by apangin** [comment]
Recording individual events is one of the features I'd like to implement in async-profiler.
This is already supported in some form in `-o jfr` format. However, in current implementation JFR output is not readable if profiler has not been stopped correctly.

I've implemented a new prototype of immediate tracing - check out [trace](https://github.com/jvm-profiling-tools/async-profiler/tree/trace) branch.

This adds a new `-o trace` output format that writes events as soon as they occur.  
How to run:

    ./profiler.sh start -e malloc -o trace -f trace.txt <pid>

The output will look like
```
[stacktrace] id=36001 java/lang/invoke/MethodHandle.<clinit>;...;ZIP_GetEntry2;__GI___libc_malloc
[event] time=1547347233641 thread=1847 stacktrace=36001 counter=72
[event] time=1547347233641 thread=1847 stacktrace=36001 counter=36
             ^                                    ^             ^
         Java timestamp                           |             |
                        ID of previously written [stacktrace]   |
                                                              Allocation size
```

**Comment by squito** [comment]
awesome, thanks @apangin !  I've tried it out and seems to work pretty nicely.  sorry for the delay, I was traveling so didn't get a chance to test it out until now.

One very minor usability thing, for me -- I'd rather have the output go to stdout, not to another file (has to do with how logs get collected by the framework).  Not a big deal, I can work around this, but I was wondering if there is some option I might have been missing (I tried using `-` for the file name, but that was interpreted literally, and leaving off `-f` completely, but that didn't seem to do anything).

**Comment by apangin** [comment]
The problem is that profiler works in the context of the target JVM. It can easily write to stdout of the Java process, but not in the console where you run `profiler.sh`.

As a workaround try `-f /proc/$$/fd/1` - this should be stdout of the current shell.

**Comment by krzysztofslusarski** [comment]
Is there a posibility to dump all traces to file after profiling has been completed? (not agreggated events)

Would be useful in alloc, malloc and page fault profiling,

**Comment by apangin** [comment]
@krzysztofslusarski Yes, JFR format (`-o jfr`) stores all samples

**Comment by krzysztofslusarski** [comment]
@apangin do you know some good JFR viewer other then Mission Controll (I hate it)? I

**Comment by apangin** [comment]
@krzysztofslusarski I don't know

**Comment by krzysztofslusarski** [comment]
@apangin thanks, and thank you and other contributions for async-profiler. It rocks.

**Comment by apangin** [comment]
Further work will be done in #404
