### ISSUE TITLE
Can't run allocation profiler with Java 11

### ISSUE THREAD

**Issue by doom369** [jvm-profiling-tools/async-profiler#193]
Hello,

tried to run async-profiler with next command:

`./profiler.sh -e alloc -d 10 3055`

However, it is failed with:
> No AllocTracer symbols found. Are JDK debug symbols installed?

I didn't find any instruction on how to deal with it. Any clues?

System info:

```
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment (build 11.0.1+13-Ubuntu-3ubuntu118.04ppa1)
OpenJDK 64-Bit Server VM (build 11.0.1+13-Ubuntu-3ubuntu118.04ppa1, mixed mode, sharing)
```

`Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-43-generic x86_64)`

CPU profiling works fine.

**Comment by doom369** [comment]
Oops. Sorry. Was looking into troubleshot section

**Comment by eolivelli** [comment]
I have no "root" access to some system.
is there a workaround to do basic allocation profiling without debug symbols, on JDK11 ?

**Comment by franz1981** [comment]
Without debug symbols you have less information for inlined frames for CPU profiling, for alloc I have no idea
Some info about the former here https://jpbempel.github.io/2022/06/22/debug-non-safepoints.html @jpbempel

**Comment by eolivelli** [comment]
thanks

**Comment by apangin** [comment]
@eolivelli Debug symbols are not needed for allocation profiling on JDK 11+

**Comment by pnf** [comment]
Good to know.  When did this change?  I hadn't even attempted allocation profiling before, because the `README` still says "The allocation profiler requires HotSpot debug symbols" and goes on to give instructions for installing those symbols in jdk11 with apt.

**Comment by TYTheBeast** [comment]
Any idea of which package I have to install on Arch to get Hotspot debug symbols?

**Comment by apangin** [comment]
@TYTheBeast With the [recent addition](https://github.com/async-profiler/async-profiler/issues/929), async-profiler can read debug symbols from debuginfod cache. See [this page](https://wiki.archlinux.org/title/Debuginfod) how to install/use debuginfod on Arch Linux.

BTW, why do you need debug symbols? Starting from JDK 11, async-profiler works just fine even when JDK debug symbols are not available. The only downside is that you'll see `libjvm.so` frames in a profile instead of JVM internal functions.

**Comment by TYTheBeast** [comment]
The Spark mod needs Hotspot debug symbols when using `/sparkc profiler start --alloc`, so I was trying to get it working on my system.

**Comment by apangin** [comment]
> The Spark mod needs Hotspot debug symbols when using /sparkc profiler start --alloc

This is an issue with the Spark mod then - I suggest you reach out to its authors.
Async-profiler does not require debug symbols to run allocation profiling on JDK 11. You may try running `asprof` directly.
