### ISSUE TITLE
Can't get cache-misses event in aarch64

### ISSUE THREAD

**Issue by miaozhuojun** [jvm-profiling-tools/async-profiler#197]
The command below is OK in linux X86 platform but failed in linux aarch64.
`./profiler.sh -e cache-misses pid`
The failure message for target Java process is:
`perf_event_open failed: Operation not permitted`
and both 
`echo 1 > /proc/sys/kernel/perf_event_paranoid`
`echo 0 > /proc/sys/kernel/kptr_restrict`
is set.

For the return value of _perf_event_open_ is EPERM, I comment the statement
`attr.exclude_idle = 1;`
in _PerfEvents::createForThread_, as a result, event _cache-misses_ is available in
aarch64.

**Comment by apangin** [comment]
Thank you for the report and the analysis.
I haven't seen any difference when profiling without `exclude_idle` on x64, so I think it's OK to simply remove this line. Would you like to create a PR?

**Comment by miaozhuojun** [comment]
OK.
