### ISSUE TITLE
JVM crash on attaching async profile 

### ISSUE THREAD

**Issue by billythach** [jvm-profiling-tools/async-profiler#199]
Hello !

The JVM crashed when i launched Async profiler :

Commande line : 
`async_profiler/profiler.sh -b 100000000 -d $duration -e alloc -f /tmp/async-profiler/${timestamp}-${server}-alloc.svg`

Extract from _hs_err_pid.log_ : 
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f789796b7b8, pid=5071, tid=0x00007f78dee99700
#
# JRE version: OpenJDK Runtime Environment (8.0_191-b12) (build 1.8.0_191-b12)
# Java VM: OpenJDK 64-Bit Server VM (25.191-b12 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libasyncProfiler.so+0x157b8]  Profiler::copyToFrameBuffer(int, ASGCT_CallFrame*, CallTraceSample*)+0x48
# 
```

It's very strange because i have launched Async Profiler several times without errors, the difference is : i have increased the frame buffer size. But with this value of buffer size, i haven't got any error with another server.

If more information is needed,  feel free to ask.

**Comment by apangin** [comment]
I suppose this could be caused by out-of-memory condition. The option `-b 100000000` means the frame buffer can occupy up to 2.2 GB (24 * 100'000'000). But I can't tell for sure without seeing full `hs_err.log` crash log.

**Comment by apangin** [comment]
The problem was in too large frame buffer. Now async-profiler throws an error if it fails to allocate memory for the buffer.
