### ISSUE TITLE
Can you support offcpu profiling?

### ISSUE THREAD

**Issue by rockiee281** [jvm-profiling-tools/async-profiler#201]
Sometime it's useful to find which thread  was  locked or sleep too long to wait the condition. On this situation off-cpu profiling is very important

**Comment by apangin** [comment]
Have you closed the issue because you found the solution?
There is a wall-clock mode (`-e wall`) exactly for off-cpu profiling.

**Comment by rockiee281** [comment]
> Have you closed the issue because you found the solution?
> There is a wall-clock mode (`-e wall`) exactly for off-cpu profiling.

Yes， wall-clock mode is good enough for me  :D
