### ISSUE TITLE
Consider sending profiler information via Graphite/Riemann/Aeron/TCP/UDP protocol

### ISSUE THREAD

**Issue by maseev** [jvm-profiling-tools/async-profiler#205]
Considering that async-profiler provides a low overhead way to profile JVM applications, I think it would be a great idea to make async-profiler send the profiler information via some well-known metrics protocols like [Graphite](https://graphiteapp.org) or [Riemann](http://riemann.io), for example. 

If I understand it correctly, right now async-profiler assumes that the file that contains the profiler information would be analyzed after the profiling process is stopped (in case of the agent-based approach - the JVM has been successfully stopped).

Wouldn't it be great to have a production profiling that always on and the profiling information is constantly sent to the monitoring platform where it is saved to a time-series database (like [Timescale](https://www.timescale.com/), for example) for later analysis?

This external application could potentially have all monitoring features you can imagine, like constantly collecting profiling information from the dozens of JVMs, which can come in handy considering the fact that microservices/distributed architecture is very popular nowadays. It could also compare historical data between JVM restarts (when a new release is deployed, for example). Also, not to mention, the different kinds of notifications that could be sent via E-mail/PagerDuty/Slack when something goes wrong.

I'm pretty sure there're a lot of people (myself included), who would like to build this kind of monitoring platform based on async-profiler.
If sending profiler information through the network isn't possible at the moment, a profiler file log rotation feature would be a great start, I believe.

What do you think?

These could be related:
https://www.opsian.com/
https://github.com/jvm-profiling-tools/honest-profiler/issues/63

**Comment by apangin** [comment]
Online reporting of profiling events is certainly an expected feature of async-profiler. It is already on my list. However, it won't be a simple task. While it's relatively easy to report events immediately as they happen, providing them with necessary metadata (e.g. stack traces with human readable method names) can be problematic or too heavyweight.

So far metadata was processed offline. But I have created a prototype for writing stacktraces immediately to a file - see #191.

**Comment by maseev** [comment]
I guess I'll go with the approach that was implemented in this [pull request](https://github.com/jvm-profiling-tools/async-profiler/pull/71). Although, it'll require to develop a separate daemon application that would deliver the profiler snapshots over the network. Thanks.
