### ISSUE TITLE
No JVM(GC, JIT etc.) code in profile

### ISSUE THREAD

**Issue by pjastrz** [jvm-profiling-tools/async-profiler#206]
I am trying to profile web application with simple: `./profiler.sh -d 120 -f /tmp/profile.svg <PID>`, the problem is JVM code(yellow stuff on flame graph), that is garbage collector and JIT compiler code are not showing up on result flame graph. I know that garbage collections are happening from GC logs. It works locally, but doesn't work when deployed to AWS cloud. I suspect it is included within red `/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-0.42.amzn1.x86_64/jre/lib/amd64/server/libjvm.so` which makes a big portion of the graph. 
The system and java are:
```
Amazon Linux AMI 2018.03
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
```

**Comment by apangin** [comment]
JDK binaries installed on your system have no debug symbols. You need to install a separate package with JDK symbols.

E.g. on Debian and Ubuntu:

    # apt install openjdk-8-dbg

On CentOS:

    # yum install java-1.8.0-openjdk-debuginfo.x86_64
