### ISSUE TITLE
Question: How to understand results regarding C1/C2 compiler?

### ISSUE THREAD

**Issue by ldebello** [jvm-profiling-tools/async-profiler#210]
Hi,

First of all thanks for your work, the tool is really amazing and also sorry to bother you with this simple question.

I am trying to understand some flame-graphs taken from our product (which is a customization of eclipse) and we are getting some slowness when creating a project, and I saw 47% usage of CPU for C1/C2 compiler, in order to remove our source code I ran the same test using a eclipse installation and the cpu usage is the same, after creating 4 projects one after the other the CPU usage looks the same.

Also reading the README in the repo I saw "Flame Graph visualization" which contains a good percentage of C1/C2 compiler, so I am trying to get some lights on how to understand those values.

Maybe I am doing something wrong to profile my app, the commands are:

1) ./profiler.sh start <PID>
2) ./profiler.sh stop -o svg <PID> > Eclipse.svg

I thought about asking this in stack-overflow but giving the fact you are the expert I decided to ask this here, sorry if this is not the best to way to ask.

<img width="1295" alt="Eclipse1" src="https://user-images.githubusercontent.com/2062115/55335960-807a1480-5472-11e9-8504-fba813b02d4a.png">
<img width="1225" alt="Eclipse2" src="https://user-images.githubusercontent.com/2062115/55335961-8112ab00-5472-11e9-9bfc-c8ba8db071f4.png">
<img width="1213" alt="Eclipse3" src="https://user-images.githubusercontent.com/2062115/55335962-8112ab00-5472-11e9-8959-ed16657f7b07.png">
<img width="1195" alt="Eclipse4" src="https://user-images.githubusercontent.com/2062115/55335963-8112ab00-5472-11e9-9c55-a12f3716f9d0.png">

**Comment by apangin** [comment]
Right - Java applications tend to spend much time compiling code at startup or when executing some action for the first time. This is not necessarily a performance problem. Since there are typically multiple compiler threads, they together make up a considerable portion of a CPU profile.

Try running profiler with `-t` option to build per-thread flame graphs.  
Performance problems are not always related to CPU bottlenecks, so another thing to try is to run profiler in wall-clock mode (`-e wall`).

**Comment by nitsanw** [comment]
@ldebello consider that:
- The compiler works in parallel to your application
- The JVM allocates compiler threads ergonomically
- Generally efficiency improvements by compiler are worth it, especially for long running code.

So:
- Are you competing with the compiler threads for CPU? This will be the case if CPU utilization is at 100% and the compiler is preventing your application from utilizing more CPU
- Is the compiler 'stuck' compiling some code? You can look at the compilation logs to see how long compilations took. Or use a tool like JitWatch to analyse the logs for you. This is not super likely but could happen sometimes.
- Will your application be better off without C2 compilation? the C1 compiler (A.K.A client) is faster but less sophisticated, but is perhaps the right choice for your UI application. You can force the JVM to C1 compile only.
- Maybe you need to look at AOT compilation for your product?
