### ISSUE TITLE
SVG output format not auto-detected

### ISSUE THREAD

**Issue by oehme** [jvm-profiling-tools/async-profiler#211]
The documentation says that the output format will be svg automatically if the file name ends with .svg. This does not work, at least when passing arguments via Java agent args like `libasyncProfiler.so=start,file=profile.svg,simple,event=cpu`. This will result in an empty output file instead. Adding `,svg` to the end fixes it.

**Comment by apangin** [comment]
Right, autodetection currently works only when starting `profiler.sh` script.
Will make this work in the agent, too.

**Comment by apangin** [comment]
Moved autodetection logic from `profiler.sh` to the agent.

Supported extensions:

- .svg
- .html
- .collapsed or .folded
- .txt
