### ISSUE TITLE
how to profile a java process in container depending on Ubuntu image from host system

### ISSUE THREAD

**Issue by mashoubing** [jvm-profiling-tools/async-profiler#212]
I run a docker with Ubuntu image, then I run a java process in Ubuntu system of the container.How to profiler the java process from the host system? I know the container process id and the java process id in Ubuntu of the container.I run ./profiler  with container process id, Ubuntu system of the container exits because of sigquit, then I run ./profiler with the java process id of Ubuntu from host system and failed ,because not found /tmp/.java_pidxxx socket file.

root@29c48953523a:/home/docker-test# java TestJava &
[1] 31

![image](https://user-images.githubusercontent.com/45619323/55926684-d73ad780-5c44-11e9-986b-eb508cc0728a.png)

**Comment by apangin** [comment]
Have you checked https://github.com/jvm-profiling-tools/async-profiler#troubleshooting?

Why do you think the problem is in `/tmp/.java_pidxxx` socket file? Did you run `strace`?
Please tell the exact error message and the output of `strace jattach <javaPID> properties`.

**Comment by mashoubing** [comment]
I run strace，all commands below。java process is runnning in ubuntu system of a containier.  I run strace in host system。

# mashoubing @ jvm-127-21 in ~ [16:00:13] C:130
$ docker run --privileged -it --rm --cpus=4 --security-opt seccomp=unconfined -v /home/mashoubing/:/home/  ubuntu:v2 /bin/bash
root@dd85bb14a48f:/home/docker-test# java TestJava &
[1] 30

root@jvm-127-21:/home/mashoubing/async-profiler# strace build/jattach 30 properties
execve("build/jattach", ["build/jattach", "30", "properties"], 0x7ffeac7cb920 /* 41 vars */) = 0
brk(NULL)                               = 0x561988a97000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=71436, ...}) = 0
mmap(NULL, 71436, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f07ee1b2000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\260A\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1996592, ...}) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f07ee1b0000
mmap(NULL, 2004992, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f07edfc6000
mprotect(0x7f07edfe8000, 1826816, PROT_NONE) = 0
mmap(0x7f07edfe8000, 1511424, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x22000) = 0x7f07edfe8000
mmap(0x7f07ee159000, 311296, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x193000) = 0x7f07ee159000
mmap(0x7f07ee1a6000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1df000) = 0x7f07ee1a6000
mmap(0x7f07ee1ac000, 14336, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f07ee1ac000
close(3)                                = 0
arch_prctl(ARCH_SET_FS, 0x7f07ee1b1540) = 0
mprotect(0x7f07ee1a6000, 16384, PROT_READ) = 0
mprotect(0x561987d4d000, 4096, PROT_READ) = 0
mprotect(0x7f07ee1ed000, 4096, PROT_READ) = 0
munmap(0x7f07ee1b2000, 71436)           = 0
geteuid()                               = 0
getegid()                               = 0
readlink("/proc/30/root", "/", 950)     = 1
brk(NULL)                               = 0x561988a97000
brk(0x561988ab8000)                     = 0x561988ab8000
openat(AT_FDCWD, "/proc/30/status", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
read(3, "Name:\tmigration/3\nUmask:\t0000\nSt"..., 1024) = 1005
read(3, "", 1024)                       = 0
close(3)                                = 0
stat("/proc/self/ns/mnt", {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
stat("/proc/30/ns/mnt", {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
rt_sigaction(SIGPIPE, {sa_handler=SIG_IGN, sa_mask=[PIPE], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f07ee007100}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
stat("/tmp/.java_pid30", 0x7ffd140774a0) = -1 ENOENT (No such file or directory)
creat("/proc/30/cwd/.attach_pid30", 0660) = 3
close(3)                                = 0
stat("/proc/30/cwd/.attach_pid30", {st_mode=S_IFREG|0640, st_size=0, ...}) = 0
geteuid()                               = 0
kill(30, SIGQUIT)                       = 0
nanosleep({tv_sec=0, tv_nsec=20000000}, NULL) = 0
stat("/tmp/.java_pid30", 0x7ffd14076fc0) = -1 ENOENT (No such file or directory)
nanosleep({tv_sec=0, tv_nsec=40000000}, NULL) = 0
stat("/tmp/.java_pid30", 0x7ffd14076fc0) = -1 ENOENT (No such file or directory)
nanosleep({tv_sec=0, tv_nsec=60000000}, NULL) = 0
stat("/tmp/.java_pid30", 0x7ffd14076fc0) = -1 ENOENT (No such file or directory)
nanosleep({tv_sec=0, tv_nsec=80000000}, NULL) = 0
stat("/tmp/.java_pid30", 0x7ffd14076fc0) = -1 ENOENT (No such file or directory)
nanosleep({tv_sec=0, tv_nsec=100000000}, NULL) = 0
stat("/tmp/.java_pid30", 0x7ffd14076fc0) = -1 ENOENT (No such file or directory)
nanosleep({tv_sec=0, tv_nsec=120000000}, NULL) = 0
stat("/tmp/.java_pid30", 0x7ffd14076fc0) = -1 ENOENT (No such file or directory)
nanosleep({tv_sec=0, tv_nsec=140000000}, NULL) = 0
stat("/tmp/.java_pid30", 0x7ffd14076fc0) = -1 ENOENT (No such file or directory)
nanosleep({tv_sec=0, tv_nsec=160000000}, NULL) = 0
stat("/tmp/.java_pid30", 0x7ffd14076fc0) = -1 ENOENT (No such file or directory)
nanosleep({tv_sec=0, tv_nsec=180000000}, NULL) = 0
stat("/tmp/.java_pid30", 0x7ffd14076fc0) = -1 ENOENT (No such file or directory)
nanosleep({tv_sec=0, tv_nsec=200000000}, NULL) = 0
stat("/tmp/.java_pid30", 0x7ffd14076fc0) = -1 ENOENT (No such file or directory)
nanosleep({tv_sec=0, tv_nsec=220000000}, NULL) = 0
stat("/tmp/.java_pid30", 0x7ffd14076fc0) = -1 ENOENT (No such file or directory)
nanosleep({tv_sec=0, tv_nsec=240000000}, NULL) = 0
stat("/tmp/.java_pid30", 0x7ffd14076fc0) = -1 ENOENT (No such file or directory)
nanosleep({tv_sec=0, tv_nsec=260000000}, NULL) = 0
stat("/tmp/.java_pid30", 0x7ffd14076fc0) = -1 ENOENT (No such file or directory)
nanosleep({tv_sec=0, tv_nsec=280000000}, NULL) = 0
stat("/tmp/.java_pid30", 0x7ffd14076fc0) = -1 ENOENT (No such file or directory)
unlink("/proc/30/cwd/.attach_pid30")    = 0
dup(2)                                  = 3
fcntl(3, F_GETFL)                       = 0x402 (flags O_RDWR|O_APPEND)
fstat(3, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 32), ...}) = 0
write(3, "Could not start attach mechanism"..., 60Could not start attach mechanism: No such file or directory
) = 60
close(3)                                = 0
exit_group(1)                           = ?
+++ exited with 1 +++

**Comment by apangin** [comment]
`30` is the pid *inside* the container, i.e. in different pid namespace. When running profiler from the host, you need to specify pid in the host namespace.

**Comment by mashoubing** [comment]
I have fixed this problem. From the host to profile the java process in a container, two ponints are important. 
1、we need to know the process id in the host namespace.
docker ps
docker top containerid 
2、 we need to make the java process in container access the libasyncProfiler.so.The path of libasyncProfiler.so can be got by the java process through files mounting in the same path. For example docker run -v xxx:xxx （xxx  path include the libasyncProfiler.so）
