### ISSUE TITLE
Failed to inject profiler

### ISSUE THREAD

**Issue by computinglife** [jvm-profiling-tools/async-profiler#214]
Hi, 

Iam trying to attach the profiler but getting the below error (I removed the /dev/null redirect to find what the script outputs, as seen from another issue with attach errors)

# ./profiler.sh start 31465
Connected to remote JVM
Response code = -1

Failed to inject profiler into 31465
        linux-vdso.so.1 =>  (0x00007fff60786000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fed246f3000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fed244d5000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fed242cd000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007fed23fc7000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fed23d42000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fed23b2c000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fed23798000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fed24fb6000)

I have ensured the profiler is copied into a directory accessible to the said process and permissions are present. (again resolution from another attach issue)

When i check the stdout of the process i see the following error : 

OpenJDK Server VM warning: You have loaded library /home/async/build/libasyncProfiler.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
OpenJDK Server VM warning: Unable to fix stack guard. Giving up.

Any help would be much appreciated. 

Thanks

uname - a
Linux finesse25 2.6.32-696.el6.x86_64 #1 SMP Tue Mar 21 19:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by apangin** [comment]
Don't you run 32-bit JVM? The "stack guard" warning typically means that the JVM executable and the shared library are compiled for different architectures.
What does `jcmd 31465 VM.version` say?

**Comment by computinglife** [comment]
Thanks for getting back
Here is the output. 

 $jcmd 31465 VM.version
31465:
OpenJDK Server VM version 24.181-b00
JDK 7.0_181

My process runs on a 64 bit platform and hence i had run the make file for the aysnc profiler on the same platform - is there a flag i can provide to the async build to force it to be 32 bit?

**Comment by apangin** [comment]
Yes, add `-m32` gcc flag to force cross compilation for i386.
This may require installing `gcc-multilib` and `g++-multilib` packages.
```
make CFLAGS="-O2 -m32" CPPFLAGS="-O2 -m32"
```

BTW, why not running 64-bit JDK instead?

**Comment by computinglife** [comment]
Thanks i will try that out. 

>BTW, why not running 64-bit JDK instead?

Don't ask. Getting to Java 11 from Java 7 next year. Unless something impacts the customer directly, the tech stack rarely gets prioritized for updates.

**Comment by computinglife** [comment]
That worked and it is now linking. However i see lots of messages in the sysout of my Java process. And it core dumps. 

perf_event mmap failed: Operation not permitted
perf_event mmap failed: Operation not permitted
perf_event mmap failed: Operation not permitted

The core dump that is created,  clearly calls out that the crash happened in native code and stack points to libasyncProfiler.so 

I hope this is all it takes to enable the perf events - 

# cat /proc/sys/kernel/perf_event_paranoid
1

#cat /proc/sys/kernel/kptr_restrict
0

**Comment by apangin** [comment]
The problem is too old Linux kernel.
There was already [a similar issue](https://github.com/jvm-profiling-tools/async-profiler/issues/195#issuecomment-456340847) with 2.6.32.
`-e itimer` mode might help.

**Comment by computinglife** [comment]
It seems to work for short periods if i trigger with -e cpu but it does core dump randomly. It is not clear what triggers it - but the segfault is always seen from JAVA compiler thread. 

We will be moving to a later kernel in a few weeks. Hopefully that should help us with this. 

Thanks a lot.

**Comment by computinglife** [comment]
BTW - 

  [ 0] /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.181/jre/lib/i386/server/libjvm.so
  [ 1] [unknown]
  [ 2] [unknown]

When is it that i get an unknown stack ?

**Comment by apangin** [comment]
I don't know - this might be related to how OpenJDK is compiled for x86. If it does not include an option to preserve a frame pointer, then traversing VM stack is not always possible.

It also seems that you don't have OpenJDK debug symbols installed, so the profiler shows only the library name (/usr/lib/.../libjvm.so) instead of the concrete VM function.

[More about installing debug symbols »](https://github.com/jvm-profiling-tools/async-profiler/issues/206#issuecomment-472191215)
