### ISSUE TITLE
Can AP get assembly hotspots like 'perf annotate' ?

### ISSUE THREAD

**Issue by miaozhuojun** [jvm-profiling-tools/async-profiler#216]
I want to see the hotest assembly instruction in my Java method, but this looks like it doesn't have any solution.

**Comment by apangin** [comment]
Instruction level statistics is currently out of async-profiler's scope.

**Comment by nitsanw** [comment]
There's an open issue and prototype for PMA to allow this integration:
https://github.com/jvm-profiling-tools/perf-map-agent/issues/7

You can use Oracle Studio, which is free or VTune which is sort of free to get similar functionality.
Finally, in JMH you can use the perfasm profiler.

**Comment by miaozhuojun** [comment]
OK，Thank you lot！
