### ISSUE TITLE
May I ask a question about function loadAllMethodIDs?

### ISSUE THREAD

**Issue by huangchen007** [jvm-profiling-tools/async-profiler#222]
The agent will invoke loadAllMethodIDs when it is started or attached, but the function seems to do nothing. It loads all the classes' method but frees them all as well. 
Can I know why it should be like this?
``
`
  if (jvmti->GetClassMethods(klass, &method_count, &methods) == 0) {
    jvmti->Deallocate((unsigned char *) methods);
  }
`

**Comment by apangin** [comment]
The purpose is to allocate `jmethodID`s for all methods.
HotSpot creates `jmethodID` lazily, on the first call to JNI/JVMTI function dealing with the method (in this case). However, we cannot call JNI/JVMTI functions from the signal handler, so we need to preallocate `jmethodID`s by calling `GetClassMethods`.

**Comment by huangchen007** [comment]
Thank you very much!

**Comment by apangin** [comment]
@MattAlp This is a workaround for the JVM bug [JDK-8062116](https://bugs.openjdk.org/browse/JDK-8062116). You may find some discussion in [this topic](https://github.com/async-profiler/async-profiler/issues/14#issuecomment-384935007). Async-profiler here constructs JVM structures for holding `jmethodID` list.
