### ISSUE TITLE
need to specify the full path to the svg file

### ISSUE THREAD

**Issue by cloud-66** [jvm-profiling-tools/async-profiler#229]
When i run profiler with simplie command ./profiler.sh -d 30 -f profile.svg 88721 , There are no errors. But i can not find the file, it is not exists in the current directory or in the home or in the temp. I have to write the full path to the svg file every time. Which is very uncomfortabl.

**Comment by apangin** [comment]
Since the profiler works in the context of the target JVM process, the path is considered relative to the working directory of the JVM process.

The problem is understood. I think I'll fix it by the next release.

**Comment by cloud-66** [comment]
Thank you, I think saving the file to the current directory is the best choice.

**Comment by apangin** [comment]
Fixed as discussed in #159 
Now relative paths are treated as relative to current shell directory (rather than current directory of a target Java process).
