### ISSUE TITLE
output too fragmented

### ISSUE THREAD

**Issue by filevanderl** [jvm-profiling-tools/async-profiler#232]
Hi, i have a question. My output from profiler looks  really fragmented. Every filter in my application generates own calltree. Is it possible to merge this kind of calls or ignore some specific packages ?
![Screenshot 2019-08-06 at 16 01 28](https://user-images.githubusercontent.com/6726190/62547562-ae7ac580-b865-11e9-964e-43206f6c052d.png)

**Comment by apangin** [comment]
Looks like your stack traces are deeper than 2048 frames. That's too much.
Currently async-profiler has a hard stack depth limit.

Increase [`MAX_STACK_FRAMES`](https://github.com/jvm-profiling-tools/async-profiler/blob/master/src/profiler.h#L38) constant and [rebuild](https://github.com/jvm-profiling-tools/async-profiler#building) the library.

A bit later I'll make the limit adjustable with a command line option. Actually, there is already `-j` option, but it can only lower the limit. I think I'll reuse this option to allow increasing the limit as well.

**Comment by apangin** [comment]
I committed the fix that allows to increase maximum Java stack depth.
E.g. add `-j 10000` profiler option.
