### ISSUE TITLE
Wish: multiple async-profiler output files

### ISSUE THREAD

**Issue by lestephane** [jvm-profiling-tools/async-profiler#235]
## Use Case

I have a flaky test case that fails intermittently. I need to generate multiple flame graphs over the same test run, using different perf events, because I'm not sure yet which graph will give me the information I need.

I briefly considered perf + perf-map-agent (even added agentpath support to it on my local dev machine), but that fails miserably because perf-map-agent has no visibility into interpreter frames. And you then have to understand perf well enough to write the correct incantation of `perf record` for the set of events you're interested in. And then you have to find the correct incantation to split that perf data into its constituent parts, and generate svg out of that.

By comparison, async-profiler is a breath of fresh air, so much easier to use. But it does not see possible to generate multiple outputs.

### First Try: multiple `-agentpath`s

My first instinct was to run my test with launch configuration set to repeat running until failure (this is a thing in Intellij), with these additional VM arguments:

```
-XX:+PreserveFramePointer
-XX:+UnlockDiagnosticVMOptions
-XX:+DebugNonSafepoints
-agentpath:async-profiler/build/libasyncProfiler.so=start,event=cpu,svg,file=/tmp/flamegraph-cpu.svg
-agentpath:async-profiler/build/libasyncProfiler.so=start,event=wall,svg,file=/tmp/flamegraph-wall.svg
-agentpath:async-profiler/build/libasyncProfiler.so=start,event=lock,svg,file=/tmp/flamegraph-lock.svg
-agentpath:async-profiler/build/libasyncProfiler.so=start,event=alloc,svg,file=/tmp/flamegraph-alloc.svg
```

**Result:** only `/tmp/flamegraph-alloc.svg` is written

### Second try: one mega `-agentpath`

```
-XX:+PreserveFramePointer
-XX:+UnlockDiagnosticVMOptions
-XX:+DebugNonSafepoints
-agentpath:async-profiler/build/libasyncProfiler.so=start,event=cpu,svg,file=/tmp/flamegraph-cpu.svg,event=wall,svg,file=/tmp/flamegraph-wall.svg,event=lock,svg,file=/tmp/flamegraph-lock.svg,event=alloc,svg,file=/tmp/flamegraph-alloc.svg
```

**Result:** only `/tmp/flamegraph-alloc.svg` is written

Here is a modest request for considering enabling multiple outputs.

This would enable devs to run individual tests (that are typically short running) under the microscope, and gain more insights on flaky tests (that are typically hard to debug).

My wish is either to be able to specify the agent multiple times (as in the first try), or if JVMTI won't allow it, to be able to configure the one agentpath with something like this:

```text
-agentpath:async-profiler/build/libasyncProfiler.so=start,event:cpu:svg:/tmp/flamegraph-cpu.svg,event:wall:svg:/tmp/flamegraph-wall.svg,event:lock:svg:tmp/flamegraph-lock.svg,event:alloc:svg:/tmp/flamegraph-alloc.svg
```

**Comment by apangin** [comment]
This seems to be a demanded feature.
It is already on my list, and I'm indeed going to implement it, though I can't commit to particular time frames, sorry.

Let me merge this issue with #150
