### ISSUE TITLE
Jattach not able to attach with openjdk binaries

### ISSUE THREAD

**Issue by sattishv** [jvm-profiling-tools/async-profiler#239]
HI team,

Today when we tried to attach async-profiler to a java process having open-jdk binaries we encountered errors. We could attach to the same process having oracle jdk
Error received:
Could not start attach mechanism: No such file or directory

Even with jstack we werent able to attach
/java/bin/jstack -m 76316
Attaching to process ID 76316, please wait...
Error attaching to process: sun.jvm.hotspot.debugger.DebuggerException: cannot open binary file
sun.jvm.hotspot.debugger.DebuggerException: sun.jvm.hotspot.debugger.DebuggerException: cannot open binary file
	at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal$LinuxDebuggerLocalWorkerThread.execute(LinuxDebuggerLocal.java:163)
	at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal.attach(LinuxDebuggerLocal.java:278)
	at sun.jvm.hotspot.HotSpotAgent.attachDebugger(HotSpotAgent.java:671)
	at sun.jvm.hotspot.HotSpotAgent.setupDebuggerLinux(HotSpotAgent.java:611)
	at sun.jvm.hotspot.HotSpotAgent.setupDebugger(HotSpotAgent.java:337)
	at sun.jvm.hotspot.HotSpotAgent.go(HotSpotAgent.java:304)
	at sun.jvm.hotspot.HotSpotAgent.attach(HotSpotAgent.java:140)
	at sun.jvm.hotspot.tools.Tool.start(Tool.java:185)
	at sun.jvm.hotspot.tools.Tool.execute(Tool.java:118)
	at sun.jvm.hotspot.tools.JStack.main(JStack.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.tools.jstack.JStack.runJStackTool(JStack.java:140)
	at sun.tools.jstack.JStack.main(JStack.java:106)
Caused by: sun.jvm.hotspot.debugger.DebuggerException: cannot open binary file
	at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal.attach0(Native Method)
	at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal.access$100(LinuxDebuggerLocal.java:62)
	at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal$1AttachTask.doit(LinuxDebuggerLocal.java:269)
	at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal$LinuxDebuggerLocalWorkerThread.run(LinuxDebuggerLocal.java:138)

We did a strace while trying to attach:
strace build/jattach 76316 load /async-profiler/build/libasyncProfiler.so true list
execve("build/jattach", ["build/jattach", "76316", "load", "/async-profiler/build/libasyncPr"..., "true", "list"], [/* 34 vars */]) = 0
brk(NULL)                               = 0x1acb000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=18957, ...}) = 0
mmap(NULL, 18957, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f0a69039000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P\t\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1868984, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f0a69038000
mmap(NULL, 3971488, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f0a68a4f000
mprotect(0x7f0a68c0f000, 2097152, PROT_NONE) = 0
mmap(0x7f0a68e0f000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1c0000) = 0x7f0a68e0f000
mmap(0x7f0a68e15000, 14752, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f0a68e15000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f0a69037000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f0a69036000
arch_prctl(ARCH_SET_FS, 0x7f0a69037700) = 0
mprotect(0x7f0a68e0f000, 16384, PROT_READ) = 0
mprotect(0x602000, 4096, PROT_READ)     = 0
mprotect(0x7f0a6903e000, 4096, PROT_READ) = 0
munmap(0x7f0a69039000, 18957)           = 0
geteuid()                               = 0
getegid()                               = 0
brk(NULL)                               = 0x1acb000
brk(0x1aec000)                          = 0x1aec000
open("/proc/76316/status", O_RDONLY)    = 3
fstat(3, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
read(3, "Name:\tjava\nState:\tS (sleeping)\nT"..., 1024) = 978
read(3, "", 1024)                       = 0
close(3)                                = 0
readlink("/proc/76316/root", 0x6031e0, 950) = -1 EACCES (Permission denied)
stat("/proc/self/ns/mnt", {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
stat("/proc/76316/ns/mnt", 0x7ffd2c694200) = -1 EACCES (Permission denied)
setresgid(-1, 61000, -1)                = 0
setresuid(-1, 223, -1)                  = 0
rt_sigaction(SIGPIPE, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x7f0a68a844b0}, {SIG_DFL, [], 0}, 8) = 0
stat("/tmp/.java_pid76316", 0x7ffd2c693e90) = -1 ENOENT (No such file or directory)
creat("/proc/76316/cwd/.attach_pid76316", 0660) = 3
close(3)                                = 0
stat("/proc/76316/cwd/.attach_pid76316", {st_mode=S_IFREG|0640, st_size=0, ...}) = 0
geteuid()                               = 223
kill(76316, SIGQUIT)                    = 0
nanosleep({0, 20000000}, NULL)          = 0
stat("/tmp/.java_pid76316", 0x7ffd2c6939c0) = -1 ENOENT (No such file or directory)
nanosleep({0, 40000000}, NULL)          = 0
stat("/tmp/.java_pid76316", 0x7ffd2c6939c0) = -1 ENOENT (No such file or directory)
nanosleep({0, 60000000}, NULL)          = 0
stat("/tmp/.java_pid76316", 0x7ffd2c6939c0) = -1 ENOENT (No such file or directory)
nanosleep({0, 80000000}, NULL)          = 0
stat("/tmp/.java_pid76316", 0x7ffd2c6939c0) = -1 ENOENT (No such file or directory)
nanosleep({0, 100000000}, NULL)         = 0
stat("/tmp/.java_pid76316", 0x7ffd2c6939c0) = -1 ENOENT (No such file or directory)
nanosleep({0, 120000000}, NULL)         = 0
stat("/tmp/.java_pid76316", 0x7ffd2c6939c0) = -1 ENOENT (No such file or directory)
nanosleep({0, 140000000}, NULL)         = 0
stat("/tmp/.java_pid76316", 0x7ffd2c6939c0) = -1 ENOENT (No such file or directory)
nanosleep({0, 160000000}, NULL)         = 0
stat("/tmp/.java_pid76316", 0x7ffd2c6939c0) = -1 ENOENT (No such file or directory)
nanosleep({0, 180000000}, NULL)         = 0
stat("/tmp/.java_pid76316", 0x7ffd2c6939c0) = -1 ENOENT (No such file or directory)
nanosleep({0, 200000000}, NULL)         = 0
stat("/tmp/.java_pid76316", 0x7ffd2c6939c0) = -1 ENOENT (No such file or directory)
nanosleep({0, 220000000}, NULL)         = 0
stat("/tmp/.java_pid76316", 0x7ffd2c6939c0) = -1 ENOENT (No such file or directory)
nanosleep({0, 240000000}, NULL)         = 0
stat("/tmp/.java_pid76316", 0x7ffd2c6939c0) = -1 ENOENT (No such file or directory)
nanosleep({0, 260000000}, NULL)         = 0
stat("/tmp/.java_pid76316", 0x7ffd2c6939c0) = -1 ENOENT (No such file or directory)
nanosleep({0, 280000000}, NULL)         = 0
stat("/tmp/.java_pid76316", 0x7ffd2c6939c0) = -1 ENOENT (No such file or directory)
unlink("/proc/76316/cwd/.attach_pid76316") = 0
dup(2)                                  = 3
fcntl(3, F_GETFL)                       = 0x8002 (flags O_RDWR|O_LARGEFILE)
fstat(3, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 1), ...}) = 0
write(3, "Could not start attach mechanism"..., 60Could not start attach mechanism: No such file or directory
) = 60
close(3)                                = 0
exit_group(1)                           = ?
+++ exited with 1 +++

Thanks
Sattish.

**Comment by apangin** [comment]
The error "Could not start attach mechanism: No such file or directory" means the profiler was not able to find the JVM’s attach socket. Typical reasons are listed in the [Troubleshooting section](https://github.com/jvm-profiling-tools/async-profiler#troubleshooting).

Check if thread dump is printed in the console of the target Java application.
Is there `Attach Listener` thread?

Try also `sudo lsof -p PID | grep java_pid` to see if JVM has created attach socket at all.

**Comment by sattishv** [comment]
Hi Team,

Thanks for the response. Yes the thread dump showed the existence of Attach Listener thread
Attach Listener
priority:9 - threadId:0x00007f6a4c02a000 - nativeId:0x4c90 - nativeId (decimal):19600 - state:RUNNABLE
stackTrace:
java.lang.Thread.State: RUNNABLE

We are running Java inside the container and we could see java_pid been created in the respective folder

Sattish.

**Comment by apangin** [comment]
So what does `sudo lsof -p PID | grep java_pid` print?

**Comment by sattishv** [comment]
The issue seems to be sporadiac i am not able to reproduce it. We can close this ticket as of now.
Will open the ticket again if we happens to encounter again

**Comment by apangin** [comment]
Agreed
