### ISSUE TITLE
What is all this empty space?

### ISSUE THREAD

**Issue by LoganDark** [jvm-profiling-tools/async-profiler#241]
![image](https://user-images.githubusercontent.com/4723091/64056128-f4196e00-cb45-11e9-8f9f-14910a29bd7f.png)
What's the empty space?

Here's the whole function:
```java
    @Override
    @Unique
    public IBlockState getFast(int x, int y, int z) {
        return palette.getBlockState(storage.getAt(y << 8 | z << 4 | x));
    }
```

I'm trying to figure out how to make this faster, but I'm not sure how, or if it's even possible.

**Comment by apangin** [comment]
1. There's too little context to give a precise answer. Please provide a complete verifiable example.
2. The picture does not look like a flame graph produced by async-profiler. This must be some other tool, and I can't tell for sure how it collects and presents data.
3. The rectangles with no frames on top of them denote the "self" time of a method. The self time of the given `getFast` method may consist of arithmetic operations, field accesses (palette, storage) and virtual method calls.

**Comment by LoganDark** [comment]
1. I can't, it's part of Minecraft. A complete verifiable example would require you to decompile the game, patch in changes, recompile it, start it up with the profiler, and look at the generated graph.
2. This flame graph was generated by IntelliJ IDEA, I'm not sure if it was straight from your profiler.
3. So self time is unavoidable overhead? I assume the bit shifts make up some of that overhead, right?

**Comment by apangin** [comment]
I wouldn't call it "overhead" - it looks more like the real workload (if one may ever conclude that from such a little piece of code). Yes, bit operations make a part of it (probably smaller), as well as field access and method calls.

Apparently this piece of code is called extremely often, if such a simple expression is highlighted in the profile. Can it be optimized? Well, the authors of the code should know better.

**Comment by LoganDark** [comment]
> Can it be optimized? Well, the authors of the code should know better.

Yes, I am calling this piece of code hundreds of millions of times per second. I need to optimize it as much as possible.

**Comment by apangin** [comment]
BTW, did you specify `-XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints` options? They help making profiles more detailed.
Anyway, I hope I answered the question about interpreting spaces in the profile.

**Comment by LoganDark** [comment]
The profiler already fucks with the game enough (random SIGILLs, it often takes 5 or more tries to get a profile because I get no data when it crashes), I think I'm good without 'diagnostic VM options' or anything to do with non-safety...

**Comment by apangin** [comment]
These options are not about (non-)safety at all - they just add more auxiliary information to the compiled code to facilitate getting stack traces not only at the known places (aka safepoints), but throughout the whole compiled method. These options are generally recommended for improving profiling quality.

As to random crashes - this is definitely not an expected behavior, so please open a separate issue and attach the JVM crash report (`hs_err_pid*.log`) - I'll see what can be done to avoid this.

**Comment by LoganDark** [comment]
> attach the JVM crash report (hs_err_pid*.log)

For a SIGILL? I don't think so. It causes instant termination. There is absolutely no possibility for an error handler of any kind - the process ends before another single instruction is executed.

**Comment by apangin** [comment]
All signals (except `SIGKILL` and `SIGSTOP`) can be caught by a process.

JVM handles many "fatal" signals including `SIGILL`, and creates a crash report before terminating. Look for `hs_err_pid*.log` files (usually in the current working directory of `java` or in `/tmp`).

**Comment by LoganDark** [comment]
```
0 LoganDark ~/baritone find . -iname 'hs*'
0 LoganDark ~/baritone find /tmp -iname 'hs*'
0 LoganDark ~/baritone which java
/Library/Java/JavaVirtualMachines/jdk1.8.0_212.jdk/Contents/Home/bin/java
0 LoganDark ~/baritone find /Library/Java/JavaVirtualMachines/jdk1.8.0_212.jdk/Contents/Home -iname 'hs*'
```

**Comment by apangin** [comment]
There are other ways to debug JVM crashes:

- by using `-XX:+ShowMessageBoxOnError` option;
- by enabling coredumps;
- by using OS-level debugger, e.g. lldb.

I fixed one macOS-specific crash in the profiler a few months ago. Not sure which version of async-profiler is integrated into IDEA, probably it does not yet have a fix for this bug.

**Comment by LoganDark** [comment]
> Not sure which version of async-profiler is integrated into IDEA

It says 1.5.

**Comment by apangin** [comment]
Right, then it apparently lacks the fix.
I've just built the version corresponding to the latest commit in `master` -
[async-profiler-1.6-ea-macos-x64.tar.gz](https://github.com/jvm-profiling-tools/async-profiler/files/3562632/async-profiler-1.6-ea-macos-x64.tar.gz)

You may try this one (or build a similar from the sources). As far I as remember, IDEA allows to override the path to `libasyncProfiler.so`. Alternatively, async-profiler can be run standalone with the included `profiler.sh` script.

**Comment by LoganDark** [comment]
> As far I as remember, IDEA allows to override the path to libasyncProfiler.so.

Yep.

![image](https://user-images.githubusercontent.com/4723091/64066909-a13ac780-cbd4-11e9-8349-040641dbc026.png)

And it works perfectly now!! It no longer crashes when the window goes out of focus, or randomly in the main menu or in the world, or randomly while in the middle of the intense workload that I'm profiling...

Thank you!

I'll close the issue now since you answered it a while ago.

**Comment by LoganDark** [comment]
Oh, also, quick question: what's the "agent options" equivalent of those `-XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints` options?

**Comment by apangin** [comment]
These are VM options, not profiler's.
But you are right, when the agent is loaded at startup, they are not needed.

**Comment by LoganDark** [comment]
Well RIP. SIGILL again. With the 1.6 agent. I'll open a separate issue for this.
