### ISSUE TITLE
Random SIGILL on macOS

### ISSUE THREAD

**Issue by LoganDark** [jvm-profiling-tools/async-profiler#242]
As discussed in #241 my profiler causes random SIGILLs in Minecraft for some reason. I'm not sure why, it just happens.

I'm using a build provided by @apangin of the latest master commit, which supposedly solved a macOS issue. Not this one it seems...

The profiler is running in IntelliJ IDEA 2019.2 Ultimate on macOS 10.14.5.

No crash report, log, etc. is ever generated. Output simply stops with this message:

```
Process finished with exit code 132 (interrupted by signal 4: SIGILL)
```

**Comment by apangin** [comment]
I reproduced the bug. Looks like the same problem as #219. The previous fix is incomplete.
Will investigate this further...

**Comment by LoganDark** [comment]
That's interesting because this is JDK 8...

**Comment by apangin** [comment]
I think I found the problem.
Profiler was using `pthread_mach_thread_np` function to get current thread ID inside signal handler, however, the function is not async signal safe.

Replaced it with `mach_thread_self` syscall.

Please check the updated version -
[async-profiler-1.6-ea-macos-x64.tar.gz](https://github.com/jvm-profiling-tools/async-profiler/files/3563491/async-profiler-1.6-ea-macos-x64.tar.gz)

**Comment by LoganDark** [comment]
@apangin Have any idea when exactly it would crash in that case, or was it just undefined behavior or some kind of race condition?

**Comment by apangin** [comment]
A race condition.
I don't have a reliable way to reproduce the bug, but chances are higher when profiling an application with many active threads, using small profiling interval and "threads" option.

I haven't seen crashes on my side after the fix.

An interesting fact is that JVM also uses `pthread_mach_thread_np` to get current thread ID, including the crash reporting code. Actually JVM catches the error, but when trying to create a crash report, it also calls the problematic function and then recursively fails.

**Comment by LoganDark** [comment]
Absolutely 0 crashes! I've just been messing around normally, running some very intensive tasks that involve threading (including incredibly multiplexed pathing algorithms) with no issue. Thank you!

Your profiler also no longer randomly crashes and freezes (without termination) when collecting data :>

**Comment by LoganDark** [comment]
Thank you so much for this!
