### ISSUE TITLE
How to profile short lived application

### ISSUE THREAD

**Issue by mpapirkovskyy** [jvm-profiling-tools/async-profiler#244]
I'm looking for way to stop profiling on JVM exit.
Profiler can be attached and started using -agentpath option on process start.
But how to stop it properly if JVM exits after few seconds without losing precious information?

**Comment by apangin** [comment]
If you specify the output filename (`file=`) and the output format (`svg`, `collapsed`, etc.) in the agent arguments, the profiler will automatically dump the collected data before the JVM exits.

E.g.
```
-agentpath:/path/to/libasyncProfiler.so=start,svg,file=/results/profile.svg
```

Also, the latest version from master has the output format autodetection, i.e. `svg` option is no longer needed if the filename ends with `.svg`.

**Comment by mpapirkovskyy** [comment]
Thanks, it worked.
I thought I tried this already, but looks like did something wrong.
