### ISSUE TITLE
Refuses to attach and coredumps

### ISSUE THREAD

**Issue by computinglife** [jvm-profiling-tools/async-profiler#247]
Hi, 

Iam using the 1.6 version of the async-profiler. But when i try to attach it, this is what i get 
"Error reading response: No such file or directory". 

Following this, the original process core dumps too. 

I would like to know why it refuses to attach and a  feasibility of a patch to not coredump the original process. 

I have captured the strace of the attach call to show where it fails below.

Thanks
Arun

------------------------

uname -a 

Linux finesse25.autobot.cvp 3.10.0-862.11.6.2.el7.x86_64 

-----------------

 java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)

-----------------

strace build/jattach 19848  load /root/async-64/build/libasyncProfiler.so true start,event=start,file=/root/async-64/profiler-data

stat("/tmp/.java_pid14726", {st_mode=S_IFSOCK|0600, st_size=0, ...}) = 0
unlink("/proc/14726/cwd/.attach_pid14726") = 0
socket(AF_LOCAL, SOCK_STREAM, 0)        = 3
connect(3, {sa_family=AF_LOCAL, sun_path="/tmp/.java_pid14726"}, 110) = 0
fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fe860be7000
write(1, "Connected to remote JVM\n", 24Connected to remote JVM
) = 24
write(3, "1\0", 2)                      = 2
write(3, "load\0", 5)                   = 5
write(3, "/root/async-64/build/libasyncPro"..., 41) = 41
write(3, "true\0", 5)                   = 5
write(3, "start,event=start,file=/root/asy"..., 54) = 54
write(1, "Response code = ", 16Response code = )        = 16
read(3, "", 8191)                       = 0
dup(2)                                  = 4
fcntl(4, F_GETFL)                       = 0x8002 (flags O_RDWR|O_LARGEFILE)
fstat(4, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fe860be6000
write(4, "Error reading response: No such "..., 50Error reading response: No such file or directory
) = 50
close(4)                                = 0
munmap(0x7fe860be6000, 4096)            = 0
write(1, "\n", 1
)                       = 1
close(3)                                = 0
exit_group(1)                           = ?
+++ exited with 1 +++

**Comment by apangin** [comment]
The crash of the original process is the primary problem.
Is there `hs_err_pidXXX.log` crash report you can share?

**Comment by moliqingwa** [comment]
I have the same issue on OpenJDK 1.8

**Comment by apangin** [comment]
@moliqingwa If by "the same issue" you mean that JVM crashes, please send the crash log `hs_err_pidXXX.log`.

**Comment by moliqingwa** [comment]
[javacore.20191007.164020.38776.0001.txt](https://github.com/jvm-profiling-tools/async-profiler/files/3696267/javacore.20191007.164020.38776.0001.txt)
Here's the java core dump file. The error shows:

Could not start attach mechanism: No such file or directory

Thanks.

**Comment by apangin** [comment]
@moliqingwa You are running OpenJ9 JVM, it is not compatible with async-profiler.
As the documentation says, the profiler works with Java runtimes based on HotSpot JVM.

**Comment by apangin** [comment]
Closing the issue, since there has been no feedback, and there is nothing more to do from async-profiler side.
