### ISSUE TITLE
how to profile cpu in container

### ISSUE THREAD

**Issue by Wenfeng-GAO** [jvm-profiling-tools/async-profiler#253]
We used async-profiler to profile heap memory and lock in production, and found it's quite good, thank you guys.

But here comes a question that our java process is running in Docker container with non-root privilege, so the process has no permission to call perf.

Any ideas or workarounds to fix this?

**Comment by marshallpierce** [comment]
Use `-e itimer`. You won't get kernel CPU information but otherwise it's great.

**Comment by apangin** [comment]
Please check the documentation:
https://github.com/jvm-profiling-tools/async-profiler#profiling-java-in-a-container

In short, async-profiler does not require root privileges, but it needs `perf_event_open` syscall enabled in the container. You'll need to adjust Docker security profile or use `-e timer` mode.

**Comment by Wenfeng-GAO** [comment]
Thanks @marshallpierce @apangin , `-e itimer` works but I still want kernel stack info if I could.

In fact, containers are running in the k8s cluster  with `SYS_ADMIN` capacity, and `seccomp` 
is disabled by k8s by default.
As can been seen in the container:
```bash
$ grep Seccomp /proc/1/status
Seccomp:	0
```
And I could do perf in the container by myself, although it seems be a host scope perf.
```bash
$ perf stat
$ ^C
 Performance counter stats for 'system wide':

     136581.695714      cpu-clock (msec)          #   63.904 CPUs utilized
         1,674,099      context-switches          #    0.012 M/sec
           313,813      cpu-migrations            #    0.002 M/sec
           208,409      page-faults               #    0.002 M/sec
   114,131,753,440      cycles                    #    0.836 GHz
    98,941,216,359      instructions              #    0.87  insn per cycle
    19,604,555,445      branches                  #  143.537 M/sec
       266,656,176      branch-misses             #    1.36% of all branches

       2.137304005 seconds time elapsed
```

However, when I use `profiler.sh`, I get a blank flame graph, and I found some error logs in catalina.out.
```bash
perf_event_open failed: Permission denied
perf_event_open failed: Permission denied
perf_event_open failed: Permission denied
perf_event_open failed: Permission denied
perf_event_open failed: Permission denied
```
The java process is not running in user `root`
```bash
[root@FATD00142120 100005602]# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   7628  2940 ?        Ssl  Sep30  15:48 /usr/local/libexec/cinit/cinit -logdir /mnt/mesos/sandbox -stdout /mnt/mesos/sandbox/stdout -stderr /mnt/mesos/sandbox/stderr -cmd /opt/container/entrypoint.sh -args []
root        15  0.0  0.0 121884 13256 ?        S    Sep30  14:59 /usr/bin/python /usr/bin/supervisord -c /etc/supervisord.conf
root        33  0.0  0.0 107976  9744 ?        S    Sep30   0:00 python /usr/local/sbin/listener
root        34  0.0  0.0 107812  9456 ?        S    Sep30   0:00 python /usr/local/sbin/post_start_hook tomcat sudo -E -u deploy sh /opt/tomcat/bin/payment_sqltrace/apptrace-service/bin/start.sh
root        35  0.0  0.0 114964  2520 ?        S    Sep30   0:00 /usr/sbin/sshd -D
deploy      37 11.9 45.7 38177568 7677584 ?    Sl   Sep30 2083:53 /usr/java/jdk1.8/bin/java -Djava.util.logging.config.file=/opt/tomcat/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -server -XX:
```
so I thought it was a permission issue, but now I'm confused at all, any ideas about this?

**Comment by apangin** [comment]
Try setting `/proc/sys/kernel/perf_event_paranoid` to `0`.
Check if async-profiler works with `--all-user` (to see if perf_event work at all).

When you run `./profiler start PID`, does it print `Started [cpu] profiling` or an error message?
What is the kernel version? I remember there was a bug in 3.10 that prevented from using perf_events in a process that voluntarily drops its privileges.

**Comment by Wenfeng-GAO** [comment]
First, with `--all-user` works well, but when run `./profiler.sh start PID`, it shows error:
```bash
Perf events unavailable. See stderr of the target process.
```

After setting `/proc/sys/kernel/perf_event_paranoid` to `0`, all works well, thanks @apangin .

However, `perf_event_paranoid` couldn't been set directly inside the container
```bash
$ echo 0 > /proc/sys/kernel/perf_event_paranoid
bash: /proc/sys/kernel/perf_event_paranoid: Read-only file system
```
I have to set it on the host machine, in which case affects all containers on this host, which leverage s some security risks.

**Comment by apangin** [comment]
I suppose `perf_event_paranoid = 1` is enough to allow kernel-level profiling.
The basic options are either to enable kernel-level profiling with `perf_event_paranoid` or to run profiler with `--all-user`.

[Kernel documentation](https://www.kernel.org/doc/html/latest/admin-guide/perf-security.html) describes an alternative way to enable perf_events for unprivileged users. Note: in the case of async-profiler, the executable is not `perf`, but rather `java`, since async-profiler works in the context of the target JVM.
