### ISSUE TITLE
JVM may crash when profiling with -g option

### ISSUE THREAD

**Issue by justinas-dabravolskas** [jvm-profiling-tools/async-profiler#255]
Hi,
after updating Async Profiler from v1.4 to v1.6 and adding -g flag we observe random JVM crashes during cpu profiling. hs_err file is very similar in all cases. They don't happen always but we have at least three similar hs_err files. For now I'll remove -g flag from command line arguments.

\#  SIGSEGV (0xb) at pc=0x00000031b562b3ef, pid=32552, tid=910
\#
\# JRE version: OpenJDK Runtime Environment (11.0.4+11) (build 11.0.4+11)
\# Java VM: OpenJDK 64-Bit Server VM (11.0.4+11, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
\# Problematic frame:
\# C  [libc.so.6+0x2b3ef]  uselocale+0x1f
 ...
---------------  T H R E A D  ---------------

Current thread (0x00007f722c001000):  JavaThread "Attach Listener" daemon [_thread_in_vm, id=910, stack(0x00007f7231a6c000,0x00007f7231b6d000)]

Stack: [0x00007f7231a6c000,0x00007f7231b6d000],  sp=0x00007f7231b68d18,  free space=1011k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libc.so.6+0x2b3ef]  uselocale+0x1f

siginfo: si_signo: 11 (SIGSEGV), si_code: 128 (SI_KERNEL), si_addr: 0x0000000000000000

Register to memory mapping:

RAX=0x00000031b598cac0: <offset 0x000000000038cac0> in /lib64/libc.so.6 at 0x00000031b5600000
RBX=0x00007f7231b69e00 is pointing into the stack for thread: 0x00007f722c001000
RCX=0xffffffffffffff98 is an unknown value
RDX=0x00000031b598ee40: <offset 0x000000000038ee40> in /lib64/libc.so.6 at 0x00000031b5600000
RSP=0x00007f7231b68d18 is pointing into the stack for thread: 0x00007f722c001000
RBP=0x00007f71edf92890 points into unknown readable memory: 00 00 00 00 00 00 00 00
RSI=0x00007f71be1762b9: <offset 0x000000000001f2b9> in /opt/async-profiler/build/libasyncProfiler.so at 0x00007f71be157000
RDI=0x756d6d492f746365 is an unknown value
R8 =0x00007f71be1762ad: <offset 0x000000000001f2ad> in /opt/async-profiler/build/libasyncProfiler.so at 0x00007f71be157000
R9 =0x7820747865743c0a is an unknown value
R10=0x342e32393131223d is an unknown value
R11=0x0 is NULL
R12=0x00007f71edf92890 points into unknown readable memory: 00 00 00 00 00 00 00 00
R13=0x00000032814f32c0: _ZNSs4_Rep20_S_empty_rep_storageE+0x0000000000000000 in /usr/lib64/libstdc++.so.6 at 0x0000003281200000
R14=0x00000000ffffffff is an unknown value
R15=0x00007f71be581058: _ZN8Profiler9_instanceE+0x00000000002000f8 in /opt/async-profiler/build/libasyncProfiler.so at 0x00007f71be157000

...

Stack slot to memory mapping:
stack at sp + 0 slots: 0x00007fda296c2830: _ZN9FrameNameD1Ev+0x0000000000000010 in /opt/async-profiler/build/libasyncProfiler.so at 0x00007fda296ae000
stack at sp + 1 slots: 0x00007fdc7a420b78 points into unknown readable memory: 74 65 72 43 6f 6e 74 65
stack at sp + 2 slots: 0x00007fda296c89f7: _ZN8Profiler14dumpFlameGraphERSoR9Argumentsb+0x0000000000000437 in /opt/async-profiler/build/libasyncProfiler.so at 0x00007fda296ae000
stack at sp + 3 slots: 0x00007fdaa39a4ce0 is pointing into the stack for thread: 0x00007fdc90003800
stack at sp + 4 slots: 0x00007fdaa39a5d60 is pointing into the stack for thread: 0x00007fdc90003800
stack at sp + 5 slots: 0x00007fdaa39a6240 is pointing into the stack for thread: 0x00007fdc90003800
stack at sp + 6 slots: 0x6dedfaf30000002e is an unknown value
stack at sp + 7 slots: 0x00007fdaa39a4c90 is pointing into the stack for thread: 0x00007fdc90003800

Regards,
Justinas

**Comment by apangin** [comment]
Can you post the complete crash log?
Or email it to upload482 @ and.su

The crash does not happen without -g, right?

**Comment by justinas-dabravolskas** [comment]
I think it doesn't happen without -g and it can be reproduced with signatures over 800 characters (frameName.h: char _buf[800])
Run wall profiling on following Java file.

[VeryLongSignature.txt](https://github.com/jvm-profiling-tools/async-profiler/files/3723630/VeryLongSignature.txt)

**Comment by apangin** [comment]
You're right, this is a typical buffer overrun issue. Thanks for posting.
Will fix it.

**Comment by apangin** [comment]
The fix is committed
