### ISSUE TITLE
'wall' event and `THREADS_PER_TICK`

### ISSUE THREAD

**Issue by nobeh** [jvm-profiling-tools/async-profiler#257]
`wallClock.cpp` (1) defines 

```cpp
const int THREADS_PER_TICK = 8;
```

(and it used to be 7 then 8).

Would you please clarify where this fixed number comes from and why is there such limitation? Could this be also an input parameter to the tool?

(1): https://github.com/jvm-profiling-tools/async-profiler/blob/a97a5cae13713e49ecc24a5a230eb4128dc188a5/src/wallClock.cpp#L27

**Comment by apangin** [comment]
The number was chosen empirically. It's not a limitation, but rather an optimization to avoid long application pauses. There is arguably little value in configuring it, since the desired tick interval can be already configured with `-i`. However, I don't mind changing this later if a good reason shows up.

As far as I know, JFR does a similar thing, collecting at most [5 samples at a time](http://hg.openjdk.java.net/jdk/jdk/file/9b67dd88a931/src/hotspot/share/jfr/periodic/sampling/jfrThreadSampler.cpp#l285).

**Comment by nobeh** [comment]
Thank you @apangin for the explanation and the reference to JFR. I managed to have a look at the code both for async-profiler and compare a bit with JFR.

What I found also matches my observation (previous understanding from `wallClock.cpp`) and I try t outline it here.

In async-profiler and for every sampling iteration:

- A list of threads are obtained; `THREADS`.
- `THREADS` is iterated using `THREAD_PER_TICK`
- Default `next()` method is called on `THREADS`
- Loop is complete.

The above implementation would imply that we always iterate over **the first 8 threads** obtained from OS API. Since profiling occurs in small durations and potentially on a JVM with large number of threads (>= 128), it could be argued that the sampling logic in async-profiler could be create samples are always based on the first `THREAD_PER_TICK` limitation.

My source of understanding: 

https://github.com/jvm-profiling-tools/async-profiler/blob/a97a5cae13713e49ecc24a5a230eb4128dc188a5/src/wallClock.cpp#L81. 

In JFR, and for the same sampling logic:

- A list of threads are obtained; `THREADS`.
- Extra state are maintained for iterating `THREADS`
- `_cur_index`: the current index inside `THREADS` during iteration for sampling thread list
- `next_thread` is a method that uses `_cur_index` to find the next thread or fall back to 0 when sampling has gone over all threads during the profiling 

The above implementation would imply that it gives a more *fair* chance to *all threads* to be sampled during the runtime of the JVM and during the profiling period.

My source of understanding:

- http://hg.openjdk.java.net/jdk/jdk/file/9b67dd88a931/src/hotspot/share/jfr/periodic/sampling/jfrThreadSampler.cpp#l505
- http://hg.openjdk.java.net/jdk/jdk/file/9b67dd88a931/src/hotspot/share/jfr/periodic/sampling/jfrThreadSampler.cpp#l406

---- 

Based on the above, would you agree to turn this question to a potential improvement for async-profiler?

**Comment by apangin** [comment]
Once async-profiler obtains a list of **all** threads, it iterates through **the whole list** in chunks of THREADS_PER_TICK elements. How would you like to improve this?

**Comment by nobeh** [comment]
Thanks @apangin . Indeed I missed that in async-profiler there're two loops. Outer is controlled by a timer and the inner iterates over the threads. The inner also resets the thread list when it completes the iteration. 

So with a closer understanding of how `wall` mode works in async-profiler, what is the recommendation for `-i` if one intends to profile "short-lived" threads? For example, using `-i 10us` would probably cause an overhead for a JVM with large number of threads.

**Comment by apangin** [comment]
Currently the minimal interval for wall clock profiling is 1 ms - the limitation of [`poll`](http://man7.org/linux/man-pages/man2/poll.2.html). Of course, there are ways to allow higher frequency, but this indeed will cause the significant overhead.

Actually, the application-wide wall clock profiling does not suit well for high frequencies and the large number of threads. In these cases cpu/itimer mode would be more appropriate. Alternatively, the selective wall clock profiling (aka thread filtering) as discussed in #237 may help. I think this feature definitely worth doing, and it may appear in one of the upcoming releases.

**Comment by nobeh** [comment]
Thanks @apangin for the discussions on this topic. I am happy to close this one.
