### ISSUE TITLE
SVG file is empty when SVG file is dumped during allocation profiling

### ISSUE THREAD

**Issue by RoySunnySean007** [jvm-profiling-tools/async-profiler#260]
Dear Async profiler experts,

I use ./profiler.sh -d 30 -f /tmp/result.svg <java pid>, but when I open result.svg, it shows empty.
The following is content of result.svg. 
Does it mean that we can't dump allocation profiling result to file?

</script>
<rect x="0" y="0" width="100%" height="100%" fill="rgb(240,240,220)"/>
<text id="title" x="600" y="24">Flame Graph</text>
<text id="details" x="10" y="69"> </text>
<text id="unzoom" x="10" y="24" class="hide">Reset Zoom</text>
<text id="search" x="1090" y="24">Search</text>
<text id="matched" x="1090" y="69"> </text>
<g id="frames">
</g>
</svg>

Really appreciate ur great help in advance!

Thanks,
Roy

**Comment by apangin** [comment]
There are two reasons why the graph can be empty. Either allocation profiling is not supported by your JVM (e.g. `libjvm.so` is missing debug symbols), or the allocations are too rare to be sampled.

See [README](https://github.com/jvm-profiling-tools/async-profiler/blob/master/README.md#allocation-profiling) for details.

Are there any error messages in the profiler console or in stderr of the target JVM if you run profiler without `-f` option?

**Comment by RoySunnySean007** [comment]
Dear @apangin ,

Thanks for ur quick reply!

>>>Either allocation profiling is not supported by your JVM (e.g. libjvm.so is missing debug symbols)
[Roy] I am using Oracle JDK, it do support. 
>>>the allocations are too rare to be sampled.
>>>Are there any error messages in the profiler console or in stderr of the target JVM if you run profiler without -f option?
[Roy] I don't think so and there is no error, you can refer to my sampling result via  https://github.com/jvm-profiling-tools/async-profiler/issues/261

Please kindly let me know what can I do to troubleshooting this problem, thx!

Thanks,
Roy

**Comment by apangin** [comment]
Did I understand correctly that allocation profiling works without `-f` option, but produces an empty file with `-f /tmp/result.svg`? Do other output formats work? E.g. `-f result.collapsed`?

**Comment by RoySunnySean007** [comment]
Dear @apangin ,

It is too strange...This time it do have data in svg. 
I don't know what happened, will keep an eye on it. 
Thanks for ur great help anyway.

Thanks,
Roy
