### ISSUE TITLE
Internal API on MacOS throws NoSuchMethodError when resume/stop is used

### ISSUE THREAD

**Issue by eranff** [jvm-profiling-tools/async-profiler#262]
When trying to profile a very simple program using the resume/stop methodology using the internal API, the result shows that AsyncProfiler.start0 throws NoSuchMethodError all the time.

The program to reproduce
package example;

import one.profiler.AsyncProfiler;

public class ClassA {

    public static void main(String...args){
        AsyncProfiler profiler = AsyncProfiler.getInstance(
            "/Users/eran/git/gitexample/build/libasyncProfiler.so");
        var array = new Object[10000];
        profiler.start("alloc", 1_000);
        var tmp = new Object();
        profiler.stop();
        for (int i=0; i < array.length; ++i) {
            profiler.resume("alloc", 1_000);
            array[i] = new Object();
            profiler.stop();
        }
        System.out.println(profiler.dumpTraces(0));
    }
}

OS:
MacOS Catalina
10.15

Java version
Erans-MacBook-Pro:gitexample eran$ java -version
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)

Results when Flat is dumped
--- Execution profile ---
Total samples       : 59

Frame buffer usage  : 0.0052%

       bytes  percent  samples  top
  ----------  -------  -------  ---
    12535808   82.44%       25  java.lang.Object[]
     1570816   10.33%        5  long[]
      528384    3.47%        4  int[]
      522240    3.43%        1  byte[]
       47104    0.31%       23  short[]
        2048    0.01%        1  java.lang.String

Results when trace is dumped

--- Execution profile ---
Total samples       : 51

Frame buffer usage  : 0.0052%

--- 8886272 bytes (58.45%), 19 samples
  [ 0] java.lang.Object[]
  [ 1] java.lang.Throwable.fillInStackTrace
  [ 2] java.lang.Throwable.fillInStackTrace
  [ 3] java.lang.Throwable.<init>
  [ 4] java.lang.Error.<init>
  [ 5] java.lang.LinkageError.<init>
  [ 6] java.lang.IncompatibleClassChangeError.<init>
  [ 7] java.lang.NoSuchMethodError.<init>
  [ 8] one.profiler.AsyncProfiler.start0
  [ 9] one.profiler.AsyncProfiler.resume
  [10] example.ClassA.main

--- 2619392 bytes (17.23%), 7 samples
  [ 0] long[]
  [ 1] java.lang.Throwable.fillInStackTrace
  [ 2] java.lang.Throwable.fillInStackTrace
  [ 3] java.lang.Throwable.<init>
  [ 4] java.lang.Error.<init>
  [ 5] java.lang.LinkageError.<init>
  [ 6] java.lang.IncompatibleClassChangeError.<init>
  [ 7] java.lang.NoSuchMethodError.<init>
  [ 8] one.profiler.AsyncProfiler.start0
  [ 9] one.profiler.AsyncProfiler.resume
  [10] example.ClassA.main

--- 1077248 bytes (7.09%), 16 samples
  [ 0] short[]
  [ 1] java.lang.Throwable.fillInStackTrace
  [ 2] java.lang.Throwable.fillInStackTrace
  [ 3] java.lang.Throwable.<init>
  [ 4] java.lang.Error.<init>
  [ 5] java.lang.LinkageError.<init>
  [ 6] java.lang.IncompatibleClassChangeError.<init>
  [ 7] java.lang.NoSuchMethodError.<init>
  [ 8] one.profiler.AsyncProfiler.start0
  [ 9] one.profiler.AsyncProfiler.resume
  [10] example.ClassA.main

--- 1048576 bytes (6.90%), 2 samples
  [ 0] java.lang.NoSuchMethodError
  [ 1] one.profiler.AsyncProfiler.start0
  [ 2] one.profiler.AsyncProfiler.resume
  [ 3] example.ClassA.main

--- 1047288 bytes (6.89%), 5 samples
  [ 0] int[]
  [ 1] java.lang.Throwable.fillInStackTrace
  [ 2] java.lang.Throwable.fillInStackTrace
  [ 3] java.lang.Throwable.<init>
  [ 4] java.lang.Error.<init>
  [ 5] java.lang.LinkageError.<init>
  [ 6] java.lang.IncompatibleClassChangeError.<init>
  [ 7] java.lang.NoSuchMethodError.<init>
  [ 8] one.profiler.AsyncProfiler.start0
  [ 9] one.profiler.AsyncProfiler.resume
  [10] example.ClassA.main

--- 524288 bytes (3.45%), 2 samples
  [ 0] java.lang.String
  [ 1] one.profiler.AsyncProfiler.start0
  [ 2] one.profiler.AsyncProfiler.resume
  [ 3] example.ClassA.main

Thank you

E.

**Comment by apangin** [comment]
Indeed there was a bug in method signature on JDK 9+. Thank you for reporting. I committed the fix.
