### ISSUE TITLE
unknown function name

### ISSUE THREAD

**Issue by wenbeicai** [jvm-profiling-tools/async-profiler#266]
hi. why has some unknown function name?i use async-profiler-1.6-linux-x64.tar.gz.
![image](https://user-images.githubusercontent.com/16438030/68914515-c97ca000-0799-11ea-927f-51358c58b8db.png)

**Comment by apangin** [comment]
Apparently, async-profiler hasn't detected the load of RocksDB native library.
What is the OS, JDK and RocksDB version?
I'll try to reproduce the problem, but if you already have an example that you can share, this would be very helpful.

**Comment by wenbeicai** [comment]
Thanks for your replay!
 My os is Ubuntu-18.04.1,jdk is openjdk-1.8.0_222,and RocksDb is rocksdbjni-4.9.0.
More import,other stack also has unknow function,like this.
![other unknown function](https://user-images.githubusercontent.com/16438030/68986688-c8607700-085c-11ea-9b75-10e183104c99.png)
![other unknown function](https://user-images.githubusercontent.com/16438030/68986727-242b0000-085d-11ea-8c28-5de05672fa46.png)
I see you resolved  question like this [(Java jni call unknown function name )](https://github.com/jvm-profiling-tools/async-profiler/issues/233) ,is same?But i already use the lastest version.（async-profiler-1.6-linux-x64.so）

**Comment by apangin** [comment]
Interesting. Symbols for Java NIO native library are also missing.
Could you please show the contents of `/proc/PID/maps` before starting profiler?
Also. what is the kernel version (`uname -rv`)?

**Comment by wenbeicai** [comment]
Hi！
Run 'uname -rv' command output is
 (5.0.0-36-generic #39~18.04.1-Ubuntu SMP Tue Nov 12 11:09:50 UTC 2019).

And next  is /proc/PID/maps file. Total has more than 800 lines.I already delete lines ehat end with '00000000 00:00 0'.

55d499d74000-55d499d75000 r-xp 00000000 103:06 5378691                   /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
55d499f74000-55d499f75000 r--p 00000000 103:06 5378691                   /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
55d499f75000-55d499f76000 rw-p 00001000 103:06 5378691                   /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
55d49a57c000-55d49a59d000 rw-p 00000000 00:00 0                          [heap]
7f4a469a6000-7f4a46dd6000 r-xp 00000000 103:06 665952                    /**use dir**/soft/tomcat/apache-tomcat-8.5.47/temp/librocksdbjni5357098699542552616.so
7f4a46dd6000-7f4a46fd6000 ---p 00430000 103:06 665952                    /**use dir**/soft/tomcat/apache-tomcat-8.5.47/temp/librocksdbjni5357098699542552616.so
7f4a46fd6000-7f4a46fed000 rw-p 00430000 103:06 665952                    /**use dir**/soft/tomcat/apache-tomcat-8.5.47/temp/librocksdbjni5357098699542552616.so
7f4aa8e63000-7f4aa8e72000 r-xp 00000000 103:06 2230407                   /lib/x86_64-linux-gnu/libnss_myhostname.so.2
7f4aa8e72000-7f4aa9072000 ---p 0000f000 103:06 2230407                   /lib/x86_64-linux-gnu/libnss_myhostname.so.2
7f4aa9072000-7f4aa9075000 r--p 0000f000 103:06 2230407                   /lib/x86_64-linux-gnu/libnss_myhostname.so.2
7f4aa9075000-7f4aa9076000 rw-p 00012000 103:06 2230407                   /lib/x86_64-linux-gnu/libnss_myhostname.so.2
7f4aa9a7e000-7f4aa9a95000 r-xp 00000000 103:06 2233523                   /lib/x86_64-linux-gnu/libresolv-2.27.so
7f4aa9a95000-7f4aa9c95000 ---p 00017000 103:06 2233523                   /lib/x86_64-linux-gnu/libresolv-2.27.so
7f4aa9c95000-7f4aa9c96000 r--p 00017000 103:06 2233523                   /lib/x86_64-linux-gnu/libresolv-2.27.so
7f4aa9c96000-7f4aa9c97000 rw-p 00018000 103:06 2233523                   /lib/x86_64-linux-gnu/libresolv-2.27.so
7f4aa9c99000-7f4aa9c9e000 r-xp 00000000 103:06 2233472                   /lib/x86_64-linux-gnu/libnss_dns-2.27.so
7f4aa9c9e000-7f4aa9e9e000 ---p 00005000 103:06 2233472                   /lib/x86_64-linux-gnu/libnss_dns-2.27.so
7f4aa9e9e000-7f4aa9e9f000 r--p 00005000 103:06 2233472                   /lib/x86_64-linux-gnu/libnss_dns-2.27.so
7f4aa9e9f000-7f4aa9ea0000 rw-p 00006000 103:06 2233472                   /lib/x86_64-linux-gnu/libnss_dns-2.27.so
7f4aa9ea0000-7f4aa9ea2000 r-xp 00000000 103:06 2233480                   /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
7f4aa9ea2000-7f4aaa0a1000 ---p 00002000 103:06 2233480                   /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
7f4aaa0a1000-7f4aaa0a2000 r--p 00001000 103:06 2233480                   /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
7f4aaa0a2000-7f4aaa0a3000 rw-p 00002000 103:06 2233480                   /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
7f4aaa0b6000-7f4aaa0bb000 r--s 002f9000 103:06 5378746                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/charsets.jar
7f4aaa9bc000-7f4aaa9cf000 r--s 00346000 103:06 5378784                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/resources.jar
7f4b3ca3a000-7f4b3ca62000 r-xp 00000000 103:06 5378739                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libsunec.so
7f4b3ca62000-7f4b3cc61000 ---p 00028000 103:06 5378739                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libsunec.so
7f4b3cc61000-7f4b3cc65000 r--p 00027000 103:06 5378739                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libsunec.so
7f4b3cc65000-7f4b3cc66000 rw-p 0002b000 103:06 5378739                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libsunec.so
7f4b4c07c000-7f4b4c09d000 r--p 00000000 103:06 6034016                   /usr/share/locale-langpack/zh_CN/LC_MESSAGES/libc.mo
7f4b4caa3000-7f4b4cab4000 r-xp 00000000 103:06 5378730                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libnio.so
7f4b4cab4000-7f4b4ccb3000 ---p 00011000 103:06 5378730                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libnio.so
7f4b4ccb3000-7f4b4ccb4000 r--p 00010000 103:06 5378730                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libnio.so
7f4b4ccb4000-7f4b4ccb5000 rw-p 00011000 103:06 5378730                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libnio.so
7f4b4ccb5000-7f4b4cccb000 r-xp 00000000 103:06 5378729                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libnet.so
7f4b4cccb000-7f4b4ceca000 ---p 00016000 103:06 5378729                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libnet.so
7f4b4ceca000-7f4b4cecb000 r--p 00015000 103:06 5378729                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libnet.so
7f4b4cecb000-7f4b4cecc000 rw-p 00016000 103:06 5378729                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libnet.so
7f4b4cecc000-7f4b4ced5000 r-xp 00000000 103:06 5378727                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libmanagement.so
7f4b4ced5000-7f4b4d0d4000 ---p 00009000 103:06 5378727                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libmanagement.so
7f4b4d0d4000-7f4b4d0d5000 r--p 00008000 103:06 5378727                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libmanagement.so
7f4b4d0d5000-7f4b4d0d6000 rw-p 00009000 103:06 5378727                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libmanagement.so
7f4b4d9df000-7f4b4d9e3000 r-xp 00000000 103:06 5378710                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libdt_socket.so
7f4b4d9e3000-7f4b4dbe2000 ---p 00004000 103:06 5378710                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libdt_socket.so
7f4b4dbe2000-7f4b4dbe3000 r--p 00003000 103:06 5378710                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libdt_socket.so
7f4b4dbe3000-7f4b4dbe4000 rw-p 00004000 103:06 5378710                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libdt_socket.so
7f4b54009000-7f4b54010000 r--s 00000000 103:06 5638609                   /usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache
7f4b54010000-7f4b54012000 r--s 00016000 103:06 5378777                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jce.jar
7f4b54012000-7f4b54014000 r--s 00002000 103:06 663186                    /**use dir**/soft/tomcat/apache-tomcat-8.5.47/lib/annotations-api.jar
7f4b54014000-7f4b54017000 r--s 00026000 103:06 663194                    /**use dir**/soft/tomcat/apache-tomcat-8.5.47/lib/jasper-el.jar
7f4b54017000-7f4b54019000 r--s 00014000 103:06 663193                    /**use dir**/soft/tomcat/apache-tomcat-8.5.47/lib/el-api.jar
7f4b54019000-7f4b5401d000 r--s 00016000 103:06 663208                    /**use dir**/soft/tomcat/apache-tomcat-8.5.47/lib/tomcat-i18n-zh-CN.jar
7f4b5401d000-7f4b5401f000 r--s 00007000 103:06 663210                    /**use dir**/soft/tomcat/apache-tomcat-8.5.47/lib/tomcat-jni.jar
7f4b5401f000-7f4b54022000 r--s 00022000 103:06 663209                    /**use dir**/soft/tomcat/apache-tomcat-8.5.47/lib/tomcat-jdbc.jar
7f4b54022000-7f4b54024000 r--s 00005000 103:06 663196                    /**use dir**/soft/tomcat/apache-tomcat-8.5.47/lib/jaspic-api.jar
7f4b54024000-7f4b54028000 r--s 00030000 103:06 663211                    /**use dir**/soft/tomcat/apache-tomcat-8.5.47/lib/tomcat-util-scan.jar
7f4b54028000-7f4b5402c000 r--s 00038000 103:06 663198                    /**use dir**/soft/tomcat/apache-tomcat-8.5.47/lib/servlet-api.jar
7f4b5402c000-7f4b54031000 r--s 00033000 103:06 663213                    /**use dir**/soft/tomcat/apache-tomcat-8.5.47/lib/tomcat-websocket.jar
7f4b54031000-7f4b54035000 r--s 0000e000 103:06 663202                    /**use dir**/soft/tomcat/apache-tomcat-8.5.47/lib/tomcat-i18n-de.jar
7f4b54035000-7f4b54037000 r--s 00011000 103:06 663189                    /**use dir**/soft/tomcat/apache-tomcat-8.5.47/lib/catalina-storeconfig.jar
7f4b54037000-7f4b5404c000 r--s 00183000 103:06 663191                    /**use dir**/soft/tomcat/apache-tomcat-8.5.47/lib/catalina.jar
7f4b5404c000-7f4b54058000 r--s 000c1000 103:06 663200                    /**use dir**/soft/tomcat/apache-tomcat-8.5.47/lib/tomcat-coyote.jar
7f4b54058000-7f4b5405c000 r--s 00026000 103:06 663206                    /**use dir**/soft/tomcat/apache-tomcat-8.5.47/lib/tomcat-i18n-ko.jar
7f4b5405c000-7f4b54063000 r--s 0008b000 103:06 663195                    /**use dir**/soft/tomcat/apache-tomcat-8.5.47/lib/jasper.jar
7f4b54063000-7f4b54066000 r--s 0000d000 103:06 663197                    /**use dir**/soft/tomcat/apache-tomcat-8.5.47/lib/jsp-api.jar
7f4b54066000-7f4b54069000 r--s 00007000 103:06 663207                    /**use dir**/soft/tomcat/apache-tomcat-8.5.47/lib/tomcat-i18n-ru.jar
7f4b54069000-7f4b5406c000 r--s 0001b000 103:06 663188                    /**use dir**/soft/tomcat/apache-tomcat-8.5.47/lib/catalina-ha.jar
7f4b5406c000-7f4b54070000 r--s 00026000 103:06 663205                    /**use dir**/soft/tomcat/apache-tomcat-8.5.47/lib/tomcat-i18n-ja.jar
7f4b54070000-7f4b54071000 r--s 00002000 103:06 663199                    /**use dir**/soft/tomcat/apache-tomcat-8.5.47/lib/tomcat-api.jar
7f4b54071000-7f4b54076000 r--s 00021000 103:06 663204                    /**use dir**/soft/tomcat/apache-tomcat-8.5.47/lib/tomcat-i18n-fr.jar
7f4b54076000-7f4b54089000 r--s 00244000 103:06 663192                    /**use dir**/soft/tomcat/apache-tomcat-8.5.47/lib/ecj-4.6.3.jar
7f4b54089000-7f4b5408e000 r--s 00043000 103:06 663201                    /**use dir**/soft/tomcat/apache-tomcat-8.5.47/lib/tomcat-dbcp.jar
7f4b5408e000-7f4b54091000 r--s 00025000 103:06 663212                    /**use dir**/soft/tomcat/apache-tomcat-8.5.47/lib/tomcat-util.jar
7f4b54091000-7f4b54093000 r--s 00008000 103:06 663214                    /**use dir**/soft/tomcat/apache-tomcat-8.5.47/lib/websocket-api.jar
7f4b54093000-7f4b54097000 r--s 00016000 103:06 663203                    /**use dir**/soft/tomcat/apache-tomcat-8.5.47/lib/tomcat-i18n-es.jar
7f4b54097000-7f4b5409c000 r--s 00043000 103:06 663190                    /**use dir**/soft/tomcat/apache-tomcat-8.5.47/lib/catalina-tribes.jar
7f4b5409c000-7f4b540a1000 r--s 000a3000 103:06 5378779                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jsse.jar
7f4b543f2000-7f4b545c2000 r--s 03c5c000 103:06 5378785                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar
7f4b68000000-7f4b68002000 r--s 0000c000 103:06 663187                    /**use dir**/soft/tomcat/apache-tomcat-8.5.47/lib/catalina-ant.jar
7f4b68002000-7f4b6801d000 r--s 00394000 103:06 5378756                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/cldrdata.jar
7f4b696d9000-7f4b696e1000 r-xp 00000000 103:06 5378742                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libzip.so
7f4b696e1000-7f4b698e0000 ---p 00008000 103:06 5378742                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libzip.so
7f4b698e0000-7f4b698e1000 r--p 00007000 103:06 5378742                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libzip.so
7f4b698e1000-7f4b698e2000 rw-p 00008000 103:06 5378742                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libzip.so
7f4b698e2000-7f4b698ed000 r-xp 00000000 103:06 2233474                   /lib/x86_64-linux-gnu/libnss_files-2.27.so
7f4b698ed000-7f4b69aec000 ---p 0000b000 103:06 2233474                   /lib/x86_64-linux-gnu/libnss_files-2.27.so
7f4b69aec000-7f4b69aed000 r--p 0000a000 103:06 2233474                   /lib/x86_64-linux-gnu/libnss_files-2.27.so
7f4b69aed000-7f4b69aee000 rw-p 0000b000 103:06 2233474                   /lib/x86_64-linux-gnu/libnss_files-2.27.so
7f4b69af4000-7f4b69b0b000 r-xp 00000000 103:06 2233468                   /lib/x86_64-linux-gnu/libnsl-2.27.so
7f4b69b0b000-7f4b69d0a000 ---p 00017000 103:06 2233468                   /lib/x86_64-linux-gnu/libnsl-2.27.so
7f4b69d0a000-7f4b69d0b000 r--p 00016000 103:06 2233468                   /lib/x86_64-linux-gnu/libnsl-2.27.so
7f4b69d0b000-7f4b69d0c000 rw-p 00017000 103:06 2233468                   /lib/x86_64-linux-gnu/libnsl-2.27.so
7f4b69d0e000-7f4b69d19000 r-xp 00000000 103:06 2233485                   /lib/x86_64-linux-gnu/libnss_nis-2.27.so
7f4b69d19000-7f4b69f18000 ---p 0000b000 103:06 2233485                   /lib/x86_64-linux-gnu/libnss_nis-2.27.so
7f4b69f18000-7f4b69f19000 r--p 0000a000 103:06 2233485                   /lib/x86_64-linux-gnu/libnss_nis-2.27.so
7f4b69f19000-7f4b69f1a000 rw-p 0000b000 103:06 2233485                   /lib/x86_64-linux-gnu/libnss_nis-2.27.so
7f4b69f1a000-7f4b69f22000 r-xp 00000000 103:06 2233470                   /lib/x86_64-linux-gnu/libnss_compat-2.27.so
7f4b69f22000-7f4b6a122000 ---p 00008000 103:06 2233470                   /lib/x86_64-linux-gnu/libnss_compat-2.27.so
7f4b6a122000-7f4b6a123000 r--p 00008000 103:06 2233470                   /lib/x86_64-linux-gnu/libnss_compat-2.27.so
7f4b6a123000-7f4b6a124000 rw-p 00009000 103:06 2233470                   /lib/x86_64-linux-gnu/libnss_compat-2.27.so
7f4b6a124000-7f4b6a12e000 r-xp 00000000 103:06 5378713                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libinstrument.so
7f4b6a12e000-7f4b6a32d000 ---p 0000a000 103:06 5378713                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libinstrument.so
7f4b6a32d000-7f4b6a32e000 r--p 00009000 103:06 5378713                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libinstrument.so
7f4b6a32e000-7f4b6a32f000 rw-p 0000a000 103:06 5378713                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libinstrument.so
7f4b6a32f000-7f4b6ad00000 r--p 00000000 103:06 5380833                   /usr/lib/locale/locale-archive
7f4b6ad00000-7f4b6ad02000 r-xp 00000000 103:06 5378731                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libnpt.so
7f4b6ad02000-7f4b6af02000 ---p 00002000 103:06 5378731                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libnpt.so
7f4b6af02000-7f4b6af03000 r--p 00002000 103:06 5378731                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libnpt.so
7f4b6af03000-7f4b6af04000 rw-p 00003000 103:06 5378731                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libnpt.so
7f4b6af04000-7f4b6af3e000 r-xp 00000000 103:06 5378723                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libjdwp.so
7f4b6af3e000-7f4b6b13d000 ---p 0003a000 103:06 5378723                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libjdwp.so
7f4b6b13d000-7f4b6b13e000 r--p 00039000 103:06 5378723                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libjdwp.so
7f4b6b13e000-7f4b6b13f000 rw-p 0003a000 103:06 5378723                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libjdwp.so
7f4b6b13f000-7f4b6b169000 r-xp 00000000 103:06 5378718                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libjava.so
7f4b6b169000-7f4b6b368000 ---p 0002a000 103:06 5378718                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libjava.so
7f4b6b368000-7f4b6b369000 r--p 00029000 103:06 5378718                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libjava.so
7f4b6b369000-7f4b6b36b000 rw-p 0002a000 103:06 5378718                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libjava.so
7f4b6b36b000-7f4b6b37b000 r-xp 00000000 103:06 5378741                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libverify.so
7f4b6b37b000-7f4b6b57a000 ---p 00010000 103:06 5378741                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libverify.so
7f4b6b57a000-7f4b6b57c000 r--p 0000f000 103:06 5378741                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libverify.so
7f4b6b57c000-7f4b6b57d000 rw-p 00011000 103:06 5378741                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libverify.so
7f4b6b57d000-7f4b6b584000 r-xp 00000000 103:06 2233525                   /lib/x86_64-linux-gnu/librt-2.27.so
7f4b6b584000-7f4b6b783000 ---p 00007000 103:06 2233525                   /lib/x86_64-linux-gnu/librt-2.27.so
7f4b6b783000-7f4b6b784000 r--p 00006000 103:06 2233525                   /lib/x86_64-linux-gnu/librt-2.27.so
7f4b6b784000-7f4b6b785000 rw-p 00007000 103:06 2233525                   /lib/x86_64-linux-gnu/librt-2.27.so
7f4b6b785000-7f4b6b79c000 r-xp 00000000 103:06 2233421                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7f4b6b79c000-7f4b6b99b000 ---p 00017000 103:06 2233421                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7f4b6b99b000-7f4b6b99c000 r--p 00016000 103:06 2233421                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7f4b6b99c000-7f4b6b99d000 rw-p 00017000 103:06 2233421                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7f4b6b99d000-7f4b6bb3a000 r-xp 00000000 103:06 2233447                   /lib/x86_64-linux-gnu/libm-2.27.so
7f4b6bb3a000-7f4b6bd39000 ---p 0019d000 103:06 2233447                   /lib/x86_64-linux-gnu/libm-2.27.so
7f4b6bd39000-7f4b6bd3a000 r--p 0019c000 103:06 2233447                   /lib/x86_64-linux-gnu/libm-2.27.so
7f4b6bd3a000-7f4b6bd3b000 rw-p 0019d000 103:06 2233447                   /lib/x86_64-linux-gnu/libm-2.27.so
7f4b6bd3b000-7f4b6beb4000 r-xp 00000000 103:06 5383035                   /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25
7f4b6beb4000-7f4b6c0b4000 ---p 00179000 103:06 5383035                   /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25
7f4b6c0b4000-7f4b6c0be000 r--p 00179000 103:06 5383035                   /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25
7f4b6c0be000-7f4b6c0c0000 rw-p 00183000 103:06 5383035                   /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25
7f4b6c0c4000-7f4b6cd63000 r-xp 00000000 103:06 5378745                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so
7f4b6cd63000-7f4b6cf63000 ---p 00c9f000 103:06 5378745                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so
7f4b6cf63000-7f4b6cff7000 r--p 00c9f000 103:06 5378745                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so
7f4b6cff7000-7f4b6d020000 rw-p 00d33000 103:06 5378745                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so
7f4b6d050000-7f4b6d06a000 r-xp 00000000 103:06 2233517                   /lib/x86_64-linux-gnu/libpthread-2.27.so
7f4b6d06a000-7f4b6d269000 ---p 0001a000 103:06 2233517                   /lib/x86_64-linux-gnu/libpthread-2.27.so
7f4b6d269000-7f4b6d26a000 r--p 00019000 103:06 2233517                   /lib/x86_64-linux-gnu/libpthread-2.27.so
7f4b6d26a000-7f4b6d26b000 rw-p 0001a000 103:06 2233517                   /lib/x86_64-linux-gnu/libpthread-2.27.so
7f4b6d26f000-7f4b6d272000 r-xp 00000000 103:06 2233407                   /lib/x86_64-linux-gnu/libdl-2.27.so
7f4b6d272000-7f4b6d471000 ---p 00003000 103:06 2233407                   /lib/x86_64-linux-gnu/libdl-2.27.so
7f4b6d471000-7f4b6d472000 r--p 00002000 103:06 2233407                   /lib/x86_64-linux-gnu/libdl-2.27.so
7f4b6d472000-7f4b6d473000 rw-p 00003000 103:06 2233407                   /lib/x86_64-linux-gnu/libdl-2.27.so
7f4b6d473000-7f4b6d48f000 r-xp 00000000 103:06 2233556                   /lib/x86_64-linux-gnu/libz.so.1.2.11
7f4b6d48f000-7f4b6d68e000 ---p 0001c000 103:06 2233556                   /lib/x86_64-linux-gnu/libz.so.1.2.11
7f4b6d68e000-7f4b6d68f000 r--p 0001b000 103:06 2233556                   /lib/x86_64-linux-gnu/libz.so.1.2.11
7f4b6d68f000-7f4b6d690000 rw-p 0001c000 103:06 2233556                   /lib/x86_64-linux-gnu/libz.so.1.2.11
7f4b6d690000-7f4b6d877000 r-xp 00000000 103:06 2233384                   /lib/x86_64-linux-gnu/libc-2.27.so
7f4b6d877000-7f4b6da77000 ---p 001e7000 103:06 2233384                   /lib/x86_64-linux-gnu/libc-2.27.so
7f4b6da77000-7f4b6da7b000 r--p 001e7000 103:06 2233384                   /lib/x86_64-linux-gnu/libc-2.27.so
7f4b6da7b000-7f4b6da7d000 rw-p 001eb000 103:06 2233384                   /lib/x86_64-linux-gnu/libc-2.27.so
7f4b6da7d000-7f4b6da81000 rw-p 00000000 00:00 0 
7f4b6da81000-7f4b6da8f000 r-xp 00000000 103:06 5378704                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/jli/libjli.so
7f4b6da8f000-7f4b6dc8e000 ---p 0000e000 103:06 5378704                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/jli/libjli.so
7f4b6dc8e000-7f4b6dc8f000 r--p 0000d000 103:06 5378704                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/jli/libjli.so
7f4b6dc8f000-7f4b6dc90000 rw-p 0000e000 103:06 5378704                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/jli/libjli.so
7f4b6dc90000-7f4b6dcb7000 r-xp 00000000 103:06 2233356                   /lib/x86_64-linux-gnu/ld-2.27.so
7f4b6dcb7000-7f4b6dcb9000 r--s 00001000 103:06 531540                    /**use dir**/soft/idea-IU-191.7479.19/lib/rt/debugger-agent-storage.jar
7f4b6dcbb000-7f4b6dcc2000 r--s 00066000 103:06 531541                    /**use dir**/soft/idea-IU-191.7479.19/lib/rt/debugger-agent.jar
7f4b6dcc2000-7f4b6dcc4000 r--s 0000b000 103:06 663148                    /**use dir**/soft/tomcat/apache-tomcat-8.5.47/bin/tomcat-juli.jar
7f4b6dcc4000-7f4b6dcc6000 r--s 00005000 103:06 663030                    /**use dir**/soft/tomcat/apache-tomcat-8.5.47/bin/commons-daemon.jar
7f4b6dcc6000-7f4b6dcc8000 r--s 00007000 103:06 663021                    /**use dir**/soft/tomcat/apache-tomcat-8.5.47/bin/bootstrap.jar
7f4b6dcc8000-7f4b6dce3000 r--s 001d6000 103:06 5378761                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/nashorn.jar
7f4b6dce3000-7f4b6dced000 r--s 00116000 103:06 5378760                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/localedata.jar
7f4b6dced000-7f4b6dcee000 r--s 0000d000 103:06 5378762                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunec.jar
7f4b6dcee000-7f4b6dcf0000 r--s 00007000 103:06 5771842                   /usr/share/java/java-atk-wrapper.jar
7f4b6dcf0000-7f4b6dcf1000 r--s 0000a000 103:06 5378759                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/jaccess.jar
7f4b6de9d000-7f4b6dea2000 r--s 0003c000 103:06 5378763                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunjce_provider.jar
7f4b6dea2000-7f4b6dea3000 r--s 00010000 103:06 5378765                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/zipfs.jar
7f4b6dea3000-7f4b6dea5000 r--s 00001000 103:06 5378757                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/dnsns.jar
7f4b6dea5000-7f4b6dea8000 r--s 00039000 103:06 5378764                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunpkcs11.jar
7f4b6dea8000-7f4b6deab000 r--s 0000f000 103:06 5378758                   /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/icedtea-sound.jar
7f4b6deab000-7f4b6deb3000 rw-s 00000000 103:06 1316287                   /tmp/hsperfdata_*user*/5205
7f4b6deb7000-7f4b6deb8000 r--p 00027000 103:06 2233356                   /lib/x86_64-linux-gnu/ld-2.27.so
7f4b6deb8000-7f4b6deb9000 rw-p 00028000 103:06 2233356                   /lib/x86_64-linux-gnu/ld-2.27.so
7f4b6deb9000-7f4b6deba000 rw-p 00000000 00:00 0 
7ffff0a20000-7ffff0a42000 rw-p 00000000 00:00 0                          [stack]
7ffff0b62000-7ffff0b65000 r--p 00000000 00:00 0                          [vvar]
7ffff0b65000-7ffff0b66000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

**Comment by apangin** [comment]
Thank you for the info. Now I understand what's happened.

These `[unknown]` part is basically the kernel functions. But the default settings in 5.0-Ubuntu Linux deny access to the kernel symbols.

Run `echo 0 | sudo tee /proc/sys/kernel/kptr_restrict` to enable kernel symbols.

Meanwhile I'll work on the fix to make the output more obvious about kernel restrictions.

**Comment by wenbeicai** [comment]
It's my fault . I already set this value.But when I reboot my computer then the value be restored.
One More question,I already set this value,but still has some methods are unkonwn.Like this.
![2019-11-17 10-30-55 的屏幕截图](https://user-images.githubusercontent.com/16438030/69002210-5d2ea780-0925-11ea-882c-e67805dc5921.png)
It's normal?

**Comment by apangin** [comment]
> It's normal?

Yes, this is kind of normal. Apparently, glibc was compiled with `-fomit-frame-pointer` option, which makes impossible to get the stack trace by traversing frame pointer chain. So, the native stack trace breaks at glibc function (`read` and `write` in your case) and then continues from Java part.

Fortunately, this is not a big problem for Java, since the missed part usually consists of 1-2 frames which are often obvious from the context. After all, this is not an async-profiler's bug. I'll investigate the alternative approaches to stack walking in #215.

**Comment by wenbeicai** [comment]
thanks！
