### ISSUE TITLE
itimer event need '-XX:+PreserveFramePointer'?

### ISSUE THREAD

**Issue by wenbeicai** [jvm-profiling-tools/async-profiler#275]
Hi,Because many machine '/proc/sys/kernel/perf_event_paranoid' value is 3. So i choose itimer event.Does this event need target VM add  '-XX:+PreserveFramePointer' property?

**Comment by apangin** [comment]
async-profiler does not require `-XX:+PreserveFramePointer`.
Neither in `cpu`, nor in `itimer` mode.

**Comment by wenbeicai** [comment]
Thanks
