### ISSUE TITLE
Correlate with Java threads

### ISSUE THREAD

**Issue by felixbarny** [jvm-profiling-tools/async-profiler#277]
First of all, thanks for this awesome library!

I'm trying to correlate stack traces with Java threads. However, the thread ids reported by async-profiler are the native thread ids which are not equal to Java thread ids.

Async-profiler reports the thread name which matches with `java.lang.Thread::getName`. However, not all threads seem to have a name attached to them. See the else block here:

https://github.com/jvm-profiling-tools/async-profiler/blob/2557363892b7f83dec4c652ca1b19e50e21877e4/src/frameName.cpp#L165-L169

My question is why is the thread name unknown sometimes and in which cases? The thread name seems to be mandatory at the Java level.

**Comment by felixbarny** [comment]
In case you're wondering about all my issues: I'm evaluating how we could leverage async-profiler in the Elastic APM Java agent. The goal would be both, to offer a dashboard for CPU profiling, aggregated at the service level, and to create spans for long executing methods for individual transactions.

**Comment by apangin** [comment]
It is one of the main features of async-profiler that it samples not only Java threads, but also native threads, including JIT compiler, GC, and other VM threads.
These threads are not running Java code, they do not have Java thread ID or a Java thread name.

**Comment by felixbarny** [comment]
Makes sense, thanks.

**Comment by felixbarny** [comment]
There is one issue, however. The name of threads is not guaranteed to be unique. Would it be possible to include a method in the Java API that returns the native thread id given a Java thread?

**Comment by apangin** [comment]
It's not hard to add such a method, but it doesn't seem very useful.
By the time the method is called, a thread may have already exited. Even though java.lang.Thread object still exists, it does not necessary have a native thread ID.

**Comment by felixbarny** [comment]
> By the time the method is called, a thread may have already exited.

That could be solved by instrumenting `Thread::start` calling the method before `Thread::start` exits.

> Even though java.lang.Thread object still exists, it does not necessary have a native thread ID.

Are you referring to Fibers?

**Comment by felixbarny** [comment]
I hope it's ok to reopen. This is currently the last remaining issue for us to be able to use async-profiler in the Elastic APM Java agent.

**Comment by apangin** [comment]
I added `AsyncProfiler.getNativeThreadId()` method. Hopefully, it's what you are looking for. But be aware that the method is not safe wrt. thread races. It returns -1 if the target thread has not yet started or has already finished.

**Comment by felixbarny** [comment]
This is great, thanks! I intend to use it in the context of the current thread (`AsyncProfiler.getNativeThreadId(Thread.currentThread())). That should leave no chance for race conditions.

Not sure if that's possible but IMOH the ideal way to correlate to Java thread would be to fill the `javaThreadId` property of the thread data structure in the JFR file. But I'm not sure if it's possible to get the Java thread id given a native thread id.

**Comment by felixbarny** [comment]
> I intend to use it in the context of the current thread (AsyncProfiler.getNativeThreadId(Thread.currentThread())). That should leave no chance for race conditions.

Seems like there can still be situations where `AsyncProfiler.getNativeThreadId` can return `-1`, even if the thread is in a `RUNNABLE` state. Consecutive calls may return `-1`, `0` or the actual native thread id. 

In my test this loop takes around 1 million iterations until it terminates:
```java
long nativeThreadId = -1;
do {
    nativeThreadId = asyncProfiler.getNativeThreadId(thread);
} while (nativeThreadId < 1);
```

Do you know what could be the reason for that and how to circumvent it?

**Comment by apangin** [comment]
No, I haven't seen such a problem. Can you share the whole test program that demonstrates the issue?

**Comment by felixbarny** [comment]
Although I can reproduce this as a side effect of a rather complex unit test, I failed to reproduce it in a more isolated test. It seems to be a concurrency issue. If one thread `start`s profiling and another one calls `getNativeThreadId`, this situation can occur. My guess is that first calling either `AsyncProfiler.start` or `AsyncProfiler.getNativeThreadId` sort of initializes the native agent in a way that `AsyncProfiler.version` does not and doing that initialization from two different threads leads to problems.

A workaround is to call `instance.getNativeThreadId(Thread.currentThread())` inbetween these lines:

https://github.com/jvm-profiling-tools/async-profiler/blob/5044869ecd9ed705ab1c3aac9a09b98e4ccf40ea/src/java/one/profiler/AsyncProfiler.java#L49-L50

or within the constructor.

**Comment by apangin** [comment]
Right, the ability to get native thread ID of an arbitrary Java thread requires [rather complicated] initialization sequence. It may result in a race condition with another thread that starts profiling.

I don't want to complicate things even more by adding mutexes, etc. Running initialization in the constructor is not the best option either, since this would imply doing redundant work in the very basic case (when the profiler starts right after the initialization).

Given that `getNativeThreadId(Thread)` API wasn't really safe from the very beginning, and since you always call it with `Thread.currentThread()`, I decided to replace this API altogether.

Now this is just `getNativeThreadId()` without arguments. It returns `tid` of the current thread. This is much simpler and safer, and does not concur with other profiler methods.

**Comment by felixbarny** [comment]
Sounds good, thanks!

What do you think about this?
> Not sure if that's possible but IMOH the ideal way to correlate to Java thread would be to fill the javaThreadId property of the thread data structure in the JFR file. But I'm not sure if it's possible to get the Java thread id given a native thread id.

**Comment by apangin** [comment]
This is definitely doable. I'll consider this option.
However, I'm not excited about extending JFR output too much right now, since my bigger plan is to rework the profiler output entirely, in order to dump as much details as possible and to allow building custom converters and visualizers.

**Comment by felixbarny** [comment]
Is there some place I can go for snapshot builds? If not, could you do me a favor and upload `libasyncProfiler.so` for Linux?

**Comment by apangin** [comment]
Here it is - [async-profiler-1.7.0-776b559-linux-x64.tar.gz](https://github.com/jvm-profiling-tools/async-profiler/files/4048359/async-profiler-1.7.0-776b559-linux-x64.tar.gz)

I'll see how I can organize regular snapshot builds.

**Comment by apangin** [comment]
I updated JFR writer to record Java thread IDs.

If I simply add a new field in the Thread data structure, the generated JFR won't be opened in Java Mission Control. Hence one more level of indirection: a new JavaThread data structure that maps Java thread ID to OS thread ID. A new ContentType table was added to the Checkpoint section of JFR.

**Comment by felixbarny** [comment]
Thanks! I could now replace `getNativeThreadId()` with the Java thread id from the JFR recording. As far as I'm concerned the method could be removed.
