### ISSUE TITLE
Export to JFR does not work when using Java API

### ISSUE THREAD

**Issue by felixbarny** [jvm-profiling-tools/async-profiler#278]
It seems like exporting to JFR does not work when using the Java API:

**Export JFR**
```
File file = new File(System.getProperty("java.io.tmpdir") + "/recording.jfr");
System.out.println(asyncProfiler.execute("start"));
Thread.sleep(1000);
System.out.println(asyncProfiler.execute("stop,jfr,file=" + file));
System.out.println(file.exists());
```

Output:
```
Started [cpu] profiling


false
```

I can't see any error, it just doesn't print `OK` and does not export the file.

Do you have any clue?

Exporting a with `traces` format works as expected:

**Export traces**
```
File file = new File(System.getProperty("java.io.tmpdir") + "/traces.txt");
System.out.println(asyncProfiler.execute("start"));
Thread.sleep(1000);
System.out.println(asyncProfiler.execute("stop,traces,file=" + file));
System.out.println(file.exists());
```

Output:
```
Started [cpu] profiling

OK
true
```

**Comment by apangin** [comment]
Unlike other output formats, JFR dumps results *at profiling time* rather than in the end (because it outputs all samples without aggregating them in memory).

This implies that the output file name should be specified with the `start` command instead of the `stop`.

**Comment by felixbarny** [comment]
Ah, of course! thx!
