### ISSUE TITLE
Wall-clock profiling in containers

### ISSUE THREAD

**Issue by felixbarny** [jvm-profiling-tools/async-profiler#280]
In https://github.com/jvm-profiling-tools/async-profiler#profiling-java-in-a-container a work-around for the limitations in containers is described: enabling `itimer` profiling mode.

My question is whether there's something similar for wall-clock profiling. Or should wall-clock profiling already work within containers?

**Comment by apangin** [comment]
Limitations apply only to the events collected through Linux perf counters API:

https://github.com/jvm-profiling-tools/async-profiler/blob/2557363892b7f83dec4c652ca1b19e50e21877e4/src/perfEvents_linux.cpp#L234-L252

`-e wall` and other profiling modes should work in a container with no additional requirements.
