### ISSUE TITLE
alloc flamegraph color schema

### ISSUE THREAD

**Issue by SergejIsbrecht** [jvm-profiling-tools/async-profiler#281]
I created several FlameGraphs with async-profiler and was wondering about the chosen colors for the Classes, which are allocated.

usage:
> -e alloc -d 60 -f /tmp/flame.svg

FlameGraph
![alloc_color_schema](https://user-images.githubusercontent.com/4427685/70930338-3c956280-2035-11ea-8940-5635a0b7c1aa.png)

> io.reactivex.subjects.PublishSubject$PublishDisposable[] 

The displays show an orange and an aqua/ cyan frame. Both frame are from the same class, but differ in the color and samples. Is this on purpose and if so, what is the meaning of the chosen colors?

I had a quick look in the code, but did not find any orange being used in: 
> FlameGraph::printFrame

Thank you for time and help

**Comment by apangin** [comment]
The color denotes where the object is allocated:

- objects allocated in a new Thread Local Allocation Buffer (TLAB) are displayed in aqua;
- objects allocated outside TLAB (directly in Eden or in OldGen) are displayed in orange.

**Comment by SergejIsbrecht** [comment]
@apangin , thank you for the explanation. 

Maybe we should extend the documentation on this in the README.md (https://github.com/jvm-profiling-tools/async-profiler#flame-graph-visualization). I would be glade to provide a short overview for FlameGraphs and the meaning for each stack-frame as a PR.

**Comment by apangin** [comment]
@SergejIsbrecht I agree, a paragraph in README would make sense. Documentation PRs are highly appreciated! Though I don't think it worth covering FlameGraph basics, as they are already explained well on the Brendan Gregg's website.
