### ISSUE TITLE
Failed to inject profiler into Error

### ISSUE THREAD

**Issue by Buffer0x7cd** [jvm-profiling-tools/async-profiler#282]
Hi, I am getting this error **Failed to inject profiler into Error** while trying to load the shared library inside the JVM, as per the README the issue occurs while running JVM and the profiler with different users, but in my case, I am running both the container process and profiler as root user. for the debugging purpose, I tried putting the profiler into a shared directory(between host and container) but it still didn't work. 

**Java Version info (host)**
```
$java -version
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```
Here is the output of running **jattach load command**
```
$./jattach $pid load ./async-profiler.jar false
Connected to remote JVM
Response code = -1

$ldd libasyncProfiler.so
	linux-vdso.so.1 =>  (0x00007fff2e5fa000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f168e802000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f168e5e5000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f168e3dd000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f168e05b000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f168dd52000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f168db3c000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f168d772000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f168f038000)
$
```
and here is the output of running `java -agentpath:./libasyncProfiler.so=start,summary,flat -version`

````
$java -agentpath:./libasyncProfiler.so=start,summary,flat -version
Started [cpu] profiling
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
--- Execution profile ---
Total samples       : 1

Frame buffer usage: 0.0018%

          ns  percent  samples  top
  ----------  -------  -------  ---
    10064005  100.00%        1  /lib/x86_64-linux-gnu/ld-2.23.so
```

can you please let me know if there is something that I am missing here ?

**Comment by apangin** [comment]
The error means that JVM cannot load libasyncProfiler.so, because the library or one of its dependencies is not accessible from inside the container.

Does the container run the same OS as the host? E.g. if the profiler was built on the host with glibc, but the container runs Alpine with musl, it won't work. You would need the profiler built for Alpine.

Try to log into the container and execute `ldd /full/path/to/libasyncProfiler.so` from inside.
Note that `/full/path/to/libasyncProfiler.so` must be the same path in the container and on the host.
