### ISSUE TITLE
`itimer` profiling under WSL doesn't generate data

### ISSUE THREAD

**Issue by genmeblog** [jvm-profiling-tools/async-profiler#286]
As README suggest `itimer` profiling should be used when `perf_event_open` is not supported (here: in WSL). But unfortunatelly `itimer` doesn't generate any data. I tried `alloc` events and got beautiful flame graph.

Details:

- WSL 1.0, with Linux kernel 4.4 (Ubuntu 18.04.3)
- OpenJDK 11.0.5
- tested on locally compiled version also released (1.6)
- tested with recommended JVM settings

```
./profiler.sh -d 10 -e itimer -f profile.svg 22391
```
Results empty g tag: `<g id="frames"></g>`, while

```
./profiler.sh -d 10 -e alloc -f profile.svg 22391 
```
is full of frames.

**Comment by apangin** [comment]
True. I'm also a WSL user, and I'm sorry to admit that neither perf, nor itimer works there.
`setitimer(ITIMER_PROF)` is not supported on WSL, see https://github.com/microsoft/WSL/issues/1577

Unlike WSL 2, WSL 1 is not a true Linux kernel, and there are so many things that do not work properly there.

I think I'll adapt wall-clock profiling mode to replace "cpu" profiler on WSL. Though I wouldn't trust performance results on WSL anyway.

**Comment by apangin** [comment]
I committed the fix that enables CPU profiling (`-e cpu`) on WSL using the fallback engine. It's not very accurate, but still better than safepoint-based profilers.

Also added the error message saying that `-e itimer` is not supported on WSL.

**Comment by genmeblog** [comment]
Great, thanks, I'll check it soon.

**Comment by genmeblog** [comment]
cpu generates data, so thanks a lot
