### ISSUE TITLE
Actual sampling interval is much lower than the configured one with wall profiler

### ISSUE THREAD

**Issue by felixbarny** [jvm-profiling-tools/async-profiler#287]
When setting a sampling interval like 5ms, the actual interval seems to be more like 25ms. From https://github.com/jvm-profiling-tools/async-profiler/issues/257 I understand that there is some sort of throttling mechanism to avoid overhead? But it seems like the actual interval is always around 5x higher than the configured one. Probably that factor also depends on the number of threads? This makes it quite unpredictable what the actual interval is. Could you explain a bit of background around that and would it be possible to bring the actual interval closer to the configured one? 

In the aforementioned issue, you stated

> It's not a limitation, but more like an optimization to avoid long application pauses.

What do you mean with "application pauses" here? IIUC, the `wall` profiler does not rely on a global safepoint (which means stop-the-world-pauses).

From your experience, what would be a good default value for the sampling interval of the wall profiler so that the overhead is still low? Should something in the 5-20ms range work fine?

I'd also be interested to learn a bit more about how the wall profiler actually works. AFAIU, it's working quite differently in the sense that it's not based on AsyncGetCallTree or perf_events, right? Maybe you could explain a little how it works or link to some relevant resources?

Thanks a bunch 🙂

**Comment by felixbarny** [comment]
I think I understand a bit more now. This limit is also important to ensure that the spin-lock is not contended. So it does not really make sense to increase the number of threads to concurrently take a stack trace from.

https://github.com/jvm-profiling-tools/async-profiler/blob/9b24fdef997b39dbc72f0c78e1fbc11b93f71379/src/wallClock.cpp#L29

But would it be possible to dynamically adjust the sampling interval so that the actual delta between two thread dumps of the same thread is closer to the actual interval?

Example: interval is set to 10ms and the application runs with 8 threads. In this case, the actual interval is the same as the configured one. However, if the application has 80 threads, the actual interval would be around 10 ms. Would it be possible for async-profiler to dynamically adjust the underlying timer to fire every 1ms so we would end up with an actual delay of 10 ms?

If that's possible, it probably makes sense to set a lower limit for the timer or to just hard-limit at 1ms.

**Comment by felixbarny** [comment]
To make this backwards compatible (avoiding unexpected performance side effects when upgrading async-profiler), by default, the lower limit could be the same as the interval. Then there could be an option to specify a different limit, with 1ms being the minimum.

Or, maybe the interval could accept a range like `1ms-10ms` and `10ms` would be equal to `10ms-10ms`

**Comment by apangin** [comment]
I committed the fix into thread-filter branch.

1. At the beginning of each sampling cycle, the profiler estimates the number of threads, either in the filtered set, or in the entire process.
2. The sampling rate is automatically adjusted to complete the cycle in the specified amount of time.
3. Sampling is performed in portions of 8 threads at once. After each portion, profiler sleeps for at least 100 microseconds.
4. The default wall clock profiling interval is increased to 50 ms.
5. CPU profiling mechanics is not affected.

For example, when profiling an application for 30 seconds with 10ms interval, the profiler will try to produce 30*100 = 3000 samples for *each* thread (assuming the number of threads is reasonable).

**Comment by apangin** [comment]
Merged into master.
