### ISSUE TITLE
Allocation-Profile with cstack in rare cases without allocated class

### ISSUE THREAD

**Issue by SergejIsbrecht** [jvm-profiling-tools/async-profiler#288]
Environment:
* Linux 4.x
* OpenJDK8
* Version master (5044869ecd9ed705ab1c3aac9a09b98e4ccf40ea)

Action:
-d 60 -e alloc --cstack -f /tmp/fg.svg

Problem:
I saw in rare cases, that the allocated class on top of the stack is missing

![cstack_alloc_no_class](https://user-images.githubusercontent.com/4427685/71965721-86223900-3200-11ea-84bd-d0b3c0217530.png)

Expected behavior:
Top of the stack is always a Java-Class (e.g. char[]).

Edit:
Problem is probably not related to --cstack, because I do see profiles with call-stacks without a java class on top.

Example: (build with 1.6 release)
![top_of_stack_not_java_class](https://user-images.githubusercontent.com/4427685/71966701-5b38e480-3202-11ea-9930-148aad5a8a47.png)

Note:
Problem is visible only on very rare cases (0.1% in the example)

**Comment by apangin** [comment]
Try `--minwidth 0`

By default, built-in FlameGraph visualizer truncates stack traces smaller than 0.25px in width (i.e. traces with less than 0.02% samples). Too small details may bloat the output svg, so it could be hardly opened in a browser. `--minwidth` option configures the level of details.
