### ISSUE TITLE
Empty flame graphs generated on Ubuntu + JDK8

### ISSUE THREAD

**Issue by DSteve595** [jvm-profiling-tools/async-profiler#289]
I've used async-profiler successfully on Mac, but after switching to a Linux machine (Ubuntu 19.10), I'm only getting empty flame graphs like this one: [flame.zip](https://github.com/jvm-profiling-tools/async-profiler/files/4048051/flame.zip)

I'm trying to profile a Gradle daemon using this command:
`./profiler.sh -f ~/Desktop/flame.svg start [pid]`
No errors are surfaced, but the flame graph shows no methods.
VisualVM and JProfiler are working properly.

Any ideas?

```
java -version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-8u232-b09-0ubuntu1.1-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)
```

**Comment by apangin** [comment]
- Check the console of the target program for the errors
 - Make sure `/proc/sys/kernel/perf_event_paranoid` is set to 1 or 0
 - Try `-e itimer`

**Comment by DSteve595** [comment]
`/proc/sys/kernel/perf_event_paranoid` was set to `3`. After changing it to `1`, the profiler works! Thanks very much.

**Comment by DSteve595** [comment]
Might be worth warning users if the currently-set value won't work?

**Comment by apangin** [comment]
The warning is actually printed, both in the stderr of the Java process, and in the profiler console (or in the output file, if `-f` specified). But I agree that current error reporting mechanism is not user-friendly. Going to rework this in future versions.

**Comment by DSteve595** [comment]
I didn't see anything in my output SVG, though I only looked at the rendered output, not the source. By "the Java process", do you mean the process for the target JVM, or the profiler process?

**Comment by apangin** [comment]
The target JVM process.
