### ISSUE TITLE
Can't do profiling due to "Perf events unavailable."

### ISSUE THREAD

**Issue by RoySunnySean007** [jvm-profiling-tools/async-profiler#292]
Dear experts,

I put the async-profiler under the user home which is running java progress.
And I grant full permission "chmod -R 777 async-profile" of async-profiler folder.
And I comment "> /dev/null" in the profiler.sh

The following is the result. Pls kindly let me know how I can proceed with troubleshooting, thx in advance! BTW,  I can do allocation profiling.

./profiler.sh start 1488
Connected to remote JVM
Response code = 0
0

Perf events unavailable. See stderr of the target process.

Thanks,
Roy Zhang

**Comment by apangin** [comment]
The reasons of this problem and the solutions to it are discussed in the [Troubleshooting](https://github.com/jvm-profiling-tools/async-profiler#troubleshooting) section of README.

**Comment by RoySunnySean007** [comment]
Dear @apangin 

I am profiling in a virtual machine.

“Make sure the user of JVM process has permissions to access libasyncProfiler.so by exactly the same absolute path.”

I grant full permission "chmod -R 777 async-profile" of async-profiler folder, and use the user of JVM process to do profiling. So I think requirement "Make sure the user of JVM process has permissions to access libasyncProfiler.so" is met.

What do u mean by "by exactly the same absolute path."? Thx!

Thanks,
Roy

**Comment by apangin** [comment]
Please read carefully the [Troubleshooting](https://github.com/jvm-profiling-tools/async-profiler#troubleshooting) section I've linked above. It contains the answer to your problem.

> ```
> Perf events unavailble. See stderr of the target process.
> ```
> `perf_event_open()` syscall has failed. The error message is printed to the error stream
> of the target JVM.
> 
> Typical reasons include:
>  1. `/proc/sys/kernel/perf_event_paranoid` is set to restricted mode (>=2).
>  2. seccomp disables perf_event_open API in a container.
>  3. OS runs under a hypervisor that does not virtualize performance counters.
>  4. perf_event_open API is not supported on this system, e.g. WSL.
> 
> If changing the configuration is not possible, you may fall back to
> `-e itimer` profiling mode. It is similar to `cpu` mode, but does not
> require perf_events support. As a drawback, there will be no kernel
> stack traces. 
> 
>

**Comment by apangin** [comment]
@Artyomcool I'm not sure I understand. When do you need to restart a process?
In case of a permission issue, `perf_event_paranoid`, `--fdtransfer`, or `-e itimer` solutions can be applied immediately without a restart.

**Comment by Artyomcool** [comment]
```
./profiler.sh -e cpu,alloc -o jfr -f pack.jfr --chunktime 5 start jps
[WARN] Kernel symbols are unavailable due to restrictions. Try
  sysctl kernel.kptr_restrict=0
  sysctl kernel.perf_event_paranoid=1
[WARN] perf_event_open for TID 8519 failed: Permission denied
[WARN] perf_event_open for TID 8520 failed: Permission denied
[WARN] perf_event_open for TID 8525 failed: Permission denied
[WARN] perf_event_open for TID 8526 failed: Permission denied
[WARN] perf_event_open for TID 8527 failed: Permission denied
[WARN] perf_event_open for TID 8533 failed: Permission denied
[WARN] perf_event_open for TID 8534 failed: Permission denied
[WARN] perf_event_open for TID 8536 failed: Permission denied
[WARN] perf_event_open for TID 8539 failed: Permission denied
[WARN] perf_event_open for TID 8540 failed: Permission denied
[WARN] perf_event_open for TID 8546 failed: Permission denied
[WARN] perf_event_open for TID 8547 failed: Permission denied
[WARN] perf_event_open for TID 8548 failed: Permission denied
[WARN] perf_event_open for TID 8549 failed: Permission denied
[WARN] perf_event_open for TID 8550 failed: Permission denied
[WARN] perf_event_open for TID 8553 failed: Permission denied
[WARN] perf_event_open for TID 8555 failed: Permission denied
[WARN] perf_event_open for TID 8566 failed: Permission denied
[WARN] perf_event_open for TID 8576 failed: Permission denied
[WARN] perf_event_open for TID 8577 failed: Permission denied
[WARN] perf_event_open for TID 8578 failed: Permission denied
[WARN] perf_event_open for TID 8579 failed: Permission denied
[WARN] perf_event_open for TID 8580 failed: Permission denied
[WARN] perf_event_open for TID 8581 failed: Permission denied
[WARN] perf_event_open for TID 8582 failed: Permission denied
[WARN] perf_event_open for TID 8593 failed: Permission denied
[WARN] perf_event_open for TID 8597 failed: Permission denied
[WARN] perf_event_open for TID 10008 failed: Permission denied
[ERROR] No access to perf events. Try --fdtransfer or --all-user option or 'sysctl kernel.perf_event_paranoid=1'
```


After that I'm performing the suggestion:
```
sudo su
sysctl kernel.kptr_restrict=0
sysctl kernel.perf_event_paranoid=1
exit

```
And repeat:
```
./profiler.sh -e cpu,alloc -o jfr -f pack.jfr --chunktime 5 start jps
[ERROR] Perf events unavailable

```
Process restart helps)

**Comment by apangin** [comment]
Interesting. On my system (CentOS 7, kernel 5.3.1) `perf_event_paranoid` settings take effect immediately without restart.

**Comment by Artyomcool** [comment]
OS: Ubuntu 16.04.12
Linux version: 4.15.0-142-generic

It could be just an OS issue but maybe just mentioning such possibility in troubleshooting section could help someone)
Do you want me to make such changes in docs?

**Comment by apangin** [comment]
@Artyomcool This appeared to be a stupid bug. I pushed the fix, now the workarounds should have effect without restart.
