### ISSUE TITLE
How to use Async Profiler internal Java API ? 

### ISSUE THREAD

**Issue by logan-dev-oss** [jvm-profiling-tools/async-profiler#293]
Hi!

### Goal
At the end of the day, I would like to use Async profiler during my iteration measurements with [JMH](https://openjdk.java.net/projects/code-tools/jmh/).

I found some information on following issues : 
#76 Marry async-profiler and JMH
#93 Publish Jar (with embedded native agent) to Maven central 

The last comment in issue #76 introduce an implementation of AsyncProfiler for JMH : 
https://github.com/ktoso/sbt-jmh/blob/master/extras/src/main/java/pl/project13/scala/jmh/extras/profiler/AsyncProfiler.java
This implementation use `jattach` internally.

I would like to create my own implementation but only using async-profiler internal Java API (I may be wrong and I should keep jattach for readability/performance ? but that's another problem). 

### Problem
I made some research and I tried to use internal async-profiler API on a simple toy project (without any jmh related stuff) and i fail to run any profiled code ... 

### Example
If I did not miss something in issue #93 internal API is not available on Maven central, therefore this is what I did : 

1. Copy all content of async-profiler::java.one.profiler package to my toy project.
2. Profile my application like this : 
 ```java
package async;

import profile.AsyncProfiler;
import profile.Events;

public final class Main {
    public static void main(String[] args) {
        AsyncProfiler profiler = AsyncProfiler.getInstance("/path/to/libasyncProfiler.so");
        profiler.start(Events.CPU, 1000);
        anyMethodCall();
        profiler.stop();
    }
}
```

I also tried with only `AsyncProfiler profiler = AsyncProfiler.getInstance()`and set `java.library.path` when starting jvm but I still get following error : 
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'java.lang.String profile.AsyncProfiler.version0()'
	at profile.AsyncProfiler.version0(Native Method)
	at profile.AsyncProfiler.<init>(AsyncProfiler.java:31)
	at profile.AsyncProfiler.getInstance(AsyncProfiler.java:49)
	at async.Main.main(Main.java:8)
```

### Question
Can you provide me some help for using internal async profiler java API please ? 

### System information 
```
OS: Arch Linux x86_64
Kernel: 5.4.13-arch1-1
```
```
$ java --version 
openjdk 13.0.1 2019-10-15
OpenJDK Runtime Environment (build 13.0.1+9)
OpenJDK 64-Bit Server VM (build 13.0.1+9, mixed mode)
```
The java version is recompiled with debug symbols.
```
$ ./profiler.sh --version
Async-profiler 1.6 built on Jan 19 2020
Copyright 2019 Andrei Pangin
```
I built async profiler with the recommended fix for JDK13 in pull request #285  Make release version of javac specifiable. 

For information, my async-profiler works as expected when used with `profiler.sh` script or via java agent.

Thanks.

**Comment by apangin** [comment]
Keeping original `one.profiler` package is essential for interaction between Java API and the native library. That's how JNI works.

Try to run the original unmodified code.

**Comment by felixbarny** [comment]
If you really want to relocate the package, there's a trick to do that with Byte Buddy: https://gist.github.com/raphw/be0994259e75652f057c9e1d3ee5f567

**Comment by logan-dev-oss** [comment]
Thanks for your answer, keeping originial package fix my problem. Thanks.

**Comment by apangin** [comment]
I've updated profiler to automatically discover the proper class containing native methods.
This allows easy shading of AsyncProfiler API without Byte Buddy tricks etc.

**Comment by retronym** [comment]
I'm going to contribute an async-profiler integration to JMH. Here's my work so far: https://github.com/retronym/jmh/pull/2
