### ISSUE TITLE
async-profiler for x86 platform

### ISSUE THREAD

**Issue by Konstantinx64** [jvm-profiling-tools/async-profiler#294]
Is there an async-profiler version for x86 java/linux?
I can see x86 linux mentioned in _Supported platforms_, but don't see any download links for this version.
If I try **Linux x64 (glibc)** version by the command:
`java -agentpath:./libasyncProfiler.so=start,summary,flat -version`
then it shows me error:
`Error occurred during initialization of VM
Could not find agent library ./libasyncProfiler.so in absolute path, with error: ./libasyncProfiler.so: wrong ELF class: ELFCLASS64 (Possible cause: architecture word width mismatch)`

**Comment by apangin** [comment]
Since there is not much demand for x86 port, I don't prepare binaries.

However, it should be fairly easy to [build the project](https://github.com/jvm-profiling-tools/async-profiler/#building) from sources. Typically this is just a matter of the single `make` command.

**Comment by apangin** [comment]
I've published x86 build of the current development version, see https://github.com/jvm-profiling-tools/async-profiler/releases/tag/v1.7-ea
