### ISSUE TITLE
Update set of monitored threads for wall profiler

### ISSUE THREAD

**Issue by felixbarny** [jvm-profiling-tools/async-profiler#296]
Currently, when starting async-profiler in wall mode, it collects samples of up to 8 threads each interval.

There's a discussion about optimizations for the wall profiler: https://github.com/jvm-profiling-tools/async-profiler/issues/237

What I would like to propose additionally is to have a Java API which lets me update the threads I'm currently interested in monitoring. As those interesting threads can change during the course of a profiling session, I'd like to have the possibility to call this method while the profiler is running.

**Comment by apangin** [comment]
Proposed API:

https://github.com/jvm-profiling-tools/async-profiler/blob/26643237cd4e9a0129b4cebada8bd0ea4c9628b5/src/java/one/profiler/AsyncProfiler.java#L165-L173

**Comment by apangin** [comment]
Revised Java API to update the set of monitored threads:

```java
// Add the given thread to the set of profiled threads
public void addThread(Thread thread);

// Remove the given thread from the set of profiled threads
public void removeThread(Thread thread);
```
