### ISSUE TITLE
jattach permission denied

### ISSUE THREAD

**Issue by SugisakiKen** [jvm-profiling-tools/async-profiler#299]
![image](https://user-images.githubusercontent.com/23693530/74442138-f1b88f80-4eab-11ea-810e-fa1386b7645f.png)

version: 1.7 ea2
environment : linux x64 rhel , open jdk 1.8

hope you help,sincerely

**Comment by apangin** [comment]
Take a look at file mode bits.
Seems like `x` (execute) permission was lost when unpacking archive.
```
$ ls -l async-profiler/build/
total 268
-rw-r--r-- 1 root root   3639 Feb 13 03:14 async-profiler.jar
-rwxr-xr-x 1 root root  21795 Feb 13 03:14 jattach
-rwxr-xr-x 1 root root 245412 Feb 13 03:14 libasyncProfiler.so
```

**Comment by SugisakiKen** [comment]
> Take a look at file mode bits.
> Seems like `x` (execute) permission was lost when unpacking archive.
> 
> ```
> $ ls -l async-profiler/build/
> total 268
> -rw-r--r-- 1 root root   3639 Feb 13 03:14 async-profiler.jar
> -rwxr-xr-x 1 root root  21795 Feb 13 03:14 jattach
> -rwxr-xr-x 1 root root 245412 Feb 13 03:14 libasyncProfiler.so
> ```

works for me ,thx a lot :)
