### ISSUE TITLE
Class profiling

### ISSUE THREAD

**Issue by cloud-66** [jvm-profiling-tools/async-profiler#300]
Hello,  Is it possible  to profile every method from a specific class, for example
-e ClassName.*

If no, Do you plan to add this future?

**Comment by apangin** [comment]
@cloud-66 Do you mean method invocation profiling, i.e. when async-profiler records the fact of invocation of each method in the given class?

**Comment by cloud-66** [comment]
@apangin  yes

**Comment by apangin** [comment]
Async-profiler cannot do this right now, but it shouldn't be difficult to implement.
Do you have an example of a potential use case for this feature?

**Comment by apangin** [comment]
Async-profiler now recognizes star pattern in method names, e.g.
```
-e java.io.File.*
-e java.io.File.get*
```
