### ISSUE TITLE
Feature Request: list of hotspots by self time

### ISSUE THREAD

**Issue by andredasilvapinto** [jvm-profiling-tools/async-profiler#302]
Would it be possible to add an output format that sorts usage by the aggregated sum of self time per function?

I feel like the hierarchical nature of the current representations is not optimal for detecting bottlenecks as the same method can be invoke by following multiple different code paths.

**Comment by apangin** [comment]
Such option has existed from the very beginning :)
Use `-o flat` to get the list of hot spots sorted by self time.

Alternatively, try `--reverse` to flip Flame Graph or Tree View from bottom to top, that its, the graph will have the hottest leaf methods as roots.

**Comment by andredasilvapinto** [comment]
Thanks! I knew I couldn't be the only one looking for this.
