### ISSUE TITLE
Trying to understand how methods executing in different threads are aggregated during Sampling

### ISSUE THREAD

**Issue by h4xr** [jvm-profiling-tools/async-profiler#304]
Hi, I am trying to understand how does methods executing in different threads are aggregated by Async profiler to generate the final results.
For some of the applications, we can at times have 100's of threads which could be executing at the same time and when the profiler takes a sample,I assume the method invocation stack snapshot is taken for all these threads. If this is the what is taking place, how are the method invocation snapshots merged to generate the visualisation? or does this process look different?

**Comment by apangin** [comment]
Without `-t` option (the default), profiler aggregates samples by stack traces, no matter which thread generates an event. With `-t` option, samples are grouped by a thread, i.e. each thread has a separate profile.

CPU and wall-clock modes produce samples differently. In CPU mode (the default), samples are generated by the hardware when a thread is running on a core. In this case, even if an application has 100 threads, at any given moment of time there can't be more than N actively running threads, where N is the number of CPUs. In wall-clock mode (`-e wall`), all threads, both running and idle, are sampled equally.

**Comment by h4xr** [comment]
@apangin Thanks a lot for the clarification. Just trying to improve my clarity on the use case when per thread mode option is not provided.
Let's say we have a program which contains a method "methodA" and there are 4 threads which are executing concurrently. All of these 4 threads are executing "methodA" only.

Now, if we sample for 100 seconds at a 1 second interval, will this translate to "methodA" being counted as 100 samples or 400 samples?

**Comment by apangin** [comment]
400 samples (assuming that `methodA` is 100% cpu-bound, and there are at least 4 cpu cores).

**Comment by h4xr** [comment]
Thanks a lot @apangin 
That provides clarity to what I have been thinking.
Closing this issue :)
