### ISSUE TITLE
Provide trigger based profiling

### ISSUE THREAD

**Issue by rohitsethiyasnow** [jvm-profiling-tools/async-profiler#305]
Will it be possible to provide capability to capture profiling using the agent based on thresholds like 80%mem or cpu

**Comment by apangin** [comment]
[Java API](https://github.com/jvm-profiling-tools/async-profiler/blob/master/src/java/one/profiler/AsyncProfiler.java) of async-profiler allows to start/stop/resume profiling right from Java code at any desired moment of time.

But please have in mind, that when cpu usage reaches certain threshold, it's probably too late to start profiling. When a hot code starts running, it's not yet accounted in the process' cpu usage. When profiler is triggered basing on cpu usage, it will likely loose the most interesting samples.

**Comment by jcdauchy** [comment]
I have some scala code where i would like to profile the call of a function. If i understand correctly, i can the start / stop from within my scala code to do the profiling ?

Thanks

**Comment by apangin** [comment]
@jcdauchy Yes, you can call AsyncProfiler.start/stop (or resume/stop, if the method is called multiple times) right from your Scala code.

[Here is an example in Java »](https://github.com/apangin/codeone2019-java-profiling/blob/master/src/demo8/FileConverter3.java)

Alternatively, you can profile the whole application, and then use `-I` option to filter only interesting method.
