### ISSUE TITLE
Unable to use Java API

### ISSUE THREAD

**Issue by rohitsethiyasnow** [jvm-profiling-tools/async-profiler#306]
hi @apangin 
I am trying to call the async profiler as java api in code but facing this exception when i use Asyncprofiler.getInstance("/path/to/libasyncProfiler.so");
Exception in thread "worker.36" java.lang.UnsatisfiedLinkError: Can't load library: /*/lib/libasyncProfiler.so
I made sure i add the .so file in the java library path and added this in java.policy file: 
permission java.lang.RuntimePermission 
    		"loadLibrary.*";

**Comment by apangin** [comment]
There are multiple reasons why the library can't be loaded. For example, missing dependencies (async-profiler depends on `libstdc++`), or the wrong architecture (e.g. you are loading a 64-bit profiler library into a 32-bit JVM process).

Try
1. `ldd /path/to/libasyncProfiler.so`
2. `java -agentpath:/path/to/libasyncProfiler.so=version=full -version`
