### ISSUE TITLE
profiler.sh doesn't show any errors if write to file failed

### ISSUE THREAD

**Issue by turbanoff** [jvm-profiling-tools/async-profiler#309]
I've tried to run `profiler.sh` and write output to file which I don't have permission to write.
Script didn't any errors.
It would be nice for troubleshooting and make user experience better to show error if creating/writing output file failed.
```
covstaging@covstaging [2020-03-18 19:21:34]:/tmp/async-profiler-1.7-linux-x64$ ./profiler.sh -d 60 -f profile.svg 10051
covstaging@covstaging [2020-03-18 19:24:02]:/tmp/async-profiler-1.7-linux-x64$ ls
build  profiler.sh
covstaging@covstaging [2020-03-18 19:24:03]:/tmp/async-profiler-1.7-linux-x64$
```
After I added permission, all worked fine
```
covstaging@covstaging [2020-03-18 19:24:24]:/tmp/async-profiler-1.7-linux-x64$ ./profiler.sh -d 60 -f profile.svg 10051
covstaging@covstaging [2020-03-18 19:25:30]:/tmp/async-profiler-1.7-linux-x64$ ls
build  profiler.sh  profile.svg
covstaging@covstaging [2020-03-18 19:25:30]:/tmp/async-profiler-1.7-linux-x64$
```

**Comment by apangin** [comment]
Output file is written by the target JVM process, not by the profiler script. If the file cannot be opened, the error message is printed to `stderr` of the target process (JVM console):
```
Could not open profile.svg
```
Unfortunately, the agent library (loaded into JVM) does not have a simple way to communicate its status back to the profiler script. Some kind of IPC would be needed. I was thinking of communicating through a pipe, but this may be tricky, given that the target process can be launched in a different namespace, under a different user etc. I will consider improving IPC on the next iteration of refactoring of the launcher.

**Comment by turbanoff** [comment]
I think we can improve `Troubleshooting` section in readme. It was not clear for me that profiler prints something to stderr of target JVM.
