### ISSUE TITLE
Profiling crashes Zing JVM after commit 119da0fc

### ISSUE THREAD

**Issue by pavel-vyssotski** [jvm-profiling-tools/async-profiler#310]
async-profiler crashes trying to get lastJavaSP from VMStructs as VMStructs is not initialized with Zing. 
Could you please add the check if VM::is_hotspot() in code added by the commit https://github.com/jvm-profiling-tools/async-profiler/commit/119da0fc "Replace unsafe calls to JVMTI GetStackTrace with manually patched AsyncGetCallTrace":
```
    } else if (trace.num_frames == ticks_unknown_not_Java) {
        VMThread* thread = VMThread::fromEnv(jni);
        if (thread != NULL) {
            uintptr_t& sp = thread->lastJavaSP();
            uintptr_t& pc = thread->lastJavaPC();
...
```

**Comment by apangin** [comment]
Thank you for the report.
Reverted `VM::is_hotspot()` check.

**Comment by yakirgb** [comment]
Thank you @apangin, the issue resolved.
