### ISSUE TITLE
1.7 Allocation Profiling producing empty flamegraph with Zing VM

### ISSUE THREAD

**Issue by debashisdeb** [jvm-profiling-tools/async-profiler#312]
I tried profiling my application which uses Zing VM,
`JDK version : JDK-1_8_0_191-zing_18_10_3_0`
`OS version  : rh7-release-x86_64-r12`

I'm using `jattach` to attach the lib to the running process, I'm able to do cpu profiling, wall clock profiling but allocation profiling is failing.

The output flame graph was empty, didn't capture any data. 
I tried other formats like `collapsed` too, but the file produced was of size `0 bytes`

`-rw-rw-r-- 1 ddeb  ddeb       0 Apr  9 17:11 result.collapsed`

Which versions of Zing is supported for Allocation Profiling ?

When I read the release notes for v1.6 of async-profiler, it had enabled Allocation profiling in JDK 12 and 13. But the v1.7 release note doesn't specify any specific version of Zing. 

I added the flamegraph, please rename it to .svg, as github isn't allowing svg uploads !
![alloc](https://user-images.githubusercontent.com/7792488/78922246-d89b1c00-7ab3-11ea-94a0-be20230aa668.jpeg)

Please help :)

**Comment by apangin** [comment]
Allocation profiling works with Zing JDK 8 and Zind JDK 11, at least with the following versions:
```
java version "1.8.0-zing_19.08.1.0"
Zing Runtime Environment for Java Applications (build 1.8.0-zing_19.08.1.0-b2)
Zing 64-Bit Tiered VM (build 1.8.0-zing_19.08.1.0-b3-product-azlinuxM-X86_64, mixed mode)
```
and
```
java version "11.0.4" 2019-09-20 LTS
Zing Runtime Environment for Java Applications 19.09.0.0+3 (product build 11.0.4+11-LTS)
Zing 64-Bit Tiered VM 19.09.0.0+3 (product build 11.0.4-zing_19.09.0.0-b4-product-azlinuxM-X86_64, mixed mode)
```

Looks like you have an older build which does not support allocation profiling. In this case the error message is printed to the console of the Java process:
```
No AllocTracer symbols found. Are JDK debug symbols installed?
```
