### ISSUE TITLE
profiler not sample all function

### ISSUE THREAD

**Issue by lebron374** [jvm-profiling-tools/async-profiler#313]
- [ ] 我已经在 [issues](https://github.com/alibaba/arthas/issues) 里搜索，没有重复的issue。

### 环境信息

* `arthas-boot.jar` 或者 `as.sh` 的版本： xxx
* Arthas 版本: 3.1.8
* 操作系统版本: mac os
* 目标进程的JVM版本: jdk1.8.0_191
* 执行`arthas-boot`的版本: 3.1.4

### problem reproduct

```
public class ArthasTest {

    public static void main(String[] args) throws Exception {

        while (true) {
            Calculate.doCalculate();

            Calculate.doSleep();
        }
    }
}


public class Calculate {

    public static void doCalculate() {
        for (int i = 0; i < 10000000; i++) {
            int d = i * i;
        }
    }

    public static void doSleep() {
        for (int i = 0; i < 10; i++) {
            int d = i * i;
        }
    }
}
```
### expect result 

火焰图展示出doCalculate和doSleep的CPU使用率

### actual result

only show ArthasTest.main but not include doCalculate
![image](https://user-images.githubusercontent.com/5032169/78890375-20ac4580-7a98-11ea-9952-3348f6e698d3.png)

**Comment by apangin** [comment]
Please, submit issues in English. I can't guarantee I will be able to read and answer comments in other languages.

In the given example async-profiler works correctly.

`doCalculate` method does not have any side effects, and nobody consumes its result. The loop does nothing useful, and thus JIT compiler optimizes it away entirely. What takes CPU time here is the endless loop in `ArthasTest.main`. Both `doCalculate` and `doSleep` are effectively a no-op.
