### ISSUE TITLE
Some JVM callstacks only display the top frame

### ISSUE THREAD

**Issue by QuantumBear** [jvm-profiling-tools/async-profiler#321]
I used the lastest code from master then try a simple example.

```
import java.util.ArrayList;
import java.util.List;

public class HeapOOM {
    static class OOMObject {}
    public static void main(String[] args) {
        List<OOMObject> xs = new ArrayList<>();

        int i = 0;
        while (i++ < Integer.MAX_VALUE/2) {
            xs.add(new OOMObject());
        }
    }
}

```

Try to generate svg file

```
MYSERVER: [me@MYSERVER] ~/async-profiler$ /opt/jdk8/bin/java -Xms30m -Xmx30m -agentpath:./build/libasyncProfiler.so=start,file=profile.svg HeapOOM                                               
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3210)
        at java.util.Arrays.copyOf(Arrays.java:3181)
        at java.util.ArrayList.grow(ArrayList.java:261)
        at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:235)
        at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:227)
        at java.util.ArrayList.add(ArrayList.java:458)
        at HeapOOM.main(HeapOOM.java:11)

```
My enviroment is CentOS release 6.5 (Final) with  2.6.32-696.6.3.el6.x86_64 and use Oracle JDK8.

```
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
```
My svg file attached here. I see the SpinPause is just on the all level. How can I generate a svg file that I can figure out which JVM internal function calls this SpinPause.

Thanks for your great profiler!

[profile.svg.zip](https://github.com/jvm-profiling-tools/async-profiler/files/4632143/profile.svg.zip)

**Comment by QuantumBear** [comment]
I generate a txt file using this command

```
/opt/jdk8/bin/java -Xms30m -Xmx30m -agentpath:./build/libasyncProfiler.so=start,collapsed,file=profile.txt HeapOOM
```

[profile.txt](https://github.com/jvm-profiling-tools/async-profiler/files/4632804/profile.txt)

**Comment by apangin** [comment]
I'm surprised that perf events work on 2.6.32 at all. This kernel version is too old. From my observation, perf events became more or less stable since 2.6.39.

Try timer-based profiling instead. Add `event=itimer` to the command line:
```
java -agentpath:./build/libasyncProfiler.so=start,event=itimer,file=profile.svg ...
```

I tried your example on my system (also with Oracle JDK 8u60), and the output was fine.
![profile](https://user-images.githubusercontent.com/1749416/82097208-20444180-970b-11ea-8be3-06d742937db5.png)

SVG version: [profile.svg.zip](https://github.com/jvm-profiling-tools/async-profiler/files/4637165/profile.svg.zip)

**Comment by QuantumBear** [comment]
Thanks, solved my problem!
