### ISSUE TITLE
Requirements for building it in a Cygwin environment

### ISSUE THREAD

**Issue by rovf** [jvm-profiling-tools/async-profiler#324]
I would like to build the profiler in a Windows 10 environment (Java8, Cygwin). What else, except gcc, is necessary to get things done?  I didn't find build instructions inside README.md

**Comment by martin-g** [comment]
On Linux one just needs to execute `make`

**Comment by apangin** [comment]
At the moment, Windows / cygwin is not a supported platform.

Closing as a duplicate of #188
