### ISSUE TITLE
Question related to issue 154 and JDK-8212155

### ISSUE THREAD

**Issue by krzysztofslusarski** [jvm-profiling-tools/async-profiler#325]
Hi, you wrote at issue 154 that attaching async-profiler as an agent is workaround for JDK-8212155. I want to use async-profiler in continous profiling on my production system, dumping cpu profiling every minute to a file. It means I will start and stop profiling 1440 times a day.

If I run profiler as an agent, and then use:
./profiler start <PID>
./profiler stop <PID>

will it prevent me from JDK-8212155?

Best regards.

**Comment by apangin** [comment]
Yes, the problem mentioned in #154 can occur only when attaching the profiler for the first time. If the profiler is started with `-agentpath`, this should not happen, no matter how many times you then start and stop profiling.

**Comment by krzysztofslusarski** [comment]
Thank you.
