### ISSUE TITLE
Allocation profiling gets SIGSEGV on ARMv7

### ISSUE THREAD

**Issue by jgneff** [jvm-profiling-tools/async-profiler#329]
I'm getting a SIGSEGV error on the Ubuntu and AdoptOpenJDK builds of JDK versions 11 and 14 when running with allocation profiling on both a real ARMv7 Cortex-A9 processor and a QEMU ARMv7 virtual machine.

The `cpu` and `lock` profiling work fine on both ARMv7 systems, and I don't see the problem with the `alloc` profiling on an Intel Xeon processor.

The errors for Ubuntu OpenJDK 14 on Ubuntu 20.04 are shown below.

### 1.0 GHz i.MX6SLL ARM Cortex-A9 with 512 MiB of RAM
See [hs_err_pid10889.log](https://github.com/jvm-profiling-tools/async-profiler/files/4789512/hs_err_pid10889.log) for the full log file.
```console
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x76b3b826, pid=10889, tid=10890
#
# JRE version: OpenJDK Runtime Environment (14.0.1+7) (build 14.0.1+7-Ubuntu-1ubuntu1)
# Java VM: OpenJDK Server VM (14.0.1+7-Ubuntu-1ubuntu1, mixed mode, sharing, serial gc, linux-arm)
# Problematic frame:
# V  [libjvm.so+0x52e826]
#
# Core dump will be written. Default location: core.10889 (may not exist)
#
# An error report file with more information is saved as:
# /home/ubuntu/src/epd-javafx/hs_err_pid10889.log
#
# If you would like to submit a bug report, please visit:
#   Unknown
#
```

### QEMU armv7l virtual machine with 1 CPU and 1 GiB of RAM
See [hs_err_pid2364.log](https://github.com/jvm-profiling-tools/async-profiler/files/4789513/hs_err_pid2364.log) for the full log file.
```console
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0xb6aeb894, pid=2364, tid=2365
#
# JRE version: OpenJDK Runtime Environment (14.0.1+7) (build 14.0.1+7-Ubuntu-1ubuntu1)
# Java VM: OpenJDK Server VM (14.0.1+7-Ubuntu-1ubuntu1, mixed mode, sharing, serial gc, linux-arm)
# Problematic frame:
# V  [libjvm.so+0x52e894]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /home/ubuntu/src/epd-javafx/core.2364)
#
# An error report file with more information is saved as:
# /home/ubuntu/src/epd-javafx/hs_err_pid2364.log
#
# If you would like to submit a bug report, please visit:
#   Unknown
#
```

I'm passing the *async-profiler* options `-agentpath:$HOME/opt/async-profiler-1.7.1/build/libasyncProfiler.so=event=alloc,start,file=alloc-jdk14.svg`.

**Comment by apangin** [comment]
Seems that AdoptOpenJDK is compiled with Thumb instruction set, while async-profiler expects ARM instruction set.

Can you try if it works with [Liberica JDK](https://bell-sw.com/pages/downloads/#/java-14-current)?

**Comment by jgneff** [comment]
> Can you try if it works with [Liberica JDK](https://bell-sw.com/pages/downloads/#/java-14-current)?

Wow, it works! Thanks for the suggestion. Ubuntu JDK 14 and AdoptOpenJDK 14 both fail with a SIGSEGV error when profiling the heap allocation, while the Liberica 32-bit Linux ARM Standard JDK 14 (bellsoft-jdk14.0.1+8-linux-arm32-vfp-hflt.tar.gz) works without problems.

**Comment by apangin** [comment]
I've fixed async-profiler to support JDKs compiled in THUMB mode.
