### ISSUE TITLE
Consider moving async-profiler repo under the jvm-profiling-tools

### ISSUE THREAD

**Issue by nitsanw** [jvm-profiling-tools/async-profiler#33]
This has been setup recently to host JVM profiling tools under an org rather than personal repos and thus encourage more community investment.
For your consideration.

**Comment by apangin** [comment]
I personally don't mind, but I guess I need proper permissions under jvm-profiling-tools.

> Users must have admin or owner permissions within the receiving organization before they can transfer a repository that they individually own.

> Only owners in the organization are allowed to create new issue assignments.

https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/

**Comment by nitsanw** [comment]
@apangin you've been added as member/administrator, so should work now

**Comment by apangin** [comment]
I've transfered the repository. But I need your help now to modify the permissions, so that I have access to repository settings etc.

**Comment by nitsanw** [comment]
Made you an admin of this repo, thanks for joining the org :-)
