### ISSUE TITLE
Release `tar` files are "tar bombs"

### ISSUE THREAD

**Issue by nitsanw** [jvm-profiling-tools/async-profiler#330]
Downloading and extracting release `tar` files requires a preparation step of creating a folder. This is a minor inconvenience/frustration for users who assume the common practice of `XXX.tar` extracting into `XXX` or some similar convention.

**Comment by apangin** [comment]
Yes, I realized this is not a proper way to pack things. Will fix it in the next release.

**Comment by apangin** [comment]
Fixed in release 1.8
