### ISSUE TITLE
Memory allocation measurement after a GC

### ISSUE THREAD

**Issue by eranff** [jvm-profiling-tools/async-profiler#332]
**Issue**
When starting an allocation profiler following a Systme.gc() results in measurements errors.

**Description**
When starting a memory allocation profiler immediately after calling System.gc(), resulting in the profiler reporting allocations that should not be reported. If you remove the call to System.gc() or instantiate one object between System.gc() and starting the allocation profiler, accurate results are reported. 

**Environment**
OS: MacOS 10.15.5
Java version: openjdk 11.0.5 2019-10-15
AsyncProfiler: 1.7.1
GC: G1, SerialGC

**How to reproduce**

Case 1: 

```
public static void main(String[] args) {
        var profiler = AsyncProfiler.getInstance();
        var array = new long[1024];
        for (var i=0; i<1024; ++i) {
            array = new long[1024];
            for (var j = 0; j < 1024; ++j) {
                array[j] = i * j;
            }
        }
        System.gc();
        profiler.start("alloc", 50);
        System.out.println("a");
        profiler.stop();
        System.out.println(profiler.dumpTraces(20));
     }
```
which results in

```
--- Execution profile ---
Total samples       : 1

Frame buffer usage  : 0.0004%

--- 187864 bytes (100.00%), 1 sample
  [ 0] java.lang.String
  [ 1] one.profiler.AsyncProfiler.start0
  [ 2] one.profiler.AsyncProfiler.start
  [ 3] com.fxagg.apps.DemoProblem.main

```
Case 2

```
public static void main(String[] args) {
        var profiler = AsyncProfiler.getInstance();
        var array = new long[1024];
        for (var i=0; i<1024; ++i) {
            array = new long[1024];
            for (var j = 0; j < 1024; ++j) {
                array[j] = i * j;
            }
        }
        System.gc();
        var number = (new Random()).nextInt();
        profiler.start("alloc", 50);
        System.out.println("a");
        profiler.stop();
        System.out.println(profiler.dumpTraces(20));
        System.out.println(number);
     }
```

Results in

```
--- Execution profile ---
Total samples       : 0

Frame buffer usage  : 0%
```

Case 3

```
public static void main(String[] args) {
        var profiler = AsyncProfiler.getInstance();
        var array = new long[1024];
        for (var i=0; i<1024; ++i) {
            array = new long[1024];
            for (var j = 0; j < 1024; ++j) {
                array[j] = i * j;
            }
        }
        profiler.start("alloc", 50);
        System.out.println("a");
        profiler.stop();
        System.out.println(profiler.dumpTraces(20));
     }
```
Results in

```
--- Execution profile ---
Total samples       : 0

Frame buffer usage  : 0%
```
**Notes**

Case #1 is very simplistic and we can see that the AsyncProfiler sample the instantiation of a class from the AsyncProfiler framework. In real life example, the sampled class is not limited to one from the framework

**Comment by apangin** [comment]
This is the expected behavior. This is just how TLAB-based allocation sampling works. How do you judge about "accuracy" of a sampling profiler with just one sample?

If you want async-profiler to record *all* allocations, use G1 GC with TLAB turned off:
```
java -XX:+UseG1GC -XX:-UseTLAB
```
but bear in mind that turning off TLAB has *huge* performance impact, and is not suitable for production use.
