### ISSUE TITLE
Wall-clock profiler and kernel functions

### ISSUE THREAD

**Issue by krzysztofslusarski** [jvm-profiling-tools/async-profiler#334]
Hi, is it possible for a wall-clock profiler to dump also kernel functions? I'm trying to get both output of both CPU and Wall at the same time using JFR output in wall mode, as you suggested in #311, but I don't see kernel functions in wall output.

**Comment by apangin** [comment]
No, wall-clock profiler does not show kernel stack traces, and I doubt it can ever do so.
