### ISSUE TITLE
CPU usage become very high when using the incorrect interval param.

### ISSUE THREAD

**Issue by during3a3** [jvm-profiling-tools/async-profiler#339]
When I use this command './profiler.sh -d 15 -i 10.1ms -o collapsed 2121155' to profile a java process, the cpu of the user process rise to more than 3000%. I guess, maybe the interval param should be long type but here we set to a decimal type caused this problem. So would it be better to check before execution?

**Comment by apangin** [comment]
`10.1ms` is not a valid value for the interval argument. Use `10100us` instead.

Profiler treated it as just `10` (nanoseconds), which obviously causes too big performance overhead. I fixed the parser to print error in such cases.
