### ISSUE TITLE
analyze native memory allocation

### ISSUE THREAD

**Issue by yaoliao** [jvm-profiling-tools/async-profiler#341]
First of all, thanks for this awesome software!

I am using async-profiler to analyze memory allocation. I have some question about the result.

I find method `Unsafe_AllocateMemory` in jvm only use `os::malloc` to allocate memory.  why I can see `mprotect` and `mmap` in stack.

this is my test code:
```java
public class MemoryTest {

    public static void main(String[] args) throws Exception {
        new Thread(() -> {
            while (true) {
                ByteBuffer buffer = ByteBuffer.allocateDirect(1024 * 1024 * 10);
                try {
                    TimeUnit.MILLISECONDS.sleep(100);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        }, "leak_thread").start();

        System.in.read();
    }
}
```

```
$./profiler.sh -d 10 -e malloc 30035
Started [malloc] profiling
--- Execution profile ---
Total samples       : 121

Frame buffer usage  : 0.0132%

--- 1006632960 events (99.99%), 96 samples
  [ 0] malloc
  [ 1] os::malloc(unsigned long, MemoryType)
  [ 2] Unsafe_AllocateMemory
  [ 3] sun.misc.Unsafe.allocateMemory
  [ 4] java.nio.DirectByteBuffer.<init>
  [ 5] java.nio.ByteBuffer.allocateDirect
  [ 6] NativeLeakTest.lambda$main$0
  [ 7] NativeLeakTest$$Lambda$1.834600351.run
  [ 8] java.lang.Thread.run

   .....
```
```
./profiler.sh -d 10 -e mprotect 30035
Started [mprotect] profiling
--- Execution profile ---
Total samples       : 57

Frame buffer usage  : 0.0026%

--- 53 events (92.98%), 53 samples
  [ 0] __GI___mprotect
  [ 1] sun.misc.Unsafe.allocateMemory
  [ 2] java.nio.DirectByteBuffer.<init>
  [ 3] java.nio.ByteBuffer.allocateDirect
  [ 4] NativeLeakTest.lambda$main$0
  [ 5] NativeLeakTest$$Lambda$1.834600351.run
  [ 6] java.lang.Thread.run
```

```
./profiler.sh -d 10 -e mmap 30035
Started [mmap] profiling
--- Execution profile ---
Total samples       : 12

Frame buffer usage  : 0.0008%

--- 1006632960 events (100.00%), 10 samples
  [ 0] mmap64
  [ 1] sun.misc.Unsafe.allocateMemory
  [ 2] java.nio.DirectByteBuffer.<init>
  [ 3] java.nio.ByteBuffer.allocateDirect
  [ 4] NativeLeakTest.lambda$main$0
  [ 5] NativeLeakTest$$Lambda$1.834600351.run
  [ 6] java.lang.Thread.run
```
`Unsafe_AllocateMemory` in jvm
```
UNSAFE_ENTRY(jlong, Unsafe_AllocateMemory(JNIEnv *env, jobject unsafe, jlong size))
  UnsafeWrapper("Unsafe_AllocateMemory");
  size_t sz = (size_t)size;
  if (sz != (julong)size || size < 0) {
    THROW_0(vmSymbols::java_lang_IllegalArgumentException());
  }
  if (sz == 0) {
    return 0;
  }
  sz = round_to(sz, HeapWordSize);
  void* x = os::malloc(sz, mtInternal);
  if (x == NULL) {
    THROW_0(vmSymbols::java_lang_OutOfMemoryError());
  }
  //Copy::fill_to_words((HeapWord*)x, sz / HeapWordSize);
  return addr_to_java(x);
UNSAFE_END
```

**Comment by franz1981** [comment]
Please there is another issue re this where @apangin has already answered why and how :)

**Comment by franz1981** [comment]
https://github.com/jvm-profiling-tools/async-profiler/issues/336

**Comment by krzysztofslusarski** [comment]
One hint from me, if you want to find places in your system that really easts your RAM you can profile ```page-faults```.

**Comment by apangin** [comment]
As I explained in [this video](https://vimeo.com/364039638), `malloc` implementation calls `mmap` and `mprotect` under the hood to extend native memory pool.

libc (which malloc is a part of) is usually compiled without frame pointers ([`-fomit-frame-pointer`](https://stackoverflow.com/questions/14666665/trying-to-understand-gcc-option-fomit-frame-pointer) optimization), that's why async-profiler can't show that `mprotect`/`mmap` is actually called by `malloc`.

**Comment by yaoliao** [comment]
> As I explained in [this video](https://vimeo.com/364039638), `malloc` implementation calls `mmap` and `mprotect` under the hood to extend native memory pool.
> 
> libc (which malloc is a part of) is usually compiled without frame pointers ([`-fomit-frame-pointer`](https://stackoverflow.com/questions/14666665/trying-to-understand-gcc-option-fomit-frame-pointer) optimization), that's why async-profiler can't show that `mprotect`/`mmap` is actually called by `malloc`.

Thank you very much for your reply. The video is very good.

**Comment by mkaranth-tech** [comment]
> One hint from me, if you want to find places in your system that really consumes your RAM you can profile `page-faults`.

@apangin @krzysztofslusarski could you please tell me what to look for in page-faults flame graph to say what is actually consuming RAM?

**Comment by krzysztofslusarski** [comment]
Flame graph just presents you what were the execution stacks that consumed some resource. The resource can be CPU, Heap, time, native memory ....  The semantics of the flame graph is the same for all the resources. In case of page faults it simply shows you the stacks where page fault occurred. The top frame is responsible for the page fault, everything beneath is simply a stack trace. 

Page fault is not a 1-1 relation to RSS expansion, but from my experience this usually brings needed information. You also need to watch out for heap expansions, to avoid that you can use `Xmx == Xms` and `+XX:AlwaysPreTouch`.
