### ISSUE TITLE
Feature: export data proto buf format

### ISSUE THREAD

**Issue by blasrodri** [jvm-profiling-tools/async-profiler#343]
Hi! First, thanks for this amazing tool. I love it.

I'm trying to collect data from multiple instances, on a rolling basis. And then I need to post-process the data so that I can retrieve meaningful information out of it.

Looking at the way Google's `pprof`[https://github.com/google/pprof] work, I was wondering if would be possible to add the protobuf capability (or something alike). Why so? Because it would make serialization and deserialization straightforward and avoid having to parse text output.

**Comment by krzysztofslusarski** [comment]
With collapsed stack format you don't need to parse output, you can just join multiple text files.

**Comment by apangin** [comment]
Please take a look at the following comments:

- https://github.com/jvm-profiling-tools/async-profiler/issues/297#issuecomment-582201329
- https://github.com/jvm-profiling-tools/async-profiler/issues/248#issuecomment-633311384

Hopefully they explain my position about new formats.

In short, async-profiler already supports two formats that should cover all use cases:
- `collapsed` - the simplest text format that requires almost no parsing;
- `jfr` - full-fledged binary format; Java standard; supported internally by JDK as well as by many external tools and libraries.

**Comment by blasrodri** [comment]
Thanks guys!
