### ISSUE TITLE
Documentation wrongly states that debug symbols are embedded in Oracle JDK

### ISSUE THREAD

**Issue by zabetak** [jvm-profiling-tools/async-profiler#351]
The current documentation states the following:

_"The allocation profiler requires HotSpot debug symbols. Oracle JDK already has them embedded in libjvm.so Oracle JDK already has them embedded in libjvm.so"_

The latter does not seem to be true, at least in certain versions of JDK. 

I just downloaded `jdk-8u261-linux-x64.tar.gz` and run the following: `gdb ./jre/lib/amd64/server/libjvm.so`

The result shows the following. 
```
GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./jre/lib/amd64/server/libjvm.so...(no debugging symbols found)...done.
```
If I am not misinterpret the output of gdb the debug symbols do not seem to be embedded in this version of JDK.

**Comment by apangin** [comment]
I believe symbols are there. The documentation wasn't quite accurate about the command to check symbols. I updated README.

Try
```
gdb ./jre/lib/amd64/server/libjvm.so -ex 'info address UseG1GC'
```
It should print `Symbol "UseG1GC" is at 0xxxxx`

**Comment by zabetak** [comment]
Thanks, I tried the above and indeed it prints a valid address so I am closing this issue.
