### ISSUE TITLE
Limit chunk size in jfr output

### ISSUE THREAD

**Issue by gorrus** [jvm-profiling-tools/async-profiler#360]
By default maxchunksize in jfr is 12Mb, this allows to load more chunks in parallel and minimize loaders memory requrements. As chunks are mostly self contained.
That would be great to limit chunk size in async jfr output as well.

**Comment by gorrus** [comment]
At least chunk size should never be more than 2Gb, current parsers will not be able to handle this

**Comment by apangin** [comment]
Implemented support for multi-chunk recordings in [`chunked-jfr`](https://github.com/jvm-profiling-tools/async-profiler/tree/chunked-jfr) branch.

1. Added `chunksize=N`, `chunktime=M` options to automatically switch to a new JFR chunk afer N bytes or M seconds. E.g. `chunksize=1g,chunktime=10m` will force a new chunk after writing 1 GiB of events or after 10 minutes of profiling, whichever happens first. The defaults are 0 (i.e. write single chunk as before).
2. Added `dump,jfr` command to switch to a new chunk manually.
3. Bonus: `dump` command accepts other formats as well. E.g. `dump,flamegraph` will produce a flame graph from currently collected data without stopping profiling. It's now possible to get a profile on the fly.
4. `JfrReader` now supports multi-chunk JFRs, both from async-profiler and from the original Flight Recorder. jfr2flame and jfr2nflx converters handle multi-chunk JFRs accordingly.

**Comment by gorrus** [comment]
probably chunksize default should be 2Gb to avoid issues with the current jfr parsers

**Comment by apangin** [comment]
- Changed the default values to: chunksize=100 MB, chunktime=1 hour.
- Updated JfrReader to support chunks larger than 2GB.
- Merged the changes into master.
