### ISSUE TITLE
Allocation profiler - object type filter

### ISSUE THREAD

**Issue by krzysztofslusarski** [jvm-profiling-tools/async-profiler#361]
Use case:
- you found, that in your JVM there is some heap memory leak
- from heap dump you know, which objects are causing leak
- you want to know, where in your appliaction those objects are allocated

Now we have posibility to dump event=alloc to collapse stack and then post-process it with grep to find it, but it can generate houndreds of MB just to find 1 or 2 lines. It would be nice to have an option to add filter on object type, so profiler output could dump only alloaction of object, that we need.

**Comment by apangin** [comment]
Doesn't `include`/`exclude` option solve the problem?

E.g. `start,event=alloc,collapsed,include=java.util.Formatter` will output only allocations of `java.util.Formatter` class. Contrariwise, `exclude=byte[],exclude=int[]` will output all allocations except `byte[]` and `int[]` arrays. Wildcard patterns also work, like `include=java.util.*`

The corresponding options in `profiler.sh` script are `-I`/`-X`:
```
profiler.sh -d 10 -e alloc -f out.collapsed -I java.util.Formatter <pid>
```

**Comment by krzysztofslusarski** [comment]
Works like a charm :) Thank you.

I shouldn't post issues so late. I figured out that I also did this one time with method profiling, profiling <init> of thata objects.

I also need to read while README one more time.

Best regards.
