### ISSUE TITLE
Async event malloc didnt record samples when executed inside container

### ISSUE THREAD

**Issue by sattishv** [jvm-profiling-tools/async-profiler#364]
Hi Team,

We tried to record allocation samples using the event -e malloc,mmap tp debug a native memory leak but async-profiler didnt record any samples inside the container to verify we used event alloc we were able to see samples been recorded. Do we need any library path to be set for events like malloc,mmap . Please confirm also is it possible to see the exeception thrown when no samples were recorded. Thanks

**Comment by apangin** [comment]
When you execute
```
profile.sh start -e malloc <pid>
```
what is printed in the console and in the output of the target Java process?

**Comment by sattishv** [comment]
Thanks for the response. Got this message Perf events unavailable. See stderr of the target process. We had issues in installing perf we cant generate graphs for malloc without perf events

**Comment by krzysztofslusarski** [comment]
I believe you don''t need to install perf, but your container needs higher privileges. It is explained here:
https://youtu.be/vD9o219Z13k?t=2157
@apangin correct it if i'm wrong

**Comment by apangin** [comment]
async-profiler does not depends on `perf`, so no need to install it.

However, it relies on `perf_event_open` Linux syscall, which is by default disabled in containers. In addition to setting `sysctl kernel.perf_event_paranoid=1` you'd need to adjust [seccomp profile](https://docs.docker.com/engine/security/seccomp/) to enable `perf_event_open` syscall.

**Comment by apangin** [comment]
@krzysztofslusarski Exactly. Thanks for the link.

**Comment by sattishv** [comment]
Thanks for the inputs. Since we cant access docker run because all our instances are managed by Mesos. Is it possible to disable seccomp from docker exec Or can we install perf inside the containers to get access on perf_event_open. Please confirm. Note: We installed async-profiler inside the container we arent running async-profiler as a container

**Comment by apangin** [comment]
As I told earlier, async-profiler does not depend on `perf` in any way. Therefore, installing `perf` will not affect async-profiler capabilities. But if you can make `perf` work inside the container, async-profiler will work, too, since they both rely on the same kernel API.

Container privileges and security restrictions cannot be altered from inside the container (otherwise there will be no sence in them, obviously). Please contact your system administrators to enable `perf_event_open` API in the container.

**Comment by sattishv** [comment]
Thanks pangin for the instant response. Appreciate your support in clarifying.

**Comment by apangin** [comment]
OK, I'm closing the issue then. Feel free to open a new one if you need support from async-profiler side.
