### ISSUE TITLE
Question - is allocation size stored in JFR format?

### ISSUE THREAD

**Issue by krzysztofslusarski** [jvm-profiling-tools/async-profiler#366]
Hi, is allocation size stored in JFR format? I looked at source code and some generated JFRs and cannot find it :(

event=alloc, v1.8.1

**Comment by apangin** [comment]
Not in 1.8.x.

But async-profiler 2.0 (pre-release published today) writes `jdk.ObjectAllocationInNewTLAB` and `jdk.ObjectAllocationOutsideTLAB` events containing `allocationSize` and `tlabSize` fields.

**Comment by krzysztofslusarski** [comment]
Great, thank you.
