### ISSUE TITLE
Speedscope output format

### ISSUE THREAD

**Issue by huguesb** [jvm-profiling-tools/async-profiler#368]
Large flame graphs generated by profiling Spark applications (~10Mb) tend to lock up SVG viewers, even on powerful machines. [Speedscope](https://github.com/jlfwong/speedscope) can deal with large profiles. It would be nice if async-profiler could be extended to output profiles in speedscope format.

**Comment by krzysztofslusarski** [comment]
You can load "collapsed stack" format to speedscope, isn't it good enough?

**Comment by apangin** [comment]
Try [async-profiler 2.0](https://github.com/jvm-profiling-tools/async-profiler/releases/tag/v2.0-b1). It has completely rewritten Flame Graph renderer (which retains the familiar UX though). Now Flame Graphs are generated in HTML; they are smaller in size and much faster in rendering, comparing to equivalent SVG.

As to the new output format, my position is explained [here](https://github.com/jvm-profiling-tools/async-profiler/issues/343#issuecomment-681834004):

> Please take a look at the following comments:
> 
> * [#297 (comment)](https://github.com/jvm-profiling-tools/async-profiler/issues/297#issuecomment-582201329)
> * [#248 (comment)](https://github.com/jvm-profiling-tools/async-profiler/issues/248#issuecomment-633311384)
> 
> Hopefully they explain my position about new formats.
> 
> In short, async-profiler already supports two formats that should cover all use cases:
> 
> * `collapsed` - the simplest text format that requires almost no parsing;
> * `jfr` - full-fledged binary format; Java standard; supported internally by JDK as well as by many external tools and libraries.

**Comment by pnf** [comment]
> You can load "collapsed stack" format to speedscope, isn't it good enough?

You can, but large profiles cause memory problems.
