### ISSUE TITLE
Please don't rewrite git history

### ISSUE THREAD

**Issue by willymilkytron** [jvm-profiling-tools/async-profiler#369]
We noticed the commit releasing v1.8.2 was pushed twice: https://github.com/jvm-profiling-tools/async-profiler/commit/683144a90774a7c07760d2e46381f81ae4aff79d https://github.com/jvm-profiling-tools/async-profiler/commit/13394b7125100a301bbadc9eb7bdd4f87b1f3cd6.

Please consider releasing a newer tag (e.g v1.8.3) if additions need to be made. Rewriting git history is bad, especially when done in the master branch of public repositories.

Thank you.

**Comment by apangin** [comment]
One of the commits was made by mistake, it existed for a short time. Sorry for the inconvenience.
