### ISSUE TITLE
Unable to get flamegraph output

### ISSUE THREAD

**Issue by eranshpiner** [jvm-profiling-tools/async-profiler#370]
Hello,

Trying to use the "async-profiler" for the first time, using the recent v2.0-b1 version. It seems that I'm unable to get the output in the SVG (flamegraph) format. Here is the command I'm running:

`./profiler.sh -d 60 -f /var/log/flamegraph.svg 1`  

Even trying the explicit "-o svg" flag, I keep getting the output in the textual format, such as the below:

--- Execution profile ---
Total samples       : 55499
unknown_Java        : 17 (0.03%)
not_walkable_Java   : 3 (0.01%)
deoptimization      : 55 (0.10%)

     counter  percent  samples  top
  ----------  -------  -------  ---
 64617610099   10.07%     5328  InstanceKlass::oop_follow_contents(oopDesc*)
 44145927041    6.88%     4000  InstanceKlass::oop_adjust_pointers(oopDesc*)
 43616412628    6.79%     4232  OtherRegionsTable::add_reference(void*, int)
 22353505298    3.48%     2161  UpdateRSOopClosure::do_oop(oopDesc**)
 17242357822    2.69%     1351  MarkSweep::follow_stack()

Can you please advise? 
Am I missing anything here?

Regards,
Eran.

**Comment by krzysztofslusarski** [comment]
In 2.0 flame graphs are generated in HTML format so use 
```
./profiler.sh -d 60 -f /var/log/flamegraph.html 1
```

**Comment by eranshpiner** [comment]
This indeed works. Thank you!

**Comment by martin-g** [comment]
I've built Async Profiler v2.0 branch locally with `make clean all` and I run it with: `./profiler.sh -e wall -d 25 -f ~/wall-arm64-tomcat.html tomcat-embedded-1.0-SNAPSHOT.jar` but it produces `Tree view`, not an HTML with FlameGraph.

Using `-f file.svg` does produce an SVG and behaves as in 1.x series.

What is the final decision here ?

**Comment by apangin** [comment]
@martin-g It seems like async-profiler 1.x has been already loaded into the JVM before. The new version will not take effect until the JVM restarts. Check `profiler.sh -v <pid>`

**Comment by martin-g** [comment]
Thank you, @apangin ! Indeed this was the problem!
