### ISSUE TITLE
Does not build on FreeBSD

### ISSUE THREAD

**Issue by ltning** [jvm-profiling-tools/async-profiler#371]
Compiling fails with a bunch of
```
src/stackFrame_x64.cpp:32:24: error: no member named 'gregs' in '__mcontext'                                                                     
    return (uintptr_t&)REG(REG_RIP, __rip);                                                                                                      
                       ^~~~~~~~~~~~~~~~~~~                                                                                                       
```

Note that this is after symlinking /usr/local/libexec/openjdk8/include/freebsd/* into /usr/local/libexec/openjdk8/include .

Semi-relevant things I found on The Internet:
https://github.com/dotnet/runtime/issues/4106
https://github.com/RPCS3/rpcs3/commit/392d91b6043f9858462f385ef5e23d14d50e2283

**Comment by apangin** [comment]
FreeBSD is not in the list of project [supported platforms](https://github.com/jvm-profiling-tools/async-profiler#supported-platforms).

If you know how to fix this in a simple way without affecting other platforms, pull requests are welcome.
