### ISSUE TITLE
Profile of FileChannel.map not showing mmap being used

### ISSUE THREAD

**Issue by balamaci** [jvm-profiling-tools/async-profiler#375]
Hi all,
Tried to profile a simple FileChannel.map on Ubuntu 20.04

https://github.com/balamaci/async-profiler-playground/blob/b4950683870b8b296d6db70e5f4f1c62eb2b77ec/src/main/java/com/balamaci/file/MappedFileTest.java#L24

But I do not see any calls being made to mmap in the flamegraph.
https://raw.githubusercontent.com/balamaci/async-profiler-playground/master/file_mmap.svg 

Then I tried with
./profiler.sh -e mmap -d 10 -i 10us -s pid
Started [mmap] profiling
--- Execution profile ---
Total samples       : 0

Frame buffer usage  : 0%

      events  percent  samples  top
  ----------  -------  -------  ---

Tried with
./profiler.sh -e syscalls:sys_enter_mmap -d 10 -i 10us -s pid
and surprised to see
Unsupported event type

If I do call
'''
sudo bpftrace -e 'tracepoint:syscalls:sys_enter_mmap /pid == 18692/ {printf("Process Name: %s\nSyscall Requested:%s %d\n", comm, probe, args->len);}'
'''
I do see lots of:
Process Name: java
Syscall Requested:tracepoint:syscalls:sys_enter_mmap 5242880
Process Name: java
Syscall Requested:tracepoint:syscalls:sys_enter_mmap 5242880
Process Name: java
Syscall Requested:tracepoint:syscalls:sys_enter_mmap 5242880
Process Name: java
Syscall Requested:tracepoint:syscalls:sys_enter_mmap 5242880
Process Name: java

I assume the call to mmap is being made because I can see with debug I hit 
https://github.com/openjdk/jdk/blob/f3eb44a94d7aa01de2f2936ce1a31e7e4d340c33/src/java.base/share/classes/sun/nio/ch/FileChannelImpl.java#L1089
and I assume this gets into https://github.com/openjdk/jdk/blob/270674ce1b1b8d44bbe92949c3f7db7b7c767cac/src/java.base/unix/native/libnio/ch/FileChannelImpl.c#L126

PS:
./profiler.sh -e mmap64 -d 10 -i 10us -s pid
still produces empty result.

**Comment by apangin** [comment]
1. `-i` parameter is misused. Time suffix makes sense only for cpu or wall-clock profiling. Here `-i` specifies the number of events, i.e. you profile only each 10000th `mmap` call. Try to remove this argument entirely.

    `./profiler.sh -e mmap -d 10 jps` should work fine.

2. In order to resolve `syscalls:sys_enter_mmap` tracepoint ID, async-profiler read `debugfs`. However, by default, accessing `debugfs` requires root privileges. Use can use one of the following options:

    1. Run Java process by root. Note that async-profiler works in the context of the target JVM, so you need to run Java by root, not `profiler.sh`.
    2. Make `debugfs` accessible by non-privileged user:
        ```
        sudo chmod 777 /sys/kernel/debug
        sudo chmod 777 /sys/kernel/debug/tracing
        ```
    3. Replace `syscalls:sys_enter_mmap` with `trace:<id>` where `<id>` is a number from `/sys/kernel/debug/tracing/events/syscalls/sys_enter_mmap/id`.

So, a simple and a safe way to profile kernel tracepoints by a non-privileged user, is to run
```
./profiler.sh -e trace:`sudo cat /sys/kernel/debug/tracing/events/syscalls/sys_enter_mmap/id` -d 10 jps
```

**Comment by balamaci** [comment]
Thanks Andrei, I can see the call being made after just removing the -i, but I'm curios if there might be a way to show 'mmap' when cpu profiling, not just focusing on mmap. I mean I'm curios if we can get an idea of how much time is spent on the mmap call compared to other code sections. 
./profiler.sh -d 20 -s 6150 -f memory.svg
produces
https://raw.githubusercontent.com/balamaci/async-profiler-playground/master/file_mmap2.svg

**Comment by balamaci** [comment]
Actually there is a mmap call exactly where expected but it is just very small that I missed it. I could find it and drill down to it.
Thank you!
