### ISSUE TITLE
-e on specific java class isn't working

### ISSUE THREAD

**Issue by rbalamohan** [jvm-profiling-tools/async-profiler#376]
E.g Specifying "-e java.util.Properties.getProperty" is not picked by profiler correctly.

**Comment by apangin** [comment]
I don't see any problems in profiling `java.util.Properties.getProperty`.
Why do you think it's not working? Please provide an example.
Also, please tell the version of async-profiler and the JVM.

**Comment by rbalamohan** [comment]
Thanks @apangin . Looks like I was using old version of profiler on JDK 1.8.0_262. I tried with "async-profiler-1.8.2-linux-x64.tar.gz" and it works fine now. I will close this ticket.
