### ISSUE TITLE
Can async profiler tool could profile the process with pid 1?

### ISSUE THREAD

**Issue by Myasuka** [jvm-profiling-tools/async-profiler#380]
I like this async-profiler very much and use it in our many production cases. However, I found it seems cannot profile the process with pid 1 in docker environment. We only get an empty picture of thread stacks.

Is that expected due to some limitation?

**Comment by apangin** [comment]
async-profiler can profile applications in a container, `pid` value does not matter.

However, there are a few things to keep in mind when profiling in a container, see https://github.com/jvm-profiling-tools/async-profiler/blob/master/README.md#profiling-java-in-a-container

**Comment by apangin** [comment]
Since there is no further feedback, I assume the question is answered.
