### ISSUE TITLE
Collecting jni traces for tensorflow

### ISSUE THREAD

**Issue by timurbey** [jvm-profiling-tools/async-profiler#387]
I'm currently working on profiling a simple tensorflow program (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/java/src/main/java/org/tensorflow/examples/LabelImage.java) and I am running into an issue where the traces contain pointers to native code that is obscured. Below are two such examples:

```
__memcpy_avx_unaligned_erms
/tmp/tensorflow_native_libraries-1611685895630-0/libtensorflow_jni.so
/tmp/tensorflow_native_libraries-1611685895630-0/libtensorflow_jni.so
/tmp/tensorflow_native_libraries-1611685895630-0/libtensorflow_jni.so
/tmp/tensorflow_native_libraries-1611685895630-0/libtensorflow_jni.so
/tmp/tensorflow_native_libraries-1611685895630-0/libtensorflow_jni.so
/tmp/tensorflow_native_libraries-1611685895630-0/libtensorflow_jni.so
/tmp/tensorflow_native_libraries-1611685895630-0/libtensorflow_jni.so
/tmp/tensorflow_native_libraries-1611685895630-0/libtensorflow_jni.so
/tmp/tensorflow_native_libraries-1611685895630-0/libtensorflow_jni.so
/tmp/tensorflow_native_libraries-1611685895630-0/libtensorflow_jni.so
/tmp/tensorflow_native_libraries-1611685895630-0/libtensorflow_jni.so
/tmp/tensorflow_native_libraries-1611685895630-0/libtensorflow_jni.so
/tmp/tensorflow_native_libraries-1611685895630-0/libtensorflow_jni.so
/tmp/tensorflow_native_libraries-1611685895630-0/libtensorflow_jni.so
/tmp/tensorflow_native_libraries-1611685895630-0/libtensorflow_jni.so
/tmp/tensorflow_native_libraries-1611685895630-0/libtensorflow_jni.so
/tmp/tensorflow_native_libraries-1611685895630-0/libtensorflow_jni.so
/tmp/tensorflow_native_libraries-1611685895630-0/libtensorflow_jni.so
Java_org_tensorflow_Session_run
org.tensorflow.Session.run
org.tensorflow.Session.access$100
org.tensorflow.Session$Runner.runHelper
org.tensorflow.Session$Runner.run
eflect.experiments.LabelImage.executeInceptionGraph
eflect.experiments.LabelImage.main
```

```
/tmp/tensorflow_native_libraries-1611685895630-0/libtensorflow_jni.so
/tmp/tensorflow_native_libraries-1611685895630-0/libtensorflow_jni.so
Eigen::ThreadPoolTempl<tensorflow::thread::EigenEnvironment>::WorkerLoop(int)
std::_Function_handler<void ()
```

Is there a way to retrieve the actual signature? I am running this program on the following:

```
Intel E5-2630 v4 2.20 GHz
64 DDR4 RAM
Debian 4.9 OS
JVM Hotspot 11.0.2+9-LTS
```

Let me know if there is any other information I can provide!

**Comment by martin-g** [comment]
What is the version of the Linux kernel?
Debian 4.9 seems quite old.

**Comment by timurbey** [comment]
I realized made a splicing mistake there when I copied this. It's supposed to be Debian 9 (Linux kernel 4.9.0-14-amd64). Sorry!

**Comment by apangin** [comment]
It seems like private symbols were stripped off the JNI library. Have you compiled `libtensorflow_jni.so` yourself or got precompiled binaries?

**Comment by timurbey** [comment]
libtensorflow is a pre-compiled binary.

**Comment by apangin** [comment]
OK, I've found it:

https://github.com/tensorflow/tensorflow/blob/07592d94b658cb4d5e54cbf827a326904431d64e/tensorflow/java/BUILD#L437-L440

The JNI library is indeed compiled without internal symbols, so all function names are lost.
Build the library yourself without `-s` linked option:

https://github.com/tensorflow/tensorflow/blob/07592d94b658cb4d5e54cbf827a326904431d64e/tensorflow/java/BUILD#L449

or ask tensorflow maintainers how the version with debug symbols.

**Comment by timurbey** [comment]
Thanks so much! I'll dig into this.
