### ISSUE TITLE
Run async-profiler in GitHub workflow

### ISSUE THREAD

**Issue by pan3793** [jvm-profiling-tools/async-profiler#388]
I'm trying to integrate async-profiler with my project in GitHub workflow, but encountered some issues.

The error message indicated I need to setup some kernel status.
```
# Preparing profilers: AsyncProfiler 
Iteration   1: WARNING: Kernel symbols are unavailable due to restrictions. Try
  echo 0 > /proc/sys/kernel/kptr_restrict
  echo 1 > /proc/sys/kernel/perf_event_paranoid
perf_event_open failed: Permission denied
```

And after updating workflow to add the command, I got an error below.
```
> Run echo 0 > /proc/sys/kernel/kptr_restrict
  echo 0 > /proc/sys/kernel/kptr_restrict
  echo 1 > /proc/sys/kernel/perf_event_paranoid
  shell: /usr/bin/bash -e {0}
  env:
    JAVA_HOME_8.0.282_x64: /opt/hostedtoolcache/jdk/8.0.282/x64
    JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.282/x64
    JAVA_HOME_8_0_282_X64: /opt/hostedtoolcache/jdk/8.0.282/x64
/home/runner/work/_temp/964931ea-1133-4ac8-818a-e9813a9695e7.sh: line 1: /proc/sys/kernel/kptr_restrict: Permission denied
Error: Process completed with exit code 1.
```

What can I do next? And is there possible to run async-profiler in GitHub workflow?

The project link is: [ClickHouse-Native-JDBC](https://github.com/housepower/ClickHouse-Native-JDBC)

Please give me some suggestion, and PR also are welcome.

**Comment by apangin** [comment]
It is typical to disable access to hardware performance counters in virtual machines / containers in public clouds or other sandboxed environments. I guess, GitHub Actions infrastructure disables that, too (I'm not sure if it is possible to enable it - better ask GitHub).

The workaround is to run async-profiler in `itimer` mode. It is quite similar to `cpu` mode, except that it does not show kernel stack traces. For details, see [Profiling Java in a container](https://github.com/jvm-profiling-tools/async-profiler/#profiling-java-in-a-container) and [Troubleshooting](https://github.com/jvm-profiling-tools/async-profiler/#troubleshooting).

**Comment by pan3793** [comment]
`itimer` mode works for me! Thanks!
