### ISSUE TITLE
MacOS/AArch64 support

### ISSUE THREAD

**Issue by henryjcee** [jvm-profiling-tools/async-profiler#390]
Given that Apple is planning to migrate all of their desktop offerings to AArch64 over the next 2 years, it seems like effort spent on porting wouldn't be wasted. I'm hoping that the existing Linux AArch64 support can be shared but I haven't taken a good look at the docs yet.

Opening this with lofty ambitions to take a look at this over the next few weeks but I'm under no illusions that this change is probably well beyond my current skill level. More realistically I guess it'd be good to just get this on the radar.

**Comment by apangin** [comment]
Thank you for your interest in async-profiler.
No doubts that macOS/ARM64 port will be a valuable addition to the project. I don't expect much difficulties in creating the initial port; however, supporting new platform in future is a continuous job that includes regular building, testing, publishing, etc.

In the mean time, I don't even have the suitable hardware to do this.
I'll make the port if someone gets me a new M1 MacBook Pro :wink:

Seriously, I think this would be a fair deal: permanently adding macOS/ARM64 to the list of async-profiler supported platforms for one-time material support of the open source project.

**Comment by henryjcee** [comment]
Sorry for the radio silence on this, you raise a valid point. I'm a bit snowed at the moment with other work but have done a bit of digging and at least for now it looks like [GHA support for M1 runners is a while away](https://github.com/actions/virtual-environments/issues/2187) so there goes that bright idea. Still won't have time to dedicate to this for now but that _might_ change in the next few weeks.

**Comment by avocade** [comment]
This is critical for us as well, using it with the clojure wrapper [clj-async-profiler](https://github.com/clojure-goes-fast/clj-async-profiler) 🙏🏻

**Comment by apangin** [comment]
macOS/ARM64 port has been pushed to the `master`. It will be included in the nearest release.

**Comment by apangin** [comment]
Here is a pre-release package of async-profiler for macOS/arm64.
Please try and provide the feedback.

[async-profiler-2.1-ea-macos-aarch64.zip](https://github.com/jvm-profiling-tools/async-profiler/files/6643894/async-profiler-2.1-ea-macos-aarch64.zip)
