### ISSUE TITLE
Failed to inject profiler into PID

### ISSUE THREAD

**Issue by Xichen96** [jvm-profiling-tools/async-profiler#391]
I tried to use the compiled library directly and it was working fine. However when I tried to compile it myself, I was able to compile successfully, but when I tried to run it, I got "Failed to inject profiler into PID". Could it be compiler related? the dumped ldd result seemed to be identical. I use gcc 6.3.

**Comment by apangin** [comment]
There are already several answers regarding this message - just search for "Failed to inject profiler" here on GitHub.

Try `java -agentpath:/path/to/libasyncProfiler.so -version`
This will show the detailed message if there is something wrong with the way how the library is compiled.
