### ISSUE TITLE
Options to allow non-truncated signatures

### ISSUE THREAD

**Issue by PaulBGD** [jvm-profiling-tools/async-profiler#392]
Given it's hard coded to a 255 limit, would it be possible to make it configurable whether we want the signature truncated?

**Comment by apangin** [comment]
Signatures are not truncated in JFR output.
As to text formats - such long signatures aren't readable anyway, are they? They won't even fit onto the screen. Or what is the use case?

**Comment by PaulBGD** [comment]
I use the library programmatically, then parse the signatures to apply mappings to the stack. Without the full signature I can't find the correct mapping for the method

**Comment by apangin** [comment]
What output format do you use for parsing?
I believe, JFR is the best for automatic processing, and it does not truncate symbols.

**Comment by PaulBGD** [comment]
Hmm it's tempting to use JFR, although I would have to force an update to JDK 9 to use the library. I think I'll look into that route, because it beats my flaky text parsing.

**Comment by apangin** [comment]
> I would have to force an update to JDK 9 to use the library

What do you mean? async-profiler writes JFR compatible profiles even with JDK 7.
It also includes [JFR parser](https://github.com/jvm-profiling-tools/async-profiler/blob/master/src/converter/one/jfr/JfrReader.java) that works with JDK 7+.
And here is an [example](https://github.com/jvm-profiling-tools/async-profiler/blob/master/src/converter/jfr2flame.java) how to use this parser to convert JFR to FlameGraph.

**Comment by PaulBGD** [comment]
Oh wow, I didn't even see the parser in the repository! Thank you much, and I apologize for all the stupid issues I've opened on the repo.

**Comment by PaulBGD** [comment]
This might deserve its own issue now, but it seems like the parser doesn't support JFR version 0.9, which is what the flight recorder puts out. Removing the version check, and it fails to parse. I'm assuming it's outdated?

**Comment by apangin** [comment]
> It's not the first time I see this issue, however, up to the moment it wasn't a real problem. My point is, text-based output formats (including collapsed format) are designed mainly for visualization for end user (who doesn't parse 1KB strings by eye anyway). For computer processing, there is a jfr format.
On the other hand, the suggested PR does not fix the root cause, just makes the issue appear less often.
