### ISSUE TITLE
Allocations sampling rate

### ISSUE THREAD

**Issue by ksafonov** [jvm-profiling-tools/async-profiler#396]
Latest version allows to control sampling frequency in "allocations" mode by "--alloc" parameter.
1) what is the [default] value of the sampling rate if parameter is not specified? Does the "-i" parameter come into play?
2) what is the recommended value? I would use the smallest possible value to get maximum precision (if performance degradation is small or negligible), but the docs says it depends on TLAB size. Could profiler be so kind and calculate this size for me?
3) please makes the docs consistent: https://github.com/jvm-profiling-tools/async-profiler says about "--alloc" for bytes and "-i" for seconds while "https://github.com/jvm-profiling-tools/async-profiler/wiki/Allocation-profiling" seems to say about "-i" for bytes.

**Comment by apangin** [comment]
I have synchronized wiki with README.

Previously `-i` option was used to set profiling internval for all modes.
One of the new features of async-profiler 2.0 is profiling multiple events together: cpu+alloc+lock. Obviously, one option does not work anymore. So, `-i` now specifies CPU sampling interval; `--alloc` - allocation sampling interval, and `--lock` - lock duration threshold.

By default, when `--alloc` option is omitted, async-profiler samples all allocations that happpen outside TLAB or in newly created TLAB. So, the actual sampling rate depends on the particular JVM configuration and/or application. E.g. if an average TLAB size is 1MB, the allocation sampling rate will be also 1MB.

This basically provides the best available sampling rate, unless TLAB is manually tuned with JVM options. If you are fine with that (i.e. the observed overhead is satisfactory), there is no need to alter `--alloc` option. If you feel the overhead is too big in your particular case (e.g. if an application has a really high allocation rate), then you can increase `--alloc` value to reduce the sampling rate.
