### ISSUE TITLE
Can't find jattach when profiler.sh is symlinked

### ISSUE THREAD

**Issue by oehme** [jvm-profiling-tools/async-profiler#405]
I symlinked profiler.sh into my `~/bin`, but it fails to attach because it [doesn't resolve the script directory correctly](https://github.com/jvm-profiling-tools/async-profiler/blob/master/profiler.sh#L100). The accepted answer on this [stackoverflow thread ](https://stackoverflow.com/questions/59895/how-can-i-get-the-source-directory-of-a-bash-script-from-within-the-script-itsel)seems to work in all cases.

**Comment by apangin** [comment]
I have changed this part multiple times already - to make the script work on macOS, Alpine, without bash, etc. I'm about to give up shell scripting in favor of a normal binary launcher. This will also make `jattach` helper unnecessary.

**Comment by apangin** [comment]
OK, I made profiler.sh resolve absolute symlinks.
Don't want to overcomplicate things right now by handling all sorts of links, as this shell script will be eventually replaced by a normal executable.
