### ISSUE TITLE
Help finding a suitable JDK

### ISSUE THREAD

**Issue by mjaggard** [jvm-profiling-tools/async-profiler#407]
We'd like to run the profiler inside Docker using Java 15 but we're having trouble knowing which JDK is the correct one to use in order to have debug symbols. We chose one but are getting this error every few seconds:
`WARNING: Install JVM debug symbols to improve profile accuracy`

**Comment by mjaggard** [comment]
We currently use https://hub.docker.com/layers/adoptopenjdk/openjdk15/slim/images/sha256-3d1ad8ba1e6e7defa2751a7108e8babd7892f8b31ca0d44bc66cfb58587093e7?context=explore

**Comment by apangin** [comment]
[Liberica JDK](https://bell-sw.com/pages/downloads/) will be a good choice. Their `lite` builds are really small, yet fully functional. Liberica JDK is profiler-ready out of the box. They also provide [docker images](https://hub.docker.com/u/bellsoft) for the popular environments.

[Zulu](https://www.azul.com/downloads/zulu-community/) is another great option. They offer a wide range of packages and docker images for all occasions.

**Comment by nithinnambiar** [comment]
@mjaggard is this an issue with JDK 11 builds also?

**Comment by petrbouda** [comment]
I created my own image for testing purposes: https://github.com/petrbouda/openjdk-x-dbg-asyncprofiler

**Comment by apangin** [comment]
@petrbouda `Symbol "UseG1GC" is at 0x15bdc44` message says that the symbol was found, and correctly resolved to the address `0x15bdc44`.
I agree, gdb message sounds confusing. The thing is that "debuginfo" includes more than just "symbols", and async-profiler needs only symbols from `.symtab` section, not the full debuginfo.

**Comment by petrbouda** [comment]
Then it makes sense to me because I was able to see JVM frames. Thanks a lot for your explanation! :+1:

**Comment by sxa** [comment]
@mjaggard What was the reason for you choosing the `slim` builds? They are intended to be very small (so we strip them, unlike the non-slim builds) so the expectation was likely that people picking them up want the smallest image possible for their deployments, irrespective of being able to monitor/debug it. Have you tried with the normal AdoptOpenJDK docker images as they shouldn't be stripped - you shouldn't necessarily have to go to another provider to be able to use the profiler ;-) ?
