### ISSUE TITLE
Content Security Policy blocks inline execution of scripts and stylesheets

### ISSUE THREAD

**Issue by wolfch-elsevier** [jvm-profiling-tools/async-profiler#410]
When loading the generated flamegraph HTML from disk, it renders properly.  If setup to write the flamegraph HTML to the document root of a webapp, and then accessing it over HTTP, the graph does not render.  This issue occurs in both Chrome and Firefox - the error in the browser console is:
`Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).`

The issue appears to be due to an inline `<script/>` element. See:
https://github.com/jvm-profiling-tools/async-profiler/blob/master/src/converter/FlameGraph.java#L242

Although the server could be configured to send 
```
Content-Security-Policy: default-src 'self'
```
In my case, I don't have access to the web app since it's an embedded jetty app - "Apache Solr".

I am not an expert with CSP, but I believe the issue would be resolved if the JS is loaded from a separate JS file, rather then inline.

**Comment by apangin** [comment]
Keeping the flame graph in a single self-contained file is essential for the typical use case.

I have tested multiple web servers in the default configuration, and I can see Chrome successfully opening remote flame graphs with the embedded script. Looks like it's a configuration problem with your particular web app.
