### ISSUE TITLE
Send errors/warning to a separate file (instead of the process' stderr)

### ISSUE THREAD

**Issue by Jongy** [jvm-profiling-tools/async-profiler#412]
@apangin , is there any particular reason for the use of `fprintf(stderr, ...)`? It makes debugging of AP-related issues much less straight-forward because you don't see the errors immediately. Skimming through issues here, this looks like a common point for confusion.
If AP would write logs to `/tmp/...` (or, to a path given to `profiler.sh`) then `profiler.sh` could read it after `jattach` to show you the information immediately.
After https://github.com/jvm-profiling-tools/async-profiler/pull/411 we can also get this error file to be written in "host" FS, but that's less important IMO compared to getting it separated from the app's stderr first.

If you think this change is appropriate, I can implement it and post a PR.

**Comment by apangin** [comment]
There is already `log` option for redirecting errors and warnings to the specified file. What else would you like to implement?

**Comment by Jongy** [comment]
> There is already `log` option for redirecting errors and warnings to the specified file. What else would you like to implement?

Ah, totally my bad :facepalm: I was looking at the code of v1.8.4, not master. Just now saw 7ec5c195e7ec4ad37d0673f6830a256c105721de. That's exactly what I needed :)
