### ISSUE TITLE
FlameGraphs with stacks higher than 2000 frames are not rendered correctly

### ISSUE THREAD

**Issue by apangin** [jvm-profiling-tools/async-profiler#418]
The canvas with the height > 32767px does not work in Chrome (and probably oher browsers).

**Comment by oehme** [comment]
I noticed that the tops of my graphs are often seemingly empty. Zooming in I would find a single stack that's super high, but only a single pixel wide. Maybe having a higher minimum width would also help with the height of the canvas?

**Comment by apangin** [comment]
Yes, that's what `--minwidth` argument does. If you specify `--minwidth 0.1`, frames with less than 0.1% samples will be omitted, and this will often decrease the graph height.

Since the introduction of HTML Flame Graphs, the default `minwidth` was dropped to zero, because small frames no longer affect the rendering performance as much as with SVG. Even when barely visible, small frames are useful for understanding the entire profile, in particular, when searching for a specific method to find out its cumulative impact.

**Comment by oehme** [comment]
Makes sense, I'll just change my minwidth setting then.
