### ISSUE TITLE
The question about --lock duration

### ISSUE THREAD

**Issue by sherman** [jvm-profiling-tools/async-profiler#420]
Hi, @apangin!

Running the following command:
```
./profiler.sh -d 10 -e lock --lock 10ms <pid>
```

I'm trying to set different values from 10ms to 1 second, but the log looks the same.
When I set 1 second I expected to see an empty log (I believe I have no such terrible contention in my application), but I can see the samples.

* Could you please clarify what the lock option does?
* Is it possible to capture only events which are waiting more the 10 ms (for example)?

**Comment by apangin** [comment]
It works for me as expected.
Are you sure you use async-profiler 2.0? (verify with `./profiler.sh -v <pid>`)

How does `--lock` parameter affect the profiling results on a simple test like this?
```java
public class LockTest {
    private static final Object lock = new Object();

    public static void main(String[] args) throws Throwable {
        new Thread(LockTest::run).start();
        new Thread(LockTest::run).start();
    }

    private static void run() {
        try {
            for (int i = 0; i < 10; i++) {
                synchronized (lock) {
                    System.out.println(Thread.currentThread().getName() + ": " + i);
                    Thread.sleep(500);
                }
                Thread.sleep(10);
            }
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
}
```

**Comment by apangin** [comment]
I assume the question is answered.
Closing the issue in the lack of additional input.
