### ISSUE TITLE
Cannot build using jdk17

### ISSUE THREAD

**Issue by navyxliu** [jvm-profiling-tools/async-profiler#423]
I got error message as follows. 

```
../jdk/build/linux-x86_64-server-release/images/jdk/bin/javac -source 6 -target 6 -d build/api src/api/one/profiler/Events.java src/api/one/profiler/AsyncProfiler.java src/api/one/profiler/AsyncProfilerMXBean.java src/api/one/profiler/Counter.java
warning: [options] bootstrap class path not set in conjunction with -source 6
error: Source option 6 is no longer supported. Use 7 or later.
error: Target option 6 is no longer supported. Use 7 or later.
make: *** [build/async-profiler.jar] Error 2
```

I saw you guys made it configurable in #285 .  I change it from 6 to 7 and get passed. 
Why do we need to specify a source version here?

**Comment by apangin** [comment]
async-profiler supports a wide range of JDK versions, starting from JDK 6, so we need to compile Java classes with the minimum supported bytecode level.

In order to build it with a recent JDK, run
```
make JAVAC_RELEASE_VERSION=7
```

**Comment by apangin** [comment]
For now, I've made javac use Java 6 target only when building `release`.

**Comment by navyxliu** [comment]
your patch LGTM. Thanks for solving it!

**Comment by ijuma** [comment]
I think it would make sense to drop Java 6 support in the next release. All the major vendors dropped support for that a while back. Even Java 7 is only one year away from the end of extended support by Oracle (and Red Hat's support seems to end this month).

**Comment by apangin** [comment]
@ijuma Already did this a few hours ago :)
https://github.com/jvm-profiling-tools/async-profiler/commit/ff49ccccb73c2a5e677653da67f269c4daa7057d#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R19

**Comment by ijuma** [comment]
Awesome!
