### ISSUE TITLE
async-profiler v1.8.5 and v2.0

### ISSUE THREAD

**Issue by shipilev** [jvm-profiling-tools/async-profiler#427]
I was lead to understand that v1.x branch holds maintenance releases. But I see that both `v2.0` and `v1.8.5` tags point to the same changeset, namely:

```
commit 3ff315ea8ff3ed8fb55d931f67cac634d8c51b99 (HEAD, tag: v2.0, tag: v1.8.5)
Author: Andrey Pangin <andrey.pangin@corp.mail.ru>
Date:   Sun Mar 14 20:19:13 2021 +0300

    Release 2.0
```

Was this intentional? Does this mean `v1.x` would no longer be maintained?

**Comment by shipilev** [comment]
Context: JMH was apparently broken for `1.8.5` users: https://github.com/openjdk/jmh/pull/36.

**Comment by apangin** [comment]
It is a mistake. Thank you for reporting.
v1.8.5 was released from `v1.x` branch, but the tag was incorrectly set on the master branch. I've moved the tag to the correct commit. The [published artifacts](https://github.com/jvm-profiling-tools/async-profiler/releases/tag/v1.8.5) were built from the correct commit though.

**Comment by apangin** [comment]
I'll keep maintaining `v1.x` branch until the end of this year.

1.8.5 still produces SVG Flame Graphs (and accepts `-o svg` option).
Flame Graphs became HTML in 2.0.

**Comment by shipilev** [comment]
All right, thank you!

I see the updated `v1.8.5` tag points to "Release 1.8.5" now. I believe both the original reporter and me have been building from the wrong `v1.8.5`, and thus misleading ourselves into thinking that 1.8.5 does not support `-o svg`. I checked the builds from new tags work fine.

With openjdk/jmh#36, JMH should now autodetect 1.x as "svg"/".svg" and everything else as "flamegraph"/".html". Shout back if think that is incorrect.

**Comment by apangin** [comment]
That's correct.
BTW, `-o flamegraph` works both in 1.x and 2.x. I mean, it's enough to select just the file extension, and leave the same output option for either version.

**Comment by shipilev** [comment]
Right on, I simplified it even further. I also checked that https://github.com/jvm-profiling-tools/async-profiler/releases/download/v1.8.5/async-profiler-1.8.5-linux-x64.tar.gz does indeed contain the version that produces proper SVGs.
