### ISSUE TITLE
Корпоративные ограничения

### ISSUE THREAD

**Issue by blissdeathour** [jvm-profiling-tools/async-profiler#432]
Добрый день! 
На моем корпоративном ноутбуке macos стоит запрет на запуск приложений от неустановленных разработчиков.
Столкнулся с проблемой: ./profiller не может запускаться на macos с такими ограничениями.

Он ругается на 2 файла: jattach и libasyncProfiler.so
jattach можно скачать github.com/apangin/jattach  и скомпилировать, а вот libasyncProfiler.so найти не удается.
Помогите пожалуйста решить эту проблему

**Comment by apangin** [comment]
async-profiler можно точно так же [скомпилировать из исходников](https://github.com/jvm-profiling-tools/async-profiler#building).
Для этого достаточно иметь Xcode Command Line Tools и JDK.
Нужно перейти в каталог проекта и выполнить `make`.

Отдельно скачивать и собирать `jattach` не требуется - он уже включен в async-profiler и собирается автоматически.

**Comment by apangin** [comment]
Ещё: если вы скачали с профайлер отсюда с гитхаба, чтобы снять ограничение на запуск, достаточно удалить у файлов расширенный атрибут `com.apple.quarantine`. Для этого выполните команду
```
xattr -dr com.apple.quarantine async-profiler-2.0-macos-x64
```

В будущих релизах я попробую подписывать бинарники, чтобы подобных предупреждений более не возникало.

На этом считаю вопрос отвеченным и закрываю.
Если возникнут дальнейшие вопросы, создайте новый Issue, желательно на английском языке.
