### ISSUE TITLE
Strange call stack symbols on linux-aarch64

### ISSUE THREAD

**Issue by dpochepko** [jvm-profiling-tools/async-profiler#433]
how to reproduce:
get some application which is actively working with GC. It can also be some synthetic simple app(attached test.java). Compile and run it. Launch async profiler after several seconds warmup. I used 10 seconds recording.
Resulting async profiler report contains $x symbols (usually in several places). (example report is attached: out.html. Zoom into GC-related part).

[attachments.tar.gz](https://github.com/jvm-profiling-tools/async-profiler/files/6533156/attachments.tar.gz)

I wasn't able to reproduce it on linux-x86_64. Reproducible on linux-aarch64.
java version used: jdk-11.0.11

**Comment by dpochepko** [comment]
It looks like it is special mapping symbols on aarch64: https://sourceware.org/binutils/docs-2.29/as/AArch64-Mapping-Symbols.html

**Comment by apangin** [comment]
You are right. A good explanation of mapping symbols can be found [here](https://developer.arm.com/documentation/ihi0056/g/?lang=en#symbol-table).
So, when parsing ELF, we shall just skip all STB_LOCAL symbols with zero size and the name starting with `$`.
I've committed the fix.
