### ISSUE TITLE
multiple flamegraph on different events from JFR

### ISSUE THREAD

**Issue by cloud-66** [jvm-profiling-tools/async-profiler#436]
The only way to get multiple event profile is JFR. Then i get profile with command

 ./profiler.sh -e cpu,alloc,lock -f profile.jfr 

Then, i convert to flamegraph  with command

 java -cp converter.jar jfr2flame profile.jfr profile.html

I get only cpu profile flamegraph. Is it possible to get also alloc and lock profile flamegraph?

**Comment by apangin** [comment]
Yes, see https://github.com/jvm-profiling-tools/async-profiler/issues/150#issuecomment-817355771
