### ISSUE TITLE
Could not start attach mechanism: No such file or directory

### ISSUE THREAD

**Issue by egor-ryashin** [jvm-profiling-tools/async-profiler#44]
``` bash
sudo ./profiler.sh -d 15 2381

Could not start attach mechanism: No such file or directory
```
Cannot figure out what's wrong.

**Comment by egor-ryashin** [comment]
The process was in a docker container.

**Comment by apangin** [comment]
Right, the profiler and the JVM should have access to each other, which is not usually the case with containers. I've added Troubleshooting section to README. Thank you for the report.
