### ISSUE TITLE
Is there any way to know a frame is a compiled frame or an interpreted frame?

### ISSUE THREAD

**Issue by guanggenzhang** [jvm-profiling-tools/async-profiler#448]
Our process runs slowly after couple of days.  It maybe caused by some method run in interpreter mode instead of compiled mode. Is there anyway to know a frame is run in interpreter mode/compiled mode?

**Comment by apangin** [comment]
I'm investigating how async-profiler can supplement output with JIT/Interpreter information.
This looks difficult, but not impossible.

Meanwhile I committed a change that adds dummy "Interpreter" frame above Java stack trace, if the topmost Java frame runs in the interpreter.
![interp](https://user-images.githubusercontent.com/1749416/127787992-9cbedc54-455e-48a6-9c25-114204c0a908.png)

Check [interpreter](https://github.com/jvm-profiling-tools/async-profiler/tree/interpreter) branch.

However, the scenario you've described is highly unlikely. Methods that run long/often enough, are almost always JIT compiled. Especially if the application has already been running for a couple of days. Other ("cold") methods that run in the interpreter, do not typically affect performance. A notable exception is when the Code Cache becomes full, but this is easy to check with any JMX capable tool like Visual VM / JConsole / Mission Control.

**Comment by guanggenzhang** [comment]
Another possibility could be generated method is too large and exceed the HugeMethodLimit.
By the way is it possible that code cache get too fragmented to hold a large method?

**Comment by krzysztofslusarski** [comment]
@guanggenzhang yes it is possible. In older versions of JVM there was also a bug https://bugs.openjdk.java.net/browse/JDK-8244278 which could casue a lot of fragmentation. With this bug the JVM could compile simple method few times a day. Here is a part of the JVM log with such a situation

```
[09:04:52.835] 214973       4       java.util.HashMap::<init> (11 bytes)
[10:49:55.579] 214973       4       java.util.HashMap::<init> (11 bytes)   made not entrant
[10:49:57.884] 228194       4       java.util.HashMap::<init> (11 bytes)
[11:31:19.272] 228194       4       java.util.HashMap::<init> (11 bytes)   made not entrant
[11:31:19.853] 231080       4       java.util.HashMap::<init> (11 bytes)
[14:06:29.779] 231080       4       java.util.HashMap::<init> (11 bytes)   made not entrant
[14:06:30.992] 241011       4       java.util.HashMap::<init> (11 bytes)
[14:49:54.579] 241011       4       java.util.HashMap::<init> (11 bytes)   made not entrant
[14:49:57.921] 242993       4       java.util.HashMap::<init> (11 bytes)
```

If you want to know if specified method is compiled or not you can run:
```
jcmd <pid> Compiler.codelist
```
at runtime.

**Comment by apangin** [comment]
The feature has been integrated. async-profiler now shows the compilation state of the top frames:

- Light green are interpreted;
- Cyan are inlined;
- Green are regular (specifically, green top frames are compiled; the state of non-top frames is unknown).
