### ISSUE TITLE
Memory profiling - unknown function names

### ISSUE THREAD

**Issue by pedegie** [jvm-profiling-tools/async-profiler#451]
Hello, I run profiling for malloc memory events like this:

`profiler.sh -e malloc -d 90 -f graph.html PID` which generates this flamegraph:

![image](https://user-images.githubusercontent.com/10982244/130221179-09c8fe85-e0a8-4440-8251-1c22c6c88585.png)

`DB.set` method is native method of kyotocabinet database client library. There we can see, [unknown] method calls.

When i run profiling, on the same app with jemalloc prof profiler, then i can see more accurate results:

![image](https://user-images.githubusercontent.com/10982244/130221487-bfde4cef-35ff-4990-ad54-431fdd6de7d7.png)

We can see, that the most important informations are lost using async profiler. I run asyncprofiler after loading kyoto lib.

JDK: openjdk-1.8.0_272
OS: Ubuntu 20.04.2 LTS
`profiler.sh --version`: 2.0 built on Mar 14 2021

**Comment by apangin** [comment]
Seems that kyoto is compiled without frame pointers (`-fomit-frame-pointer`), so perf_events stack walker is helpless.

DWARF-based stack unwinding could probably help, but I explained in [this answer](https://github.com/jvm-profiling-tools/async-profiler/issues/215#issuecomment-617443443) why I didn't implement that.

**Comment by apangin** [comment]
I wouldn't say that async-profiler loses "the most important information" though. From the point of leak detection, the library internals are less important than the use cases of that library. That's what async-profiler shows, and that's what you probably have control over.

BTW, I have recently added an experimental mode specifically for [native leak detection](https://github.com/jvm-profiling-tools/async-profiler/tree/malloc#finding-native-memory-leaks). It's available in [malloc](https://github.com/jvm-profiling-tools/async-profiler/tree/malloc) branch.

**Comment by pedegie** [comment]
Yeah, at least we know that something is wrong with **this** library but 2nd screen let me dive into kyotocabinet source code and find the reason (or leak) why memory is never released. I can see on each malloc it checks some global integer counter and compares current cache size. The "global integer" is configuration parameter which leads me to just narrow cache limit what solves problem - with only async-profiler (it's a great tool i really appreciate) there would be too many places to check.

Thanks for quick response, I will play with profiler from malloc branch on Monday! :))

**Comment by pedegie** [comment]
Profiling with DWARF (using perf) shows symbols correctly so thanks for hint. I also run profiler on malloc branch - it's working fine for me and confirms that kyoto doesn't free memory. The only problem I had is when file.jfr becomes bigger (more than 2GB) it throws Size exceeds Integer.MAX_VALUE from one.jfr.JfrReader.<init> because Java allows mmaping up to 2GB only.

**Comment by gorrus** [comment]
@pedegie please check https://github.com/jvm-profiling-tools/async-profiler/issues/360#issuecomment-722515066 about the 2Gb limit

**Comment by apangin** [comment]
> The only problem I had is when file.jfr becomes bigger (more than 2GB) it throws Size exceeds Integer.MAX_VALUE

Fixed. JfrReader now supports files larger than 2GB.

As to DWARF support, I think I answered the question, so let me close the issue.

**Comment by apangin** [comment]
FYI, I've implemented [DWARF unwinding](https://github.com/jvm-profiling-tools/async-profiler/issues/215#issuecomment-974360695)
