### ISSUE TITLE
Conversion fails on large JFR recordings

### ISSUE THREAD

**Issue by nitsanw** [jvm-profiling-tools/async-profiler#452]
We have a file of size more than `Integer.MAX_VALUE`.
`FileChannel::size()` returns a long:
https://docs.oracle.com/javase/7/docs/api/java/nio/channels/FileChannel.html#size()
`JfrReader` Tries to mmap the full file length, the `size` parameter accepts a `long`:
https://github.com/jvm-profiling-tools/async-profiler/blob/master/src/converter/one/jfr/JfrReader.java#L72
But from the `FileChannel::map` docs:
> size - The size of the region to be mapped; must be non-negative and no greater than Integer.MAX_VALUE

A workaround is to disassemble the recording(e.g. with `jfr disassemble --max-size 1000000000`) and convert the smaller files.

**Comment by apangin** [comment]
The fix has been merged into master.
