### ISSUE TITLE
How to use the option --fdtransfer for profiling from the host

### ISSUE THREAD

**Issue by sattishv** [jvm-profiling-tools/async-profiler#455]
Hi ,

While searching for an option to execute the profiler from the host we found an new option --fdtransfer.

When we tried that option on our host

sudo -u username ./profiler.sh -e cpu -d 30 --fdtransfer -f /tmp/sample.html  <PID> we encountered Unrecognized option: --fdtransfer
we used both 1.8.6 and 2.0 versions of async-profiler We arent sure whether the approach  is correct is their any pre-requisite required  could you guide us. Thanks in advance

**Comment by martin-g** [comment]
You should use latest `master` branch and build it locally.
`fdtransfer` has been merged to `master` just the other day. It is not released yet.

**Comment by sattishv** [comment]
Martin .Thanks for the response. Will try to build it

**Comment by sattishv** [comment]
Hi Martin,

We were to build it locally . Now i could see the option when i invoked ./profiler.sh help

But while trying to attach profiler to the process id from the host, we encountered the below listed error
sudo -u user ./profiler.sh status 210391
/tmp/async-profiler/build/jattach: 1: /tmp/async-profiler/build/jattach: Syntax error: "(" unexpected.

Thanks
Sattish

**Comment by Jongy** [comment]
@sattishv , it seems like `jattach` is being interpreted as a shell script, but it's a binary. Any chance you're running a `jattach` built for a different architecture? Can you please provide the output of:
```
$ uname -m
$ file /tmp/async-profiler/build/jattach
```

**Comment by sattishv** [comment]
@Jongy Sorry my bad i used the binary created in Mac OS on linux x64. Thanks for pointing out it. Later on we were able to create a binary successfully on linux.  But  when i tried to attach to java process using the new binary i got the below listed error.
Failed to enter the net NS of target process <PID>

**Comment by Jongy** [comment]
@sattishv a few questions if you mind - 
* What kernel version are you running?
* Is the application running in a container?

If possible, could you modify the `fdtransfer` function in `profiler.sh` and prefix `"$FDTRANSFER" "$PID"` with `strace`, so we can get a full log of the syscalls and see which one failed and why.

**Comment by Jongy** [comment]
> I could see the both variables already defined in profiler.sh

Sorry, I meant to prefix their evaluation with `strace`, so that we can see what exactly fails. Like this:
```
diff --git a/profiler.sh b/profiler.sh
index b10214a..c52ca92 100755
--- a/profiler.sh
+++ b/profiler.sh
@@ -89,7 +89,7 @@ check_if_terminated() {
 
 fdtransfer() {
     if [ "$USE_FDTRANSFER" = "true" ]; then
-        "$FDTRANSFER" "$PID"
+        strace "$FDTRANSFER" "$PID"
     fi
 }
```

**Comment by sattishv** [comment]
Hi Yonatan,
Thanks for the clarity. Here is the output after prefixing with strace

sudo -u altusapp ./profiler.sh --fdtransfer -d 30 -f profile.html 210391
execve("/opt/async-profiler/build/fdtransfer", ["/opt/async-profiler/build/fdtran"..., "210391"], [/* 18 vars */]) = 0
brk(NULL)                               = 0x13b7000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
access("/etc/ld.so.preload", R_OK)      = 0
open("/etc/ld.so.preload", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
close(3)                                = 0
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=53486, ...}) = 0
mmap(NULL, 53486, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fcf175a9000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0`\t\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1868984, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fcf175a8000
mmap(NULL, 3971488, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fcf16fc8000
mprotect(0x7fcf17188000, 2097152, PROT_NONE) = 0
mmap(0x7fcf17388000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1c0000) = 0x7fcf17388000
mmap(0x7fcf1738e000, 14752, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fcf1738e000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fcf175a7000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fcf175a6000
arch_prctl(ARCH_SET_FS, 0x7fcf175a7700) = 0
mprotect(0x7fcf17388000, 16384, PROT_READ) = 0
mprotect(0x602000, 4096, PROT_READ)     = 0
mprotect(0x7fcf175b7000, 4096, PROT_READ) = 0
munmap(0x7fcf175a9000, 53486)           = 0
brk(NULL)                               = 0x13b7000
brk(0x13d8000)                          = 0x13d8000
open("/proc/210391/status", O_RDONLY)   = 3
fstat(3, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
read(3, "Name:\tjava\nUmask:\t0022\nState:\tS "..., 1024) = 1024
read(3, "0000000,00000000,00000000,000000"..., 1024) = 357
read(3, "", 1024)                       = 0
close(3)                                = 0
stat("/proc/self/ns/net", {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
stat("/proc/210391/ns/net", {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
open("/proc/210391/ns/net", O_RDONLY)   = 3
setns(3, 0)                             = -1 EPERM (Operation not permitted)
close(3)                                = 0
write(2, "Failed to enter the net NS of ta"..., 52Failed to enter the net NS of target process 210391
) = 52
exit_group(1)                           = ?
+++ exited with 1 +++

Please review and share your thoughts

Thanks
Sattish

**Comment by Jongy** [comment]
@sattishv `setns` fails with `EPERM`. The man page for this syscall lists one reason:
```
EPERM  The calling thread did not have the required capability for this operation.
```
`fdtransfer` needs to run as root - so `sudo -u altusapp` won't work. You can run it as root (just `sudo`) and `jattach` (invoked by `profiler.sh`) will switch UID/GID so it matches the target application.

**Comment by sattishv** [comment]
Hi @Jongy 

It worked with the user as root thanks for the inputs. To track system calls, while running it from host do we need to install linux perf tool on the host. Will async-profiler trace the native calls without perf or it needs to be installed.

**Comment by apangin** [comment]
No, it doesn't need to be installed; async-profiler does not depend on `perf`.

**Comment by Jongy** [comment]
As Andrei said, you don't need to install anything. The `perf` tool is just one usermode interface to the kernel `perf_events` subsystem. async-profiler uses the `perf_events` subsystem directly.

Also note that async-profiler is able to trace native code in usermode (JVM / libc / ...) in `itimer` mode (without using fdtransfer). `cpu` mode (and fdtransfer) add kernel code.

**Comment by sattishv** [comment]
Thanks for all the inputs. Apprecaite your swift response.

**Comment by sattishv** [comment]
HI Team,

Sorry for continuing this thread. Tried the same binary (--fdtransfer) on one of our prod instance but in prod for the below listed error. The same binary worked in QA env. Both my QA and Prod uses Linux.

# ./profiler.sh --fdtransfer 3660816
Failed to inject profiler into 3660816
FdTransfer accept(): Resource temporarily unavailable

Thanks
Sattish

**Comment by sattishv** [comment]
@Jongy 
Have attached the strace output gathered from prod instance.
./profiler.sh --fdtransfer -e cpu  3274513
execve("/tmp/async-profiler/build/fdtransfer", ["/tmp/async-profiler/build/fdtran"..., "3274513"], [/* 20 vars */]) = 0
brk(NULL)                               = 0x1b36000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=41776, ...}) = 0
mmap(NULL, 41776, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f8e45408000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0`\t\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1868984, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8e45407000
mmap(NULL, 3971488, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f8e44e24000
mprotect(0x7f8e44fe4000, 2097152, PROT_NONE) = 0
mmap(0x7f8e451e4000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1c0000) = 0x7f8e451e4000
mmap(0x7f8e451ea000, 14752, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f8e451ea000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8e45406000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8e45405000
arch_prctl(ARCH_SET_FS, 0x7f8e45406700) = 0
mprotect(0x7f8e451e4000, 16384, PROT_READ) = 0
mprotect(0x602000, 4096, PROT_READ)     = 0
mprotect(0x7f8e45413000, 4096, PROT_READ) = 0
munmap(0x7f8e45408000, 41776)           = 0
brk(NULL)                               = 0x1b36000
brk(0x1b57000)                          = 0x1b57000
open("/proc/3274513/status", O_RDONLY)  = 3
fstat(3, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
read(3, "Name:\tjava\nUmask:\t0022\nState:\tS "..., 1024) = 1024
read(3, "\t00000000,00000000,00000000,0000"..., 1024) = 369
read(3, "", 1024)                       = 0
close(3)                                = 0
stat("/proc/self/ns/net", {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
stat("/proc/3274513/ns/net", {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
open("/proc/3274513/ns/net", O_RDONLY)  = 3
setns(3, 0)                             = 0
close(3)                                = 0
socket(PF_LOCAL, SOCK_SEQPACKET, 0)     = 3
setsockopt(3, SOL_SOCKET, SO_RCVTIMEO, "\n\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 16) = 0
bind(3, {sa_family=AF_LOCAL, sun_path=@"async-profiler-5036"}, 22) = 0
listen(3, 1)                            = 0
stat("/proc/self/ns/pid", {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
stat("/proc/3274513/ns/pid", {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
open("/proc/3274513/ns/pid", O_RDONLY)  = 4
setns(4, 0)                             = 0
close(4)                                = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f8e454069d0) = 1458075
exit_group(0)                           = ?
+++ exited with 0 +++
Failed to inject profiler into 3274513

Thanks
Sattish.

**Comment by apangin** [comment]
@sattishv This problem is not related to `fdtransfer`.

"Failed to inject profiler into <pid>" issue is mentioned in [README | Troubleshooting](https://github.com/jvm-profiling-tools/async-profiler#troubleshooting):

> The connection with the target JVM has been established, but JVM is unable to load profiler shared library. Make sure the user of JVM process has permissions to access libasyncProfiler.so by exactly the same absolute path.

Most often, this happens when a container does not "see" the directory with the profiler.

**Comment by sattishv** [comment]
Hi @apangin 

Thanks for the Inputs. I tried connecting to target JVM available in container from host(container pid from host) using --fdtransfer as root user in my QA env. I was able to connect without issues. But when i tried the same from my prod env i got the below mentioned error.
Failed to inject profiler into 3816973  

Troubleshooting carried out:
From host:
Invoked the command by removing /dev/null as mentioned in the troubleshoot 
#  ./profiler.sh --fdtransfer list 3816973
Connected to remote JVM
JVM response code = -1

java -agentpath:/tmp/async-profiler/build/libasyncProfiler.so=start,summary,flat -version
[WARN] Install JVM debug symbols to improve profile accuracy
Profiling started
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~16.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
--- Execution profile ---
Total samples       : 0

          ns  percent  samples  top
  ----------  -------  -------  ---

"Make sure the user of JVM process has permissions to access libasyncProfiler.so by exactly the same absolute path."
We tried changing the ownership of the folder structure to the same user who owns the JVM process but still the same issue.

**Comment by apangin** [comment]
I mean, if async-profiler resides, for example, in `/some/path/async-profiler` directory, the same directory with the same name `/some/path/async-profiler` should exist in the container.

**Comment by sattishv** [comment]
@apangin Thanks it works now i was able to take cpu profiles after copying the same folder contents available in the  host to the container. Appreciate the support

**Comment by sattishv** [comment]
@apangin . While generating profiles using fdtransfer sometimes the contents arent wriiten to the file we specify in the command rather it prints all the contents while stopping the profiler.

Command used: ./profiler.sh --fdtransfer -e cpu -d 300 -o collapsed -f /tmp/sample_cpu.txt 346735
1. When using the above command after profiling for 300 seconds the user logged out.
2. But when we checked the status using ./profiler.sh status 346735 we got the below msg
Profiling for 667 seconds 
3. When we stopped the process by ../profiler.sh stop 346735 process got stopped and all the comtents are displayed in the console no file is created in the container

Is the command we used is correct are we missing something over here

**Comment by apangin** [comment]
The command
```
./profiler.sh -d 300 -o collapsed -f /tmp/sample_cpu.txt 12345
```
works as a shortcut for
```
./profiler.sh start 12345
    (wait for 300 sec)
./profiler.sh stop -o collapsed -f /tmp/sample_cpu.txt 12345
```
If in the middle of waiting the script is forcibly terminated (other than by CTRL+C), the subsequent `stop` command is not executed, and therefore profiler will continue working.
`CTRL+C` is handled specially: waiting is interrupted, profiler immediately stops and dumps output.

As explained above, `-o` and `-f` options are applied to `stop` command rather than `start`. This makes possible to dump the same profile multiple times in different formats. So if you want to dump profile to a file rather than console, run `profiler.sh stop -f sample_cpu.txt ..` rather than just `profiler.sh stop`.

I'll probably reconsider in future versions how command line arguments are handled (to make them more intuitive), but as of version 2.x, they work like this.
Hope this helps.
