### ISSUE TITLE
Report for number of allocations, in addition to aggregate size

### ISSUE THREAD

**Issue by retronym** [jvm-profiling-tools/async-profiler#46]
Ideally, both would be recorded and available to the output formatter.

A new command line option `-a size|count` could control which counter the current formatters choose to report.

More advanced formatters/visualization tools could display both.

**Comment by retronym** [comment]
Relatedly, it would be good to have separate counters for TLAB and non-TLAB allocations.

The README does refer to this limitation.

I've been looking at the heap profiles of the Scala compiler, and the results are dominated resizing of large arrays (e.g. resizing our name table, or reading a classfile into a `byte[]`).

My intuition suggests that lumping both counters together will bias the profile towards the non-TLAB allocations. Assuming TLAB is < 1M, a 1M allocation has 100% chance of being counted, whereas only some of 100 0.1M allocations will be sampled.

My workaround is to filtering out the stack traces that are known to allocate large arrays before generating a flame graph.

**Comment by retronym** [comment]
I was tying this out with:

```diff
⚡ git diff master
diff --git a/src/allocTracer.cpp b/src/allocTracer.cpp
index 394560e..062f1ef 100755
--- a/src/allocTracer.cpp
+++ b/src/allocTracer.cpp
@@ -92,7 +92,7 @@ void AllocTracer::signalHandler(int signo, siginfo_t* siginfo, void* ucontext) {
         return;
     }

-    Profiler::_instance.recordSample(ucontext, obj_size, alloc_class);
+    Profiler::_instance.recordSample(ucontext, 1, alloc_class);

     // Leave the trapped function by simulating "ret" instruction
     frame.ret();
@@ -112,12 +112,12 @@ bool AllocTracer::start() {
     installSignalHandler();

     _in_new_tlab.install();
-    _outside_tlab.install();
+    //_outside_tlab.install();

     return true;
 }

 void AllocTracer::stop() {
     _in_new_tlab.uninstall();
-    _outside_tlab.uninstall();
+    //_outside_tlab.uninstall();
 }
```

And came across this VM crash:

```
guarantee(zombie_ok || !nm->is_zombie()) failed: cannot lock a zombie method
```

https://gist.github.com/retronym/34f87b2a55b1b48b8b6a235306a8ba0d

Perhaps my patch is doing the wrong thing, but I thought I'd report in case it unrelated and someone else runs into the same error message.

**Comment by apangin** [comment]
Thank you for the feedback. This functionality will be indeed useful; it already on my TODO list.

**Comment by apangin** [comment]
As to the crash, I'm pretty sure this is a JVM bug.

The crash happens early at the agent startup inside JVM TI GenerateEvents() call, when async-profiler has not yet done anything special. As far as I see from HotSpot sources, there is a chance of a race condition between the moments when `nmethod` is checked for liveness and when it is locked:
http://hg.openjdk.java.net/jdk8u/jdk8u/hotspot/file/aa4ffb1f30c9/src/share/vm/prims/jvmtiCodeBlobEvents.cpp#l234

If you have a case that reproduces the bug more or less often, I can submit a report directly in OpenJDK bugtracker.

**Comment by retronym** [comment]
I just tried to reproduce this but wasn't able to provoke the crash.

FTR, here's what I tried.

I ran our JMH benchmark, for around 30s per fork:

```
% git clone scala/compiler-benchmark; cd compiler-benchmark
% sbt 'set scalaVersion in compilation := "2.12.3"' 'hot -psource=scalap -f10 -w0 -wi 0 -i3 -jvmArgs -XX:+UnlockDiagnosticVMOptions -jvmArgs -XX:+DebugNonSafepoints'
```

I then ran 3s profiling sessions continually against this:

```
% for i in {1..120}; do echo $i; PID=$(jps -v | grep ForkedMain | awk -F' ' '{print $1}'); [[ -z "$PID" ]] || ./profiler.sh -d 3 -m cpu -b 5000000 -o summary $PID; done
```

**Comment by apangin** [comment]
> And came across this VM crash:
> 
> ```
> guarantee(zombie_ok || !nm->is_zombie()) failed: cannot lock a zombie method
> ```
> https://gist.github.com/retronym/34f87b2a55b1b48b8b6a235306a8ba0d
> 
> Perhaps my patch is doing the wrong thing, but I thought I'd report in case it is unrelated to my change and someone else runs into the problem.

I had a chance to investigate this deeper and came to conclusion that this is indeed a JVM issue. I submitted the bug report https://bugs.openjdk.java.net/browse/JDK-8212159 with the analysis and the suggested fix. Fortunately, the chances to hit this issue are very and very small. It took me several hours to reproduce the crash with the specially crafted stress test.

The workaround is to load profiler at JVM startup time using `-agentpath` option.
