### ISSUE TITLE
Allow to annotate native methods with enclosing library

### ISSUE THREAD

**Issue by quijote** [jvm-profiling-tools/async-profiler#462]
Async Profiler provides insights into native code but currently there seems to be no way to determine the origin of a certain method. 

My use case is to automatically analyze and highlight certain native code (e.g. in flamegraphs). E.g. I would like to determine CPU time consumed by libjvm.so and libmyagent.so.  

Determining library from method name is difficult. One library may contain symbols from hundreds of different namespaces. Multiple libraries may contain the exact same symbol. 

It would be useful to have an option similar to `-a` to annotate native methods with e.g. `_[n:libjvm.so]`.

**Comment by apangin** [comment]
Added profiler.sh `-l` option with its agent equivalent `lib`.
The format follows `perf` convention, i.e. ``library.so`function_name``.

Example:
![libs](https://user-images.githubusercontent.com/1749416/135371879-8a6bd1b2-b76f-430c-a76f-490dd967a5e3.png)
