### ISSUE TITLE
Does async-profiler can be used for node.js pr python process

### ISSUE THREAD

**Issue by sattishv** [jvm-profiling-tools/async-profiler#463]
Team,

can we use async-profiler to trigger cpu profile from the host(fdtransfer) against node.js or python process.

**Comment by Jongy** [comment]
No. asnyc-profiler uses JVM-specific APIs to extract the Java stack traces. You need another solution to extract Python or Node.JS stacks from those runtimes.
For Python you can try [py-spy](https://github.com/benfred/py-spy). For Node.JS you can check [this](https://nodejs.org/en/docs/guides/diagnostics-flamegraph/) guide.
