### ISSUE TITLE
Don't show system calls on MacOS

### ISSUE THREAD

**Issue by SeveNChaK** [jvm-profiling-tools/async-profiler#469]
Please, can you tell me is it possible to enable the display of system calls on Mac OS?

**Comment by apangin** [comment]
You probably mean, kernel stack traces?
async-profiler *does* show system calls, but not kernel stacks. It can't, because of the restriction of the operating system.

This is mentioned in [README](https://github.com/jvm-profiling-tools/async-profiler/#restrictionslimitations):
> macOS profiling is limited to user space code only.

**Comment by SeveNChaK** [comment]
Thanks!
