### ISSUE TITLE
Profiler error: There is no dump file

### ISSUE THREAD

**Issue by shangjianan2** [jvm-profiling-tools/async-profiler#470]
Idea said "Profiler error: There is no dump file" where I use async-profiler in idea. What is the meaning of this error? How can I solve this problem?

system: windows10
idea version:
![image](https://user-images.githubusercontent.com/29392363/135740126-95ab5c59-21ad-494b-8dec-18a819f251cb.png)

my operation step
1 run code
![bd52027183132473983bd0a1e56a2ab](https://user-images.githubusercontent.com/29392363/135740197-6d86e626-e176-4e5d-b595-90762a571943.png)

2 result
![1633235559(1)](https://user-images.githubusercontent.com/29392363/135740223-0775caf5-a409-40d3-9082-e53ae27a049b.jpg)

**Comment by apangin** [comment]
Windows Async Profiler is supported by JetBrains.
Please submit a report at https://youtrack.jetbrains.com/issues/IDEA
