### ISSUE TITLE
Profile N times in a row for X seconds

### ISSUE THREAD

**Issue by jaroslawr** [jvm-profiling-tools/async-profiler#471]
In some cases it would be useful if you could run `./profiler.sh -n 10 -d 60`, which would result in the profiler running for `10*60=600` but emitting 10 different output files (e.g. flamegraphs) for each 60 second period, so you can track minute-to-minute changes in what consumes the CPU. You can run the profiler in a bash loop, but it looks like detaching from the JVM takes some time and there is some substantial delay between the samples (`./profiler.sh -d 60` takes 70 seconds to execute or something like this).

**Comment by apangin** [comment]
You don't need to run profiler 10 times to track minute-to-minute changes.
That's what `jfr` output is for. It keeps time information for all events.
Just run profiler for 10 minutes with `-f result.jfr` - you'll get the full profile that you can narrow down to the specific time window in JMC or other JFR viewer.

In the recent async-profiler 2.5 release, there in an option to automatically begin new JFR chunk each N seconds, e.g.
```
./profiler.sh -f result.jfr -d 600 --chunktime 60s <pid>
```

Then you can split `result.jfr` by chunks to individual 1-minute JFRs:
```
jfr disassemble --max-chunks 1 result.jfr
```

Both IntelliJ IDEA and JMC can open `.jfr` files and display them as Flame Graphs.

Alternatively, you can use [`converter.jar`](https://github.com/jvm-profiling-tools/async-profiler/releases/download/v2.5/converter.jar) included in async-profiler bundle to convert .jfr to .html Flame Graph:
```
java -cp converter.jar jfr2flame result_0.jfr result_0.html
```

Finally, you can benefit from converting the entire (non-splitted) `jfr` to the [`flamescope`](https://github.com/Netflix/flamescope) format:
```
java -cp converter.jar jfr2nflx result.jfr result.nflx
```
where you'll be able inspect the timeline and build a flame graph from any selected time region:

![flamescope](https://user-images.githubusercontent.com/1749416/135757805-2934ec39-1153-424b-90ce-6ddaa0406c5a.png)

**Comment by jaroslawr** [comment]
@apangin This is super cool :) Thanks a lot for your answer!
