### ISSUE TITLE
Collapsed output format could better represent missing stacktraces

### ISSUE THREAD

**Issue by retronym** [jvm-profiling-tools/async-profiler#48]
When first using this tool I was confused about the "Ignored .... lines with invalid format" error reported by the flamegraph script.

Inspection of the generated file showed lines with just a frequency and no stacktrace.

Running without `-o collapsed -f ...` revealed that the framebuffer was undersized. Increasing its size fixed the problem.

Usability suggestions:

 - Render `<unknown>`, with a reason if known, as the stacktrace in the output format
 - Refer back tothe `-b` option in the `Troubleshooting` section of the README, describing what to do when `<unknown>` traces are reported
 - Perhaps explicitly mention to run `-o summary` as a troubleshooting step for people like me who dived straight into flamegraph generation.

**Comment by apangin** [comment]
Render `[frame_buffer_overflow]` in the output. Added a paragraph in troubleshooting section.
