### ISSUE TITLE
Track only longest operations with Java API

### ISSUE THREAD

**Issue by QIvan** [jvm-profiling-tools/async-profiler#480]
Hi! That might be a weird question, but it's kinda important when you investigate latency issues: 
is it possible to leave the traces only for the longest requests (like operations above some timeout)?

I was thinking about something like
```java
AsyncProfiler.getInstance().resume(Events.CPU, 100_000);
long startTime = System.nanoTime();
// do something
long duration =  System.nanoTime() - startTime;
AsyncProfiler.getInstance().execute("stop,file=" + file); 
```

and after that being able to do 
```java 
if (duration > timeout) {
    saveLastTrace();
}
```
or 
```java 
if (duration < timeout) {
    removeLastTrace();
}
```
But if you know another way to do so, I'd be more than glad to read it.

How do you investigate issues when 1 operation takes x100 more time than a regular one (for example database rebalancing)? 
Many thanks in advance!

**Comment by krzysztofslusarski** [comment]
I use async-profiler in such a case on a daily basis.

Main idea is that JFR format contains:
- thread id
- stacktrace
- timestamp
If you can trace in your app that one thread has processed operation for a long time then the JFR format contains all the information you need. For Apache Tomcat server such an information is in "access log". 

I you use 1.8.x line you can check my tool https://github.com/krzysztofslusarski/collapse-jfr for an inspiration.

**Comment by apangin** [comment]
Seems like there's nothing else to do about this issue.
