### ISSUE TITLE
Profiling object promotion rate to old generation

### ISSUE THREAD

**Issue by amirhadadi** [jvm-profiling-tools/async-profiler#484]
AsyncProfiler supports profiling allocation rate, giving a rate per class.
Would it be possible to add support for profiling the rate objects are being promoted to the old generation?
Obviously this would apply only to generational collectors.

**Comment by apangin** [comment]
Yes, it's possible, in a way similar to how survived objects are tracked in [this commit](https://github.com/jvm-profiling-tools/async-profiler/commit/42fd0308d972b2e9e774dedbe8b30d207d607713).
The function to trace will be different, depending on the selected garbage collector.
