### ISSUE TITLE
Accessing some features through the Java API

### ISSUE THREAD

**Issue by dmos62** [jvm-profiling-tools/async-profiler#489]
I'm wrapping async-profiler for use with Pyroscope through the Java API, namely the `one.profiler.AsyncProfiler` class ([current implementation](https://github.com/pyroscope-io/pyroscope-java/blob/main/agent/src/main/java/io/pyroscope/javaagent/Profiler.java)), and there are a few features that I'm not sure how to access: per-thread profiling (equivalent of the CLI `-t` option) and multiple-event profiling (e.g. `-e alloc,cpu`).

Could you shine some light on this? What are the steps required to extend `AsyncProfiler` to support that, broadly speaking?

**Comment by krzysztofslusarski** [comment]
In the original implementation: [AsyncProfiler.java](https://github.com/jvm-profiling-tools/async-profiler/blob/master/src/api/one/profiler/AsyncProfiler.java) there is an ```execute``` method that can do everything. See @apangin answer for #473.
