### ISSUE TITLE
std::map over profiler code

### ISSUE THREAD

**Issue by toktarev** [jvm-profiling-tools/async-profiler#492]
Hello Andrei.

Maybe this is not an issue, but analyzing the profiler's code I noticed that std::map is used almost everywhere.

Maybe std::unordered_map would be more efficient?

**Comment by apangin** [comment]
`std::unordered_map` requires newer version of libstdc++ than used by some customers.
For compatibility reasons, async-profiler links with a quite old version of libstdc++.

Performance does not suffer here. Where needed, async-profiler uses specialized maps.

**Comment by toktarev** [comment]
I see, thanks.
