### ISSUE TITLE
Async profiler unit tests

### ISSUE THREAD

**Issue by toktarev** [jvm-profiling-tools/async-profiler#493]
Hello Andrei.

Due to the active usage of the Async profiler, I had to download and walk through the C++ code.

May I ask (may be a dummy) question?

Do Async profiler have enough coverage by C++ unit tests (using gtest for example) ?

If you consider this question as unappropriate, please just close this issue (or I can close it)

**Comment by apangin** [comment]
This is a valid question, though I think it fits [Discussions](https://github.com/jvm-profiling-tools/async-profiler/discussions) format better.

So far the testing was mostly manual (besides a number of smoke tests on the basic functionality). However, I recently started improving automatic test coverage. The current work is in [test](https://github.com/jvm-profiling-tools/async-profiler/tree/test) branch. More tests will come soon.

**Comment by toktarev** [comment]
created https://github.com/jvm-profiling-tools/async-profiler/discussions/495
