### ISSUE TITLE
Signal safe allocation

### ISSUE THREAD

**Issue by toktarev** [jvm-profiling-tools/async-profiler#497]
I've found the following code:

```
    // mmap() is not guaranteed to be async signal safe, but in practice, it is.
    // There is no a reasonable alternative anyway.
    void* result = mmap(NULL, size, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
```

and thought about https://manpages.debian.org/testing/libatomic-ops-dev/libatomic-malloc.3.en.html.

Looks like this is a signal-safe allocation library (guaranteed).

And taking into account its internals it uses "mmap" only in cases of big chunk allocations.

From my experience mmap is quite a dangerous call that can affect OS page cache pollution and make allocation heavy
(sorry if I am not accurate here)

**Comment by apangin** [comment]
async-profiler already has [fast signal-safe allocator](https://github.com/jvm-profiling-tools/async-profiler/blob/master/src/linearAllocator.cpp), and it works perfectly for its use cases.

Using a non-stadard third-party barely known library with a non-compatible license is absolutely unacceptable. After all, the proposed library does not do anything better than async-profiler already does on its own.

Please, don't suggest to "fix" things that are not broken.

**Comment by toktarev** [comment]
Hmm, I didn't say this is a bug.

The issue was the kind of clarification.

You are right linearAllocator does the same as a proposed library (I just don't know codebase quire enough).
