### ISSUE TITLE
No access to perf events

### ISSUE THREAD

**Issue by toktarev** [jvm-profiling-tools/async-profiler#498]
Hello.

I use async-profiler using Java API.

After it's running I see the following error: 'No access to perf events. Try --fdtransfer or --all-user option or 'sysctl kernel.perf_event_paranoid=1'

I have no possibility to run sysctl kernel.perf_event_paranoid=1' because the server is not under my control.
So I want to pass the "--all-user" option.

However, I don't see such possibility in async profiler's Java API method "start";

```
    public void start(String event, long interval) throws IllegalStateException {
        if (event == null) {
            throw new NullPointerException();
        }
        start0(event, interval, true);
    }

```
But ше throws execution exactly on this call.

Is there any workaround here?

Thanks.

**Comment by apangin** [comment]
Use `AsyncProfiler.execute()`

See also #473, #489

**Comment by toktarev** [comment]
Just a little question.

Why don't you want to add arguments for the start method ?

**Comment by apangin** [comment]
Which arguments? All possible combinations of profiling options? I don't think it's a good solution to mirror all options on Java level, then keep maintaining them both in native and Java whenever they change, and risk to deal with API compatibility issues from release to release.

**Comment by toktarev** [comment]
At least only "boolean allUsers" flag.
Because it is really not so convenient to use "execute" instead of "start: just because of the problem with permission on server.

**Comment by toktarev** [comment]
`            try {
                asyncProfiler.start(Events.CPU, INTERVAL_CONSTANT);
            } catch (IllegalStateException e) {
                try {
                    asyncProfiler.execute("start,event=" + Events.CPU + ",allUser,interval=" + INTERVAL_CONSTANT);
                } catch (IOException ioException) {
                    throw new RuntimeException(ioException);
                }
            }
`

Is this valid API usage?

I am worried because "start0" method makes some actions before it actually finds out that 
"No access to perf events. Try --fdtransfer or --all-user option or 'sysctl kernel.perf_event_paranoid=1".

**Comment by toktarev** [comment]
Thanks.

**Comment by toktarev** [comment]
```
            try {
                final String standardParams = "event=" + Events.CPU + ",interval=" + INTERVAL_CONSTANT;
                String command = "start," + standardParams;

                if (!asyncProfiler.execute("check," + standardParams).startsWith("OK\n")) {
                    command = command + ",alluser";
                }

                asyncProfiler.execute(command);
            } catch (IOException ioException) {
                throw new RuntimeException(ioException);
            }
```

Maybe it would be useful for other users.

**Comment by toktarev** [comment]
```
            try {
                final String standardParams = "event=" + Events.CPU + ",interval=" + INTERVAL_CONSTANT;
                String command = "start," + standardParams;

                try {
                    asyncProfiler.execute("check," + standardParams);
                } catch (IllegalStateException ex) {
                    command = command + ",alluser";
                }

                asyncProfiler.execute(command);
            } catch (IOException ioException) {
                throw new RuntimeException(ioException);
            }

```


P.S.(from the generic user): I had to read C++ code to find out how the "check" command works.

**Comment by martin-g** [comment]
```java
} catch (IllegalStateException ex) {
    command = command + ",alluser";
    asyncProfiler.execute(command);     // I guess you want to execute second time only if the first one fails
}
```

**Comment by toktarev** [comment]
From what I understand 

```
                    asyncProfiler.execute("check," + standardParams);
```

does not start profiler.

So I just create a command and run 

```
                asyncProfiler.execute(command);
```
