### ISSUE TITLE
JVM Crashed with segfault and hs_err_pid

### ISSUE THREAD

**Issue by toktarev** [jvm-profiling-tools/async-profiler#501]
Stack: [0x00007f090f348000,0x00007f090f449000],  sp=0x00007f090f445320,  free space=1012k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0x1f5c1e]
V  [libjvm.so+0x58b4cf]  AsyncGetCallTrace+0x1cf
C  [profiler16367091390978467745864966299567.so+0x36a88]  Profiler::getJavaTraceAsync(void*, ASGCT_CallFrame*, int)+0xd8
C  [profiler16367091390978467745864966299567.so+0x37362]  Profiler::recordSample(void*, unsigned long long, int, Event*)+0xd2
C  [profiler16367091390978467745864966299567.so+0x33594]  PerfEvents::signalHandler(int, siginfo*, void*)+0x144
C  [libc.so.6+0x3f040]
C  [linux-vdso.so.1+0x982]  clock_gettime+0x32
C  [libc.so.6+0x130d36]  __clock_gettime+0x26
v  ~StubRoutines::call_stub
C  0x0000000668be5868

**Comment by krzysztofslusarski** [comment]
Can you attach full hs_err.log?

**Comment by toktarev** [comment]
Sure, trying to download it from server.

**Comment by toktarev** [comment]
Some internal cleaner deleted log from the remote node, so I can't download it.
Next run did not reproduce sefault.
Once it happens again I will try to down load full hs_err.log

**Comment by apangin** [comment]
What is the version of the Profiler, JDK, OS?
Profiler arguments, Java options?
Steps to reproduce the problem?

**Comment by toktarev** [comment]
Profiler: v2.5
OS: 5.4.0-1056-gcp #60~18.04.1-Ubuntu SMP Tue Oct 19 15:05:21 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
JDK: 1.8 (without debug symbols)

Profiler started with:
    final String standardParams = "event=" + Events.CPU + ",interval=" + 1_000_000;

Steps:
    Started JVM,
    Started profiler with parameters pointed above;
    Look into spark's driver log - there is 
    
`    `Exception message: /bin/bash: line 1:  3815 Aborted                 
/usr/lib/jvm/java-8-openjdk-amd64/jre//bin/java -server -Xmx17408m '-verbose:gc' '-XX:+PrintGCDetails' '-XX:+PrintGCTimeStamps' '-DprofilerOutput=/tmp/profile.log' -Djava.io.tmpdir=/hadoop/yarn/local/usercache/appcache/application_1634630611119_0596/container_e368_1634630611119_0596_01_000047/tmp '-Dspark.history.ui.port=18080' '-Dspark.driver.port=36183' -Dspark.yarn.app.
container.log.dir=/hadoop/yarn/logs/application_1634630611119_0596/container_e368_1634630611119_0596_01_000047 -XX:OnOutOfMemoryError='kill %p' org.apache.spark.executor.CoarseGrainedExecutorBackend --driver-url spark://Coars
eGrainedScheduler@gce-be-1.net:36183 --executor-id 46 --hostname cslave.internal --cores 5 --app-id application_1634630611119_0596 --user-class-path file:/hadoop/yarn/loca
l/usercache/appcache/application_1634630611119_0596/container_e368_1634630611119_0596_01_000047/__app__.jar --user-class-path file:/hadoop/yarn/local/usercache/appcache/application_1634630611119_0596/container_e
368_1634630611119_0596_01_000047/libs.jar > ``

**Comment by toktarev** [comment]
I see the following warnings:

[WARN] Install JVM debug symbols to improve profile accuracy
[WARN] Install JVM debug symbols to improve profile accuracy

**Comment by toktarev** [comment]
This is how we dump profiler's result

Put result to hdfs:

```
       private static final int TRACES_DEPTH = 100;
       
           @Override
    public void shutdown() {
       ....
        try (final FSDataOutputStream outputStream = fs.create(outputFilePath)) {
            final String profilerResult =
                    ProfilerInstance.getInstance().getAsyncProfiler().execute("traces=" + TRACES_DEPTH);
            outputStream.write(profilerResult.getBytes());
        }
        ....
     }

```

**Comment by toktarev** [comment]
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~18.04-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)

**Comment by toktarev** [comment]
Link to your so file:

https://file.re/2021/11/12/libasyncprofiler/

(will be deleted tomorrow)

**Comment by toktarev** [comment]
Was not able to reproduce again during many other executions at the same env.

Looks like Heisenbug.

**Comment by apangin** [comment]
What is "our so file"?
Please note that I do not provide support for async-profiler builds other than [official releases](https://github.com/jvm-profiling-tools/async-profiler/releases).

**Comment by toktarev** [comment]
No, I downloaded it from github.
And did not build it manually.

"our so file" means that I downloaded it from server where bug happened.

**Comment by toktarev** [comment]
As I see

C [linux-vdso.so.1+0x982] clock_gettime+0x32
C [libc.so.6+0x130d36] __clock_gettime+0x26

Where receive some signal caused by system timer, receive it fail.

Probably something internally is not signal safe (sorry if I say something wrong, I am not an Async Profiler expert).

**Comment by toktarev** [comment]
https://bugs.openjdk.java.net/browse/JDK-8153270

**Comment by apangin** [comment]
This is a JVM bug in `AsyncGetCallTrace` implementation. A quite rare one.
async-profiler has a workaround for it: `safemode=64` option. The downside of the workaround is that some Java stack traces will not be collected, i.e. you'll see more `[unknown_Java]` frames (usually around 1%, but may be less or more, depending on the application).

**Comment by toktarev** [comment]
Was that bug fixed in later versions of java (1.8) ?

**Comment by apangin** [comment]
I don't know. On one hand, I've never seen this problem in JDK 11 or newer. On the other hand, there were not much changes in AGCT code.

**Comment by toktarev** [comment]
Thanks !

**Comment by toktarev** [comment]
We can not just switch to java 11 (project is not j11- compatible).

But we could switch to the more fresh build of j8.

This is why I asked question in such manner.

**Comment by toktarev** [comment]
https://github.com/jvm-profiling-tools/async-profiler/issues/66

I saw these plans (from 2017).
And I noticed in C++ code that there is only one place .

Do you have plans to get rid of AsyncGetCallTrace from the project?

**Comment by apangin** [comment]
I do. No exact timeline though.

**Comment by toktarev** [comment]
Should we close the issue?

Or it might be useful in the active state?

**Comment by apangin** [comment]
- This is a JVM bugs;
- async-profiler has a workaround;
- the long-term plan is to get rid of the problematic call entirely.

Considering the above, I think there is nothing more to do in the context of this issue. Let me close it then.

**Comment by toktarev** [comment]
[hs_err_pid19491.log](https://github.com/jvm-profiling-tools/async-profiler/files/7554035/hs_err_pid19491.log)

Reproduced many times once I increased number of JVMs in cluster.

**Comment by apangin** [comment]
It's without `safemode`, right? Does `safemode=64` help?

If you have multiple crash reports, please attach them as well - I'll check if there is a specific pattern that leads to a problem.

**Comment by toktarev** [comment]
Yes, that was without safemode.

`safemode=64 ` looks like it halped.

**Comment by toktarev** [comment]
Yes, that was without safemode.

`safemode=64 ` looks like it halped.

**Comment by toktarev** [comment]
http://psy-lob-saw.blogspot.com/2016/06/the-pros-and-cons-of-agct.html

I've found this very interesting article.

`
AsyncGetCallTrace is NOT official JVM API
`

Looks like this is the main reason - why we catch bugs there.
