### ISSUE TITLE
java.lang.NegativeArraySizeException on AsyncProfiler.dumpCollapsed

### ISSUE THREAD

**Issue by tuxslayer** [jvm-profiling-tools/async-profiler#506]
I have got this exception in my dockered java instance

```
"java.lang.NegativeArraySizeException: -2093828439\
\	at one.profiler.AsyncProfiler.execute0(Native Method)\
...
```
on `AsyncProfiler.dumpCollapsed(SAMPLES)`

Java:
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment (build 17.0.1+12-39)
OpenJDK 64-Bit Server VM (build 17.0.1+12-39, mixed mode, sharing)

AsyncProfiler version 2.5 

Cannot reproduce it though.

**Comment by toktarev** [comment]
Does that make sense to catch this exception and rethrow it with a message like:

"Not enough memory for dump profiling results. Please use 'file=somefile.txt' option" ?

**Comment by tuxslayer** [comment]
Oh.. that makes sense, thank you :) 

>Does that make sense to catch this exception and rethrow it with a message like:

Well, if the profiler could do that - it would  for sure simplify troubleshooting for those who hit it in the future! :)

**Comment by toktarev** [comment]
> Does that make sense to catch this exception and rethrow it with a message like:

This is mostly question of usability (not some rocket since).

**Comment by apangin** [comment]
Fixed. Now profiler will throw a more meaningful exception if the output is too big.
