### ISSUE TITLE
GC log and profiler's output do not match

### ISSUE THREAD

**Issue by toktarev** [jvm-profiling-tools/async-profiler#510]
Hello, I see the following picture

My application worked  26 seconds.

This is full GC logs:

1.141: [GC (Metadata GC Threshold) [PSYoungGen: 1114640K->35370K(3421696K)] 1114640K->35394K(11242496K), 0.0162584 secs] [Times: user=0.08 sys=0.02, real=0.01 secs] 
1.157: [Full GC (Metadata GC Threshold) [PSYoungGen: 35370K->0K(3421696K)] [ParOldGen: 24K->34380K(7820800K)] 35394K->34380K(11242496K), [Metaspace: 20890K->20890K(1067008K)], 0.0350389 secs] [Times: user=0.24 sys=0.04, real=0.03 secs] 
2.592: [GC (Metadata GC Threshold) [PSYoungGen: 1182359K->45904K(3807232K)] 1216740K->80292K(11628032K), 0.0151422 secs] [Times: user=0.15 sys=0.01, real=0.01 secs] 
2.607: [Full GC (Metadata GC Threshold) [PSYoungGen: 45904K->0K(3807232K)] [ParOldGen: 34388K->66964K(8842752K)] 80292K->66964K(12649984K), [Metaspace: 34904K->34904K(1079296K)], 0.0692222 secs] [Times: user=0.64 sys=0.25, real=0.07 secs] 
[WARN] Install JVM debug symbols to improve profile accuracy
[WARN] Install JVM debug symbols to improve profile accuracy
7.582: [GC (Allocation Failure) [PSYoungGen: 3761152K->101985K(4689920K)] 3828116K->168973K(13532672K), 0.0453168 secs] [Times: user=0.61 sys=0.08, real=0.04 secs] 
11.859: [GC (Allocation Failure) [PSYoungGen: 4689505K->88584K(5664256K)] 4756493K->155580K(14507008K), 0.0151962 secs] [Times: user=0.16 sys=0.10, real=0.02 secs] 
24.473: [GC (Allocation Failure) [PSYoungGen: 5264392K->85427K(5664256K)] 5331388K->152431K(14507008K), 0.5884998 secs] [Times: user=9.13 sys=4.24, real=0.59 secs] 
Heap
 PSYoungGen      total 5664256K, used 2177494K [0x000000062ab00000, 0x0000000793100000, 0x00000007c0000000)
  eden space 5175808K, 40% used [0x000000062ab00000,0x00000006aa608ab0,0x0000000766980000)
  from space 488448K, 17% used [0x0000000766980000,0x000000076bcecec8,0x0000000784680000)
  to   space 120320K, 0% used [0x000000078bb80000,0x000000078bb80000,0x0000000793100000)
 ParOldGen       total 8842752K, used 67004K [0x0000000300000000, 0x000000051bb80000, 0x000000062ab00000)
  object space 8842752K, 0% used [0x0000000300000000,0x000000030416f078,0x000000051bb80000)
 Metaspace       used 56948K, capacity 58534K, committed 58624K, reserved 1099776K
  class space    used 7306K, capacity 7629K, committed 7680K, reserved 1048576K
![Image 25 11 2021 at 22 08](https://user-images.githubusercontent.com/4003874/143491768-52b5820f-0f2e-42b1-8782-c39a8dfa1549.jpg)

This is all GC logs from the logs.
as I see gc time from logs is not 54% of all time (from the flame graph).

**Comment by apangin** [comment]
The flame graph says nothing about GC.
The profiler expectedly warns about missing debug symbols.

**Comment by toktarev** [comment]
We were not able to turn on debugging symbols (due to organizational problems).

But what it can be besides GC ?

54% of execution time.

**Comment by apangin** [comment]
CompilerThread, VM Thread, Sweeper thread, Service Thread, or any other native VM thread.
You may want to use `threads` (`-t`) option.

**Comment by toktarev** [comment]
got it.
thanks.

BTW thanks to your profiler we found a bottleneck and the main reason for the performance problem.


Good product !!!

**Comment by apangin** [comment]
> We were not able to turn on debugging symbols

I'd recommends using a JDK that has all necessary symbols out of the box, e.g. Liberica JDK, Azul Zulu, or [others](https://jdk.dev/download/)

**Comment by toktarev** [comment]
I can't just install JDK


It can be done only via the technical department.

They can't change current JVM due to some prolicies.
