### ISSUE TITLE
Enhancement : Controlling the agent through a basic HTTP API

### ISSUE THREAD

**Issue by UnasZole** [jvm-profiling-tools/async-profiler#512]
**General description**

It would be very helpful to be able to control the agent via a minimalistic HTTP API, and not just the shell script.

It would work like this :
- You would attach the profiler at startup with ``-agentpath:libasyncProfiler.so=httpport=8080``
- The agent would listen on port 8080 for requests like GET http://localhost:8080/profiler/_arguments_
- When you call the stop/dump commands, you actually download the file in response to your GET instead of storing it locally.

**Motivation**

In my case, to ease working with kubernetes deployments - though I'm sure it could be useful to other people.

Basically, to profile an application in a kubernetes cluster, currently I need to : 
- SSH to the proper container
- Call the shell script start command
- Call the script dump command passing a -f option
- Then find a way to send the file back to my host to work on it (ssh, or just putting a file on a host volume, or whatever)

It's not practical at all to automate. Having all these operations accessible through an HTTP service would be a lot simpler.

**Technical design proposal**

If we want to avoid the maintenance cost of designing a specific API, we could just reuse the same format already used in arguments.cpp

Basically : 
- To the profiler arguments, just add an "httpport=xxxx" command, that starts this HTTP server listening on the given port.
- This server listens for requests with an HTTP query of the format "profiler/_agent argument string_", and for each
  -  parses the argument string with Arguments::parse (after urldecoding obviously)
  - If "file" attribute is present and has the special value "-", then create a temporary file name in the $TEMP folder, and substitute the dash with this new file name in the file attribute
  - Process these updated Arguments in the usual fashion
  - Once execution of the command is complete, if it's a "dump" or "stop" command and it was working on a temporary file created above, send the file in the HTTP response body (and clean it from the temp folder once response is sent).

**Comment by apangin** [comment]
I think I already answered this in #496

**Comment by toktarev** [comment]
It is always possible to run an HTTP server on your side and change the profiler's state using the profiler's java API receiving your custom commands.

**Comment by UnasZole** [comment]
@apangin Thanks, I had not seen this ticket.
You make a fair point of course - nevertherless, I feel the need to argue my case ;-)

@toktarev , I understand that, but in my use cases, it breaks an important concept, which make it painful to integrate. Perfectly possible for sure, but more painful than it should be.

When working with containerised environment, the general idea is "one process = one container". So, starting another process (a separate HTTP server) aside from the main server I'm trying to monitor kind of breaks this design.
To set it up, I have to add override the startup command of the docker image to have a shell script acting as parent of both processes. Possible, but not too clean.

Agents exposing a remote control port internally are a lot easier to integrate, as they allow using the very same docker image whether you enable the agent or not. (mount the agent in a volume, update an environment variable to set jvm startup options with -agentpath and expose the agent port)
 

That being said, I understand @apangin 's point about this being a low-level tool.
It really depends on how you consider this project :-) 
- If you intend for it to be an agent "ready for use", I do believe that remote control in the agent itself is a very valuable feature, which most agents I've used tend to deliver.
- If you consider the "agent" feature as a bonus, but your real intent is to provide a library around which other agents may be built (like elastic-apm, I've seen), then it makes sense not to include any extra functionality in the agent itself. :-)

**Comment by toktarev** [comment]
----So, starting another process (a separate HTTP server

You can start an HTTP server inside you process (as embedded one)

**Comment by apangin** [comment]
Added a simple embedded HTTP server for controlling async-profiler agent.

#### Starting server

Use `server=address` option where `address` is `port` or `ip:port`, e.g.
```
-agentlib:asyncProfiler=server=8080
-agentlib:asyncProfiler=server=127.0.0.1:8080
```

#### Executing profiler commands

```
GET /command?arg&arg    # classic URL format
GET /command,arg,arg    # raw profiler command
```

e.g.
```
curl 'http://localhost:8080/start?event=cycles&interval=5ms'
curl http://localhost:8080/start,event=cycles,interval=5ms
curl http://localhost:8080/status
curl http://localhost:8080/version=full
curl http://localhost:8080/stop
curl http://localhost:8080/dump?flamegraph       # send output to HTTP stream
curl http://localhost:8080/dump?file=out.html    # send output to a file
```

#### Warning

The server is not secure and not error-prone. Start it only in a trusted network and never expose profiler HTTP interface publicly.

**Comment by UnasZole** [comment]
Thanks a lot for that delivery !

Given your previous answer, I thought you didn't intend to deliver it, and I had actually started working with the elastic-apm agent which uses yours as a library, and works fine - but it requires a much heavier setup (as it needs to push data to an elasticsearch cluster, etc.).
I'll definitely have a look at using your agent again : with this feature, it might just be the lightweight solution that fits my need :-)
