### ISSUE TITLE
java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;

### ISSUE THREAD

**Issue by toktarev** [jvm-profiling-tools/async-profiler#516]
Hello Andrei.

I don't know if this is a bug of profiler or this is our internal problem.

Anyway, I created this issue because it might be interesting for people.

java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
	at one.jfr.JfrReader.<init>(JfrReader.java:77)
	at one.profiler.converter.jfr2flame.main(jfr2flame.java:210)
...	
       at org.apache.spark.executor.Executor$$anonfun$stop$1$$anonfun$apply$mcV$sp$1.apply(Executor.scala:250)
	at org.apache.spark.executor.Executor$$anonfun$stop$1$$anonfun$apply$mcV$sp$1.apply(Executor.scala:248)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)

**Comment by apangin** [comment]
This is not `JfrReader` from the [official release](https://github.com/jvm-profiling-tools/async-profiler/releases). Looks like the problem of your build.

**Comment by toktarev** [comment]
We tried converter.jar from the release and encountered the same error.

**Comment by apangin** [comment]
> We tried converter.jar from the release and encountered the same error.

This can't be true. `JfrReader` from `converter.jar` refers to the method
```
     162: invokevirtual #33                 // Method java/nio/ByteBuffer.flip:()Ljava/nio/Buffer;
```
not
```
java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
```

**Comment by toktarev** [comment]
Hmm, I don't have any reason to write some false here.
Colleagues downloaded the converter.jar and got that error in the trivial example.

We don't have too much time to make some hacks or special versions of the profiler to generate bugs.

Anyway, thanks for your help.

**Comment by tmancill** [comment]
Hi @toktarev .  I recall running into this issue (generally, not with async-profiler) when first migrating from JDK 8 to JDK 9+ for builds and still using Java 8 as a runtime.  Perhaps that applies to your situation?  There is more information about the underlying issue and potential workarounds here:  https://stackoverflow.com/questions/61267495/exception-in-thread-main-java-lang-nosuchmethoderror-java-nio-bytebuffer-flip

**Comment by toktarev** [comment]
@tmancill, thanks.

I'll check.

**Comment by toktarev** [comment]
I wouldn't create this issue but we

1) Build all classes (using original code) with java 8.
2) Run our application under java 8.

Looks like something tricky here.

**Comment by toktarev** [comment]
The problem was on our side, we made a build with java 11.

No problems with profiler.
