### ISSUE TITLE
Lower method is not Thread.run

### ISSUE THREAD

**Issue by toktarev** [jvm-profiling-tools/async-profiler#525]
![image](https://user-images.githubusercontent.com/4003874/147373255-5681a7b7-26d5-443c-90c2-2d4a0b56a4e5.png)

Is it really bug ?

I expect that the lower method is always Thread.run for java stacks

**Comment by Jongy** [comment]
I'm no Java expert so IDK if it's possible to have a thread based at something else from `Thread.run`. Another issue that I suspect that could happen here, is that you have reached the maximum stack depth. What is the stack depth here?

From a quick look in the source, async-profiler has a limit on the number of stack items retrieved from `AsyncGetCallTrace`. By default it is set to `2048`, and you can control it with the `-j` parameter to `profiler.sh`.

**Comment by toktarev** [comment]
I have big doubts that spark reached 2048 limit at BlockManager#putIterator call

I also have a corresponding jfr file.

However ever I can't provide JFR files to the public access (probably I can send it privately)

**Comment by Jongy** [comment]
I'm not acquainted with that specific API; You could just look in that graph - if the stack depth (until the point it is allegedly cut off) is not 2048, then the maximum depth is not the problem.

**Comment by toktarev** [comment]
I see about 40 items from BlockManager.....#apply

Up to the highest point.

**Comment by toktarev** [comment]
![image](https://user-images.githubusercontent.com/4003874/147389310-07825581-8b89-480f-8bea-5c9f5fabfe26.png)

On the top

**Comment by toktarev** [comment]
I don't insist that this is bug and it does not block me.

I posted it for the Async Profiler quality improvements.

If Andrei consider it as not bug - feel free to close it.

If this is important  I am ready to help here as I can.

**Comment by apangin** [comment]
It's definitely possible to have methods other than `Thread.run` on the bottom of the stack (e.g. any method can be invoked via JNI), but that's probably not your case.

If this is a bug - then this is a JVM bug; async-profiler does not truncate Java stack traces on its own, except for `jstackdepth` limit. I know at least one JVM issue, [JDK-8153167](https://bugs.openjdk.java.net/browse/JDK-8153167), which results in truncated Java stack traces.

If you create an isolated test case that consistently reproduces the isssue, I'll see if async-profiler can workaround it somehow, and/or submit another JDK issue.

**Comment by toktarev** [comment]
We obtained this flame graph using JFR -> FG converter.

Maybe this is just some bug in the converter?

I will try to write an isolated test but I suspect that it will be very hard.

We have 800 JVMs in cluster and I see this problem only on some of them in rare cases.

Plus it will be difficult to reproduce remote spark's nodes execution locally.

**Comment by toktarev** [comment]
![image](https://user-images.githubusercontent.com/4003874/147392128-06afb888-3954-4c7b-bbf7-81becdad2cbd.png)


Whole bottom

**Comment by apangin** [comment]
> We obtained this flame graph using JFR -> FG converter.
> 
> Maybe this is just some bug in the converter?

You can veirfy this by opening `jfr` file directly in JMC, or by printing it with `jfr print`. However, I suppose it is a stack walking issue in the JVM. I you run the original Flight Recorder, you'll probably see truncated stack traces as well.

**Comment by toktarev** [comment]
ok, I will try

**Comment by toktarev** [comment]
Tried to open JMC but see another bug:

https://stackoverflow.com/questions/48400346/java-mission-control-from-jdk-1-8-0-161-frozen-upon-startup-on-mac-os-x.

Day of bugs.

**Comment by toktarev** [comment]
BTW: I've checked the Flight Recorder java feature.

Looks like I can collect traces using the embedded java feature.

As a result, I wonder why people use Async Profiler instead of Flight Recorder? Some advantages?

Flight recorder does not avoid the safepoint bias problem?

**Comment by krzysztofslusarski** [comment]
Here is one example: https://youtu.be/H6glyrKQlg8?t=678

Watch the whole series and you understand why Async-profiler is better.

https://www.youtube.com/watch?v=H6glyrKQlg8
https://www.youtube.com/watch?v=WnRngFMBe7w
https://www.youtube.com/watch?v=bTDmpwhwy3E

**Comment by toktarev** [comment]
@krzysztofslusarski thanks

**Comment by apangin** [comment]
@toktarev Please avoid off-topic comments, GitHub Issues is not a chat. I mean, you don't need to notify us about your progress on launching JMC, etc.
The comparsion between async-profiler and Flight Recorder is a good question, but is also off-topic here - I suggest starting a separate discussion.

**Comment by toktarev** [comment]
I deleted all off-top.

**Comment by toktarev** [comment]
![image](https://user-images.githubusercontent.com/4003874/147417752-f6956d1b-d8b2-424f-b9c4-0aa56210f19a.png)

From JFR.

I think we can suspend this issue ( or close it).

I am very busy in my current work writing some special tests to reproduce such rare and difficult cases.

**Comment by toktarev** [comment]
+2 coins

The bottom call is 

```org/apache/spark/storage/BlockManager$$anonfun$doPutIterator$1$$anonfun$apply$10.apply```

I've analyzed Apache Spark code and found out that  BlockManager```doPutIterator``` 
is private method can be invoked from 2 other methods

```def getOrElseUpdate```
and
```def putIterator```

I don't see $$anonFunc$$ (or some Scala anonymous functions) among them.

**Comment by toktarev** [comment]
![image](https://user-images.githubusercontent.com/4003874/147419595-18c102f7-1228-4876-94ca-503dfff946b8.png)


This is the correct stack from other JVM nodes.

**Comment by toktarev** [comment]
Closed because it might be a problem with a graphical adapter which shows a wrong flame graph.
