### ISSUE TITLE
how to work with profiler.sh --loop  

### ISSUE THREAD

**Issue by weijia8675309** [jvm-profiling-tools/async-profiler#527]
./profiler.sh --loop 1h -f /var/log/profile-%t.jfr ${pid}
it is not work.

**Comment by apangin** [comment]
What profiler version do you use? Have you built it yourself?
Please note that `--loop` feature is available only in the master development branch; the published release doesn't include it yet.
You may try the following pre-release version: https://profiler.tools/builds/async-profiler-2.5.1-race-linux-x64.tar.gz

**Comment by apangin** [comment]
async-profiler v2.6 has been [released](https://github.com/jvm-profiling-tools/async-profiler/releases/tag/v2.6).
`--loop` should work there.
