### ISSUE TITLE
Support to default colorize a pattern grouping of flame graph items

### ISSUE THREAD

**Issue by rmarsch** [jvm-profiling-tools/async-profiler#535]
It's often the case that seeing the difference between user code (often your application code is all under a shared package) and non-user code quickly in a flame graph has value. The search function does let users manually do this, however it's likely nice to be able to search for other things while still having this basic distinction.

Also in a larger automated operation of generating flame graphs as part of tooling, it can be nice to pre-search a relevant pattern for users, such as having application lines versus 3rd party java lines as mentioned above.

**Comment by apangin** [comment]
Added `--highlight` option to the FlameGraph converter to automatically search and highlight frames matching the given RegExp. This reuses the search mechanics and the corresponding purple color.

At this point, there a no plans to add different frame types / colors for highlighting. If this is to be implemented in future, there should be some general way to provide a custom palette.
