### ISSUE TITLE
--loop option gives `collect: unexpected operator` error

### ISSUE THREAD

**Issue by charlesverdad** [jvm-profiling-tools/async-profiler#548]
From the latest release (v2.6) I've been getting the following error message: `./profiler.sh: 228: [: collect: unexpected operator`

```
charles@ubuntu-vbox:~/conprof/async-profiler$ ./profiler.sh --loop 10s -f /tmp/profiles/4/profile-%t.jfr 11117
./profiler.sh: 228: [: collect: unexpected operator
Profiling for 60 seconds
Done
```

The script still runs but it seems to just use the default duration and ignore the `--loop` parameter. I expect it to run every 10s infinitely and so produce multiple profiles of 10s chunks. But in this case it just exits after the first 60s.

Java Version

```
charles@ubuntu-vbox:~/conprof/async-profiler$ java --version
openjdk 11.0.13 2021-10-19
OpenJDK Runtime Environment (build 11.0.13+8-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.13+8-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
```

**Comment by apangin** [comment]
There was a typo in the script, now fixed.
Thanks for the notice.

**Comment by charlesverdad** [comment]
It works now! Thanks for the quick fix 😄
