### ISSUE TITLE
Support max number of profile files output in `-loop` feature

### ISSUE THREAD

**Issue by charlesverdad** [jvm-profiling-tools/async-profiler#549]
I've become a fan of the new `-loop` mode feature for continuous profiling. However I am worried that it will continue writing profiles until the disk runs out.

It would be great if we have a feature that lets us keep at most N number of profiles, and once we've reached that the profiler will overwrite the oldest file.

Implementation wise, I imagine that simplest way is to introduce a new filename template `%c` which can be used with the filename flag `-f /path/to/profile-%c.jfr` and what it does is keeps a count (i.e. from 0-9, and then back to 0). So the output filename will be `profile-0.jfr`, `profile-1.jfr` ... all the way to `profile-9.jfr` and then go back and overwrite `profile-0.jfr`. This is similar to log-rotate naming.

This way I don't have to worry about disk running out of space. At the same time if I use `-loop=60m` I can retain up to 10 hours of profiling data but only download the one I am interested in.

**Comment by apangin** [comment]
It's an interesting idea. I'd only add the possibility to control the maximum number of files, either directly in the filename pattern (e.g. `profile-%10c`) or with a separate option: `--maxfiles 10`

**Comment by rohanag12** [comment]
I am interested in having this capability as well. My use case is that I want to continuously profile some applications running in k8s, where I have limited disk space. Would you be willing to accept a PR that adds this functionality?

**Comment by apangin** [comment]
Added `%n` pattern, which is expanded to a sequence number.
It can be optionally followed by `{max}`.

Examples:

`profile-%n.jfr` is expanded to `profile-0.jfr`, `profile-1.jfr`, ..., `profile-999999.jfr`;

`p%n{4}.jfr` is expanded to `p0.jfr`, `p1.jfr`, `p2.jfr`, `p3.jfr`, `p0.jfr`, `p1.jfr`, ...
