### ISSUE TITLE
Is it possible to use async-profiler with Graal Native Image compiled app?

### ISSUE THREAD

**Issue by franz1981** [jvm-profiling-tools/async-profiler#560]
I didn't yet investigated on this, but if the answer is not: it looks possible?

**Comment by franz1981** [comment]
Thanks @petrbouda I was hoping that given dwarf call stack walking is now implemented and assuming a meaningful collected fp it was still possible (with some tweaks ie treating the profiled app as a non Java application)

**Comment by apangin** [comment]
async-profiler works in the context of a target Java process. It uses Dynamic Attach to load the agent in runtime or `-agentpath` to start it alongside with the JVM. Graal native image supports neither `-agentpath` nor dynamic attach.
Even if I manage to somehow load async-profiler in a Graal native process, it won't benefit from Java specifics. This will look like a regular native process, so async-profiler won't give you much more comparing to what perf already does.

**Comment by SergejIsbrecht** [comment]
@franz1981 ,

you do not need async-profiler for profiling native-images. Just enable the FP or use Dwarf-Debug-Symbols and use perf (e.g. -call-graph dwarf) to sample thread stacks. I tried it already and last  time I check it worked as expected.

(premise you are on linux)

https://gist.github.com/SergejIsbrecht/f0d89d4af7fe341ad2096c9da88c8b3b
