### ISSUE TITLE
Not able to generate profiling output as file format 

### ISSUE THREAD

**Issue by shhrohan** [jvm-profiling-tools/async-profiler#565]
running on below linux version.
`NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.9 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.9:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"
`
jps output:

`[root@N4TDCL-AINA4810 read_user]# jps
109361 rule-engine-0.0.1-SNAPSHOT.jar
109844 admin-0.0.1-SNAPSHOT.jar
99003 Jps
`

profiling command and its output:

`[root@N4TDCL-AINA4810 async-profiler-2.7-linux-x64]# ./profiler.sh start -f flame.html 109361
[root@N4TDCL-AINA4810 async-profiler-2.7-linux-x64]# ./profiler.sh status 109361
Profiling is running for 10 seconds
[root@N4TDCL-AINA4810 async-profiler-2.7-linux-x64]# ./profiler.sh list 109361
Basic events:
  cpu
  alloc
  lock
  wall
  itimer
Java method calls:
  ClassName.methodName
Perf events:
  page-faults
  context-switches
  cycles
  instructions
  cache-references
  cache-misses
  branch-instructions
  branch-misses
  bus-cycles
  L1-dcache-load-misses
  LLC-load-misses
  dTLB-load-misses
  rNNN
  pmu/event-descriptor/
  mem:breakpoint
  trace:tracepoint
  kprobe:func
  uprobe:path
`

stop command output : 
`[root@N4TDCL-AINA4810 async-profiler-2.7-linux-x64]# ./profiler.sh stop 109361
--- Execution profile ---
Total samples       : 17
....
....
....
....
...
           ns         percent    samples  top
    ----------    -------    -------     ---
    30785104    17.78%        3           finish_task_switch_[k]
    30030660   17.35%        3           OtherRegionsTable::occupied() const
    20559634   11.88%        2           __pthread_cond_timedwait
    20526488   11.86%        2           system_call_after_swapgs_[k]
    20044169    11.58%        2           G1YoungRemSetSamplingClosure::do_heap_region(HeapRegion*)
    10324674     5.96%         1           [vdso]
    10291796     5.95%         1            java.util.concurrent.locks.AbstractQueuedSynchronizer.release
    10286137     5.94%         1            WatcherThread::sleep() const
    10244251     5.92%         1            jdk.jfr.internal.RequestEngine$RequestHook.execute
    10017979     5.79%          1           Monitor::ILock(Thread*)` 

but i don't see any flame.html file being created anywhere in the current directory.

the profiler version i am using is this : 

> https://github.com/jvm-profiling-tools/async-profiler/releases/download/v2.7/async-profiler-2.7-linux-x64.tar.gz

- other 2 linux distro versions i tried as well. but profiler was not getting attached using them.

**Comment by apangin** [comment]
`-f` option generally applies to `stop` and `dump` commands, not `start`.

For example, you can start profiler once, and then run `stop -f <filename>` multiple times to output the results of the same profiling session in different formats or with different options.

The only exception is `jfr` output format, which requires a filename with the `start` command. That's because `jfr` is written incrementally during the profiling session; other output formats are generated in the end of the profiling session.

**Comment by shhrohan** [comment]
![mac — -zsh — 165×52_2022-03-15_10-08](https://user-images.githubusercontent.com/3836159/158307558-c5c3769a-f552-40ef-a770-e5a2d11376f6.png)

**Comment by shhrohan** [comment]
@apangin 
Solved it.  this worked.
`./profiler.sh stop -f /tmp/flame.html 40875`
curious to know why is mandatory to set output file location only in /tmp folder ? this is not the case with mac.

**Comment by martin-g** [comment]
It doesn't need to be in `/tmp` but it has to be in a writeable directory by the user running the JVM process.
`profiler.sh` just sends commands to the JVM process, so it does not matter that you execute it with `root`.

**Comment by shhrohan** [comment]
understood. thanks
