### ISSUE TITLE
Async-profiler 2.7 doesn't show java frames for OpenJ9-jdk 11 and 17

### ISSUE THREAD

**Issue by KirillTim** [jvm-profiling-tools/async-profiler#569]
STR:
1) download OpenJ9 from https://adoptopenjdk.net/installation.html and export
```
/Users/kirill.timofeev/Library/Java/JavaVirtualMachines/openj9-11.0.14.1+1/Contents/Home/bin/java -version
openjdk version "11.0.14.1" 2022-02-08
IBM Semeru Runtime Open Edition 11.0.14.1 (build 11.0.14.1+1)
Eclipse OpenJ9 VM 11.0.14.1 (build openj9-0.30.1, JRE 11 Mac OS X amd64-64-Bit Compressed References 20220209_310 (JIT enabled, AOT enabled)
OpenJ9   - 9dccbe076
OMR      - 56c3376ba
JCL      - 5c423dacd0 based on jdk-11.0.14.1+1)
```
UPD: the same thing happens for
```
openjdk version "17.0.2" 2022-01-18
IBM Semeru Runtime Open Edition 17.0.2.0 (build 17.0.2+8)
Eclipse OpenJ9 VM 17.0.2.0 (build openj9-0.30.0, JRE 17 Mac OS X amd64-64-Bit Compressed References 20220127_94 (JIT enabled, AOT enabled)
OpenJ9   - 9dccbe076
OMR      - dac962a28
JCL      - 64cd399ca28 based on jdk-17.0.2+8)
```
downloaded from: https://developer.ibm.com/languages/java/semeru-runtimes/downloads

2) download the latest async-profiler-2.7 release
3) add simple `JavaMain.java` file:
```
public class JavaMain {
    public static void main(String[] args) {
        System.out.println("JavaMain.main()");
        String result = doWork(40_000);
        System.out.println(result.length());
    }

    private static String doWork(int count) {
        String result = "";
        for (int i = 0; i < count; i++) {
            result += String.valueOf(i * i);
        }
        return result;
    }
}
```
4) Run `JavaMain.class` with profiler agent:
`/Users/kirill.timofeev/Library/Java/JavaVirtualMachines/openj9-11.0.14.1+1/Contents/Home/bin/java -agentpath:/Users/kirill.timofeev/Work/async-profiler/build/libasyncProfiler.so=start,jfr,event=cpu,interval=1ms,file=/Users/kirill.timofeev/IdeaProfilerSnapshots/JavaMain_openj9_11.jfr JavaMain`
5) Wait the program to finish:
```
Profiling started
JavaMain.main()
353751
```
6) open the dump `JavaMain_openj9_11.jfr`

**Expected result** (from coretto 17):
<img width="1366" alt="Screenshot 2022-03-25 at 21 46 30" src="https://user-images.githubusercontent.com/7231087/160182970-73f05093-eb73-418a-a0c3-d01ea96f38b5.png">

**Actual result:**
<img width="1381" alt="Screenshot 2022-03-25 at 21 46 38" src="https://user-images.githubusercontent.com/7231087/160183033-939e4465-7e30-4704-a46e-180256d99fdb.png">

**Comment by apangin** [comment]
Async-profiler supports OpenJ9 only on Linux/x64 so far.
The support for other platforms will be added later.

**Comment by KirillTim** [comment]
Ah, I see
Thanks

**Comment by apangin** [comment]
Just checked - OpenJ9 profiling also works on Linux/ARM64.

macOS is a different story. Unfortunately, Semeru Runtime 17.0.2.0 does not yet support AsyncGetCallTrace. When it does - async-profiler should work automatically. There is no access to perf_events on macOS, so my trick to profile without AsyncGetCallTrace does not apply here.

In the meantime, it's possible to use `itimer` and `wall` modes. However, `itimer` profile is skewed on macOS - it's highly biased towards syscalls. `wall` works file, but shows only Java stacks.
