### ISSUE TITLE
Profiling (deleted) libjvms

### ISSUE THREAD

**Issue by Jongy** [jvm-profiling-tools/async-profiler#572]
https://github.com/jvm-profiling-tools/async-profiler/commit/3456dd3d9040ede77fb0350cba8b63cd1fc3c5e2 has changed the way we hook onto loading of new native libraries, I'm not sure what was the motive though.

The new method requires the libjvm.so file to be present on disk, so it will fail otherwise (in case it was deleted). Also, it won't work well if the file has changed, i.e Java was upgraded (but it won't identify the file anyway because the entry would be marked as `(deleted)`).

I searched a bit online but couldn't find a way to find the GOT offsets for an already-loaded file (without reading the file). I do suppose that it is possible to achieve, but might not be generic across libcs.

@apangin , how do you think we can maintain that support? Possibly by falling back to the old method if we could not find the GOT?

**Comment by apangin** [comment]
Hi @Jongy,
The problem is understood, and I have a solution that I'll commit shortly.
The idea is to parse Dynamic Section found in ELF Program Header table (which remains loaded in the process address space even after deletion of .so).

**Comment by apangin** [comment]
I committed the fix. It should work now.

**Comment by Jongy** [comment]
Great, thanks @apangin ! I can confirm that master as of 9838ddb693e4f46c782f5ef9a93a26b83fbc9092 works as expected. Closing this.

**Comment by apangin** [comment]
Unfortunately, the fix is incomplete. It does not work on some JDKs.
I keep investigating this; will let you know once it's fixed.

**Comment by apangin** [comment]
Should be fixed now. Please check once again and close the issue if everything is OK.

**Comment by Jongy** [comment]
@apangin I confirmed again that it works (master as of 60ce15569a3860fb7db105dd3b5cdffc950848da)
I tested on:
```
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2~bpo8+1-b14)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)
```
