### ISSUE TITLE
Symbols on released SO files?

### ISSUE THREAD

**Issue by imply-cheddar** [jvm-profiling-tools/async-profiler#580]
I'm trying to convert the addresses on an err to lines and not succeeding.  `atos` on my Mac is complaining about not having symbols.  I am not an expert when it comes to native stuff, so it's entirely possible that I just have no clue what I'm doing, in that case, please educate.  But, when I download the x64 release bundle and run

```
% atos -o ~/Downloads/async-profiler-2.7-linux-x64/build/libasyncProfiler.so          
atos cannot load symbols for the file /Users/useruser/Downloads/async-profiler-2.7-linux-x64/build/libasyncProfiler.so for architecture x86_64.
``` 

I tried to see if there was some other file that might have the symbols included, but nothing jumped out at me from the release bundle.  Please educate and/or add the symbols to the files in the releases?

**Comment by apangin** [comment]
`libasyncProfiler.so` has symbols embedded in `.symtab` section; `objdump` and `gdb` show them correctly on Linux.  
Can't tell about `atos` though.
