### ISSUE TITLE
Absurd cpu performance for GC using "./profiler.sh -e itimer -i 5ms -d 120 -f output.html"

### ISSUE THREAD

**Issue by cassecou** [jvm-profiling-tools/async-profiler#581]
Hi, 
I'm using **./profiler.sh -e itimer -i 5ms -d 120 -f output.html**  to get CPU performance for different GCs and java versions.
And I'm getting the following numbers which seem erroneous. Can you please recommend what will be the correct way to measure GC performance?

> CPU (in %)    |   Java 8   |  Java 11     |   Java 17

> G1GC             |   35.32% |    0.67%    |    0.39%

> Shenandoah |  60.80% |   33.96%   |  37.95%

> ZGC               |        NA   |   63.33%  |   44.99%

**Comment by apangin** [comment]
The command is fine (except that `-e cpu` is preferred to `-e itimer` when available).

How does the profile look like, and where did you see those numbers? Depending on the application and JVM options, GC may indeed have a huge CPU overhead. So the profiling results may indicate the real issue. However, I can't say how plausible these numbers are without seeing the profile, JVM options, and GC logs.

**Comment by apangin** [comment]
> Can you please recommend what will be the correct way to measure GC performance?

Depends on what you mean by GC performance. It's not just a single number. Async-profiler likely shows the CPU overhead, but there are a lot more GC performance characteristics: application throughput, distribution of pause times, min/max/avg heap usage, memory overhead, etc.

**Comment by cassecou** [comment]
The results are for same experiment, so it doesn't make sense for results to go this awry. Sharing the results for above command for G1GC in java 8, 11 and 17. I can share for other combinations as well if you want.
<img width="1659" alt="g1gc-java8" src="https://user-images.githubusercontent.com/9259878/163808403-16d9b416-41ce-465a-bccc-5a6d4b1d8691.png">
<img width="1659" alt="g1gc-java11" src="https://user-images.githubusercontent.com/9259878/163808474-12719836-81ea-49e9-acb1-f9cfa8f4c304.png">
<img width="1659" alt="g1gc-java17" src="https://user-images.githubusercontent.com/9259878/163808496-5c6c0f68-2596-4de0-9049-6ba86b68ad1a.png">

**Comment by krzysztofslusarski** [comment]
For G1 at JDK8 you have no adaptive start of concurrent mark, it was introduced in JDK9 with https://bugs.openjdk.java.net/browse/JDK-8199262. In JDK8 it is pretty easy to reach a state where concurrent phase runs all the time.
