### ISSUE TITLE
CPU profiling of bound calls to MethodHandles

### ISSUE THREAD

**Issue by lachlan-roberts** [jvm-profiling-tools/async-profiler#588]
Binding to a `MethodHandle` causes separate spikes on the flamegraph each time to invoke the same method.

Here is a sample project which demonstrates this:
https://github.com/lachlan-roberts/MethodHandlesExample/blob/a97ac723c9730a2d57fb0e142d9b98ba08eb7b57/src/test/java/test/MethodHandleExample.java

After profiling this with `BIND_METHOD_HANDLE = true` I see hundreds of spikes on the flame graph all containing `Endpoint.onOpen(byte[])`. Each of these spikes has a different `LambdaForm$MH.0x0000000800c01800.invoke_MT` in the stacktrace.
![methodHandles](https://user-images.githubusercontent.com/19250643/167790932-d273757d-b5d1-42c8-a151-aa2cd7e29230.png)

Is it expected that this should result in multiple spikes on the flamegraph when it is invoking the same method just on a different instance of this `Endpoint` class?

**Comment by apangin** [comment]
`methodHandle.bindTo` creates a new MethodHandle each time. LambdaForms cannot be reused due to different receivers. Looks logical to me.
