### ISSUE TITLE
Native libjvm.so frames from GC missing

### ISSUE THREAD

**Issue by dreis2211** [jvm-profiling-tools/async-profiler#589]
Hi,

I unfortunately can't share much, but we noticed that one of our servers doesn't show any activity in native libjvm.so frames anymore, although there is other proof of GC activity for example where usually a big block of GC (or generally libjvm.so stuff) is happening.

We only see this tiny section in the flamegraphs
<img width="1676" alt="image" src="https://user-images.githubusercontent.com/6304496/168614442-0d570ed1-bda3-4617-b3e4-f5d5db8a4adb.png">

While `jstat` for example shows this:
```
  S0     S1     E      O      M     CCS    YGC     YGCT    FGC    FGCT    CGC    CGCT     GCT
  0,00 100,00  84,48  68,98  95,47  84,48  49139  683,260     0    0,000 18614  334,925 1018,184
  0,00 100,00  85,43  68,98  95,47  84,48  49139  683,260     0    0,000 18614  334,925 1018,184
  0,00 100,00  86,81  68,98  95,47  84,48  49139  683,260     0    0,000 18614  334,925 1018,184
  0,00 100,00  88,02  68,98  95,47  84,48  49139  683,260     0    0,000 18614  334,925 1018,184
  0,00 100,00  91,38  69,44  95,47  84,48  49139  683,260     0    0,000 18614  334,925 1018,184
  0,00 100,00  95,17  69,44  95,47  84,48  49140  683,260     0    0,000 18614  334,925 1018,184
  0,00 100,00   2,65  70,16  95,47  84,48  49140  683,272     0    0,000 18614  334,925 1018,197
```
At least some GC activity is indicated here. Admittedly not much, but all the bookkeeping from G1 is usually a major block in our applications.

JDK version
```
openjdk 11.0.14 2022-01-18
OpenJDK Runtime Environment (build 11.0.14+9-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.14+9-post-Debian-1deb10u1, mixed mode, sharing)
```
We're currently using version 2.7.

Any help or insights are appreciated.

Cheers,
Christoph

**Comment by apangin** [comment]
I'm not sure I understand the problem. What is the expected result, and what do you get instread?
Check `stderr` of the target Java process for any warnings related to the profiler.

**Comment by dreis2211** [comment]
We expect to see some something like this:
<img width="1676" alt="image" src="https://user-images.githubusercontent.com/6304496/168744211-2c2b9cef-7a97-4be4-b398-2ba9c9127983.png">

While we see this:
<img width="1676" alt="image" src="https://user-images.githubusercontent.com/6304496/168744306-5d461e9d-5834-4bfd-8448-396f392ac19e.png">

We can tell from jstat and other sources that allocations are happening and also GCs. We also see that the sweeper thread is relatively busy generally, which might be related to changes in https://bugs.openjdk.java.net/browse/JDK-8263785 .
But all of this is not shown in our profilings anymore.

**Comment by dreis2211** [comment]
After a restart of the service the big (and expected) chunk is back:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/6304496/168800698-595973e2-2a0e-4e6f-848e-b36e31dc8d29.png">

**Comment by apangin** [comment]
Your `jstat` excerpt shows very little GC activity, it can hardly be an argument for a missing big chunk.

Try different profiling modes:
`-e itimer`
`-e wall`
and also add `-t` to show thread names in the profile.
