### ISSUE TITLE
Nativemem profiling fails when used with option --fdtransfer

### ISSUE THREAD

**Issue by sattishv** [jvm-profiling-tools/async-profiler#595]
Team we are trying to identify the leak candidates of an off heap netty memory issue using async-profiler. Since our container doesn't have the perf events installed we have to rely on the option fdtransfer to generate the required profiles. 

Since its an off heap allocation we tried with option nativemem but we got a different message while invoking the command
 ./profiler.sh --fdtransfer -e nativemem -d 100 <PID>
[ERROR] Unsupported event type

We did a LD_PRELOAD of the required library both on the host and container
export LD_PRELOAD=/opt/async-profiler-2.8-linux-x64/build/libasyncProfiler.so

we used the latest version 2.8 of async-profiler.

Thanks

**Comment by apangin** [comment]
I already answered the same question in #482:

- `nativemem` option is available only in a special version built from `malloc` branch;
- `--fdtransfer` does not have effect for `nativemem`.

**Comment by sattishv** [comment]
Sorry for the repeat question. My apologies
