### ISSUE TITLE
Alloc smoke test fails with java9

### ISSUE THREAD

**Issue by rockwotj** [jvm-profiling-tools/async-profiler#60]
It seems with Java 9 the heap profile is missing stacktraces of where objects are allocated. Is this expected behavior? I can't share anything, but the `alloc-smoke-test.sh` file fails on my CentOS machine using Java9

Java -version output:
```
java version "9"
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)
```

**Comment by rockwotj** [comment]
I might also help to mention that the output of `java.trace` in that test is as follows:

```
int[]_[i] 57
int[]_[k] 25220
java.lang.Integer[]_[k] 25273
java.lang.Integer[]_[i] 50
```

**Comment by apangin** [comment]
I've found the problem. Seems like Oracle JDK is compiled with -fomit-frame-pointer option that breaks AsyncGetCallTrace when walking through VM frames. Fortunately, JVM TI GetStackTrace call will help in this case. I'm working on the fix.

**Comment by apangin** [comment]
Re-implemented Java stack traces with JVM TI for allocation profiling. Now it works well with Oracle JDK 9.

**Comment by rockwotj** [comment]
Awesome! Thanks for a quick turnaround! Is there a performance difference of using JVM TI?

**Comment by apangin** [comment]
I haven't measured, but considering the way both methods are implemented inside - there should not be significant performance difference.
