### ISSUE TITLE
Where I can find interpreted/JIT compiled/C1 frames?

### ISSUE THREAD

**Issue by franz1981** [jvm-profiling-tools/async-profiler#600]
I've used the last version of the profiler, adding -a while running it, but I didn't found anything on the html flamegraph that tells the compilation level of frames - how to access it?

**Comment by apangin** [comment]
![c1](https://user-images.githubusercontent.com/1749416/171505952-2f9b2fbf-0b44-4ff7-ab21-326b23b90827.png)

**Comment by apangin** [comment]
C1 frames are highlighted with a yellowish green color, as on the picture above.
In the collapsed stacks output, they are denoted with `_[1]` suffix.
Furthermore, a popup hint shows how many times the frame was found interpreted, c1-compiled, or inlined.

As with inlined frames, compilation level information is available only for the topmost frames.

**Comment by franz1981** [comment]
many thanks @apangin , I see that this one is nearly-duplicate of https://github.com/jvm-profiling-tools/async-profiler/issues/448#issuecomment-1086932617 - reporting to help other users, in case

**Comment by franz1981** [comment]
I'll retry again locally, to see if it works as expected with a sample program

**Comment by apangin** [comment]
Closing the question as answered. Feel free to reopen / open a new one, if you have further comments.
