### ISSUE TITLE
attach process in container error: "libasyncProfiler.so: No such file or directory"

### ISSUE THREAD

**Issue by xwjahahahaha** [jvm-profiling-tools/async-profiler#601]
I am running a java application(tomcat) inside the container and jattach on the host. but when I run `sudo -E bash -x ./profiler.sh -d 10 22491` （22491 is tomcat pid in the host machine）, error is :

(According to a method from [issues/245](https://github.com/jvm-profiling-tools/async-profiler/issues/245))
```shell
$ sudo -E bash -x ./profiler.sh -d 10 22491

/home/vagrant/.../async-profiler/build/jattach 22491 load /home/vagrant/.../async-profiler/build/libasyncProfiler.so true start,file=/tmp/async-profiler.37876.22491,,log=/tmp/async-profiler-log.37876.22491
Connected to remote JVM
JVM response code = -1
/home/vagrant/eBPF/tools_study/profile_tools/java_perf_map_test/async-profiler/build/libasyncProfiler.so was not loaded.
/home/vagrant/eBPF/tools_study/profile_tools/java_perf_map_test/async-profiler/build/libasyncProfiler.so: cannot open shared object file: No such file or directory
```

```shell
$ sudo -E strace -s999 /home/vagrant/.../async-profiler/build/jattach 22491 load /home/vagrant/.../async-profiler/build/libasyncProfiler.so true start,file=/tmp/async-profiler.37876.22491,,log=/tmp/async-profiler-log.37876.22491

...
write(3, "start,file=/tmp/async-profiler.37876.22491,,log=/tmp/async-profiler-log.37876.22491\0", 84) = 84
read(3, "-1\n/home/vagrant/.../async-profiler/build/libasyncProfiler.so was not loaded.\n/home/vagrant/.../async-profiler/build/libasyncProfiler.so: cannot open shared object file: No such file or directory\n", 8191) = 288
write(1, "JVM response code = -1\n/home/vagrant/.../async-profiler/build/libasyncProfiler.so was not loaded.\n/home/vagrant/.../async-profiler/build/libasyncProfiler.so: cannot open shared object file: No such file or directory\n", 308JVM response code = -1
/home/vagrant/.../async-profiler/build/libasyncProfiler.so was not loaded.
/home/vagrant/.../async-profiler/build/libasyncProfiler.so: cannot open shared object file: No such file or directory
) = 308
read(3, "", 8192)                       = 0
```
from the [troubleshooting](https://github.com/jvm-profiling-tools/async-profiler#troubleshooting), I check `.so` dir owner:
```shell
$ ls -l /home/vagrant/.../async-profiler/build/
-rw-rw-r-- 1 root root   3727 May 31 11:54 async-profiler.jar
-rw-rw-r-- 1 root root  41538 May 31 11:54 converter.jar
-rwxrwxr-x 1 root root  22672 May 31 11:54 fdtransfer
-rwxrwxr-x 1 root root  35416 Jun  1 08:12 jattach
-rwxrwxrwx 1 root root 342632 May 31 11:54 libasyncProfiler.so
```
and tomcat also run in root:
```shell
root@b6ba2363c4a0:/usr/local/tomcat# ps -aux 
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.3  2.6 4668316 108408 ?      Ssl  07:55   0:22 /usr/local/openjdk-11/bin/java -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -Dorg.apache.catalina.security.SecurityListener.UMASK=0027 -Dignore.endorsed.dirs= -classpath /usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar -Dcatalina.base=/usr/local/tomcat -Dcatalina.home=/usr/local/tomcat -Djava.io.tmpdir=/usr/local/tomcat/temp org.apache.catalina.startup.Bootstrap start

```

my env
```shell
Linux ubuntu-impish 5.13.0-44-generic #49-Ubuntu SMP Wed May 18 13:28:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
async-profiler git commit: `58a3cb0d252a115cbb0ec55d3073ddc068d7022b`
tomcat：9.0 # run in container 
```
I think the biggest reason may be that the JVM process in the container cannot find the `.so` file on the host due to rootFS isolation, although the user is the same.How to solve this problem? need to copy it into a container? I would be very grateful if you could help me :)

**Comment by apangin** [comment]
To load async-profiler, the target JVM process needs to access `libasyncProfiler.so` by the same path as on the host.
Start a container with a bind mount like
`-v /path/to/async-profiler:/path/to/async-profiler`

Alternatively, you may copy `libasyncProfiler.so` into the container.

**Comment by xwjahahahaha** [comment]
> To load async-profiler, the target JVM process needs to access `libasyncProfiler.so` by the same path as on the host. Start a container with a bind mount like `-v /path/to/async-profiler:/path/to/async-profiler`
> 
> Alternatively, you may copy `libasyncProfiler.so` into the container.

thx reply!  But after I copied the .so file to the container, the following error was reported because the glibc version of the host and the container were different:

error:
```shell
./libasyncProfiler.so was not loaded.
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./libasyncProfiler.so)
```

```shell
# host
$ ldd --version
ldd (Ubuntu GLIBC 2.35-0ubuntu3) 2.35

# in the container
$ ldd --version
ldd (Debian GLIBC 2.31-13+deb11u3) 2.31
$ ldd libasyncProfiler.so 
./libasyncProfiler.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./libasyncProfiler.so)
./libasyncProfiler.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./libasyncProfiler.so)
	linux-vdso.so.1 (0x00007fff441f7000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f7e9b530000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f7e9b516000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7e9b351000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f7e9b20d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7e9b750000)
```
and then，I recompile(Modified the Makefile) the `libasyncProfiler.so` file using the rpath parameter of the corresponding container：
```shell
$ g++ -O3 -fno-omit-frame-pointer -fvisibility=hidden -Wl,-z,defs -Wl,-z,nodelete -Wl,-rpath,/usr/local/tomcat/osfiles ...
$ sudo chrpath build/libasyncProfiler.so 
build/libasyncProfiler.so: RUNPATH=/usr/local/tomcat/osfiles
```
and then,  I also copy `/lib/x86_64-linux-gnu/libc.so.6` file(host) into the container working diretory `/usr/local/tomcat/osfiles`
```shell
$ sudo docker cp /lib/x86_64-linux-gnu/libc.so.6 b6ba:/usr/local/tomcat/osfiles
$ sudo docker cp build/libasyncProfiler.so b6ba:/usr/local/tomcat
```
check link int the contianer:
```shell
$ ldd libasyncProfiler.so 
	linux-vdso.so.1 (0x00007ffda2e3b000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f25a6311000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f25a62f7000)
	libc.so.6 => /usr/local/tomcat/osfiles/libc.so.6 (0x00007f25a60cf000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f25a5f8b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f25a652e000)
```
it become well. But when I run profile.sh, the error is the same:
```shell
Connected to remote JVM
JVM response code = -1
./libasyncProfiler.so was not loaded.
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./libasyncProfiler.so)

Failed to inject profiler into 22491
``` 
Does the JVM read dynamic links in a different way than ldd? how can I solve this problem😂

**Comment by apangin** [comment]
Did you try binaries from the [releases](https://github.com/jvm-profiling-tools/async-profiler/releases) page? I believe they should work both in your container and on the host. The clue is those releases were built with an old enough toolchain, so there is no dependency on a new version of GLIBC.

**Comment by apangin** [comment]
@johnaohara Setting `PROFILER` env variable right in front of `profiler.sh` command already solves the problem, but I don't mind an extra script option, too. So please go ahead and create a PR. I would only prefer a shorter name for an option (e.g. `--lib` instead of `--library`). Thanks.

**Comment by xwjahahahaha** [comment]
> Did you try binaries from the [releases](https://github.com/jvm-profiling-tools/async-profiler/releases) page? I believe they should work both in your container and on the host. The clue is those releases were built with an old enough toolchain, so there is no dependency on a new version of GLIBC.

Thank you very much! I solved the problem using a compiled executable file in release.

**Comment by xwjahahahaha** [comment]
> @johnaohara Setting `PROFILER` env variable right in front of `profiler.sh` command already solves the problem, but I don't mind an extra script option, too. So please go ahead and create a PR. I would only prefer a shorter name for an option (e.g. `--lib` instead of `--library`). Thanks.

Would you consider adding support in the `profiler.sh` to determine if attach's process is in the container and then help the user copy it to the container and delete it after execution？

**Comment by apangin** [comment]
@xwjahahahaha I thought about this - indeed, it makes sense to automate passing the shared library to a containerized application. I'll get back to this question when converting profiler.sh to a native binary.

@johnaohara Added `--lib` option to customize path to the profiler library.
