### ISSUE TITLE
effects while profiling a Java method

### ISSUE THREAD

**Issue by franz1981** [jvm-profiling-tools/async-profiler#604]
This is not an issue with the profiler itself, but more a request to help me understand this strange behaviour.
We've a load generator that cause our server app to cause a single method to still be C2 compiled but makes it terribly slow.
Disabling tiered compilation and forcing compilation of such method to stop at C1 cause it to speed up (by a factory of 3-4 times).
In order to verify what's going on I've enabled profiling of the method via the `-e ClassName::methodName` option (using the full-fat tiered compilation configuration) and the method has become fast again: I would like to understand what async profiler is doing that can makes this to happen.
I remember that attaching the profiler cause a code cache flush, but while running the profiler with the default `-e cpu` isn't producing the same behaviour: what are the differences between running async profiler with `-e cpu` and the java method profiling option?

I hope this won't be too off-topic, but I'm lost searching what's going on in the profiler code ie need a pointer to start looking at it.

**Comment by Jongy** [comment]
AFAIK using AP in `-e java_method` works by rewriting that method's bytecode, which then "deoptimizes" the C2-compiled version of it. Maybe at some point in the future that method will again be compiled with C2.

`-e cpu` (and other modes, I think) does not make any changes in the Java bytecode.

**Comment by apangin** [comment]
> I would like to understand what async profiler is doing that can makes this to happen.

`-e Class.methodName` invokes redifinition of the specified class/method, which in turn results in the deoptimization of the given compiled method. Note: the very first class redifinition causes the deoptimization of everything, unless async-profiler agent is loaded at JVM startup.

> I remember that attaching the profiler cause a code cache flush, but while running the profiler with the default -e cpu isn't producing the same behaviour

Not attaching, but the class redifinition as mentioned above (only the very first redifinition; subsequent ones work normally). Attaching in `-e cpu` mode does not cause deoptimization.

**Comment by franz1981** [comment]
Thanks to both @apangin @Jongy for the info and pointer:)
I am a bit puzzled that the flamegraphs (-e cpu) of this unlucky method is very weird too, showing many ancestor and children-free samples and some "right" (both with samples and ancestors) but still super-costy. But very happy that this time the "observer" effect could be of some help to understand the root cause

**Comment by krzysztofslusarski** [comment]
Mind, that you can be lied by the JVM - https://github.com/jvm-profiling-tools/async-profiler/discussions/541

**Comment by franz1981** [comment]
@krzysztofslusarski I can guarantee something weird is going on: the server got 1/4 of the performance then running the load generation test in isolation :(
But you're right: maybe the method reported is not the guilty one (although it happen to be the one reported in separate repeatable tests) or, at least, not directly it's fault...

**Comment by franz1981** [comment]
Attaching https://github.com/jvm-profiling-tools/async-profiler/pull/483#discussion_r735136420 for the sake of other users

**Comment by apangin** [comment]
Closing the question as answered. Feel free to reopen / open a new one, if you have further comments.
