### ISSUE TITLE
Weird problems building async-profiler -g3 on arm64 linux

### ISSUE THREAD

**Issue by pnf** [jvm-profiling-tools/async-profiler#607]
I'm not sure exactly why, but changing Makefile:13 to use `-g3` causes this assignment in flameGraph.cpp
```
        const char* tail = TREE_TEMPLATE;
```
to somehow result in `tail` pointing somewhere in the debug table.  In the debugger, you can print out both `TREE_TEMPLATE` and `tail`; the former correctly holds the contents of the html file, while the latter is gibberish.  This of course means that the `strstr` in `printTill` returns `NULL`, and we dump core.

I see this only on arm64 linux (specifically ubuntu 20.04 running in parallels on an M1 mac), not on x64.

Obviously, I was debugging a PR with more changes than just the optimization flags, but I verified the problem with a clean build of current master.

**Comment by apangin** [comment]
I think I found a way round. Please try if it helps.

**Comment by pnf** [comment]
It works.  Thanks.
