### ISSUE TITLE
copy class.method name from html flamegraph

### ISSUE THREAD

**Issue by cloud-66** [jvm-profiling-tools/async-profiler#611]
So difficult almost impossible to copy class and method name from flamegraph. I can't select the text row with problematic class to copy somewhere for saving.
Can something be done about it?

**Comment by apangin** [comment]
What browser do you use?
In Chrome, triple click on a frame selects the full frame title - exactly the class and method name.

**Comment by Jongy** [comment]
> What browser do you use? In Chrome, triple click on a frame selects the full frame title - exactly the class and method name.

I can confirm it works :) Great feature!

**Comment by cloud-66** [comment]
Thank you. It is not obvious . I have tried.  It is working on chromium based browser, but doesn't work in firefox which i use.

**Comment by apangin** [comment]
Made selection with double click. Now it should in Firefox, too.
Try [flamegraph.html](https://htmlpreview.github.io/?https://github.com/jvm-profiling-tools/async-profiler/blob/master/demo/flamegraph.html)
