### ISSUE TITLE
Receive error - Could not open Flight Recorder output file

### ISSUE THREAD

**Issue by PeretsOleksii** [jvm-profiling-tools/async-profiler#614]
Try to start profiling cpu + allocations + locks together using comman ./profiler.sh start -e itimer,alloc,lock -f profile.jfr 1.
Receive error [ERROR] Could not open Flight Recorder output file. 
But in the README I see - jfr - dump events in Java Flight Recorder format readable by Java Mission Control. This **_does not_** require JDK commercial features to be enabled.

Thanks

**Comment by PeretsOleksii** [comment]
Looks like I've missed -o jfr option

**Comment by apangin** [comment]
The error message says that async-profiler failed to create the output file `profile.jfr` in the current directory.
Make sure the JVM process has write permissions to that directory or try specifying the full path name to another directory, e.g. `-f /tmp/profile.jfr`

**Comment by apangin** [comment]
I'm closing the issue, as there is nothing to do from async-profiler side.
Feel free to reopen if you have further questions.
