### ISSUE TITLE
JDK 7 crashes in ConstMethod::id()

### ISSUE THREAD

**Issue by sp00n8** [jvm-profiling-tools/async-profiler#615]
Hi,
`./profiler.sh -v`
`Async-profiler 2.8.1 built on Jun 11 2022`

2.8 the same situation

`./profiler.sh -d 30 -i 5ms -f /full_path/xxyy0.html pid`

`A fatal error has been detected by the Java Runtime Environment:`
`SIGSEGV (0xb) at pc=0x00002b616f2d9e2e, pid=41453, tid=47700510770944`

`JRE version: 7.0_25-b15`
`Java VM: Java HotSpot(TM) 64-Bit Server VM (23.25-b01 mixed mode linux-amd64 compressed oops)`
`Problematic frame:`
`C  [libasyncProfiler.so+0x6e2e]  ConstMethod::id()+0xe`

`ulimit -c -l`
`core file size          (blocks, -c) unlimited`
`max locked memory       (kbytes, -l) unlimited`

-d 20 - time to time crushes or done
-d 30 - stable crushes

`uname -r`
`4.1.12-124.39.2.el7uek.3.x86_64`

`sysctl -a | grep -E 'perf_event_paranoid|kptr_restrict'`
`kernel.kptr_restrict = 0`
`kernel.perf_event_paranoid = 1`

any ideas ?

**Comment by apangin** [comment]
Oh, that's JDK 7...
Didn't know that people are still using it :)

I'll prepare a fix
