### ISSUE TITLE
CPU load info is not correct in container when in jfrsync mode due to JVM bug

### ISSUE THREAD

**Issue by qsLI** [jvm-profiling-tools/async-profiler#617]
Currently, we are using async profiler to do some continuous profiling. 
We have noticed that async profiler has recorded cpu load at intervals in jfr format. And it's really useful.
  - The cpu load info is correct when we use async profiler only. 
  - But it goes wrong when we specify jfrsync （ to collect more event ) .The cpu load became **much lower** than async profiler only.
  -  We dig into jvm source and find that it uses **/proc/stat** and **/proc/[pid]/stat** to calculate cpu load. And we found some related bugs when used **in container** 
      - [JDK-8268098 jdk.CPULoad event reports incorrect CPU usage inside a container - Java Bug System](https://bugs.openjdk.org/browse/JDK-8268098)
      - a solutiion but not merged [8268098: jdk.CPULoad event reports incorrect CPU usage inside a container by YaSuenag · Pull Request #4299 · openjdk/jdk](https://github.com/openjdk/jdk/pull/4299/files)
  - Async profiler uses **/proc/stat** and **linux time function** to calculate cpu load (Is it **intended** to solve container related issue?)
  - Async profiler will automaticly disable cpu load collect，and use  jfr to collect cpu load. Are there any way to change the priority?

**Comment by apangin** [comment]
async-profiler already has an argument `jfr=<mask>` to enable/disable generation of certain JFR events,
where `<mask>` is a bitset of [JfrOptions](https://github.com/jvm-profiling-tools/async-profiler/blob/2459d7eac4d4c21868f05eecb5d6e2a6fadf5fe7/src/arguments.h#L83).

Now, if some event is enabled in async-profiler, the same event is disabled in Flight Recorder.
E.g. to force async-profiler emit `jdk.CPULoad` events in jfrsync mode, pass `jfr=-9`.

**Comment by apangin** [comment]
Fixed in 2.8.3 with `jfr` option. The default behavior isn't change though.

**Comment by qsLI** [comment]
Thanks for your rapid rely. 
I found that the order of `jfr=<mask>` and `jfrsync=<config>` may lead to different result.
With JFR CPU load event disabled:
1. jfrsync=/tmp/xxx.jfc,jfr=7  CPU load is recorded correctly.
2. jfr=7,jfrsync=/tmp/xxx.jfc  no CPU load is recorded.

In case2 `_jfr_options` will be override to JFR_SYNC_OPTS, no CPU load will be recorded.

related code:
https://github.com/jvm-profiling-tools/async-profiler/blob/56ae519224ed9a9b081fd8c384326784326fae43/src/arguments.cpp#L166-L175
