### ISSUE TITLE
Allocation profiling reports in sample unit other than bytes

### ISSUE THREAD

**Issue by nitsanw** [jvm-profiling-tools/async-profiler#62]
To test I used a benchmark workload and compared JMC reporting to AP, benchmark code:
```
public class AllocationProfilingBench
{
    static class A {} // 16b
    static class B extends A {long f1,f2;} // 32b
    static class C extends B {long g1,g2,g3,g4;} // 64b

    A newA() { return new A();}
    B newB() { return new B();}
    C newC() { return new C();}

    @Benchmark
    public Object allocate()
    {
        Object result;
        double rnd = ThreadLocalRandom.current().nextDouble();
        if (rnd < 0.333)
            result = newA();
        else if (rnd < 0.666)
            result = newB();
        else
            result = newC();
        return result;
    }
}
```

In JMC I see the following breakdown:
```
Class				Size		Pressure(%)
AllocationProfilingBench$C	64b		57%
AllocationProfilingBench$B	32b		28%
AllocationProfilingBench$A	16b		14%
```
This is as expected. In AP I would expect an output in the object size multiple, but I'm getting this (trimmed the stacks):
```
AllocationProfilingBench$A_[k] 89
AllocationProfilingBench$A_[i] 5368
AllocationProfilingBench$B_[k] 213
AllocationProfilingBench$B_[i] 10599
AllocationProfilingBench$C_[k] 422
AllocationProfilingBench$C_[i] 20001
```
I assume the _[i] are in TLAB and _[k] are out of TLAB (nice touch, I'll add a wiki page on alloc profiling to give some details). The ratios look right, but the quantities reported are not in the unit I expected.

**Comment by apangin** [comment]
This behavior is intended.

In `flat` or `traces` view you will see both number of samples and bytes. Unfortunately, FlameGraph can show only one value. By default, this is number of samples. With `-o collapsed=counter` it will show total size. However, the ratio will be obviously different, since the bigger number of samples will be multiplied by a bigger object size. In this sense the number of samples is more fair.

**Comment by apangin** [comment]
@nitsanw Does my explanation make sense? Any suggestions on what to do with this issue?

**Comment by nitsanw** [comment]
I'm not sure what the best method in this case is:
 * default = samples: does not reflect size, so bias towards smaller allocations
 * counter = samples * size: reflects size, but not TLAB churn
There's a further issue here that TLAB size is not uniform and we are in that sense biased to wards the small TLAB, so TLAB size should also play into the evaluation...

**Comment by apangin** [comment]
I don't fully agree that samples bias towards smaller allocations, because smaller allocations will cause less frequent TLAB overflows. The above test case shows that the ratio is correct, and I believe current defaults are sane.

Have no idea what to do about this issue. Closing as "not-a-bug".
