### ISSUE TITLE
Inline highlighting does not work with simple example class

### ISSUE THREAD

**Issue by oehme** [jvm-profiling-tools/async-profiler#622]
I found that inline highlighting works really well in most practical use cases, but when I tried it with one of your examples, it didn't work:

```
public class ProfilerTest {
    public static void main(String[] args) {
        StringBuilder sb = new StringBuilder();
        sb.append(new char[1_000_000]);

        do {
            sb.append(12345);
            sb.delete(0, 5);
        } while (Thread.currentThread().isAlive());

        System.out.println(sb);
    }
}
```

The methods show up in regular green

![flames](https://user-images.githubusercontent.com/1191797/180461360-0904f5cd-d085-46fe-8260-eae098a1fe91.png)

Here's the output of `-XX:+PrintCompilation -XX:+PrintInlining`:

```
2162  267 %     3       ProfilerTest::main @ 17 (49 bytes)   made not entrant
                              @ 21   java.lang.StringBuilder::append (8 bytes)   already compiled into a big method
                              @ 28   java.lang.StringBuilder::delete (9 bytes)   inline (hot)
                                @ 3   java.lang.AbstractStringBuilder::delete (46 bytes)   inline (hot)
                                  @ 15   java.lang.AbstractStringBuilder::checkRangeSIOOBE (60 bytes)   inline (hot)
                                  @ 33   java.lang.AbstractStringBuilder::shift (37 bytes)   inline (hot)
                                    @ 33   java.lang.System::arraycopy (0 bytes)   (intrinsic)
```

**Comment by apangin** [comment]
In the current implementation, JIT frame types are shown only for the topmost Java frames.
The topmost frame here is a runtime stub `jbyte_disjoint_arraycopy`, which is neither interpreted nor JIT-compiled.

However, it turns out, this particular situation is easy to fix - I've just committed the change that shows inlined frames, if the topmost frame is a runtime stub (like arraycopy, itable stub, etc.)

**Comment by apangin** [comment]
That's how it looks now:
![inlined](https://user-images.githubusercontent.com/1749416/180626225-c6563ec8-4c2b-4ee1-a03a-fb49ee4dfa1f.png)

**Comment by oehme** [comment]
Awesome, thank you!
