### ISSUE TITLE
jsttach throw error:  Bad CPU type in executable in macOS x64

### ISSUE THREAD

**Issue by wisheslee** [jvm-profiling-tools/async-profiler#623]
async profiler version: async-profiler-2.8.3-macos
command:  profiler.sh 8034
**error: ./profiler.sh: line 102: xxxx/async-profiler-2.8.3-macos/build/jattach: Bad CPU type in executable**
mac version: MacBook Pro (16-inch, 2019), cpu: intel Core i7, Mac Monterey,
jdk version: Oracle JDK 1.8.0_311

then i download async-profiler-2.5.1-macos, it run correctly.

**Comment by apangin** [comment]
Something went wrong during the build process.

I rebuilt async-profiler-2.8.3-macos once again and updated the binary in the release.
Should work fine now.

**Comment by wisheslee** [comment]
Thank you! it do work.
