### ISSUE TITLE
how to detach / clean up? manual remove of java_pid  or other....

### ISSUE THREAD

**Issue by peterdnight** [jvm-profiling-tools/async-profiler#624]
Any hints on cleaning up / releasing resources after a profiling session?

- is it possible to specify java_pid_file location?
- any issues with simply deleting the socket?

I would like to be able to run multiple concurrent sessions - is this possible? And to be able to query: list out active sessions and associated pids.

I noticed with:  `async  collect <pid> --duration 60` , the python command is run in the foreground versus the background, but at the end when profiling is complete the socket file is still present? When run in the background - is there a running process that shows up that manages resources allocation? Eg. where is the collected data being stored?

Thanks for a great tool!

**Comment by apangin** [comment]
I'm not sure I understand the question. Please clarify, what problem are you trying to solve?
What kind of resources do you want to cleanup and why?

Attach socket (`/tmp/.java_pid12345`) is an artifact of the JVM, it's not the profiler that creates it. The socket is created on the first attach to the Java process and remains until the JVM exit. For example, if you run `jstack`, JVM will also create an attach socket. Do not remove it, otherwise you won't be able to attach to the JVM again (this is a [JDK bug](https://bugs.openjdk.org/browse/JDK-8225690) that has been fixed only in 11.0.13 and 8u332).

**Comment by peterdnight** [comment]
> 
Thanks for taking time to respond. 
- using https://github.com/csap-platform/csap-core/wiki/Application-Portal#service-deployment , 
- I am going to add a "start/stop" profiling that can be triggered from the UI (or rest api).
- UI should be able to query status for all/any sessions
- When stopped any resources associated with the profiling session (except for the flamegraph) should be released.
- when i did a kill on the process being monitored - the file was still there.

When I start the session - I can flag ( touch $csapService.profile) via the filesystem, and then just check the filesystem when displaying status. (Unless there is some other query i can run: show all sessions, or similar?

**Comment by apangin** [comment]
> when i did a kill on the process being monitored - the file was still there. How and when can /tmp/.java_pid* be cleaned up.

When the JVM shuts down orderly, it removes `.java_pid` socket itself. If you forcibly kill JVM, it has no chance to do it, and it's up to you to clean up.

> Unless there is some other query i can run: show all sessions, or similar

async-profiler is stateless, it does not track the processes you attach to.

> it seems profiler runs in the attached Java process space?

Yes, async-profiler runs in the context of the target Java process. All resources are counted under that process.

**Comment by apangin** [comment]
Closing the issue, since there is nothing to do on async-profiler side at this point.
Feel free to start a new discussion if you have further questions.
