### ISSUE TITLE
Programmatic usage: attach from within Java

### ISSUE THREAD

**Issue by victornoel** [jvm-profiling-tools/async-profiler#625]
Hi,

I was wondering if it would be possible to attach the profiler to the running JVM from within Java.

The purpose would be to choose when to start and stop profiling just for some parts of the application without having to do it manually from outside but just by calling some Java API :)

**Comment by krzysztofslusarski** [comment]
In the binaries you have a JAR lib ```async-profiler.jar``` that contains the Java API. 

You can also get it from maven central::
```xml
<dependency>
  <groupId>tools.profiler</groupId>
  <artifactId>async-profiler</artifactId>
  <version>1.8.3</version>
</dependency>
```

**Comment by jumarko** [comment]
As an example, here's the clojure wrapper for Async Profiler: https://github.com/clojure-goes-fast/clj-async-profiler

**Comment by victornoel** [comment]
That was fast! And it seems everything is already available for it :)
Thank you to both of you, I think I have everything I need then, I will close the ticket.

**Comment by victornoel** [comment]
Ah unfortunately, the latest version is 2.8.3 but the latest available on maven is 1.8.3.

Any idea who should we ask to get the latest version on maven?

**Comment by krzysztofslusarski** [comment]
I believe it is compatible with newest async-profiler. I used it with 2.x line. 

If it is not you can:
- just copy those classes https://github.com/jvm-profiling-tools/async-profiler/tree/master/src/api/one/profiler to your project. 
- create an issue for lack of compatible java API in maven

**Comment by victornoel** [comment]
Sounds good, thank you!
