### ISSUE TITLE
How to emulate `simple=true` when calling `jfr2flame` directly?

### ISSUE THREAD

**Issue by triceo** [jvm-profiling-tools/async-profiler#626]
Until now, I have been using only CPU profiling, with a flamegraph output.
I have now enabled `cpu` and `alloc`, which forced me to switch to JFR output and to generate flamegraphs myself.

I managed to get it working using `java -cp async-profiler-2.8.3-linux-x64/build/converter.jar jfr2flame ...`, but the resulting CPU flamegraph gives me classes with their FQN, which makes the chart hard to read. I'd rather see just their class names in there.

With the flamegraph output earlier, I was able to do that by supplying the option `simple=true`. However, scanning through the `jfr2flame` source code, I was not able to find its equivalent. Any advice?

**Comment by apangin** [comment]
There was no such option before.
Now I added `--simple`.

**Comment by triceo** [comment]
Thank you! I will close this issue as soon as there is an async-profiler release with this change included.

**Comment by apangin** [comment]
Async-profiler 2.9 includes the mentioned feature.
