### ISSUE TITLE
Adding jit support to async profiler

### ISSUE THREAD

**Issue by kapirajus** [jvm-profiling-tools/async-profiler#629]
Are there any efforts or plans to add JIT (LLVM, JavaScript, etc...) support to async profiler?

Can async profiler (AP) display symbols from JIT environment, LLVM specifically? LLVM can write debug dump at runtime, but AP can't understand the dump as of now. Any comments?

**Comment by apangin** [comment]
Async-profiler is a *Java* profiler. How does it relate to LLVM and friends?
Can you please elaborate on your use case?

**Comment by kapirajus** [comment]
I read async profiler is full stack profiler. If the stack has LLVM and Java together, can this profiler fit for profiling (with some patch) native code as well?

In detail, Linux "perf" and LLVM already have such support for JIT environment. LLVM tools compile LLVM IR code at runtime and writes object file to disk. This file later used by **_perf_** to resolve symbols via "**_perf inject_**" during report time. Async profiler can't support JIT environment as of now, any plans or inputs that help to patch this tool?

Related links
https://github.com/torvalds/linux/blob/master/tools/perf/util/jitdump.c
https://github.com/llvm/llvm-project/blob/main/llvm/lib/ExecutionEngine/PerfJITEvents/PerfJITEventListener.cpp

If needed, I can provide an example (Java and LLVM IR).

**Comment by apangin** [comment]
Thank you for the clarification. TBH, I've never seen a Java application with an embedded LLVM JIT before, except for the Falcon JIT and GraalVM (which can run LLVM Bitcode). I doubt this feature will be popular enough to justify spending resources on it. However, this could be a good candidate for a commercial version. If you/your company is interested in having LLVM support in async-profiler on a commercial basis, drop us an email at support@profiler.tools.

**Comment by kapirajus** [comment]
Thank you, closing the ticket for now.
