### ISSUE TITLE
Is it possible to add "live" options to allocation profiling

### ISSUE THREAD

**Issue by farmerworking** [jvm-profiling-tools/async-profiler#633]
If using jdk11 and do allocation profiling based on jvmti 

according to JEP 331: Low-Overhead Heap Profiling

> When an event is generated, the callback can capture a stack trace using the JVMTI GetStackTrace method. The jobject reference obtained by the callback can be also wrapped into a JNI weak reference to help determine when the object has been garbage collected. This approach allows the user to gather data on what objects were sampled, as well as which are still considered live, which can be a good means to understand the job's behavior.

I wonder if async-profiler can add "live" options so that flame graph can tell which thread hold the most memory.

Since some thread allocate a lot but most of its allocation is short lived and can be collected by ygc quickly which is harmless most of the time. 

The problem I currently have to deal with is thread do allocation a lot and keep it alive for quite long time like 30s or 1 minute. which can easily cause to-space exhausted and finally cause FGC which is really bad. a real world example would be a complicated SQL using join + group by + order

**Comment by apangin** [comment]
How would that `live` option work in your opinion?
Do you mean a flamegraph of sampled objects that were not garbage collected during the whole profiling session?

> so that flame graph can tell which thread hold the most memory

It's not quite clear what you mean by a thread holding memory. If some object is reachable from a global root (other than a thread stack), it does not really belong to any thread.

**Comment by farmerworking** [comment]
a flamegraph of sampled objects that were not garbage collected during the whole profiling session
- that would be enough

**Comment by apangin** [comment]
OK, so what you're talking about is essentially a leak profiler. I have plans to implement that, too.

**Comment by krzysztofslusarski** [comment]
Wow, that functionality would be :exploding_head:.

**Comment by farmerworking** [comment]
> OK, so what you're talking about is essentially a leak profiler. I have plans to implement that, too.

Not exactly but very close. 

An example would be: `select * from table where a > 1 limit 5000;`

if only 4000 rows match `a > 1` condition and it's a very big table, this SQL will run for quite a while and keep hold 4000 rows in memory until the full scan is over. then it will return 4000 rows to client

it's not a memory leak but it's bad for gc and easily case high memory pressure.

I mention this case because that's exactly what I'm struggling with and wish async-profiler can help

**Comment by apangin** [comment]
Added `--live` option in async-profiler 2.9.

**Comment by faucct** [comment]
Is it possible to lift the 1024 live objects to a parameter? It distorts the results.
