### ISSUE TITLE
Java Method profiling returns different stack traces other than traced one

### ISSUE THREAD

**Issue by sattishv** [jvm-profiling-tools/async-profiler#638]
Hi Team,

We are trying to trace all the invocations of an exception using event type -e ClassName.methodName. But the collapsed output doesn't have any traces related to our method.
Exception thrown: java.util.concurrent.TimeoutException
We are trying to trace rx.internal.operators.OperatorTimeoutBase$TimeoutSubscriber.onTimeout

command used : sudo -u user1 ./profiler.sh -e rx.internal.operators.OperatorTimeoutBase$TimeoutSubscriber.onTimeout -d 160s -o collapsed -f /tmp/collapsed.txt <PID>

We checked the logs to make sure the exception was thrown in the logs but not seen on collapsed output. Are we missing any parameters or is the approach we tried is the correct one. Please suggest
Stack Trace snippet:
java.util.concurrent.TimeoutException
at rx.internal.operators.OperatorTimeoutBase$TimeoutSubscriber.onTimeout(OperatorTimeoutBase.java:177)
at rx.internal.operators.OperatorTimeout$1$1.call(OperatorTimeout.java:41)
at rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$2.call(EventLoopsScheduler.java:189)

**Comment by apangin** [comment]
Do you escape `$` in the command line? Otherwise, `$TimeoutSubscriber` is interpreted as an environment variable and substituted with an empty string.

**Comment by sattishv** [comment]
Hi Andrei,

Even without escape we couldn't the relevant traces. But by specifying the correct name we were able to generate the traces confined to the method name.  Thanks

**Comment by sattishv** [comment]
Yes Andrei issue resolved
