### ISSUE TITLE
Segmentation fault in jattach

### ISSUE THREAD

**Issue by lslhcqy123** [jvm-profiling-tools/async-profiler#645]
Target java is running in the container which is run by docker with no '--pid=host' parameter,then senmentation fault.
By checking,i found the reason is :In src/jattach/pstuil.c, function alt_lookup_nspid line 97 'return atoi(entry->d_name);' after line 96 'close(dir)' where dir is null.A temporary varaible may resolve the problem.
I guess this is an issue. @apangin

**Comment by apangin** [comment]
The given information is not enough to identify the problem. Please provide the following information:
 - version of async-profiler (the output of `profiler.sh -v`)
 - the OS version (the output of `uname -a`)
 - Java version
 - container base image: is it alpine or glibc
 - steps to reproduce the issue

Segmentation fault cannot occur on the lines you mentioned:
```
closedir(dir);
return atoi(entry->d_name);
```
Both `dir` and `entry` are guaranteed to be non-null at this point, because the preceding code explicitly asserts that:
https://github.com/jvm-profiling-tools/async-profiler/blob/b8c8db45d7ba2adfc99a21fb1b561002a8500a0c/src/jattach/psutil.c#L88-L102

**Comment by lslhcqy123** [comment]
version of async-profiler (the output of profiler.sh -v) :main branch
the OS version (the output of uname -a) :
Java version:target docker container which run java(openjdk8),monitor container where run profiler.sh(openjdk11)
container base image: is it alpine or glibc: both containers are based on alpine
g++ version:gcc version 10.2.1 20201203 (Alpine 10.2.1_pre1)

steps to reproduce the issue
0.target container and monitor container was run on the same k8snode
1.on monitor container,'**make**' under the directory $dir1
2.**docker cp** libasyncProfiler.so to k8snode
3.on target container run java program
4.on monitor container, **ps -ef|grep java**,get the pid xxx
5.on monitor container**,cp libasyncProfiler.so /proc/xxx/root/$dir2**,where $dir is equal to $dir2
6.on monitor container,  **./profiler.sh -e cpu -d 60 --loop 30 -o traces xxx**

**Comment by apangin** [comment]
If I understand correctly, you build the profiler yourself from the sources.

Do the binaries from the [official release](https://github.com/jvm-profiling-tools/async-profiler/releases/tag/v2.8.3) work?
Try both [async-profiler-2.8.3-linux-musl-x64.tar.gz](https://github.com/jvm-profiling-tools/async-profiler/releases/download/v2.8.3/async-profiler-2.8.3-linux-musl-x64.tar.gz) and [async-profiler-2.8.3-linux-x64.tar.gz](https://github.com/jvm-profiling-tools/async-profiler/releases/download/v2.8.3/async-profiler-2.8.3-linux-x64.tar.gz). Thanks.

**Comment by lslhcqy123** [comment]
with [async-profiler-2.8.3-linux-musl-x64.tar.gz] on monitor container:
/home/async-profiler-2.8.3-linux-musl-x64 # **./profiler.sh -d 30 -o traces 2539**
Segmentation fault

**Comment by apangin** [comment]
OK, I see. Can you please share the output of `strace build/jattach <pid> properties` ? That is to know at which point jattach crashes.
Also, if you tell which Alpine image your container is based on, I'll try to reproduce the issue.

**Comment by lslhcqy123** [comment]
/home/async-profiler-2.8.3-linux-musl-x64 # **strace build/jattach xxx properties**
execve("build/jattach", ["build/jattach", "30309", "properties"], 0x7ffc5b1a6b60 /* 12 vars */) = 0
arch_prctl(ARCH_SET_FS, 0x7f6c30654b48) = 0
set_tid_address(0x7f6c30654f90)         = 32514
brk(NULL)                               = 0x555dc632d000
brk(0x555dc632f000)                     = 0x555dc632f000
mmap(0x555dc632d000, 4096, PROT_NONE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x555dc632d000
mprotect(0x7f6c30651000, 4096, PROT_READ) = 0
mprotect(0x555dc59e1000, 4096, PROT_READ) = 0
geteuid()                               = 0
getegid()                               = 0
open("/proc/30309/status", O_RDONLY|O_LARGEFILE) = 3
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f6c305bd000
read(3, "Name:\tjava\nUmask:\t0027\nState:\tS "..., 1024) = 1024
read(3, "00000,00000000,00000000,00000000"..., 1024) = 192
read(3, "", 1024)                       = 0
close(3)                                = 0
munmap(0x7f6c305bd000, 4096)            = 0
stat("/proc/self/ns/pid", {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
stat("/proc/30309/ns/pid", {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
open("/proc/30309/root/proc", O_RDONLY|O_LARGEFILE|O_CLOEXEC|O_DIRECTORY) = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f6c305bc000
getdents64(3, 0x7f6c305bc048 /* 68 entries */, 2048) = 2048
open("/proc/30309/root/proc/1/sched", O_RDONLY|O_LARGEFILE) = 4
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f6c305bb000
read(4, "sleep (433, #threads: 1)\n-------"..., 1024) = 998
lseek(4, -973, SEEK_CUR)                = 25
close(4)                                = 0
munmap(0x7f6c305bb000, 4096)            = 0
open("/proc/30309/root/proc/68/sched", O_RDONLY|O_LARGEFILE) = 4
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f6c305bb000
read(4, "sh (26877, #threads: 1)\n--------"..., 1024) = 997
lseek(4, -973, SEEK_CUR)                = 24
close(4)                                = 0
munmap(0x7f6c305bb000, 4096)            = 0
getdents64(3, 0x7f6c305bc048 /* 1 entries */, 2048) = 24
open("/proc/30309/root/proc/75/sched", O_RDONLY|O_LARGEFILE) = 4
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f6c305bb000
read(4, "java (30309, #threads: 33)\n-----"..., 1024) = 1000
lseek(4, -973, SEEK_CUR)                = 27
close(4)                                = 0
munmap(0x7f6c305bb000, 4096)            = 0
close(3)                                = 0
munmap(0x7f6c305bc000, 8192)            = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x7f6c305bc05b} ---
+++ killed by SIGSEGV +++
Segmentation fault

**From alpine:3.13**

**Comment by apangin** [comment]
Thanks, I see now.
You were initially right about `atoi(entry->d_name)` line; I was just confused by the phrase "dir is null". `dir` is not null, but `entry` indeed becomes invalid after closing the handle.
I'll fix this.

**Comment by lslhcqy123** [comment]
ok

**Comment by apangin** [comment]
I committed the fix, please check if helps

**Comment by lslhcqy123** [comment]
Do i need close the issue?

**Comment by apangin** [comment]
Yes, feel free to close it, if there are no more questions.
Thank you for assistance.

**Comment by lslhcqy123** [comment]
Okay.
