### ISSUE TITLE
OpenTelemetry Traces

### ISSUE THREAD

**Issue by austince** [jvm-profiling-tools/async-profiler#652]
Hey there, wondering if there've been any discussions around supporting OpenTelemetry [traces](https://opentelemetry.io/docs/concepts/signals/traces/) as an output format. The [spec](https://opentelemetry.io/docs/reference/specification/status/#tracing) has stabilized, has a stable [Java sdk](https://opentelemetry.io/docs/instrumentation/java/#status-and-releases), and would make getting data into tools like Grafana, DataDog much easier.

**Comment by apangin** [comment]
Traces are not for profiling data.
But yes - there is an active ongoing discussion about OpenTelemetry profiling, see https://github.com/open-telemetry/oteps/issues/139

**Comment by austince** [comment]
Ah great, I wasn't sure if traces could be co-opted for profiling data. Thanks for the link. Should we close this or could we move it to a "OTel Support" tracker for whenever profiling data is supported? Seems like there is good momentum in https://github.com/open-telemetry/oteps/pull/212

**Comment by apangin** [comment]
It's ok to close this for now. I keep an eye on OpenTelemetry Profiling activity.
