### ISSUE TITLE
Container got restarted while measuring the context switches consumption

### ISSUE THREAD

**Issue by sattishv** [jvm-profiling-tools/async-profiler#658]
Team,

While trying to measure the impact of context switches we noticed the container got restarted. Here is the command line options we used. not sure whether we used the correct command line options . Our app resides inside the container we ran the profiler from the host.

 ./profiler.sh -e context-switches --fdtransfer -d 300 -f /tmp/microservice1000_ctxt_switches.html  PID
Target has requested perf_event_open for TID 179237 which is not a thread of process 5208
Target has requested perf_event_open for TID 180135 which is not a thread of process 5208
[WARN] perf_event_open for TID 179237 failed: No such process
[WARN] FdTransferClient recvmsg(): Interrupted system call
[WARN] perf_event_open for TID 179537 failed: Success
[WARN] FdTransferClient recvmsg(): Interrupted system call
[WARN] perf_event_open for TID 179585 failed: Success
[WARN] FdTransferClient recvmsg(): Interrupted system call
[WARN] perf_event_open for TID 179905 failed: Success
[WARN] FdTransferClient recvmsg(): Interrupted system call
[WARN] perf_event_open for TID 179994 failed: Success
[WARN] FdTransferClient recvmsg(): Interrupted system call
[WARN] perf_event_open for TID 180055 failed: Success
[WARN] perf_event_open for TID 180141 failed: No such process
[WARN] FdTransferClient recvmsg(): Interrupted system call
[WARN] perf_event_open for TID 180215 failed: Success
[WARN] FdTransferClient recvmsg(): Interrupted system call
[WARN] perf_event_open for TID 180220 failed: Success
Profiling for 300 seconds

Thanks

**Comment by apangin** [comment]
I found and fixed the bug that caused the following log messages:
```
[WARN] FdTransferClient recvmsg(): Interrupted system call
[WARN] perf_event_open for TID 179585 failed: Success
```
However, this is unlikely a cause of the container restart.

I'm not aware of your container configuration, it's rather a question to you why it restarts: is it because of a JVM crash, or out of memory, or excessive CPU usage?

**Comment by sattishv** [comment]
Thanks @apangin for the quick fix. Since docker logs are missing we couldn't check the reason for the restart. Will the fix be available in the next version so that i can check again.

**Comment by apangin** [comment]
async-profiler 2.9 includes the fix
