### ISSUE TITLE
arm64: Could not set dlopen hook

### ISSUE THREAD

**Issue by jheusser** [jvm-profiling-tools/async-profiler#660]
Using async-profiler-2.8.3-linux-arm64 we are seeing on some Ubuntu 20.04 on AWS Graviton2 the following error:

```
[ERROR] Could not set dlopen hook. Unsupported JVM?
```

On other AWS Graviton2 with same Ubuntu version async-profiler is working without issues.

Only difference between the installations we could figure out are that on the ones where it does **not** work the `libc6-lse` package is at version glibc (2.31-0ubuntu9.9) while the ones where it is working it is at
glibc (2.31-0ubuntu9.7). It seems the later version of `libc6-lse` has the atomics libs removed.

Working machine, e.g.:
```
libdl.so.2 => /lib/aarch64-linux-gnu/atomics/libdl.so.2 (0x0000ffffa7660000)
```

Not working machine:
```
libdl.so.2 => /lib/aarch64-linux-gnu/libdl.so.2 (0x0000ffff80582000)
```

But this might just be an unrelated observation, I can't tell entirely. JVM used is in all cases:

```
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-16.0.1+9 (build 16.0.1+9, mixed mode, sharing)
```

**Comment by apangin** [comment]
Can you please show the contents of `/proc/<pid>/maps` from both JVMs after attaching profiler?

**Comment by jheusser** [comment]
> Can you please show the contents of `/proc/<pid>/maps` from both JVMs after attaching profiler?

Working, after profiling:
```
fffd7007d000-fffd700bf000 r-xp 00000000 103:01 66747                     /tmp/async-profiler-2.8.3-linux-arm64/build/libasyncProfiler.so
fffd700bf000-fffd700ce000 ---p 00042000 103:01 66747                     /tmp/async-profiler-2.8.3-linux-arm64/build/libasyncProfiler.so
fffd700ce000-fffd700cf000 r--p 00041000 103:01 66747                     /tmp/async-profiler-2.8.3-linux-arm64/build/libasyncProfiler.so
fffd700cf000-fffd700d0000 rw-p 00042000 103:01 66747                     /tmp/async-profiler-2.8.3-linux-arm64/build/libasyncProfiler.so
```

Not working, after failed profiling attempt:
```
fffd5da14000-fffd5da56000 r-xp 00000000 103:01 275212                    /tmp/async-profiler-2.8.3-linux-arm64/build/libasyncProfiler.so
fffd5da56000-fffd5da65000 ---p 00042000 103:01 275212                    /tmp/async-profiler-2.8.3-linux-arm64/build/libasyncProfiler.so
fffd5da65000-fffd5da66000 r--p 00041000 103:01 275212                    /tmp/async-profiler-2.8.3-linux-arm64/build/libasyncProfiler.so
fffd5da66000-fffd5da67000 rw-p 00042000 103:01 275212                    /tmp/async-profiler-2.8.3-linux-arm64/build/libasyncProfiler.so
```

**Comment by apangin** [comment]
I meant full `/proc/<pid>/maps`.

Does the same error happen when running
`java -agentpath:/tmp/async-profiler-2.8.3-linux-arm64/build/libasyncProfiler.so=start -version` ?

**Comment by apangin** [comment]
OK, looks like the bug is already fix. Please try the version from `master`

**Comment by jheusser** [comment]
I can confirm this works with `master` without issues on the previously problematic machines, sorry could have tried this first!
