### ISSUE TITLE
Performance boost when starting profiling

### ISSUE THREAD

**Issue by ikorennoy** [jvm-profiling-tools/async-profiler#663]
Hello!

I have a simple benchmark that checks the performance of my java library for I/O through io_uring. 

The idea for the benchmark was taken from the fio library, its code is pretty simple, one thread performs interaction with io_uring and the other calculates performance. Under normal conditions, my library is about 50% slower than fio. This state of things didn't suit me and I tried to understand the reason and profiled different characteristics with async-profiler. In the process of profiling I came across an effect that I can't explain at all, when I turn on profiling events such as:

context-switches
cycles
instructions

maybe there are others, but with these the effect is reproduced all the time, the performance increases dramatically and becomes about equal to the fio benchmark (which I use as a reference).

Have you encountered this and what could be the explanation for this effect?

Thanks!

**Comment by apangin** [comment]
This sounds strange - I suspect an issue with your library or a benchmark. It's hard to tell exactly without seeing the code.

Keep in mind that while profiler is running, it sends signals to arbitrary application threads. These signals may interrupt certain I/O syscalls in the middle, causing them to return early either with partially processed data or with `EINTR` error code. JDK handles this automatically for you, but when you write your own native I/O library, it's up to you to take care of interrupted syscalls.

**Comment by ikorennoy** [comment]
Thanks for the answer.

The bug was indeed in the tests. True, it is still hard to say for sure how the profiler improved the benchmark performance, but after I fixed the bug the performance is the same as it was when I ran the profiler.
