### ISSUE TITLE
Much of the profile dominated by unknown_java 

### ISSUE THREAD

**Issue by danielshaya** [jvm-profiling-tools/async-profiler#667]
As requested a new issue for this issue:

<img width="2971" alt="Screenshot 2022-10-27 at 10 47 08" src="https://user-images.githubusercontent.com/5359230/198400504-c52e8c82-47c4-466a-9efb-8a383253fdde.png">

If you run the Aeron Archiving Media Driver for example you get this profile

When I run my own program about half the stack is unknown_java

I'm running with the Oracle 17 jdk :
java version "17.0.4" 2022-07-19 LTS
Java(TM) SE Runtime Environment (build 17.0.4+11-LTS-179)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.4+11-LTS-179, mixed mode, sharing)
(Also tried with openjdk -same result)

ProductName: macOS
ProductVersion: 12.6
BuildVersion: 21G115

**Comment by nitsanw** [comment]
Walking the stack during ‘System.nanoTime’ is for some reason difficult for AGCT. You can use a JMH workload to demonstrate.

**Comment by danielshaya** [comment]
Thanks for your reply.

That's not altogether surprising that a lot of stack traces would be lost, because System.nanotime() is a in the busy spin loop - but a shame nevertheless.  In your experience is there a workaround to this e.g. would it be better to use a C call from JNI to get the time (rather than the Agrona OffsetEpochNanoClock strategy to get wall time)? Although I notice that the stack gets to mach_absolute_time so not sure if even that would help? Sorry being lazy here but do you know if this is particularly problematic on osx or have you seen it on other oss as well?

**Comment by danielshaya** [comment]
Interestingly this is the same Aeron Archive Media Driver profiled under Flight Recorder (also AGCT?) - it doesn't seem to have any issues processing the stack traces (or at least it doesn't admit to any...) - although it doesn't tell you where in the method it got stuck i.e. it doesn't tell you it got stuck in the System.nanotime call.

<img width="1772" alt="Screenshot 2022-10-28 at 12 38 49" src="https://user-images.githubusercontent.com/5359230/198579064-6a9658d0-7815-4181-ba8f-367084f94b58.png">

**Comment by danielshaya** [comment]
Thank you for your excellent detailed answer - I suspected JFR might be being a bit sneaky...

I will try on Linux.

**Comment by apangin** [comment]
@vans239 `--cstack vm` makes use of DWARF unwinding info on Linux, so async-profiler should be able to get stack traces of `System.nanoTime` on Linux_x64 (a quick check confirms it does). If you still see an issue, please submit a bug or reopen this one. There is a known issue with nanoTime/currentTimeMillis intrinsics on AArch64 (#819) - I will create a workaround for it.

> critical JNI and nalim would have same problem

Critical JNI should not be a problem: JVM saves last Java frame anchor when calling native methods, whether JNICritical or not. Again, if you see an issue with critical natives, please submit a bug report.

Nalim is a different story: it generates a small frameless trampoline to call target native function. async-profiler will show as if this native function is called directly from the parent Java method. However, if an execution sample hits the trampoline itself, it will likely yield `[unknown_Java]`.
