### ISSUE TITLE
How to use live option in allocation profiling 

### ISSUE THREAD

**Issue by sattishv** [jvm-profiling-tools/async-profiler#668]
We tried to generate an allocation profile having only live objects with the help of option --live. But ended up with Unrecognized option: --live

./profiler.sh --fdtransfer -e alloc  --live -d 300 -o collapsed -f /tmp/raes_alloc_live_collapsed_1.txt PID.

Am i missing any parameters . We used version async version 2.8.3

**Comment by apangin** [comment]
`--live` option has been added recently; it's available if you build async-profiler from `master`.
It will get into the next release.

**Comment by sattishv** [comment]
With --live option are we triggering a Full GC to make sure the heap has only live objects like what a heap dump does.

**Comment by apangin** [comment]
No, GC is not triggered. A sample that is not referenced but has not been yet collected will be visible in the leak report.

**Comment by apangin** [comment]
`--live` option is available in async-profiler 2.9
