### ISSUE TITLE
java.lang.NoClassDefFoundError: one/profiler/Instrument occurs when using Java method profiling

### ISSUE THREAD

**Issue by muqingCai** [jvm-profiling-tools/async-profiler#674]
I tried using Java mehod profiling to instrument the given Java method in order to record all invocations of this method with the stack traces, but got this error:

Part of the stack is desensitized for privacy, but does not affect reading~

`2022-11-06 13:28:52,554 [/// - ] ERROR xx - Request error:
java.lang.NoClassDefFoundError: one/profiler/Instrument
	at com.xx.xx
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:874)`

async-profiler can start normally, but the mothod to be profiled throwed this error, I suspect it is a classloader problem

the classloader of one.profiler.Instrument is as follows:
 
![image](https://user-images.githubusercontent.com/37564566/200173386-c7cf88bc-d9bd-4e61-bd3d-b76d629fc2ee.png)

the classloader of target class to be profiled  is as follows:
![image](https://user-images.githubusercontent.com/37564566/200173418-c2f5cfd7-0913-43f7-9ab0-289871e97047.png)

**Comment by apangin** [comment]
What are the JVM, JDK and async-profiler versions?
Can you possibly create a minimal example that reproduces the problem without depndency on private classes?

**Comment by apangin** [comment]
In the lack of further details, closing the issue as not reproducible.
