### ISSUE TITLE
how to sort profile result?

### ISSUE THREAD

**Issue by Holmesus** [jvm-profiling-tools/async-profiler#676]
Hi,i'm using wall clock feature to analyze my application in order to optimize start up time.But there is a problem that i can't find the most time-consuming frame in the frame graph.Maybe sort the profile result is a good idea,but i can't sort the data in profile.html,it seems that this is not a original frame graph format.So, how can i find the most time-consuming frame?

**Comment by Jongy** [comment]
async-profiler has several output modes, flamegraph is an hierarchical one not suitable for finding the "top frame". I suggest you try `flat` mode which gives you the top frames. (Generally, see options [here](https://github.com/jvm-profiling-tools/async-profiler#profiler-options))

**Comment by Holmesus** [comment]
thanks a lot for your reply.I find the collapsed format suitable for me.thank you anyway~
