### ISSUE TITLE
Need a way to get outer class name for anonymous classes in profile

### ISSUE THREAD

**Issue by theosib-amazon** [jvm-profiling-tools/async-profiler#683]
I'm trying to use async-profiler to analyze Apache Spark performance, and I find that, even when codegen disabled, the majority of CPU time is spent in methods in anonymous classes. Example:

```
scala/collection/Iterator$$anon$11.hasNext
```

I cannot work out from anything in the flame graph where this `Iterator$$anon$11` came from, which would be the outer class where it was created, so there's no way I can track it down.

It would be great if async-profiler provided some way to determine what class created this lambda.

The closest I've found to anyone ever even asking about this is from [Finding a specific lambda noted in a Profiler](https://stackoverflow.com/questions/33206372/finding-a-specific-lambda-noted-in-a-profiler), but that doesn't seem super helpful.

Thanks.

**Comment by theosib-amazon** [comment]
Also, I asked about this on stackoverflow: https://stackoverflow.com/questions/74465755/how-to-get-useful-names-for-anonymous-java-methods-using-async-profiler

**Comment by apangin** [comment]
Method `scala/collection/Iterator$$anon$11.hasNext` is defined in `Iterator.scala` from Scala standard library.

You can produce a Flame Graph with line numbers. To do that, use `jfr` output format when profiling and then run `jfr2flame` utility included in async-profiler package to convert the output to a Flame Graph:
```
java -cp converter.jar jfr2flame --lines output.jfr output.html
```

**Comment by Trass3r** [comment]
Is there a reason the direct flamegraph output doesn't have this `--lines` option?

**Comment by apangin** [comment]
@Trass3r No, just wasn't implemented in lack of demand. I'm happy to review a PR if you'd like to contribute.
