### ISSUE TITLE
Native method to profile for serialization cost

### ISSUE THREAD

**Issue by sattishv** [jvm-profiling-tools/async-profiler#688]
Team,

We wanted to measure the time spent by the application for serialization and deserialization operation.  If so which native method should we use profile in async-profiler in order to record all invocations of this method with the stack traces. Could you please share your thoughts

Thanks
Sattish

**Comment by apangin** [comment]
There is no single method responsible for serialization / deserialization.
What kind of serialization do you use?

**Comment by sattishv** [comment]
Mainly we use jackson library for object serialization and dozer for object mapping

**Comment by apangin** [comment]
So why not just searching for "jackson" on a flame graph - it will highlight all the places where jackson methods are called and show the total % of CPU time spent on jackson serialization/deserialization.

**Comment by sattishv** [comment]
thanks will check with my profiles
