### ISSUE TITLE
args._event equals "cpu" when sending "alloc" event in profiler.sh

### ISSUE THREAD

**Issue by lslhcqy123** [jvm-profiling-tools/async-profiler#693]
Hi,i felt a little confused when i want to get allocation of one process whereas the args._event in log is "cpu".I am not sure if it is intentionally.Below is my settings: 

1. openjdk version "11" 2018-09-25 OpenJDK Runtime Environment 18.9 (build 11+28) OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
2. async-profiler-2.8.3 release
3. cmd:./profiler.sh -e alloc --alloc 1k -o traces jps
4. my log: profiler.cpp:1273
  `void Profiler::dumpText(std::ostream& out, Arguments& args) {
    printf("enter Profiler::dumpText,args.event:%s\n",args._event);`
5. testcode:
`import java.util.Random;
public class TestBanking {
    public static void main(String[] args)throws InterruptedException {
        int total=100;
        StringBuilder sb1=new StringBuilder();
        int x[]=new int[total];
 

        for (int i=0;i<16000;i++){

                for(int j=0;j<total;j++){
                        int a=1;
                        char b='c';
                        Random random = new Random();
                        int rannum = random.nextInt(101);

                        sb1.append('a'+"");
                        sb1.append('b'+"");
                        x[j]=rannum;
                }
                Thread.sleep(1000);

        }

   }  
}`

**Comment by apangin** [comment]
`-e alloc` is an obsolete way to enable allocation profiling; it remains for compatibility reasons only.
`--alloc <size>` is a preferred way. `-e alloc` is ignored when `--alloc <size>` is specified.

Similarly, `--lock <size>` is preferred to `-e lock`.

These changes were needed to allow CPU, Allocation and Lock profiling simultaneously.

**Comment by lslhcqy123** [comment]
ok,I got it.
