### ISSUE TITLE
Converter improvement - ranged flamegraphs 

### ISSUE THREAD

**Issue by franz1981** [jvm-profiling-tools/async-profiler#695]
For long running profiling sessions is often useful to run profiling with loop option (JFR) and convert the traces in flamegraphs via converters, but sometime if there is a single JFR profiling data available would be great to extract disjoint ranged flamegraphs from it too (specifying, similar to loop option, a period/interval).

**Comment by apangin** [comment]
`jfr2flame` converter supports `--from`/`--to` arguments, see https://github.com/jvm-profiling-tools/async-profiler/pull/526#issuecomment-1149334133 - you can build a flame graph only for the specified time range.

Even better solution will be a heatmap that displays the entire .jfr on one screen and allows you to interactively get a flame graph for an arbitrary time range.

**Comment by franz1981** [comment]
I have missed it, sorry 😞
Let me close this as duplicated 

But..heatmap? We have a built-in solution wiy ap?
