### ISSUE TITLE
Built-in support for report dump at configurable intervals

### ISSUE THREAD

**Issue by zabetak** [jvm-profiling-tools/async-profiler#698]
Attaching the profiler as an agent and generating a report when the application terminates is an extremely useful and convenient feature. 

There is one caveat though, cause if the application is killed (SIGKILL) all the profiling done so far will be lost.

It would be pretty convenient if there was an option to dump the report at some configurable intervals to avoid losing everything when an applications terminates abnormally.

The same behavior could be achieved by introducing external scripts that request a dump from the JVM at regular intervals at the expense of extra complexity and code maintained in 3rd party repos.

Below some use-cases that inspired me to request this feature.

Profiling Apache Tez in the Hive/Yarn ecosystem. Tez workers are running in separate JVMs that can be scheduled to run in any node of the cluster. Usually they are stopped by Yarn either via SIGTERM or SIGKILL. The profiler can be easily used to profile any Tez JVM in the cluster since it is possible to define the JVM options in a centralized configuration file. However, the fact that Tez workers are stopped sometimes with SIGKILL makes this approach not feasible. The workaround is to rely on custom scripts that need to be deployed and run independently on the cluster that will detect the correct PIDS and request a dump before the application is stopped.

Profiling JVM applications/tests running in CI (e.g., GitHub actions) with timeout in place. GitHub actions and other CI providers allow to use timeouts to stop applications when they misbehave (and SIGKILL is a convenient way to do it). Getting the profiling report for a run that exceeded the timeout is extremely useful for diagnosing and fixing problems.

**Comment by apangin** [comment]
Async-profiler already has the proposed functionality. There are at least to ways to achieve the goal:

### 1. `--loop` option

> `--loop TIME` - run profiler in a loop (continuous profiling). The argument is either a clock time (hh:mm:ss) or a loop duration in seconds, minutes, hours, or days. Make sure the filename includes a timestamp pattern, or the output will be overwritten on each iteration.
> Example: `./profiler.sh --loop 1h -f /var/log/profile-%t.jfr 8983`

Of course, instead of 1 hour, you can set a lower dumping interval, e.g. `5m`, `60s`, etc.

### 2. Chunked JFR output

If you prefer to have one single recording that could be read even after the abnormal termination, use `jfr` format with `--chunktime` option. E.g. `--chunktime 2m` will make a checkpoint (i.e. flush jfr output) every 2 minutes. In case the JVM crashes, you will lose at most the last 2 minutes of profiling, but the rest of the recording will be valid.

**Comment by zabetak** [comment]
After seeing the answer I feel pretty stupid that I missed those options; I should have checked better before creating the request. Many thanks for the feedback and apologies for taking your time.
