### ISSUE TITLE
[ERROR] Profiler already started - easy to reproduce

### ISSUE THREAD

**Issue by ornicar** [jvm-profiling-tools/async-profiler#699]
Thanks for the fantastic profiler!

Providing a non-existing destination file path permanently locks the profiler, until the Java process is restarted.

```
# async-profiler -d 10 -e cycles -f /this/path/does/not/exist/profile.html MyMainClass
Profiling for 10 seconds
Done
[ERROR] Could not open output file

# async-profiler -d 10 -e cycles -f profile.html MyMainClass
[ERROR] Profiler already started
```

Is there a way to unlock it?

```
# async-profiler --version
Async-profiler 2.9 built on Dec 12 2022
Copyright 2016-2021 Andrei Pangin

# java -version
openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment (build 17.0.5+1)
OpenJDK 64-Bit Server VM (build 17.0.5+1, mixed mode)

# uname -a
Linux crom 5.19.11-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 24 Sep 2022 18:24:15 +0000 x86_64 GNU/Linux
```

**Comment by ornicar** [comment]
Welp, it seems that after async-profiler got blocked by the issue above, it started leaking infinite memory in the JVM process, until it was killed by the kernel OOM killer.

![](https://monitor.lichess.ovh/dashboard/snapshot/BQws6I51M4XGVAu5SRnuk6JscviBbKp1?orgId=1&viewPanel=4)

We had the bug yesterday at 12:49 and today just after the JVM restart. OOM kill at 16:20, ouch.

**Comment by apangin** [comment]
`profiler.sh -d N` is a shortcut for
```
profiler.sh start
<wait for N seconds>
profiler.sh stop
```
In your case, `stop` fails because of an invalid output filename, therefore, profiler keeps running (and eating memory). Hence the `Profiler already started` error.

Just stop the profiler with `profiler.sh stop` command. You can pass `-f FILENAME` option to `stop` command to dump the collected profile data,
