### ISSUE TITLE
Profiler options (-o, -t) are "persisted" between profiler runs (pairs of attach-stop)

### ISSUE THREAD

**Issue by stIncMale** [jvm-profiling-tools/async-profiler#70]
**async-profiler version**
8b2fd87c03f49c7b4f508b659ed58ac890124fab

**Description**
Profiler options (at least `-o` and `-t`) are "persisted" between profiler runs (pairs of attach-stop). As a result, one can not disable them once they have been set.

**Steps to reproduce**

0. Start or restart a Java process that will be profiled.
1. Run `profiler.sh -d 5 -f prof.txt -o summary,traces=1 -t 1234`.
2. Try turning off `-t` option and disable `traces`: `profiler.sh -d 5 -f prof.txt -o summary 1234`.
3. Observe that profiler's output still works as if options `traces=1 -t` have been set.

**Workaround**
Restart the Java process that is being profiled. This means that the profiler options are either stored in the memory of the process, or in a temporary file that is deleted once the process quits.

**Comment by apangin** [comment]
Thank you for the report. The problem has been introduced in the last commit: 8b2fd87c03f49c7b4f508b659ed58ac890124fab. You may take the previous version for now.
The fix will follow soon.
