### ISSUE TITLE
Monitor process twice in container,get differrent result. 

### ISSUE THREAD

**Issue by lslhcqy123** [jvm-profiling-tools/async-profiler#706]
@apangin Hey,i came up with a problem:when i tried to get allocation of a process running in alpine container,first time i got the call stacks,however,when tried again,i got the following tips:
"[WARN] Install JVM debug symbols to improve profile accuracy
[ERROR] No AllocTracer symbols found. Are JDK debug symbols installed?"

So i search the tip in source code and insert some logs,and i found the reason is the first time i hit the objectSampler engine,and second time i hit the alloctracer engine.This seems weird,becasue the process i monitor is actually the same one.

Finally,i found the direct cause of two different engines is:
vmEntry.cpp 
if (_jvmti->AddCapabilities(&capabilities) != 0) {}
"_jvmti->AddCapabilities(&capabilities)" calculation results is different,first time i got "_jvmti->AddCapabilities(&capabilities) "equals 0,sencond time i got 1,thus "_can_sample_objects = false;".

So i insert "_jvmti->GetCapabilities(&capabilities);"before "if (_jvmti->AddCapabilities(&capabilities) != 0) {}",and the error tips didn't appear anymore.,however,call stacks disappear too :(

I guess the reason may be "Some virtual machines may allow a limited set of capabilities to be added in the live phase." which is from https://docs.oracle.com/en/java/javase/11/docs/specs/jvmti.html#jvmtiCapabilities

**Comment by lslhcqy123** [comment]
my environmental configuration is:
java process is runned in alpine container,jdk version is:

c3be1b282356:/home# java -version
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment (build 11.0.9+11-alpine-r1)
OpenJDK 64-Bit Server VM (build 11.0.9+11-alpine-r1, mixed mode)

async-profiler-2.8.3 is running in another alpine container which is runned with "docker run -d --pid=host --privileged --name monitor imageid sleep inf"

**Comment by apangin** [comment]
You can run profiler as many times as you wish, as long as you use the same profiler library on the same path.
`VM::init` and therefore `AddCapabilities` is called just once in this case.

Loading two different versions of async-profiler simultaneously (or the same version located in different directories) is not supported. This issue is tracked in #701.

**Comment by lslhcqy123** [comment]
> You can run profiler as many times as you wish, as long as you use the same profiler library on the same path. `VM::init` and therefore `AddCapabilities` is called just once in this case.
> 
> Loading two different versions of async-profiler simultaneously (or the same version located in different directories) is not supported. This issue is tracked in #701.

**Comment by lslhcqy123** [comment]
sorry,i unintentionally closed the issue,my problem is actually different from [https://github.com/jvm-profiling-tools/async-profiler/issues/701](url) .i didn't load two different versions of async-profiler simultaneously or load the same version located in different directories

**Comment by apangin** [comment]
What is the output of `cat /proc/[pid]/maps | grep asyncProfiler` after the second (unsuccessful) profiling attempt?

**Comment by apangin** [comment]
Yes, since you delete `libasyncProfiler.so` after profiling, the next time you load it, it is treated as a new library.
Hence the same issue as in #701.

**Comment by lslhcqy123** [comment]
"Currently async-profiler cannot be loaded twice from different locations.",Can this be resolved?At present profiling CPU twice is OK

**Comment by apangin** [comment]
The problem can be solved. If that was trivial, I would have done that already. But since it is not, and since there is a straightforward workaround (just reuse the agent loaded once), the issue is not on the top of my current priorities.

**Comment by lslhcqy123** [comment]
OK,I got it.
