### ISSUE TITLE
Snapshot publishing?

### ISSUE THREAD

**Issue by vkostyukov** [jvm-profiling-tools/async-profiler#72]
First of all, thanks a ton for this profiler - I have been playing with it at $work and it seems to produce quite reasonable results. We're looking into ways to adopt it in our simulation runs (to identify performance problems earlier).

The problem I'm facing has probably nothing to do with the project itself - I'm quite terrible at building native packages. Is there a way to publish snapshot on regular basis (I'm not sure how this supposed to be distributed through)? I'd probably be just as happy with a new release containing binaries for Linux.

**Comment by apangin** [comment]
Thank you for the feedback.
Yes, I'm planning to do releases on a regular basis.
Currently there is a number of new features and bugfixes in master. They have been out for a while, and I believe it is a good time to publish v1.1 release.
Will make it shortly.

**Comment by apangin** [comment]
v1.1 release is [published](https://github.com/jvm-profiling-tools/async-profiler/releases/tag/v1.1)!
Feedback is welcome.
