### ISSUE TITLE
Licensing and distribution question

### ISSUE THREAD

**Issue by alexander-yakushev** [jvm-profiling-tools/async-profiler#75]
Hi, I'd like to create a Clojure wrapper library around async-profiler so that the profiler can be used from within the JVM process itself. This would require me to package the pre-built `libAsyncprofiler.so` file into a JAR, later to be deployed to https://clojars.org/. The wrapper itself is going to be open-source and hosted on Github, and it goes without saying that I will provide links and references to the original async-profiler library wherever necessary. My questions are:

1. Am I allowed to do that at all?
2. What license should I pick for that project then? Most Clojure projects are licensed under EPL, can I do that, or should I stick to Apache-2.0?

**Comment by apangin** [comment]
The careful reading of the [license](https://github.com/jvm-profiling-tools/async-profiler/blob/master/LICENSE) should answer the questions.
As far as I see, there is no problem in including async-profiler binary in the EPL licensed project as long as you provide a copy of Apache License v2 with it. Any work based on async-profiler (unless it is a separate software that just links to it by the public interfaces) should also retain the original copyright notice in the source form.

Different parts of the software may be licensed under AL or EPL. The notable example of such multi-license project is Jetty. I believe your library can go this way, too.

Good luck!

**Comment by alexander-yakushev** [comment]
Thanks for the prompt response, Andrei! I will proceed in the way you've suggested. Going to ping back with the link to the wrapper, just in case.

**Comment by alexander-yakushev** [comment]
As promised:

- Library: https://github.com/clojure-goes-fast/clj-async-profiler
- Announcement blog post: http://clojure-goes-fast.com/blog/profiling-tool-async-profiler/

Hopefully, I've done everything properly. But if some additional references/attributions/modifications should be made, I'm happy to do it.
