### ISSUE TITLE
Is it common have allocate__from__tlab__slow in memory allocation?

### ISSUE THREAD

**Issue by zdyj3170101136** [jvm-profiling-tools/async-profiler#787]
i use async-profiler memory event, and tran it to pprof.
there are lots of allocate__from__tlab__slow in callchain medium, is this common?
i think function allocate__from__tlab__slow should only occur in callchain top.

![截屏2023-08-02 下午5 39 31](https://github.com/async-profiler/async-profiler/assets/52686065/70b3f90a-e7eb-4f5a-9af3-440839406d8b)

**Comment by apangin** [comment]
Feel free to reopen the issue if you can reproduce it without pprof.

**Comment by zdyj3170101136** [comment]
> Feel free to reopen the issue if you can reproduce it without pprof.

just a jfr to pprof error.
