### ISSUE TITLE
Flame Graph visualization doesn't work out of box

### ISSUE THREAD

**Issue by stepan-romankov** [jvm-profiling-tools/async-profiler#80]
When I execute `./profiler.sh -d 10 -f /tmp/flamegraph.svg {precess id}`
 /tmp/flamegraph.svg contains following text:
`--- Execution profile ---
Total samples:         17
Non-Java:              16 (94.12%)
Unknown (native):      1 (5.88%)

Frame buffer usage:    0%
`

Expected: **file containing SVG data.**

**Comment by apangin** [comment]
I'm pretty sure you run older version of the profiler. Please note that
1) the version with FlameGraph support is not yet released - you have to built it yourself from sources;
2) if a previous version of libasyncProfiler.so has been attached to a Java process, a newer version won't work until you restart the target process.

**Comment by apangin** [comment]
@stepan-romankov Any news on this issue? Or can I close it as not reproducible?

**Comment by stepan-romankov** [comment]
@apangin sure, please close it. When do you plan to release FlameGraph support?

**Comment by apangin** [comment]
@stepan-romankov In the beginning of March, along with some other fixes.
If you need the binary with FlameGraph support before the release, let me know.
