### ISSUE TITLE
Dumping profiles can take a long time

### ISSUE THREAD

**Issue by hvanhovell** [jvm-profiling-tools/async-profiler#81]
First of, I would thank you for creating this great tool. It is really invaluable for diagnosis JVM performance issues.

When I run the profiler for a long time writing a collapsed profile can take a long time. For example a 30 second run can create a file of ~150 MB which takes 10 min to write. Which is kinda slow (250 kb/s). I did take a look at the source, and cannot find any obvious problem with it (no excessive flushing).

I am wondering if this can be sped up. A viable alternative solution (for me) would be to dump the traces and the method names to disk and to build the collapsed profiles (or any other profile) later on. That should relatively compact and should easy to dump to disk.

**Comment by apangin** [comment]
Thank you for the feedback.
Sounds interesting, I haven't seen such a problem before. Looks like I need to profile the profiler :)
I'll investigate this. Meanwhile can I ask you to compare the file size and the generation time of the same profile in two formats: `-o collapsed` vs. `-o svg`?

BTW, how do you run the profiler?
`./profiler.sh -d 30 -o collapsed -f profile.dump PID` or someway else?

**Comment by hvanhovell** [comment]
Thanks for your quick reply!

Let me try the `svg` option. I will try to get to this in the next two days.

If I use the flamegraph script, the resulting flamegraph can be around 8-10 MB in size. You can tune this by setting `minwidth` option to something reasonable, that will usually result in a file size of  800 KB. 

I will also try to give some color to what I am doing. I am generally profiling one or more machines (workers) at the same time. The profiler is controlled using RPCs and these start & stop the local profiler directly using `jattach` (using the script didn't seem necessary). Earlier I did run the profiler using a command similar to  `./profiler.sh -d 30 -o collapsed -f profile.dump PID` and this took the same amount of time.

Finally, dumping SVG's directly is very useful, but in some cases it is nice to combine the profiles generated by the multiple machines (assuming that you are running the same job); this is trivial using the collapsed format.

**Comment by apangin** [comment]
The goal of comparing `-o collapsed` vs. `-o svg` is primarily for me to understand whether the time is spent mostly to get method names or to print them.

**Comment by hvanhovell** [comment]
The I just compared them and it seems that generating an SVG is a little bit slower (3.5 vs. 3.8 min). The command that generates these profiles took 3 seconds to run BTW, the profiler was running for 5 seconds.

I also noticed that the SVG produced by the profiler is smaller (and is coarser) than the SVG produced by the combination of the `collapsed` format and the FlameGraph script. Is this by design?

**Comment by apangin** [comment]
> SVG produced by the profiler is smaller (and is coarser) ... Is this by design?

Yes. The default `minwidth` threshold in async-profiler is 1 comparing to 0.1 in flamegraph.pl.

minwidth==1 corresponds to 1/1200 of total samples, which is less than 0.1%. I believe smaller call stacks are not really important in most cases, but they make output much bigger. For example, flamegraphs larger than 10MB are almost unusable in Chrome.

Anyway, I'll make `minwidth` configurable: #82

**Comment by hvanhovell** [comment]
Yeah, that could be it. I am running this on OpenJDK 8u151.

**Comment by apangin** [comment]
@hvanhovell I've made a fix to work-around this nasty bug with slow JVMTI functions.
Please check [slow-output](https://github.com/jvm-profiling-tools/async-profiler/tree/slow-output) branch to verify that the problem has been fixed.

**Comment by hvanhovell** [comment]
Awesome! I'll give it a spin in the tomorrow.

**Comment by hvanhovell** [comment]
@apangin this seems to do the trick! I tried it on one instance where dumping the profile would take 1.7 min, this now completes in 3 seconds.

**Comment by apangin** [comment]
Thanks! I've merged the fix to master.
