### ISSUE TITLE
Make FlameGraph parameters configurable

### ISSUE THREAD

**Issue by apangin** [jvm-profiling-tools/async-profiler#82]
Add command-line option to tune certain FlameGraph attributes:

- imagewidth
- frameheight
- minwidth
- etc.

**Comment by apangin** [comment]
Added the following command-line options:
```
  --title TITLE
  --width PX
  --height PX
  --minwidth PX
```

**Comment by retronym** [comment]
`--reverse` is handy too.

**Comment by ceeaspb** [comment]
```flamegraph.pl``` ```--reverse``` and ```--inverted``` (ie. icicle graph) work together to keep the stack the right way up while grouping by the top of stack - I use it for the allocation profiling, it can be used elsewhere also.

**Comment by apangin** [comment]
@ceeaspb So what do you suggest?

**Comment by ceeaspb** [comment]
add support for ```--inverted``` if possible

**Comment by apangin** [comment]
While this one is easy to implement, I don't actually plan to replicate and maintain all possible FlameGraph options. It will be enough to support just the most common use case. `collapsed` output provides the possibility to customize flame graphs using external script.

Does it make sense to combine `--reverse` and `--inverted` into one singe option? I have never used icicle graphs myself, but if this is a popular use case, I don't mind adding this option to async-profiler.
