### ISSUE TITLE
Compile error on alpine linux

### ISSUE THREAD

**Issue by jeroentervoorde** [jvm-profiling-tools/async-profiler#86]
Compilation fails with this error:

g++ -O2 -I/opt/jdk/include -I/opt/jdk/include/linux -fPIC -shared -o build/libasyncProfiler.so src/*.cpp -ldl -lpthread
In file included from /usr/include/limits.h:8:0,
                 from /usr/include/sys/param.h:33,
                 from src/profiler.cpp:23:
src/arch.h:23:21: error: expected unqualified-id before numeric constant
 const unsigned long PAGE_SIZE = 4096;
                     ^
make: *** [Makefile:34: build/libasyncProfiler.so] Error 1

Page size is defined in /usr/include/bits/limits.h and set to 4096.

This fixes it:
https://github.com/jvm-profiling-tools/async-profiler/pull/85

**Comment by apangin** [comment]
Resolved by #85
