### ISSUE TITLE
linux binaries in 1.1 release seems not to support svg format

### ISSUE THREAD

**Issue by oshai** [jvm-profiling-tools/async-profiler#87]
I download binaries from here: https://github.com/jvm-profiling-tools/async-profiler/releases/download/v1.1/async-profiler-1.1-linux-x64.zip

After some trial and error I got to this:

Unrecognized option: --title
Usage: ./profiler.sh [action] [options] <pid>
Actions:
  start             start profiling and return immediately
  stop              stop profiling
  status            print profiling status
  list              list profiling events supported by the target JVM
  collect           collect profile for the specified period of time
                    and then stop (default action)
Options:
  -e event          profiling event: cpu|alloc|lock|cache-misses etc.
  -d duration       run profiling for <duration> seconds
  -f filename       dump output to <filename>
  -i interval       sampling interval in nanoseconds
  -b bufsize        frame buffer size
  -t                profile different threads separately
  -o fmt[,fmt...]   output format: summary|traces|flat|collapsed

<pid> is a numeric process ID of the target JVM
      or 'jps' keyword to find running JVM automatically using jps tool

Example: ./profiler.sh -d 30 -f profile.fg -o collapsed 3456
         ./profiler.sh start -i 999000 jps
         ./profiler.sh stop -o summary,flat jps

note svg format is not there.

**Comment by apangin** [comment]
FlameGraph features is not yet released in binaries:
https://github.com/jvm-profiling-tools/async-profiler/blob/master/CHANGELOG.md

You can [build](https://github.com/jvm-profiling-tools/async-profiler#building) it yourself from sources (this is almost one `make` command). Or let me know if you need binaries before the "official" release which I plan to do in a week or so.

**Comment by oshai** [comment]
It's not urgent because I managed to use sources. Its just confusing.

**Comment by apangin** [comment]
OK, no problem. New release will be available shortly.
