### ISSUE TITLE
ReentrantLock contention

### ISSUE THREAD

**Issue by franz1981** [jvm-profiling-tools/async-profiler#90]
Hi guys,

First on above: thanks for this awesome project and for the hard work on it!!!

Now my question: would be possible to have a contention profiling for Java's `ReentrantLock`s similar to the `-e lock` option? 

I was looking http://www.brendangregg.com/offcpuanalysis.html to find something similar, given that under contention `ReentrantLock` uses Unsafe::park/unpark, but having it on the async-profiler toolkit would be awesome.
If there is something I could help to make it possible I would be very happy to contribute :+1: 

Thanks,
Franz

**Comment by apangin** [comment]
Yes, this is absolutely possible. I think I can implement this if not in the nearest, then in the next release.

**Comment by franz1981** [comment]
That's would be awesome, thanks!

**Comment by apangin** [comment]
`-e lock` now handles both intrinsic locks and ReentrantLocks.

**Comment by franz1981** [comment]
Thanks for this change!!!
I've just refreshed by local repo with the last changes and compiled the whole with make.
I'm not a C guy and I'm hoping to do not have mess with anything...

I've built this test program:
```
   public static void main(String[] args) {
      final int tokens = 1;
      final boolean jucLock = true;
      final ReentrantLock lock = new ReentrantLock();
      final Object obj = new Object();
      final int writers = 4;
      final AtomicBoolean stop = new AtomicBoolean();
      ExecutorService executorService = Executors.newCachedThreadPool();
      for (int i = 0; i < writers; i++) {
         if (jucLock) {
            executorService.execute(() -> {
               while (!stop.get()) {
                  lock.lock();
                  Blackhole.consumeCPU(tokens);
                  lock.unlock();
               }
            });
         } else {
            executorService.execute(() -> {
               while (!stop.get()) {
                  synchronized (obj) {
                     Blackhole.consumeCPU(tokens);
                  }
               }
            });
         }
      }
      executorService.shutdown();
      Runtime.getRuntime().addShutdownHook(new Thread(() -> {
         stop.lazySet(true);
      }));
   }
```
Using synchronized I'm getting this:
![image](https://user-images.githubusercontent.com/13125299/36931293-3a300386-1eb3-11e8-9dc2-a7d9f7fa4a4f.png)

While for the `ReentrantLock` I'm receiving from `flamegraph`:
```
ERROR: No stack counts found
```
Probably I've done something wrong on compilation or the test I've written has something wrong.
There is anything I could do to help beside looking at `make` output (that  doesn't seems to have emitted any warning/error)?

**Comment by apangin** [comment]
Works for me. How do you run the target program and the profiler? What JDK version do you use?

`./profiler.sh -d 10 -e lock -f locks.svg PID` generates the following flame graph:

![locks](https://user-images.githubusercontent.com/1749416/36936419-46b7eb92-1f16-11e8-893e-5861d02d6a70.png)

**Comment by franz1981** [comment]
thanks for the help :+1:

> How do you run the target program and the profiler

So, running your command seems to not work for me, so I've tried this one instead:
```
$ ./profiler.sh -d 10 -o collapsed -f /tmp/collapsed.txt -e lock PID
$ ~/FlameGraph/flamegraph.pl --width=1920 --colors=java /tmp/collapsed.txt > lock.svg
```
There is anything I need to export (eg FLAMEGRAPH_HOME) in order to just use 1 command?

> What JDK version do you use

```
java -version
openjdk version "1.8.0_161"
OpenJDK Runtime Environment (build 1.8.0_161-b14)
OpenJDK 64-Bit Server VM (build 25.161-b14, mixed mode)
```
While I'm using the last master of `async.profiler` and configured the last Fedora with:
```
$ sudo dnf debuginfo-install java
-- install Package java-1.8.0-openjdk-debuginfo-1:1.8.0.161-5.b14.fc27.x86_64
$ sudo dnf install java-debug
-- Package java-1.8.0-openjdk-debug-1:1.8.0.161-5.b14.fc27.x86_64
```
Before running `make` with no errors.

**Comment by apangin** [comment]
I guess in your case the number of contended intrinsic locks is so small comparing to ReentrantLocks, that intrinsic locks were skipped as negligible from the result flamegraph.

You may modify the threshold with `--minwidth` argument or try different output format (e.g. `-o traces`) to make sure intrinsic locks are still there.

**Comment by franz1981** [comment]
> I guess in your case the number of contended intrinsic locks is so small comparing to ReentrantLocks, that intrinsic locks were skipped as negligible from the result flamegraph.

Guess correct!
Thanks to have added this feature in such a small time!  :+1:
