### ISSUE TITLE
svg is broken

### ISSUE THREAD

**Issue by victornoel** [jvm-profiling-tools/async-profiler#94]
I built latest (0c1dd39) version of async-profiler with `JAVA_HOME=/usr/lib/jvm/java-8-openjdk make` and ran it with `./profiler.sh -f result.svg -d 100 13327`.

The resulting svg file gives the following output when opened in Firefox or Chromium:
![image](https://user-images.githubusercontent.com/160975/37346749-7d5fd3a0-26d0-11e8-84e8-9518d452ad78.png)

If needed I can provide the generated svg after I obfuscate the classes names or reproduce on a libre project ;)

**Comment by apangin** [comment]
Yes, please. An example of such .svg will be helpful.

**Comment by victornoel** [comment]
Here it is: https://gist.github.com/victornoel/9306861dbde29830b73c74221ba7167d

**Comment by apangin** [comment]
Thank you. I understand the problem now. Due to locale settings floating point numbers are formatted using `,` instead of `.`.

I'll fix that.

**Comment by apangin** [comment]
I've committed the fix. Please check if it helps.

**Comment by victornoel** [comment]
@apangin it works as expected, I'm closing the issue, thanks for the quick fix ;)
