### ISSUE TITLE
Consider DTrace use for macOS systems instead of Perf

### ISSUE THREAD

**Issue by dpoluyanov** [jvm-profiling-tools/async-profiler#95]
As I know DTrace by it's functionality resemble to Linux Perf, so could it be useful for system event profiling on macOS and probably other BSD based systems?

**Comment by apangin** [comment]
Please note that async-profiler does not use `perf`, but rather [`perf_event_open`](http://man7.org/linux/man-pages/man2/perf_event_open.2.html), which is public standard API for dealing with hardware and software profiling events on Linux.

AFAIK there is no similar API on BSD/macOS. `dtrace` is a standalone utility. There is some C level API to libdtrace, though it's quite different from `perf_event_open`, and I'm not sure how standard and reliable it is.

Anyway, I'll be happy to accept contributions if someone would like to take over this feature.

**Comment by Camelion** [comment]
Thanks for explanation, Andrei. 
Even if BSD and macOS has a different API for `libdtrace` both use similar approach for tracing, so implementation for one will be helpful for another. 
I've wish to play with `ustack()` dtrace probe, that looks like missing part for restoring system piece of stack.
Can you keep this issue open for a some time?

**Comment by apangin** [comment]
Sure!

**Comment by apangin** [comment]
I've implemented native stack walking on macOS in #137. Will merge into master soon.
Now async-profiler shows all JVM code, native methods, libraries etc. - basically everything that `ustack()` covers.

The only missing thing left is kernel stack trace. BTW, `ustack()` does not cover this, too - there is a separate `stack()` function for recording kernel traces.

After investigation of DTrace possibilities I must conclude that adding kernel traces will be really hard if not impossible. Furthermore, kernel profiling is forbidden by default by SIP (System Integrity Protection). Finally, there is a very limited set of operations allowed in dtrace probe context. In particular, I don't see a way how to invoke a user-land callback synchronously in the same thread right after recording kernel stack trace.

I believe the implemented functionality provides the full picture of what happens inside JVM and Java code, so let me close the issue.
