### ISSUE TITLE
Respresent unrecognized stacks on FlameGraphs

### ISSUE THREAD

**Issue by leventov** [jvm-profiling-tools/async-profiler#96]
The default output mode prints statistics about unrecognized stacks in the beginning, e. g.
```
--- Execution profile ---
Total samples:         27890
Non-Java:              5103 (18.30%)
GC active:             54 (0.19%)
Unknown (native):      196 (0.70%)
Unknown (Java):        6 (0.02%)
```

What about outputting those columns on FlameGraphs, to make it less likely for users to miss potentially important parts of the perf picture (as in this example, 18% of non-Java samples)?

**Comment by apangin** [comment]
FlameGraph already includes those, since it displays not only Java threads, but native threads, too.

- `Non-Java` usually comes from GC threads, VMThread and WatcherThread.
- `Unknown (native)` usually denotes Compiler threads.

See #35 for the related issue.
