### ISSUE TITLE
Weird fd=0 input in PerfEvents::signalHandler 

### ISSUE THREAD

**Issue by advancedxy** [jvm-profiling-tools/async-profiler#98]
Sometimes, the PerfEvents received a weird fd=0 and causes the profiler hanging. I haven't identified the root cause yet, and by add the following code as a workaround:

``` C++
 void PerfEvents::signalHandler(int signo, siginfo_t* siginfo, void* ucontext) {
     u64 counter;
-    if (read(siginfo->si_fd, &counter, sizeof(counter)) != sizeof(counter)) {
+    if (siginfo->si_fd == 0) {
+           counter = 1;
+    } else if (read(siginfo->si_fd, &counter, sizeof(counter)) != sizeof(counter)) {
         counter = 1;
     }
```

@apangin do you know the possible cause and is my workaround effective?

**Comment by apangin** [comment]
The signal handler may be also called due to external SIGPROF, not the one generated by perf_events. Does this sound probable? I suppose we should not count such events at all.

**Comment by advancedxy** [comment]
> Does this sound probable?

Yeah, that's most probable. But how  would `fd = 0`?   it's initialized to zero?

**Comment by apangin** [comment]
Not necessarily. I think, we should check both `si_code > 0` and `si_fd != 0`.

**Comment by apangin** [comment]
I've committed the fix. Please check if it helps.

**Comment by advancedxy** [comment]
> I've committed the fix. Please check if it helps.

Thanks for the quick fix.  This indeed fixes the previous problem.
